### ISSUE TITLE
HttpClient SearchResponse / How to get complete original JSON including timing / shards?

### ISSUE THREAD

**Issue by michael-read** [sksamuel/elastic4s#1002]
Trying out the HttpClient, and I can't figure out how to get the complete original JSON from a SearchResponse. With TCPClient the RichSearchResponse contained the "original" so you could get the complete JSON with result.original.toString(), which includes timing / shards. The HitReader appears to only look at the Hits. It appears the client.show would be fine, but it's blocking... any ideas.

Actually all responses from ES, regardless of type, should give access to the original JSON.

**Comment by sksamuel** [comment]
In the 6.0.0 alpha releases you can do this. There's an `executeRaw` method that just returns plain json.

**Comment by michael-read** [comment]
I see the "def executeRaw" in the source code for 5.4.x, but the compiler isn't finding it through SBT compile, nor is the Eclipse UI. I don't see any test cases either. Is there a configuration trick in creating the HttpClient to gain access?

**Comment by sksamuel** [comment]
I've added the original json into the SearchResponse for the HTTP client in master.
