### ISSUE TITLE
No HttpExecutable for UpdateByQueryDefinition

### ISSUE THREAD

**Issue by wildroco** [sksamuel/elastic4s#1006]
I'm using elastic4s 5.4.5 with Http client.

When I try to execute UpdateByQueryDefinition,
it fails with:

> could not find implicit value for parameter exec: com.sksamuel.elastic4s.http.HttpExecutable[com.sksamuel.elastic4s.update.UpdateByQueryDefinition,U]

After looking some codes in elastic4s-http module,
I could not find implicits for UpdateByQueryDefinition.
It seems to have implicits only for UpdateDefinition.

Is there something I missed?

**Comment by manfi** [comment]
+1

**Comment by kbedel** [comment]
I can work on a PR for this. Would there be a possibility of also getting a new 5.x release created to include this?
