### ISSUE TITLE
Bug with ScriptedMetricAggregationBuilder

### ISSUE THREAD

**Issue by arsalan94** [sksamuel/elastic4s#1016]
Hi,

I think there might be a bug with ScriptedMetricAggregationBuilder. If you look at the file, you'll see that initScript, combineScript, mapScript, and reduceScript all use builder.initScript instead of using builder.initScript, builder.combineScript, builder.mapScript, and builder.reduceScript respectively.

What I noticed is that if I have the following code:

```
val metricScript = scriptedMetricAggregation("Name")
      .initScript(script(initScript))
      .mapScript(script(mapScript))
      .combineScript(script(combineScript))
      .reduceScript(script(reduceScript))

val searchQuery = search(index).aggregations(metricScript)
```

and I print out the search query using `println(searchQuery.show)`, I get:

```
"aggregations" : {
    "Name" : {
      "scripted_metric" : {
        "init_script" : {
          "inline" : initScript,
          "lang" : "painless"
        }
      }
    }
  }
```

but the other scripts are missing from the query (combineScript, reduceScript, mapScript).

**Comment by sksamuel** [comment]
Fastest way is to do a PR if you need it fixing quickly.

**Comment by animageofmine** [comment]
Thanks Stephen. 

@arsalan94 do you want create a PR?

**Comment by arsalan94** [comment]
sure
