### ISSUE TITLE
Insufficiently typesafe

### ISSUE THREAD

**Issue by missingfaktor** [sksamuel/elastic4s#1023]
Hello! Thank you for writing Elastic4S client. I have only recently started using it. I notice that there is quite a proliferation of `Any` type in places where not any values should go. If there is interest in improving type-safety of the library, I am happy to help out.

**Comment by sksamuel** [comment]
I would be happy to hear any suggestions!

**Comment by missingfaktor** [comment]
Consider the method(s) [`fields`](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/indexes/IndexDefinition.scala#L50-L52) here. Instead of allowing `Any`, we could constrain it to only allow types that ElasticSearch understands. Refuse to compile when values of unsupported types are supplied.

**Comment by missingfaktor** [comment]
You can do this using a technique I describe [here](http://www.rahulsteapot.com/writing/2014/01/18/params-abstraction-for-http-query/).

**Comment by sksamuel** [comment]
I think that's a decent addition. Changing the params to Map[String,
Readable] or something.
