### ISSUE TITLE
ScriptType: NoClassDefFoundError

### ISSUE THREAD

**Issue by juanmirocks** [sksamuel/elastic4s#1024]
### My stack:

```scala
"com.sksamuel.elastic4s" %% "elastic4s-core" % "5.4.10",
"com.sksamuel.elastic4s" %% "elastic4s-http" % "5.4.10",
```

### My problem:

When trying to do an update with script (dummy example: `update(5) in "scifi/startrek" script { "..." }`), I get the following error:

```shell
java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.script.ScriptType
	at com.sksamuel.elastic4s.script.ScriptDefinition$.apply$default$3(ScriptDefinition.scala:9)
	at com.sksamuel.elastic4s.script.ScriptDefinition$.string2Script(ScriptDefinition.scala:24)
```

In fact, just using in any way `ScriptType`, throws me the same error; example:

```
org.elasticsearch.script.ScriptType.INLINE
```

### More info:

I can perfectly do scripted updates with the pure REST API 

---

Any ideas?

**Comment by avdv** [comment]
Hi,

I ~am~was hitting the same problem...

I am using SLF4J and this could be caused by missing log4j classes, I was using `"org.apache.logging.log4j" % "log4j-to-slf4j" % "2.8.2" % Runtime` and had this error.

Now, with

```
"org.apache.logging.log4j" % "log4j-to-slf4j" % "2.8.2" % Runtime
"org.apache.logging.log4j" % "log4j-api" % "2.8.2"
```

It works.

**Comment by sksamuel** [comment]
I'd recommend trying the M4 build which has no dependency on elasticsearch's types, so these annoying dependency stub issues go away.

**Comment by juanmirocks** [comment]
Thank you very much both. I will try either solution, and report back.

**Comment by juanmirocks** [comment]
I can confirm: both solutions work.

Thank you very much, and thank you for this great library!
