### ISSUE TITLE
Bug with parameters in script

### ISSUE THREAD

**Issue by arsalan94** [sksamuel/elastic4s#1025]
Hi,

I'm not 100% sure that this is a bug but I'm having issues using parameters in scripts, specifically metric scripts.

First of all, I'm not sure how to pass in an empty json object as a parameter. So, if I wanted to do:

`"params": {
  "paramA": {},
  "paramB": "someStr"
}`

How would I pass in paramA to the .params method? The second issue I'm seeing is everything getting converted to a string. So if I do

`"params": {
  "paramA": ['StringA', 'StringB']
}`

I tried to pass it in as:
`.params(Map("paramA" -> Seq('StringA', 'StringB')))`

but instead the list would be converted to a string. Any ideas?

**Comment by sksamuel** [comment]
tcp or http client ?

**Comment by sksamuel** [comment]
Closing as no further details provided.
