### ISSUE TITLE
Slice API?

### ISSUE THREAD

**Issue by polymorpher** [sksamuel/elastic4s#1027]
Today as I was trying to implement a distributed reindexing tool via sliced scroll API (https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-scroll.html), I noticed "slice" is not implemented in elastic4s even though "scroll" is implemented.

I want to confirm I am correct about it, before implementing it and start a pull request.

**Comment by sksamuel** [comment]
No, it's not implemented currently. A PR would be welcome.
