### ISSUE TITLE
The sink stops accepting elements after the batchSize * concurrentRequests

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#1030]
With http client, see https://stackoverflow.com/questions/45623990/elastic4s-akka-stream-sink-with-httpclient

**Comment by marekmodry** [comment]
The same happens to me. However, to me it seems to be a little non-deterministic... One case out of many ends up with more elements accepted.

**Comment by sksamuel** [comment]
It might be the case that the message sent by onComplete is handled before elements sent by onNext, if akka reorders messages from the same source, which it says it won't but I can't find conclusive proof.

The fact if it happens it's `batch size * concurrentRequests` indicates that it only processes the first "collection" of elements, as it requests `batch size * concurrentRequests` once it starts as a single 'batch'.
