### ISSUE TITLE
Re-indexing/change mapping for searching

### ISSUE THREAD

**Issue by nixiehi** [sksamuel/elastic4s#1035]
I have index Artist(name,id) with mappings StringType,IntegerType analyzer StandardAnalyzer....
But when I want to search something in that idex, I want to change analyzer for example N-Gram .
I could not find reindex or sometihng like that.

Is there any suggestion?

**Comment by sksamuel** [comment]
When you create an index you can set the search analyzer.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-analyzer.html

I don't think you can vary it per request.
