### ISSUE TITLE
Inconsistency with boost types (Float for some, Double for others)

### ISSUE THREAD

**Issue by kharnt0x** [sksamuel/elastic4s#1036]
Right now the boost types are inconsistent, some requiring a Double and others a Float (i.e. MatchAllQueryDefinition (float) vs MultiMatchQueryDefinition (double). 

If there is no good reason for this could we standardise on Double?

**Comment by sksamuel** [comment]
It's because in the early days, the Java api used float, and I didn't want to accept double and then have to perform a lossy conversion.

These days we could probably just go to double across the board. If you want to make the change for 6.x (on master) I'll merge it.

**Comment by kharnt0x** [comment]
https://github.com/sksamuel/elastic4s/pull/1041
