### ISSUE TITLE
case Match in AggregationBuilderFn can't match ExtendedStatsAggregationDefinition?

### ISSUE THREAD

**Issue by JuneLang** [sksamuel/elastic4s#1037]
I got MatchError when tried to add `ExtendedStatsAggregationDefinition` in `aggs`.  
Error message:  
`scala.MatchError: ExtendedStatsAggregationDefinition(agg1,Some(data-enfants),None,None,List(),Map()) (of class com.sksamuel.elastic4s.searches.aggs.ExtendedStatsAggregationDefinition)`  
It seems that in `AggregationBuilderFn.apply()` there is no case for `ExtendedStatsAggregationDefinition`?

**Comment by JuneLang** [comment]
Im using 6.0.0-M3 version.

**Comment by sksamuel** [comment]
At the moment not supported, needs adding to `AggregationBuilderFn`

**Comment by sksamuel** [comment]
Added in master, will be in 6.0.0-rc2.
