### ISSUE TITLE
Can't use Circe for decoding JSON responses with HTTP client?

### ISSUE THREAD

**Issue by kharnt0x** [sksamuel/elastic4s#1043]
We are trying to use Circe to decode JSON from the HTTP client. 

The doco states to use the following to import Circe: 
```
import io.circe.generic.auto._ 
import com.sksamuel.elastic4s.circe._
```

I have done this however in ResponseHandler.scala it has `import com.sksamuel.elastic4s.json.JacksonSupport` and some specific code for Jackson. 

Is there a way to override this easily?

**Comment by sksamuel** [comment]
Jackson is used internally, you can use circe for marhsalling to your own case classes.
