### ISSUE TITLE
Filter not added correctly to function score scorers when using http client

### ISSUE THREAD

**Issue by kharnt0x** [sksamuel/elastic4s#1047]
The following function score query:
```
functionScoreQuery()
      .scoreFuncs(
filterFunction(weightScore(100)).filter(matchPhraseQuery("foo", "bar"))
)
```
should result in something like:
```
{
    "function_score": {
        "functions": [
            {
                "weight": 100,
                "filter": {
                    "match_phrase": {
                        "foo": {
                            "query": "bar"
                        }
                    }
                }
            }
        ]
    }
}
```
instead we just get:
```
{
    "function_score": {
        "functions": [
            {
                "weight": 100
            }
        ]
    }
}
```
Not only does it not work, the API is very confusing. Elasticsearch allows "filter" to be added to all the Score functions just like a weight can be. Right now however there is a confusing type `FilterFunctionDefinition` that must be used in order to add a filter.
I'm proposing to add an optional filter property to each ScoreFunctionDefinition and to remove the type FilterFunctionDefinition altogether. 

I'll create a PR and let me know what you think please @sksamuel

**Comment by kharnt0x** [comment]
@sksamuel I've created https://github.com/sksamuel/elastic4s/pull/1048 which is a simple fix for the above issue. I'll look at changing the API to be more consistent with a separate PR

**Comment by sksamuel** [comment]
I've merged the simple fix for now. The reason for the confusing API is because it's a copy of the way the Java API works. I agree it's not very good. Feel free to propose something completely different.

**Comment by kharnt0x** [comment]
@sksamuel I've created https://github.com/sksamuel/elastic4s/pull/1049

Let me know what you think

**Comment by sksamuel** [comment]
Closing this as the new API is very nice.
