### ISSUE TITLE
cats 1.0.0 dependency

### ISSUE THREAD

**Issue by rkrzewski** [sksamuel/elastic4s#1053]
Cats have recently released [1.0.0-MF](https://github.com/typelevel/cats/releases/tag/v1.0.0-MF) milestone release ahead of 1.0.0 planned this fall. Circe has corresponding release [0.9.0-M1](https://github.com/circe/circe/releases/tag/v0.9.0-M1).
Projects that use elastic4s and also use circe, cats and other related projects that would like to prepare for cats 1.0.0 are facing divergent dependencies problem.
Of course it can be solved by bumping the dependencies and building elastic4s locally / publishing a custom version to a company-wide artifact repository, but maybe you would like to help out such efforts globally. I understand that not all elastic4s users are interested in jumping on milestone releases of it's dependencies and having separate versions can be confusing, so this is up for your consideration. I can provide PRs for requisite branches if you wish - the changes themselves are trivial and restricted to `project/Build.scala`

**Comment by sksamuel** [comment]
Can you not just bump the versions in your build - then the older versions from elastic4s will be overriden. Of course, elastic4s will use cats final once ready.

**Comment by sksamuel** [comment]
Also, you can do a PR to update to MF on master that's fine, it'll be included in the next 6.0.0 milestone build.

**Comment by rkrzewski** [comment]
Of course I meant bumping dependencies in elastic4s build and publishing it locally :)
I'll post the PR for `master` shortly.

**Comment by omrihq** [comment]
Seeing a conflicting dep with elastic4s `6.0.0^` and `circe`: 
```
[error] missing or invalid dependency detected while loading class file 'Encoder.class'.
[error] Could not access type Contravariant in value cats.functor,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies.
```
So far fine with `5.5.4v`
