### ISSUE TITLE
No explanation in search result when `explain(enabled = true)`

### ISSUE THREAD

**Issue by missingfaktor** [sksamuel/elastic4s#1067]
`SearchDefinition` has a method `.explain` that allows asking for an explanation, but the `SearchHit`s in the response do not surface the `_explanation` field that ElasticSearch sends.

**Comment by sksamuel** [comment]
You could use the explain query for now until this is added.

**Comment by missingfaktor** [comment]
Yep, that is the workaround I am using it. Thanks!

**Comment by sksamuel** [comment]
Added to master, will be in next release.

**Comment by missingfaktor** [comment]
Thanks, mate.
