### ISSUE TITLE
Example for connecting to clusters behind proxies

### ISSUE THREAD

**Issue by oswaldo** [sksamuel/elastic4s#1070]
I'm trying to connect to an Elasticsearch instance that lays behind a proxy and I can for instance call it in the browser through an url that looks like `https://host/path`.

The README exemplifies how to connect with lines like:
`val client = HttpClient(ElasticsearchClientUri("localhost", 9200))`

But I see no example or obvious way at least looking at source code about how to define a path when using the http client to connect to a cluster and trying `val client = HttpClient(ElasticsearchClientUri("host/path", 443))` obvioustly doesn't work.

If there is support for it, what would be the way to set this up? I expected something like in [the example for the javascript api](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/host-reference.html#_examples_2).

**Comment by sksamuel** [comment]
There's no support for that at present. You could extend the client
yourself to add a path to all requests. Or submit a PR.

**Comment by sksamuel** [comment]
Can I use your implementation @oswaldo

**Comment by oswaldo** [comment]
Yes you can.
I changed jobs recently though so I don't have access to the server that was in that setup and would't be able to run tests on that infrastructure again, but the unit tests should hopefully cover the added feature besides what was before.

**Comment by sksamuel** [comment]
Was looking over your implementation and I can't see where the path you parse in the uri is actually used.
