### ISSUE TITLE
Empty GetIndexTemplateResponse

### ISSUE THREAD

**Issue by kimxogus** [sksamuel/elastic4s#1075]
[GetIndexTemplateResponse](https://github.com/sksamuel/elastic4s/blob/2f210e55c4fa407bf4daef6b108a13dd43272836/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/index/IndexTemplateImplicits.scala#L15) is empty case class, so I can't retrieve index template.
Also, response for create, delete index template are empty. They need to be implemented.

**Comment by sksamuel** [comment]
I probably started it and didn't get around to it yet. It'll be in 6.0.0 final of course.

**Comment by sksamuel** [comment]
This is now in master and will be part of 6.0.0-rc2.
