### ISSUE TITLE
set alias when creating an index

### ISSUE THREAD

**Issue by yanns** [sksamuel/elastic4s#1084]
First, thx for this lib!

ES supports setting aliases when creating a new index:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#alias-index-creation
- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#create-index-aliases

The `CreateIndexDefinition` does not have any `aliases` field.
I guess this functionality is missing from the DSL?

**Comment by sksamuel** [comment]
yep, we can add that. I can add it to my list unless you want to do another PR !

**Comment by yanns** [comment]
I tried that, but it's getting a lot of changes very quickly.
The `CreateIndexContentBuilder` must be extended to serialize the `aliases`fields.
And the `aliases` field needs `QueryBuilderFn` to serialize the `filter`.

BUT:
- `QueryBuilderFn` is in the ` http` package.
- and `CreateIndexContentBuilder` is in the `core`package.

So `CreateIndexContentBuilder` cannot use `QueryBuilderFn`.
If I move `CreateIndexContentBuilder` to the http package, then `IndexShowImplicits` cannot compile anymore.

**Comment by sksamuel** [comment]
Since the TCP client will be deleted in version 7 I think it's ok to make two copies of CreateIndexContentBuilder, and move one to TCP client and one to HTTP Client, then it'll work.

**Comment by sksamuel** [comment]
This is done in master now. Will be in 6.0.0-rc2.

**Comment by yanns** [comment]
Thx a lot!

I can open a PR to add the tests I already wrote if you're interested.

I have one problem with a test:
```
    "create aliases with index" in {
      http.execute {
        createIndex("electronics-new").mappings(mapping("electronics"))
          .alias("alias_1")
          .alias("alias_2")
      }.await
      val index = http.execute {
        getIndex("electronics-new")
      }.await
      index("electronics-new").aliases should contain key "alias_1"
      index("electronics-new").aliases should contain key "alias_2"
    }
```
fails with
```
[info] - should create aliases with index *** FAILED ***
[info]   Map("alias_1" -> Map()) did not contain key "alias_2" (IndexTest.scala:131)
```
If there's any bug, I can try to fix it.
Do you think there's an issue, or are the test expectations wrong?

**Comment by sksamuel** [comment]
I wonder if the `getIndex` is broken.

**Comment by sksamuel** [comment]
Yes PR would be welcome of course.

**Comment by yanns** [comment]
The test was broken as I have not deleted the index.
https://github.com/sksamuel/elastic4s/pull/1116
