### ISSUE TITLE
Logging JSON request and response

### ISSUE THREAD

**Issue by matteomelani** [sksamuel/elastic4s#1087]
I am using the elsatic4s HTTP client in a Play 2.6 App. I'd like to simply log all the JSON requests the client sends to Elasticsearch as well as the JSON responses the client gets back. This is quite useful especially if you need to debug problems in production. 

Is it possible with 5.x.x version? If yes is there any complete code sample I can look at?

Thank you for the great module.

**Comment by sksamuel** [comment]
Depending on which version you're using, just turn on com.sksamuel.elastic4s to DEBUG in your log config.

**Comment by matteomelani** [comment]
Thank you, that works.
