### ISSUE TITLE
Http client search: search_type error

### ISSUE THREAD

**Issue by nixiehi** [sksamuel/elastic4s#1093]
When we use searchType() in
      .search(...)
      .query(query)
      .version(true)
      .searchType(SearchType.DFS_QUERY_THEN_FETCH)

It gives the error: No search type for search_type=DFS_QUERY_THEN_FETCH. 
The search uri should be( lowercase version) 
 http://localhost:9200/..../&search_type=dfs_query_then_fetch&version=true

Could you fix this?

**Comment by sksamuel** [comment]
Fixed in master, will be in rc1.

**Comment by CNQiYang** [comment]
how can i use DFS_QUERY_THEN_FETCH in 5.6.0

**Comment by sksamuel** [comment]
Wasnt it removed

**Comment by alicefuzier** [comment]
Hi, sorry about commenting on something so old but I need to use DFS_QUERY_THEN_FETCH with elasticsearch 5.6.x (we haven't migrated our cluster to elasticsearch 6 yet). Is there a way to do that?

**Comment by alicefuzier** [comment]
BTW I've created this PR to backport the fix https://github.com/sksamuel/elastic4s/pull/1572

**Comment by sksamuel** [comment]
I've released 5.6.9
