### ISSUE TITLE
QueryStringQueryDefinition do not provide a way to set useAllFields property of java client QueryStringQueryBuilder (all_fields property in Elasticsearch Query API)) )

### ISSUE THREAD

**Issue by devsprint** [sksamuel/elastic4s#1098]
QueryStringQueryDefinition do not provide a way to set useAllFields property of java's client QueryStringQueryBuilder (all_fields property in Elasticsearch Query API)

One usage of this feature is Highlighting feature where you want to highlight values based on a search query but the list of fields could not be determined at the time of the request.

**Comment by sksamuel** [comment]
Which version?

**Comment by devsprint** [comment]
5.4.x, I did not found any trace of support for this field in source code. I also checked the master source code.

**Comment by sksamuel** [comment]
Yeah it's been removed in 6.0, `The all_fields parameter for the query_string has been removed. Set default_field to *` instead. If provided, default_field will be automatically set to *`
So there's no point adding it I don't think.

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_search_changes.html

**Comment by devsprint** [comment]
Well, I have seen that as being deprecated in Java library too, but setting only the default_field to * is not really working, because it will try to match on fields of other type like Numeric fields. Lenient property may remove the errors but I'm not sure if this  approach is not having other side effects...

**Comment by sksamuel** [comment]
Hmm if the approach is invalid for numbers, might be worth creating an issue with elastic before 6.0 is released.

**Comment by sksamuel** [comment]
Or if you to add it for 5.4 branch, if you do a PR I'll release it.

**Comment by devsprint** [comment]
Ok,  I will try to not expose that field out of QueryStringQueryDefinition because it will break backward compatibility,case class will have 23 parameters in constructor, as I have seen that code is compiled for older version of scala. I will do it in a way to not break it.

**Comment by sksamuel** [comment]
You could put it on one of the "child" case classes of the QueryStringQueryDefinition case class.
