### ISSUE TITLE
GetResponse fields empty issue

### ISSUE THREAD

**Issue by nixiehi** [sksamuel/elastic4s#1106]
GetResponse class field: fields: Map[String, AnyRef] always returns empty Map.
 Source(_source or sourceAsMap) always has fields. However, I could not use fields parameter as storedFieldsAsMap and storedFieldOpt(....)

Even though I add the storedFields(List(.....)) to get query =>
ElasticDsl.get("...").from("...","...")storedFields(List(....)), it returns empty and so it causes the None.get error.
Could you fix this?

**Comment by sksamuel** [comment]
Are you saying that `sourceField(name)` on a GetResponse is always None ?

**Comment by nixiehi** [comment]
fields parameter is  always  None. Instead the source parameter always returns the fields. As a result of being fields parameter None, storedField,storedFieldOpt,storedFieldsAsMap functions will not work properly.

GetResponse should fill the the fields parameters so I am able to call the these functions.

**Comment by sksamuel** [comment]
If you want fields to be populated, you have to specify the fields. They are called `stored fields`. If you don't specify stored fields, you get the source back. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-stored-fields.html

**Comment by nixiehi** [comment]
As I said before, my query is 
 ElasticDsl
        .get(id)
        .from("...", "...")
        .storedFields(List("name",
          "...",
          "..."
)

However, the fields parameter still returns Map()

**Comment by sksamuel** [comment]
As you said before yes. I'll add a test and see what happens.

**Comment by nixiehi** [comment]
My version is 5.5.3

**Comment by sksamuel** [comment]
Seems fine on master, I'll try 5.5.x branch now.

```
    val resp = http.execute {
      get(4) from "beer/lager" storedFields("name", "brand")
    }.await.right.get

    resp.exists should be(true)
    resp.id shouldBe "4"
    resp.storedFieldsAsMap.keySet shouldBe Set("name", "brand")
    resp.storedField("name").value shouldBe "coors light"
```

**Comment by sksamuel** [comment]
It works fine in 5.5.x too. I know what you're doing wrong I think. I bet you're not setting the fields to be stored when defining the index, eg

```
    createIndex("beer").mappings {
      mapping("lager").fields(
        textField("name").stored(true),
        textField("brand").stored(true),
        textField("ingredients").stored(true)
      )
    }
```

They're not stored by default, ie,

> https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-stored-fields.html


from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-stored-fields.html

**Comment by sksamuel** [comment]
I take it by your silence it worked.
