### ISSUE TITLE
NPE in RichAggregations

### ISSUE THREAD

**Issue by devsprint** [sksamuel/elastic4s#1110]
Elastic4s 5.4.x branch: 

There is a NPE situation in the RichAggregations implementation of getAs method:

`def getAs[T](name: String): T = aggregations.getAsMap.get(name).asInstanceOf[T]`

The get(name) may return Null and the asInstanceOf on null will throw NPE.

**Comment by sksamuel** [comment]
I've changed it to `NoSuchElementException`
