### ISSUE TITLE
Example to retrieve documents count in a type

### ISSUE THREAD

**Issue by GRpro** [sksamuel/elastic4s#1124]
Hi,
Say, I have index `myindex` and type in it `mytype`.
please provide an example how to calculate documents count in `myindex/mytype` in elastic4s 5.6.0.

I see there is a need to use `valueCountAggregation(name)`
Thanks.

**Comment by sksamuel** [comment]
`search("myindex/mytype").size(0)` then on the result just get `totalHits`
