### ISSUE TITLE
fetchSource for update broken and missing _source in UpdateResponse

### ISSUE THREAD

**Issue by francisdb** [sksamuel/elastic4s#1130]
According to the [ 5.6 docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-update.html#_parameters_2) an update can return a `_source` field containing the updated document.

On the query side for elastic4s this can be enabled by adding `fetchSource true`
However the field is only added if false, which is the default! Should be the other way round.
https://github.com/sksamuel/elastic4s/blob/b0ce6ec0e2a3f181f5eaa2881176f0516c7165d9/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/update/UpdateImplicits.scala#L76

The `_source` field also seems to be missing in `com.sksamuel.elastic4s.http.update.UpdateResponse`
(the raw `json` like SearchResponse has could also be useful to add)

**Comment by sksamuel** [comment]
Fixed in master for 6.0 release.
