### ISSUE TITLE
Why do queries in `BoolQueryDefinition` override old queries?

### ISSUE THREAD

**Issue by yannick-cw** [sksamuel/elastic4s#1134]
If I do something like this:
```scala
boolQuery()
      .must(...)
      .should(should1)
      .should(should2)
```

Only `should2` is kept and `should1` is dropped.
https://github.com/sksamuel/elastic4s/blob/a9c2a36c0dd1cb0d07560ba50e41f973bc9a3036/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/searches/queries/BoolQueryDefinition.scala#L22

Is that a deliberate choice or could we change that to append the new queries? I just stumbled across this while figuring out why some queries were ignored :) 
If we want to do something about this I would definitely be willing to take a shot

**Comment by sksamuel** [comment]
I can't change the way they work now, but we can add new methods with new names.

**Comment by sksamuel** [comment]
I've added `.withMust`, `.withShould` etc to make the naming clearer (in release 6.0.0).
