### ISSUE TITLE
Can't find ext package

### ISSUE THREAD

**Issue by wenlin0514** [sksamuel/elastic4s#1135]
Hi, I'm trying to build elastic4s in my workspace, there are a lot of errors complaining package "ext" is not a member of package com.sksamuel:

/workplace/elastic4s/src/Elastic4s/src/main/scala/com/sksamuel/elastic4s/indexes/IndexDefinition.scala:5: error: object exts is not a member of package com.sksamuel
[scalac-2.11] import com.sksamuel.exts.OptionImplicits._

**Comment by sksamuel** [comment]
That comes in as part of http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22exts_2.11%22. It's in the sbt file so perhaps there's an issue with your build?
