### ISSUE TITLE
How to check for errors and explanation w/ HTTP client

### ISSUE THREAD

**Issue by avdv** [sksamuel/elastic4s#1139]
Hi.

I am migrating to 5.x from 2.x.

The nice thing with the old API was that I could request the explanation for a search result and also check for errors (display them).

Until now, I cannot figure out how to do this with the new API. The relevant properties (hits, aggregations) are just `null`... 

I cannot see what's wrong when there is a failure. I copy the request to a terminal / insomnia and retry it manually. Also I did not find any example with error handling. How can I do this?

TIA!

**Comment by sksamuel** [comment]
In the fresh 6.0.0 release the responses from the http client include the full json body, any headers and the status code. They also have much better error handling. I think if you try that it'll do what you want, if not please re-open.

**Comment by avdv** [comment]
@sksamuel thanks a lot! We're currently stuck on elasticsearch 5.6.x - but that should be no big blocker, right?! I will try it and report back.

**Comment by avdv** [comment]
Almost forgot to report back, but migrating to the new version was a breeze and it works well so far, all tests past. So, one can indeed use elastic4s-http 6.0.0 with elasticsearch 5.6.x.
