### ISSUE TITLE
Question: do you support optimistic locking for upsert?

### ISSUE THREAD

**Issue by tomer-ben-david** [sksamuel/elastic4s#1140]
I looked at the documentation: [https://sksamuel.github.io/elastic4s/docs/document/update.html](https://sksamuel.github.io/elastic4s/docs/document/update.html) of elastic4s and I don't see mentioning of optimistic locking..

When I look at ES documentation: [https://www.elastic.co/guide/en/elasticsearch/guide/1.x/optimistic-concurrency-control.html](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/optimistic-concurrency-control.html)

I see that it's supporting it.  Is there support for it or anyway I can use this with elastic4s?

**Comment by sksamuel** [comment]
You can set the version on the update queries if that's what you're asking.

**Comment by tomer-ben-david** [comment]
yes.  cool, i'll try that, should have given it a shot.  thanks.
