### ISSUE TITLE
LocalNode(...).http(shutdownNodeOnClose = true).close() will not actually close the local node

### ISSUE THREAD

**Issue by obruchez** [sksamuel/elastic4s#1142]
Version: 6.0.0-rc1

This can clearly be checked by calling InternalLocalNode.isClosed.

Looking at the source code, it appears that shutdownNodeOnClose is ignored.

`override def http(shutdownNodeOnClose: Boolean): HttpClient = HttpClient(s"elasticsearch://$host:$port?cluster.name=$clusterName")`

**Comment by sksamuel** [comment]
Thanks, fixed in master.
