### ISSUE TITLE
`FloatBuildableTermsQuery` extends BuildableTermsQuery[Double] 

### ISSUE THREAD

**Issue by Lazu13** [sksamuel/elastic4s#1145]
```FloatBuildableTermsQuery``` as name suggest should build ```TermsQueryBuilder``` using ```Elasticsearch termsQuery``` method with ```Float``` type not ```Double```. 
However, on the master branch (build and used due to some bug fixes that aren't released yet) there is  ```FloatBuildableTermsQuery``` which uses ```Double```

**Comment by sksamuel** [comment]
Fixed on master. Thanks.
