### ISSUE TITLE
Elasticsearch 5.x/Cats 1.0.0 compatibility

### ISSUE THREAD

**Issue by goedelsoup** [sksamuel/elastic4s#1146]
We're in a troublesome position at the moment as we're trying to push strongly towards some of the standardized behaviors of cats 1.0.0 and cats-effect while also tied to ES 5.x for the time being. It'd be great to not have to execute application and data layer updates at the same time. Is this a version that is worthwhile making a PR for?

**Comment by sksamuel** [comment]
Yes, just make a PR with the updated cats version and I'll release it.
