### ISSUE TITLE
NoSuchElementException when scrolling

### ISSUE THREAD

**Issue by francisdb** [sksamuel/elastic4s#1147]
```
java.util.NoSuchElementException: Either.right.get on Left
[error] 	at scala.util.Either$RightProjection.get(Either.scala:641)
[error] 	at com.sksamuel.elastic4s.http.search.SearchIterator$$anon$1.fetchNext(SearchIterator.scala:44)
[error] 	at com.sksamuel.elastic4s.http.search.SearchIterator$$anon$1.hasNext(SearchIterator.scala:33)
```

Could this be related to a too low keepAlive?

**Comment by francisdb** [comment]
Seems to indeed be related to the keepAlive being too low, anyway this should result in a cleaner error indicating the scroll expired before the next batch was read.

**Comment by sksamuel** [comment]
The error you are getting is because you're not doing error handling on the result. You're just opting to make the assertion that the response is always "success".

```
val response = match {
  case Right(good) =>
  case Left(error) =>
}
```

Standard scala Either.

**Comment by francisdb** [comment]
Euh, the error is coming from elastic4s code, not mine

the blocking call to fetch the next result is not handing the error case

https://github.com/sksamuel/elastic4s/blob/7d29ab974f7d7af417b967787c9bb5765611e1eb/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/SearchIterator.scala#L44

**Comment by sksamuel** [comment]
Scala is throwing a match error. It tells you in the stack trace you pasted.
```
java.util.NoSuchElementException: Either.right.get on Left
[error] 	at scala.util.Either$RightProjection.get(Either.scala:641)
```
I am addressing your comment: _this should result in a cleaner error indicating the scroll expired before the next batch was read_ because you'll get the proper error if you handle both sides of an `Either`.

**Comment by sksamuel** [comment]
Ok the eror handling should be in the SearchIterator in this case. It wasn't clear to me that's what you were using.

**Comment by sksamuel** [comment]
Fixed on master.
