### ISSUE TITLE
how to check whether a document exists

### ISSUE THREAD

**Issue by Xcorpio** [sksamuel/elastic4s#1155]
hi, is there a function for
https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-exists.html#doc-exists

**Comment by sksamuel** [comment]
Added to master, will release 6.0.1 with this added.

**Comment by sksamuel** [comment]
client.execute {
  exists("id", "index", "type") 
}

**Comment by joan38** [comment]
@sksamuel I was wondering why exsits is `exists(id, index, type)` whereas get is `get(index, type, id)`.
I'm speaking about the order of the parameters.

**Comment by sksamuel** [comment]
A stupid inconsistency I have introduced :(
