### ISSUE TITLE
TopHits don't have sourceAsString or any easy method to parse to a Type

### ISSUE THREAD

**Issue by grillorafael** [sksamuel/elastic4s#1156]
Hey @sksamuel 

I'm migrating here some of the code to use `6.0.0` and I'm also changing from `elastic4s-tcp` to `elastic4s-http` as advised.

I saw that https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tcp/src/main/scala/com/sksamuel/elastic4s/searches/aggs/RichAggregations.scala does not exist in `elastic4s-http` but only in the `tcp` one.

Is there any specific reason for that?

The code I was using before was the following:

```scala
val filterAggregation = response.aggregations.getAs[Filter](filterAggName)
```
and It seems that I can't import things like `org.elasticsearch.search.aggregations.metrics.avg.InternalAvg` when using the HTTP library

I have the following modules:

```scala
val esversion = "6.0.0"

"com.sksamuel.elastic4s" %% "elastic4s-core"  % esVersion
"com.sksamuel.elastic4s" %% "elastic4s-http" % esVersion
"com.sksamuel.elastic4s" %% "elastic4s-http-streams"  % esVersion
"com.sksamuel.elastic4s" %% "elastic4s-play-json"  % esVersion
```

**Comment by grillorafael** [comment]
I think I managed to understand how to do it now.

```scala
val filterAggregation = response.result.aggs.filter(filterAggName)
val groupByAggregation = filterAggregation.terms(byResolvedIMOAggName)
```

Seems ok the issue now is that I have a `topHits` aggregation and before I was doing `Json.parse(h.getSourceAsString).as[LiveVessel]` on the `Hit`. Now I don't have access to this `getSourceAsString` and it seems that I only have access to `source` as a `Map[String, Any]`

any better way to do this?

**Comment by grillorafael** [comment]
`Json.toJson(h.source).as[LiveVessel]` seems ok

**Comment by grillorafael** [comment]
I'm going to close this issue as it was just me being a bit dumb in the morning.

**Comment by grillorafael** [comment]
`Map[String, Any]` is not a great type for PlayJson to parse. Might be better to have access to the raw string or something similar. Like `to[]` or `safeTo[]` that we have on the other ones

**Comment by sksamuel** [comment]
In 6.0.0 + the response types include the raw json as well, so you can always get the json yourself if you want to. I'm going to add `to` for aggregations as well.

**Comment by sksamuel** [comment]
Added to and safeto for aggs in 6.0.4.

**Comment by grillorafael** [comment]
Thanks, mate. Awesome addition!

**Comment by nolledge** [comment]
Hi @sksamuel, is it possible to get this method on the 'TopHit' as well so I dont have to parse the whole aggregation? I use the DSL to descend to the Hit elements but when I reach them I can only receive the source as Map[String, Any] and as said this is not a nice type to parse.
