### ISSUE TITLE
where is the source code for com.sksamuel.exts?

### ISSUE THREAD

**Issue by SethTisue** [sksamuel/elastic4s#1158]
context: I'm trying to add elastic4s to the Scala community build, which requires building all of its Scala-based dependencies from source

there are binaries for exts on Maven Central, but I can't find the source code anywhere

Scaladex thinks the source should be at https://github.com/sksamuel/exts, but that repository does not exist

**Comment by sksamuel** [comment]
It's a private repo. I supose I could make it public.

**Comment by sksamuel** [comment]
There you go. https://github.com/sksamuel/exts

**Comment by SethTisue** [comment]
thanks :-)

**Comment by sksamuel** [comment]
You're welcome :)
