### ISSUE TITLE
Routing field in search response

### ISSUE THREAD

**Issue by To-om** [sksamuel/elastic4s#1160]
I'm using Elastic4s 5.6.0 and I'm migrating from TCP to HTTP client.

I need routing information of search hits (I use parent/child documents). `_routing` field is not in `SearchResponse` (it is with TCP client). I've tried to add `storedFields("_routing", "_source")` but it doesn't help.

So, how can I retrieve this information from a `SearchResponse` ?

**Comment by sksamuel** [comment]
Added to 6.0.4.
