### ISSUE TITLE
Strored scripts wrong building

### ISSUE THREAD

**Issue by Hindu** [sksamuel/elastic4s#1162]
Hi, for ScriptType.STORED elastic requires lang == null(org.elasticsearch.script.Script:407).
```
} else if (type == ScriptType.STORED) {
     if (lang != null) {
         throw new IllegalArgumentException("lang cannot be specified for stored scripts");
     }
//...
}
```
But com.sksamuel.elastic4s.ScriptBuilder always return string with `script.lang.getOrElse(Script.DEFAULT_SCRIPT_LANG)`.

**Comment by sksamuel** [comment]
Fixed on master.
