### ISSUE TITLE
NoClassDefFoundError when using XPackElasticClient

### ISSUE THREAD

**Issue by leo-dur** [sksamuel/elastic4s#1166]
We are getting a runtime error `NoClassDefFoundError: com/sksamuel/elastic4s/xpack/security/XPackElasticClient`

With this code:
```
import com.sksamuel.elastic4s.xpack.security.XPackElasticClient

val client = XPackElasticClient(conf.settings, conf.uri)
```

With those dependencies
```
val elastic4sCore = "com.sksamuel.elastic4s" %% "elastic4s-core" % "5.6.0"
val elastic4sPlayJson = "com.sksamuel.elastic4s" %% "elastic4s-play-json" % "5.6.0"
val elastic4sTcp = "com.sksamuel.elastic4s" %% "elastic4s-tcp" % "5.6.0"
val elastic4sXPack = "com.sksamuel.elastic4s" %% "elastic4s-xpack-security" % "5.6.0"
```

With `elastic4s-xpack-security` *5.5.5* (instead of *5.6.0*) everything works fine.

**Comment by sksamuel** [comment]
Surely has to be something in your build since com/sksamuel/elastic4s/xpack/security/XPackElasticClient exists in the source and the jar. You could extract the jar and look inside to prove that it's there.

**Comment by leo-dur** [comment]
A `sbt clean` slove the issue. Thanks for your help.
