### ISSUE TITLE
ExtendedBounds doesn't support strings anymore

### ISSUE THREAD

**Issue by TrustNoOne** [sksamuel/elastic4s#1170]
I can't find a way to specify dates in ExtendedBounds using strings (ISO format, date math etc), the api now only takes two longs. It's fine for normal dates but I am using [date math](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math) in one case.

**Comment by TrustNoOne** [comment]
I noticed that date parameters (that can dynamically be longs or strings) have been transformed to Longs/Doubles in other places as well (e.g. I'm looking at DateRangeAggregation).

Maybe it's worth defining some "ElasticsearchDate" type that can polymorphically be a number or a string? It could even validate input.

I don't know  If I can find some time to work on it before new year but I could try and give it a shot

**Comment by sksamuel** [comment]
I think that's a good goal. If you want to create the elasticsearch date type, I can do the boring work of wiring it into all the request types.

**Comment by sksamuel** [comment]
Looking at `DateRangeAggregation` it already supports longs and strings, so you should be able to do what you want already, but having an ElasticsearchDate is still a good idea.

**Comment by sksamuel** [comment]
I've added an ElasticDate type, we just need to wire it into the queries now.

**Comment by sksamuel** [comment]
All wired in, will be included in release 6.1.0

**Comment by solicode** [comment]
Would this also apply to `DateHistogramAggregation`? The extended bounds on that are `Long` only currently.

**Comment by TrustNoOne** [comment]
thanks @sksamuel, that was fast! I wanted to do something to day but you beat me 
DateHistogramAggregation was my actual use case in the first place, I see it's still using the original ExtendedBounds. I see ElasticDate is always converted to a string, even when it's a long, that wouldn't work where you can pass either a long or a string, e.g. in DateHistogramAggregation.

E.g. if I have a mapping like this:
```json
{
  "mappings": {
    "my_type": {
      "properties": {
        "date": {
          "type":   "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    }
  }
}

```

I can't specify a query like this: 

```json
{"size": 0,
     "aggs": {
        "range": {
            "date_range": {
                "field": "date",
                "ranges": [
                    { "to": "2017-01-01" }, 
                    { "from": 1186083100000 } 
                ]
            }
        }
    }
}
```

I had started to work on it yesterday but didn't have time and was not satisfied with the result and then you introduced a type that's very similar to what I had in mind but uses `show` to convert everything to a string instead of having a type parameter.

This was my try:
https://github.com/TrustNoOne/elastic4s/compare/master...TrustNoOne:elasticsearch-date

**Comment by TrustNoOne** [comment]
I'm trying something similar for numbers (e.g. in RangeAggregation): ElasticNumber. I'll open a PR to show what I mean possibly today if I can make it

**Comment by TrustNoOne** [comment]
@sksamuel ExtendedBounds class still supports only longs as @solicode pointed out

**Comment by sksamuel** [comment]
Yes good spot. I'll update i to work on the other places, and handle the longs better.
