### ISSUE TITLE
Null values in HTTP response objects.

### ISSUE THREAD

**Issue by CarterWilliam** [sksamuel/elastic4s#1171]
Hello, I recently migrated from using the TCP client to the HTTP client and have run into a few problems with the `GetResponse` and `SearchResponse` objects. Mostly, the issues occur because instead of returning an empty `Map` for certain fields e.g. aggregations, I get a Java `null` object instead, causing a NullPointer whenever I try to iterate over the map.

There are a number of existing helper methods which safely return the empty Maps when used like [`highlightFragments`](https://github.com/sksamuel/elastic4s/blob/55713516a936d13541e3774bcaf46c700f44e91c/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/responses.scala#L19). However, if I want to iterate through _all_ the returned highlights I'll have to do this `Option(response.highlight).getOrElse(Map.empty)` myself. Ideally, it would be good if none of the exposed objects on the responses were null values.

What do you think? If you agree I can raise a PR.

**Comment by sksamuel** [comment]
Yes nulls should not exist. We'd need to keep backwards compatibility though if we're changing the signature (so new methods?)

**Comment by sksamuel** [comment]
Fixed in 6.3.0.
