### ISSUE TITLE
Shows could print out path as well as Json body

### ISSUE THREAD

**Issue by catalin-ursachi** [sksamuel/elastic4s#1180]
At the moment, using `httpClient.show` only provides partial info about the request, as it doesn't print out the URL path. Another consequence of that is that `Show`s are only defined for requests that do carry Json, so a method taking a generic request can't always take a `Show` as an evidence parameter.

Would it be worthwhile changing the `Show`s to render the request path as well as the Json body, and implementing them for non-Json requests as well?

**Comment by sksamuel** [comment]
Yes I have thought about this myself. I think we should probably add another typeclass, `RequestShow` or whatever, which actually has two methods to be implemented - header and body. What do you think ?

**Comment by catalin-ursachi** [comment]
Sounds sensible; shall I go ahead and write that? Is it fine if I only define it for some requests to start with, rather than all of them?

**Comment by sksamuel** [comment]
Maybe just do one so we can agree it's on the right lines and then I can
help with others.
