### ISSUE TITLE
AWS request signature does not match on getAliases

### ISSUE THREAD

**Issue by jnatten** [sksamuel/elastic4s#1188]
This might be me just misunderstanding how i should use the `Aws4ElasticClient`, but here goes.
This is with elasticsearch 6.0 in aws and elastic4s 6.0.1.

`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_DEFAULT_REGION` is set via environment variables.
Then i try to do:
```
val endpoint = "elasticsearch://awsendpointurl.com:443?ssl=true"
val client = Aws4ElasticClient(ep)

client.execute {
  getAliases("images", Nil)
}
```

And this works fine when requesting from a local elasticsearch container (which is expected since it does not require signing the request)

However, when attempting to do this towards aws, the Either returns left with a message of: 
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/images/_alias/

host:awsendpointurl.com
user-agent:Apache-HttpAsyncClient/4.1.3 (Java/1.8.0_144)
x-amz-date:20171218T142308Z

host;user-agent;x-amz-date
somelongstringhere'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20171218T142308Z
20171218/eu-central-1/es/aws4_request
adifferentlongstringhere'
```

This seems to happen with `getAliases`, but not with `createMapping`, which i find weird when the same command works locally.

**Comment by jnatten** [comment]
So i figured out that in my case (Where i want to look for indexes a given an alias) the solution was simply to not misplace the alias name in the parameterlist for `getAliases` and do 
`getAliases(Nil, List("images"))`.

But if i wanted to get aliases for a given index this would still apply, so I'm guessing there might be a 
bug somewhere (?)

**Comment by saraiva132** [comment]
I will try to reproduce this bug. If it is indeed a bug (which from the likes of it it seems to be that way) I will fix it ASAP.

**Comment by saraiva132** [comment]
It seems that the path field is not being properly encoded. Your case is easily fixable but there are more cases not covered ( i.e. / -> %252F). I should make a PR soon.
