### ISSUE TITLE
Search nestedQuery scoreMode does not work

### ISSUE THREAD

**Issue by hilalbursali** [sksamuel/elastic4s#1190]
In the nestedQuery: 
nestedQuery("..").query(matchQuery("user.name" -> "...")).scoreMode("min")

If I change scoreMode to min, max or avg, score does not change

**Comment by sksamuel** [comment]
I can't see anything wrong with the nested query code. Can you give me a full example with real data.

**Comment by hilalbursali** [comment]
I have an index and there is an nested field in it:
"user" : [ { "name" : "Alice Dave" } ]

"user" : [ { "name" : "Alice Smith" }, { "name" : "John" } ]

I figured out that it does not work due to norms. The reason is 
although they have one "Alice", the second one's score is higher because of the docCount. I could not omit norms. Is there any way to make their score same so that when I change min, max, avg, it will work?
