### ISSUE TITLE
Aws4ElasticClient does not refresh credentials

### ISSUE THREAD

**Issue by jnatten** [sksamuel/elastic4s#1195]
I use `Aws4ElasticClient` to query an aws elasticsearch endpoint.
This is using Elastic4s version `6.0.1` and Elasticsearch `6.0` in aws.
I create the client like this:
```
val elasticSearchUri = "elasticsearch://endpoint.com:443?ssl=true"
val client = Aws4ElasticClient(elasticSearchUri)
```

Which works fine if you are using permanent credentials, however if you are using temporary credentials (like the ones EC2 instances get), and the client sits for a while the aws credentials expire.
This makes calls to ElasticSearch fail with a 403 and message:
```
{
  "message": "The security token included in the request is expired"
}
```

I can't see a way to refresh the credentials of the client either so as of now i have to recreate the client every time the credentials expire.

**Comment by saraiva132** [comment]
@jnatten I will look into that, it seems I might have to use a different provider that handles auto-refreshing or do it myself under the hood. Nice catch. Fixed your other issue btw, just bump the version to 6.1.1

**Comment by MatteCarra** [comment]
I have the same problem. My code is running on an ec2 instance.

**Comment by saraiva132** [comment]
@MatteCarra I was writing a solution with aws STS provider. I had/have the code ready but I was dealing with some issues with unitary tests because apparently STS Provider by default attempts to connect to a server (get initial session token I reckon), so without having a proper integration test I was not sure if it would fix the issue. 

@jnatten  Did #1207 fix this issue?

**Comment by jnatten** [comment]
@saraiva132 It looks like the problem has been solved. 

I set up an instance with master (compiled at https://github.com/sksamuel/elastic4s/tree/db8f981f3269da48ceea251f7cb319d949f7c926) in EC2 and let it sit a while and the problem hasn't occurred.
