### ISSUE TITLE
GeoHashGridAggregation issue with HttpClient

### ISSUE THREAD

**Issue by oarshad** [sksamuel/elastic4s#1198]
Following snippet works using TcpClient, however throws error with HttpClient.

          geoHashGridAggregation("geo_hash") field "latLng" precision 9 subaggs {
            topHitsAggregation("doc") fetchSource true size 1
          }

I get following error with HttpClient:
`"root_cause":[{"type":"illegal_argument_exception","reason":"[geohash_grid] unknown field [aggs], parser not found"}]`

**Comment by sksamuel** [comment]
Do you get the error when you try to use the response, or when the request is executed?
