### ISSUE TITLE
When doing a bulk operation, errors don't show up

### ISSUE THREAD

**Issue by salvob41** [sksamuel/elastic4s#1201]
Hello.

I am using elastic4s v5.6.0 (connection is TcpClient) in order to insert with a bulk operation a Twitter Stream into elasticsearch. 

The way I am using it is this:
1. Preparing requests for every tweets into an Array `requests: Array[BulkCompatibleDefinition]`. Every single element is something like: 
`indexInto(indexName, typeName) id tmd.status.id doc json_tweet`
where `tmd` is the tweet and `json_tweet` its JSON string representation

2. Execute the bulk operation:

```
client.execute {
        bulk(requests)
      }.recover {
        case e: Exception => {
          Logger.get(MODULE_NAME).warn("Attempt #" + (retryIdx + 1) + ". Writing on ES with bulk API:\n" + e.getMessage)
          return false
        }
      }.await
```

The problem is if any of this request fail for any reason. The bulk operation do not show any error message. 
For example a error message I expected to see in one of my tests is this: 

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Could not dynamically add mapping for field [tweet.options.extra_tasks]. Existing mapping for [meta.analysis.contracts.options.tweet.options] must be of type object but found [text]."
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Could not dynamically add mapping for field [tweet.options.extra_tasks]. Existing mapping for [meta.analysis.contracts.options.tweet.options] must be of type object but found [text]."
  },
  "status": 400
}
```
But the bulk operation results gives me `success`. 
The elasticsearch error here is not important, the problem is that it doesn't show up anywhere. I had to get the JSON doc e try the POST operation on kibana by myself.

Is there something I am missing? 

Thank you in advance

**Comment by sksamuel** [comment]
Which version?

**Comment by salvob41** [comment]
Sorry... I'll update the issue details. 
I am using v5.6.0 . The connection is TCP

**Comment by sksamuel** [comment]
The future will be a success if the operation completed on the elastic side, which it will either successfully or with errors. A failed future is only used for connection issues. Use the response object to find out how many errors there were (if any). See `RichBulkResponse`.

```scala
client.execute {
  bulk(requests)
 }.onComplete {
  case Success(resp) =>
    Logger.get(MODULE_NAME).info("Completed with ${failures.size} failures")
  case Failure(e) =>
    Logger.get(MODULE_NAME).warn("Attempt #" + (retryIdx + 1) + ". Writing on ES with bulk API:\n" + e.getMessage)
}
```
