### ISSUE TITLE
Index only operations fail when not provided with type

### ISSUE THREAD

**Issue by ali-h** [sksamuel/elastic4s#1202]
Since v6 we're encouraged to use index only operations but it seems that those actually still require a type to be included. For example searching using only the index name:

```scala
client.execute {
    search("myindex") query {
        ???
    }
}
```

Will fail because it will dispatch to the following `search` method:

```scala
def search(index: String): SearchDefinition = search(IndexesAndTypes(index))
```

My question: is this the intended behaviour (types are still mandatory) or an error in the implementation ?

**Comment by sksamuel** [comment]
That should delegate to a method that creates an IndexesAndTypes where the types is Nil (so no type), so search(index) is only on the index.

**Comment by ali-h** [comment]
You're right, `search` actually raises no error, sorry for that !

The ones who actually raise an error are `update("id") in "myindex"`, `indexInto("myindex")` and `delete("id") from "myindex"`

With the same questions as above for those.

**Comment by sksamuel** [comment]
You still need to use an index currently. They'll be removed in version 7. My advice right now is to do "indexname/indexname" then drop it down to "indexname" in v7.
