### ISSUE TITLE
Add filter_path to search and get

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#1208]

**Comment by keyur9** [comment]
Hello, 

Thank you for this fantastic client.

May I know if you've any plan to include filter_path to search in the near future or it is not something in the priority list?

Thank you,

**Comment by angusdavisadobe** [comment]
My work around was to implement a Handler[SearchRequest, SearchResponse] wrapper that uses the implicit object SearchHandler to build the ElasticRequest and then add the "filter_path" param to the ElasticRequest.params.

**Comment by joshhidley** [comment]
> My work around was to implement a Handler[SearchRequest, SearchResponse] wrapper that uses the implicit object SearchHandler to build the ElasticRequest and then add the "filter_path" param to the ElasticRequest.params.

@angusdavisadobe , can you elaborate or point to a code sample?

**Comment by angusdavisadobe** [comment]
I created a wrapper class for the ElasticClient and created methods to call the client with an Elastic4s SearchRequest:

`import com.sksamuel.elastic4s.http.ElasticDsl._
import com.sksamuel.elastic4s.http.search.SearchResponse
import com.sksamuel.elastic4s.http.{Handler, delete => _, _}
import com.sksamuel.elastic4s.searches.SearchRequest

import scala.concurrent.{ExecutionContext, Future}
import scala.reflect.ClassTag

class ElasticClientWrapper(protected val esClient: ElasticClient)(implicit ec: ExecutionContext) {

  def executeRequest[T: ClassTag, U](request: T)(
    implicit
    functor: Functor[Future],
    executor: Executor[Future],
    handler: Handler[T, U],
    manifest: Manifest[U]): Future[Response[U]] = {

    esClient.execute(request)
  }

  def executeSearchRequest(request: SearchRequest)(
    implicit
    functor: Functor[Future],
    executor: Executor[Future],
    manifest: Manifest[SearchResponse]): Future[Response[SearchResponse]] = {

    // extend the default handler which builds an ElasticRequest by adding the "search_type" param
    // to the list of params to work around a bug in Elastic4s version 6.7.0 and below.
    val handler = implicitly[Handler[SearchRequest, SearchResponse]]
    val newHandler = new Handler[SearchRequest, SearchResponse] {
      override def build(request: SearchRequest): ElasticRequest = {
        val esRequest = handler.build(request)
        val newParams = esRequest.params ++ Map("search_type" -> "dfs_query_then_fetch")
        esRequest.copy(params = newParams)
      }
    }

    executeRequest(request)(
      implicitly[ClassTag[SearchRequest]],
      functor = functor,
      executor = executor,
      handler = newHandler,
      manifest = manifest
    )
  }
}
`
