### ISSUE TITLE
Open field `inner_hits` for `SearchHit`

### ISSUE THREAD

**Issue by EliseevAndrew** [sksamuel/elastic4s#1229]
Class `InnerHit` has not enough fields. We cannot get id of inner document, parent, stored fields. And we cannot get the fields (but we have them in pure response).
In tcp-client we can transform inner hit result into search hit result.
The single way to parse any field from inner hits is to use field `inner_hits` map, but the field is private.

So can we open the field `inner_hits` or how we can get any field from it?
Why we have to use special class `InnerHits` rather than `SearchHits`?

**Comment by sksamuel** [comment]
Fixed in 6.3.0. All fields are now exposed and you can get the raw json if required.
