### ISSUE TITLE
completion suggestion with regex s/regex/value/

### ISSUE THREAD

**Issue by sitio** [sksamuel/elastic4s#1235]
Using the regex completion suggestion, CompletionSuggestionBuilderFn outputs  "value" on line 16, but I think it should be "regex"

`completion.regex.foreach(builder.field("value", _))`

Results in:

`{
    "suggest": {
        "NAME": {
            "completion": {
                "contexts": {
                    "type": [
                        {
                            "boost": 1.0,
                            "context": "CONTEXT_NAME",
                            "prefix": false
                        }
                    ]
                },
                "field": "suggest",
                "regex": {},
                "size": 30
            },
            "value": "REGEX_HERE"
        }
    },
    "version": true
}`

to which ES responds:

`{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "suggestion does not support [value]",
                "line": 18,
                "col": 22
            }
        ],
        "type": "parsing_exception",
        "reason": "suggestion does not support [value]",
        "line": 18,
        "col": 22
    },
    "status": 400
}`

but if that is changed from "value": "REGEX_HERE" to "regex": "REGEX_HERE" the ES query executes without error.

[Supporting elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/search-suggesters-completion.html#regex)

Best regards!

**Comment by sksamuel** [comment]
Ok, I'm not at my development pc atm, so a PR is welcome.

**Comment by sitio** [comment]
https://github.com/sksamuel/elastic4s/pull/1236

It occurs to me maybe I could have opened a PR against this issue? Apologies for the duplication if so.
