### ISSUE TITLE
HttpIndexMatchers and HttpSearchMatchers - a good idea?

### ISSUE THREAD

**Issue by lukewyman** [sksamuel/elastic4s#1242]
I'm writing my first unit tests against some elastic4s code in my project, and I'm seeing that `HttpElasticSugar` is going to be quite helpful. The TCP version of this is just `ElasticSugar`.

The matchers in `SearchMatchers` and `IndexMatchers` look useful for what I'm doing, except I'm using the `HttpClient` in my project. Proposing adding `HttpSearchMatchers` and `HttpIndexMatchers`  - does this sound useful?

**Comment by sksamuel** [comment]
Yes, sounds very useful, especially as the old TCP stuff will be removed in 7.0

**Comment by sksamuel** [comment]
The matchers in master are now updated for HTTP.
