### ISSUE TITLE
Failures in DeleteByQuery and  UpdateByQuery

### ISSUE THREAD

**Issue by b789** [sksamuel/elastic4s#1249]
Hi, 
may be a silly question but... in older version of elastic4s (with the tcp client) i used to check the failures field on the response for UpdateByQuery and DeleteByQuery to check the results and acting in response.
With the 6.1.2 version the response is a Update/DeleteByQueryResponse that doesn't seem to contain the failure information. How can i access it ? Where's same alternative way to get the same information ?

Thanks for the attention.

**Comment by sksamuel** [comment]
For now you can check the returned json I suppose, but I'll add it into the proper type for next week.

**Comment by b789** [comment]
ok, didn't think about that. thanks

**Comment by sksamuel** [comment]
It's not ideal, but it's a workaround until I do it properly for you.
