### ISSUE TITLE
ambiguous call from tcp Dsl to fuzzyQuery(String, String)

### ISSUE THREAD

**Issue by galexia1000** [sksamuel/elastic4s#1255]
using tcp Dsl:

Calling com.sksamuel.elastic4s.ElasticDsl.fuzzyQuery("x","y") is ambiguos

com.sksamuel.elastic4s.searches.QueryApi.fuzzyQuery(String, Any)
com.sksamuel.elastic4s.ElasticDsl.fuzzyQuery(String, String)

ElasticDsl extends ElasticApi 
ElasticApi extends QueryApi

**Comment by sksamuel** [comment]
TCP is deprecated now. Please switch to the HTTP client.
