### ISSUE TITLE
Missing NestedAggResult

### ISSUE THREAD

**Issue by To-om** [sksamuel/elastic4s#1259]
With elastic4s DSL, it is possible to build query with nested aggregation using [nestedAggregation](https://github.com/sksamuel/elastic4s/blob/v6.1.2/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/searches/aggs/AggregationApi.scala#L67) but I can't find any solution to get aggregation result.

If you agree, I do a PR to add a `nested(name: String): NestedAggResult` method to `HasAggregations` trait.

**Comment by sksamuel** [comment]
Yes please do.
