### ISSUE TITLE
QueryDefinition NOOP/Identity?

### ISSUE THREAD

**Issue by fooblahblah** [sksamuel/elastic4s#1267]
I can't seem to find a way to return an `Identity` or NOOP `QueryDefinition`. Currently I'm just using an empty `should` definition, but the resulting query has a long chain of empty clauses and isn't ideal for debugging.

For example:
```
{"version":true,"query":{"term":{"blah.facet":{"value":"Bogus"}}},"post_filter":{"bool":{"must":[{"bool":{}},{"bool":{}},{"bool":{}},{"bool":{}},{"bool":{}},{"bool":{}},{"range":{"year":{"gte":2000}}},{"bool":{}},{"bool":{}}]}},"from":0,"size":20,"sort":[{"price":{"order":"desc"}}]}
```

Any suggestions? Maybe I should be using a builder of some sort?

**Comment by sksamuel** [comment]
Do you just want to return all documents? If so, use `matchAllQuery()`

**Comment by fooblahblah** [comment]
Sorry for my late reply.  What I meant by identity was if you were building up a query, there are times when there's a condition which means that a component of the query def needs to be a noop. What I've been doing is returning an `Option[QueryDefinition]` from other methods and then stitching together a `should` or `must` clause by converting the Options to a List and filtering. 

Maybe I should be using a Builder of some sort?

**Comment by sksamuel** [comment]
I understand, I'll add something.

**Comment by sksamuel** [comment]
Added to master.

**Comment by fooblahblah** [comment]
Thanks! Much appreciated.
