### ISSUE TITLE
Can I disable logging for some requests?

### ISSUE THREAD

**Issue by amerpersonal** [sksamuel/elastic4s#1269]
Hi,

I have bulk request which contains around 1000 index operations and they are flooding my logs. Is there any way to disable elastic4s logging for some requests? I mean, it's ok to log search request or one document index operation, but bulk is overhead in my opinion.

Thanks,

Amer

**Comment by sksamuel** [comment]
Just don't use debug on com.sksamuel and you should be fine.

**Comment by amerpersonal** [comment]
Thanks for answer. Thing is I want logging for most of things, except for bulk. Anyway, one solution is to log other requests in my code and just set loglevel to ERROR. Which is exact log property (path) I should set in config to ERROR?

**Comment by sksamuel** [comment]
com.sksamuel.elastic4s
