### ISSUE TITLE
Wildcard in query `field`

### ISSUE THREAD

**Issue by omrihq** [sksamuel/elastic4s#1276]
I'm trying to add fuzziness on a simple query, and I'm getting some weird behavior. 
When I use `query(searchString) fuzziness "AUTO"`, I get nothing with a typo,

but if I specify the field in a matchQuery ex:
`matchQuery("field_name", searchString) fuzziness "AUTO"`
I get correct fuzzy-matching results with the same typo.

Is it possible to do `matchQuery("*", searchString) fuzziness "AUTO"`, such that "*" matches all fields? Or better yet get `query` to fuzzy match as it should?

**Comment by sksamuel** [comment]
Can you make an actual example with real data that fails, that I can use as the basis for a test to then fix.
