### ISSUE TITLE
Why switched return types of HttpClient.execute to Either?

### ISSUE THREAD

**Issue by polarke** [sksamuel/elastic4s#1278]
Response[U] seems more in Scala way than Either[RequestFailure, RequestSuccess[U]]

**Comment by sksamuel** [comment]
`scala.Either` in the scala SDK seems pretty Scala to me :)

**Comment by aloiscochard** [comment]
Hey @sksamuel, I think that was @polarke was trying to say is that encoding anything as `Either[RequestFailure, RequestSuccess[U]]` is simply nonsensical.

It's kinda like encoding a boolean as `Either[Unit, Unit]`.

Look in `HttpClient.scala` you define an awesome algebraic data type `sealed trait Response[+U]`.

It is sealed! That is awesome! That give us exhaustive checking :-)

It means that if I have a `Response` I can simply pattern match on it and treat the two different cases:
- `RequestFailure`
- `RequestSuccess`

In that regards, wrapping such response in an `Either` is just adding structural noises!
Or do you think this add any value? If yes, please show an example.

If you agree with the thinking described here, that it is non nonsensical to wrap a `Response` in an `Either`, we will be happy to provide a PR.

**Comment by sksamuel** [comment]
@aloiscochard what you have said is of course completely sensible. I have tried to remember why I did it with the ADT _and_ the Either and I am afraid I cannot remember. Therefore I must assume I was either drunk or being an idiot.

There's no need to provide a PR because I need to change this kind of stuff anyway to incorporate #1257 and #1206 and #1885. All four issues (those three plus this one) I am going to fix in a single unified far reaching commit, which will be released as part of 6.2 or 7.0

**Comment by aloiscochard** [comment]
@sksamuel thanks for the detailed answer! my gut feeling is that you wanted to use Either to get some facilities (syntax...) associated with it at some point without realizing the ADT should be enough.

I often discussed with friends the possibility of a USB device that would record my alcoholic blood level directly in my git commit messages... Ballmer peak driver programming!

Anyway, thanks again for taking feedback into account and supporting such a useful library.

**Comment by sksamuel** [comment]
Closing this in favour of the new ticket #1279

**Comment by sksamuel** [comment]
@aloiscochard @polarke  let me ask for your feedback if I may.

In the latest snapshot I have changed the return type of the client execute methods to be a Future of an ADT. But the issue I'm having myself is that I can't do a for comprehension. In ES it's common to have three states - an underlying http error like server not found, a successful request, and a request that was serviced but failed (like invalid search term). If I use an ADT I can't do,

```scala
for (result <- search("foo");
       _       <- update(result.id)) yield ...
```

I can pattern match on the result, but that means I lose the error state and just get a generic no element found error in the Future. So maybe it's best to ditch the ADT for an Either?
Your advice would be appreciated.

**Comment by aloiscochard** [comment]
Hi @sksamuel, here is what you need ~> https://github.com/sksamuel/elastic4s/pull/1293
