### ISSUE TITLE
Reindex call fails with AWS ElasticSearch Service

### ISSUE THREAD

**Issue by xnejp03** [sksamuel/elastic4s#1283]
It returns 400 error. From our findings it's due to the status line including 

`POST _reindex HTTP/1.1`

rather than 

`POST /_reindex HTTP/1.1`

All your other calls begin with slash, so this one should as well.

**Comment by sksamuel** [comment]
Fixed in master.

**Comment by sksamuel** [comment]
Fixed also in 6.1.x branch.

**Comment by sksamuel** [comment]
6.1.5 released with this fix added.

**Comment by xnejp03** [comment]
@sksamuel I can see 6.1.5 has been released but it's not available in the public repo's yet?
