### ISSUE TITLE
Can I access 'sort' on SearchHit?

### ISSUE THREAD

**Issue by amerpersonal** [sksamuel/elastic4s#1288]
Hi,

is there any chance to access 'sort' field (which is on same level as '_source') in SearchHit? I need to sort items from multi search query by sort. I know the other way to do it (using function score), but I would like an option to extract 'sort' value from each doc. Is it possible?

Amer

**Comment by sksamuel** [comment]
Will just need to expose it on the response object. I'll add it to the latest release, if you want it on an earlier version, do a PR and I'll do a release.

**Comment by Xcorpio** [comment]
❤️  need this feature too.

**Comment by sksamuel** [comment]
6.3.0 is now released with sort exposed.
