### ISSUE TITLE
wait_for_completion in ReindexHandler

### ISSUE THREAD

**Issue by b789** [sksamuel/elastic4s#1291]
the current code for the waitForCompletion parameters
```
      if (request.waitForCompletion.getOrElse(false))
        params.put("wait_for_completion", "true")
```
doesn't allow to set the parameter to false in the request. From some test it seems that the default value in elastic is true, so passing false as parameter end's up in a wrong request.

The parameter should be easily fixed by something like
`request.waitForCompletion.map( value => params.put("wait_for_completion", value.toString))
`
The problem the will be that the response handler will be unable to correctly parse the response that will be a create task response. This could be solved by changing the returned type from
`Either[ElasticError, ReindexResponse]`
to semething like
`Either[ElasticError, Either[ReindexResponse,CreateTaskResponse]]`
but i don't know if you like it (since it will break existent code) or if ther's some better way (by maybe expand the ReindexResponse to accomodate the new returned value and set all the other parameters to some default value).

**Comment by sksamuel** [comment]
I think the best solution is to change the return type to `Either[ReindexResponse,CreateTaskResponse]`, but to do this on master which will become release 6.3.0 or 7.0.0. You won't have to wait too long for those releases and they'll work with 6.2 etc as well.

**Comment by sksamuel** [comment]
This is now part of 6.3.0
