### ISSUE TITLE
Delete by query should support multiple types

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#1305]
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/delete/DeleteHandlers.scala#L39 this line shouldn't use head.

**Comment by tksfz** [comment]
Can you please also add `routing` while you're at it?

**Comment by sksamuel** [comment]
This is now fixed in 6.2.3 and 6.1.7.
