### ISSUE TITLE
can't set highlight options

### ISSUE THREAD

**Issue by def1ne** [sksamuel/elastic4s#1308]
Hello, i'm trying to create query with highlighting on 5.6.4 http client, but it seems like it ignore highlight options.
I created simple test for this:
```scala
import com.sksamuel.elastic4s.ElasticsearchClientUri
import com.sksamuel.elastic4s.http.ElasticDsl._
import com.sksamuel.elastic4s.http.HttpClient
object Test extends App {
  val client: HttpClient = HttpClient(ElasticsearchClientUri("localhost", 2000))
  val highlightFields = highlight("text")
  val options = highlightOptions()
    .preTags(List("<highlight>"))
    .postTags(List("</highlight>"))
    .requireFieldMatch(false)
    .fragmentSize(100)
    .numOfFragments(20)
  val query = search("test_index")
    .query(queryStringQuery("test"))
    .highlighting(options, highlightFields)
  println(client.show(query))
  client.close()
}
```
When it run on 5.6.4 client it show:
``` {"query":{"query_string":{"query":"test"}},"highlight":{"fields":{"text":{}}}} ```
But on 6.2.3 client it print:
``` {"version":true,"query":{"query_string":{"query":"test"}},"highlight":{"fragment_size":100,"number_of_fragments":20,"require_field_match":false,"post_tags":["</highlight>"],"pre_tags":["<highlight>"],"fields":{"text":{}}} ```

**Comment by sksamuel** [comment]
This is fixed in 6.x and 7.x releases.
