### ISSUE TITLE
Search (scroll) when index does not exist results in Exception

### ISSUE THREAD

**Issue by yannisklonatos** [sksamuel/elastic4s#1312]
Hello,

I am using the Search/Scroll API as follows:

```
val searchResults = SearchIterator.iterate[T](elasticClient,
    search(indexName).matchAllQuery.keepAlive(contextKeepAlive).size(scrollBatchSize)
)
```

This works like a charm when the index exists, however, it results in an error when the index does not exist, even when "es.index.read.missing.as.empty"  has been set to "true". 

One workaround would be to check if the index exists, then call search only if it does, but would be nice if the library can handle it and return an empty iterator, no? I see that in this case it returns sys.error(failure.toString). 

Many thanks for the awesome work and the support!

**Comment by sksamuel** [comment]
`es.index.read.missing.as.empty` is an elastic hadoop option I think rather than an elasticsearch core option. I suppose we could add something to search to do something similar.

**Comment by yannisklonatos** [comment]
Would be nice to have in the future :-) Thanks for the quick reply.

I can even work on it myself if you want, if you can give me some pointers.

**Comment by sksamuel** [comment]
You would need to add a param to `SearchRequest` and then inside the typeclass that performs the execution `SearchHandler`, it would need to look to see if the parameter is set, and catch the index not found exception if so.
