### ISSUE TITLE
Dependency on org.apache.logging.log4j - log4j-slf4j-impl

### ISSUE THREAD

**Issue by jacool** [sksamuel/elastic4s#1330]
elastic4s-tcp v6.2.3 depends on org.apache.logging.log4j - log4j-slf4j-impl
A library should not provide a specific slf4j implementation. For example, my application uses logback as an implementation and this causes a conflict with the log4j implementation from elastic4s. As a result I have to exclude log4j-slf4j-impl from elastic4s-tcp forcefully.

**Comment by sksamuel** [comment]
It used to be the case that not including this dependency would stop the elasticsearch process starting up (really). The TCP driver is just another node, so it includes the whole server code. It maybe the case that it can now be removed, but your best solution is to ditch the TCP client in favour of the HTTP client as Elastic are removing it in a future version.

**Comment by sksamuel** [comment]
Closing this as TCP is now deleted.
