### ISSUE TITLE
Issue with deleteIn

### ISSUE THREAD

**Issue by dloshkarev** [sksamuel/elastic4s#1339]
I tried everything, but still doesn't know how to use 'deleteIn'. Got this exception:

> could not find implicit value for parameter exec: com.sksamuel.elastic4s.http.HttpExecutable[com.sksamuel.elastic4s.http.ElasticDsl.DeleteByQueryExpectsQuery,U]

with this code:
```
def clearClient(client: Client): Unit = {
    import com.sksamuel.elastic4s.http.ElasticDsl._
    import scala.concurrent.ExecutionContext.Implicits.global
    val c = HttpClient(ElasticsearchClientUri("localhost", 9200))
    c.execute {
      deleteIn("client" / "myclient")
    }
  }
```

Moreover, documentation is too poor in common. For example, I tried to use your example for transformation json into objects - resp.to[Character], but it doesn't work anymore. Some code from documentation is deprecated now and 'full documentation' is pretty empty. Please, make your cool library easy to use for people who meet that for the first time

**Comment by sksamuel** [comment]
You can delete by id, or delete by query. 

If you want to clear the entire index, you can delete by query with a match all (or just delete the index and recreate it).

```scala
def clearClient(client: Client): Unit = {
    import com.sksamuel.elastic4s.http.ElasticDsl._
    import scala.concurrent.ExecutionContext.Implicits.global
    val c = HttpClient(ElasticsearchClientUri("localhost", 9200))
    c.execute {
      deleteIn("client" / "myclient").by(matchAllQuery())
    }
  }```
