### ISSUE TITLE
How should I be using the embedded node in testing?

### ISSUE THREAD

**Issue by Lugghawk** [sksamuel/elastic4s#1350]
Can we have an example of using the embedded node in testing with multiple tests? I can get a single test to run but I need a clean index for each of my tests.

```scala
  class ElasticStorageTest {
    val entity: StoredEntity = StoredEntity()
    val name: String = UUID.randomUUID().toString
    val httpClient: HttpClient = LocalNode(name, s"/tmp/elastic/$name").http(true)
    val storage: ElasticDataStorage = ElasticDataStorage(httpClient) //Creates the index "entities" etc.
  }

"Storage" should "store and retrieve an entity by id" in new ElasticStorageTest {
    storage.put(entity).await
    val retrieved = storage.getById(entity.id).await
    retrieved shouldBe entity
}

"Storage" should "store and retrieve an entity by name" in new ElasticStorageTest {
    storage.put(entity).await
    val retrieved = storage.getByName(entity.name).await
    retrieved shouldBe entity
}
```

This recreates the node, not stopping it after tests, but seems to pass. The tests just grow slower as more tests are added and more nodes are created. Adding `BeforeAndAfter` seems to let me shutdown the nodes with `httpClient.close` or `node.stop()`, but then my tests fail and I get this exception while running:

```
15:46:22.828 [pool-6-thread-4-ScalaTest-running-MissionElasticStorageSpec] ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
```

Given that I would like to test with a clean index each time, how should I be using the embedded node?

**Comment by djx314** [comment]
Is it similar to https://github.com/sksamuel/elastic4s/pull/1309 ?

**Comment by Lugghawk** [comment]
I don't believe it is but I'll admit I'm very new to elastic4s and elastic in general.

I think the difference is that in the case where I don't close I have more and more nodes running as time goes on. And in the case where I do close it seems like it's closing too early, in the middle of a request? It's hard to tell, but my tests fail because of future timeouts.

**Comment by sksamuel** [comment]
Embedded mode is a pain to use, elastic make it hard for people to actually use it.
I'd just use docker - one line and you've got a proper full server.
