### ISSUE TITLE
Integrating smartcn

### ISSUE THREAD

**Issue by ibaisi** [sksamuel/elastic4s#1351]
Trying to implement a Chinese autocomplete, I see there is no integration with Smart Chinese Analysis Plugin (https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-smartcn.html#analysis-smartcn).

I tried something like (besides multiple other things):

```
case class SmartCnTokenizer(override val name: String) extends CustomizedTokenizer(name) {
  override def build(source: XContentBuilder): Unit = {
    source.field("type", "smartcn_tokenizer")
  }
}

val chineseAutocompleteAnalyzer = CustomAnalyzerDefinition("chineseautocomplete", SmartCnTokenizer("smartcn_tokenizer"), EdgeNGramTokenFilter("name-autocomplete", Some(1), Some(10)))
```

But it doesn't solve it.

Any ideas how could I integrate the plugin?

**Comment by sksamuel** [comment]
You can now add custom tokenizers much more easily in 7.0.1
