### ISSUE TITLE
akka 2.5.x support

### ISSUE THREAD

**Issue by MadeInChina** [sksamuel/elastic4s#1352]
does any akka 2.5.x support plan?

**Comment by TrustNoOne** [comment]
akka 2.5 is binary compatible with 2.4, I am using elastic4s in production with akka 2.5 and have no problems

**Comment by sksamuel** [comment]
I'll upgrade to 2.5 for the 7.0 release.

**Comment by eltherion** [comment]
Would you mind if I upgraded that for you (actually I already have working local copy)? If no, what branch should I pull into, because `release/7.0.x` does not exist yet?

**Comment by sksamuel** [comment]
Master is the 7.0 branch. PR most welcome.

**Comment by eltherion** [comment]
https://github.com/sksamuel/elastic4s/pull/1397 Has been merged.
Hopefully that issue can be closed now.
