### ISSUE TITLE
TaskApi

### ISSUE THREAD

**Issue by asedghi** [sksamuel/elastic4s#1365]
Trying to figure out the status of a long running updateByQuery Task.
Ideally I would like to verify that the process completed and then go to the next one.  I did see the taskAPI but I couldn't get it to return a specific task (node:id).  

listTasks("K1zwwVacQp2yYvCZJLaUlQ:174403") 

FYI Im running Master..

**Comment by asedghi** [comment]
Thank you that looks great.  Any thoughts on when to verify a long running task is completed other than repeatedly asking after a set interval?

**Comment by sksamuel** [comment]
As far as I know, you have to poll the server.

**Comment by asedghi** [comment]
I didn't notice a way to get at the resp.nodeId, resp.taskId from updateByQuery.  Am I missing something?  Thank You

**Comment by sksamuel** [comment]
Released as part of 6.3.0
