### ISSUE TITLE
Please release current `master` branch as a snapshot/preview release

### ISSUE THREAD

**Issue by lustefaniak** [sksamuel/elastic4s#1373]
It seems master has much nicer result api, current `Either` on 6.2.x is a pain to use :(

It would be great if you could release preview of all components.

Thanks!

**Comment by sksamuel** [comment]
I can do a 7.0.0-prelease but the API might change slightly before release if there is a reason to (hopefully not, the Either changes are the major API change).

**Comment by sksamuel** [comment]
6.3.0 is now release with all the changes from master.
