### ISSUE TITLE
Aggregation JSON Parser

### ISSUE THREAD

**Issue by xudongzhang** [sksamuel/elastic4s#1387]
It seems that SearchRequest/SearchDefinition is missing the option of accepting an aggregation json string? Any reason of why? We are migrating some legacy code (2.4) that accepts a json aggregation string from the client. Seems that an aggregation JSON parser is necessary for this purpose, or is there any workaround that deserializes a json string to Aggregation instances? Thanks.

**Comment by xudongzhang** [comment]
What is the API that accepts the entire query string? I've yet to find it.

**Comment by xudongzhang** [comment]
It looks like SearchRequest.source accepts the entire query as a raw json string. Will give it a shot.

**Comment by sksamuel** [comment]
Did that work for you?

**Comment by mahilee** [comment]
Perhaps a similar issue?  One is required to divide up a query as follows  as 'agg' isn't joinable 
on the first req1 statement since the SearchRequest type info isn't being resolved e.g.

val req1: SearchRequest = search("itemsearch*") from (0) size (20) query {
        boolQuery.must(matchAllQuery()
        ).filter(boolQuery.must(existsQuery("isPendingRegistration")))
      }.aggs { termsAgg("aggie1", "_index") }   // fails

But this works:
      val req1: SearchRequest = search("itemsearch*") from (0) size (20) query {
        boolQuery.must(matchAllQuery()
        ).filter(boolQuery.must(existsQuery("isPendingRegistration")))
      }
      val req1a = req1.aggs { termsAgg("aggie1", "_index") }
