### ISSUE TITLE
MoreLikeThis, fields should be optional

### ISSUE THREAD

**Issue by fmeriaux** [sksamuel/elastic4s#1390]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

The `fields` attribute in` more_like_this` type queries is optional. The default value actually allows to use the compatible fields automatically.

Problem: The library forces you to enter a field, and an empty list causes a 400 error (Elasticsearch does not accept fields as an empty array).

It is therefore Impossible for me to build the request as I wish ... Can you solve this problem please? I am using version 5.6 http.

**Comment by sksamuel** [comment]
You could do moreLikeThis(Nil).

**Comment by fmeriaux** [comment]
No because Elasticsearch considers it a bad request. 
We must do not filled the attribute.

**Comment by fmeriaux** [comment]
Perfect :)

**Comment by sksamuel** [comment]
Fixed in 6.3.0
