### ISSUE TITLE
Setting Preference results in 400 error

### ISSUE THREAD

**Issue by steve-e** [sksamuel/elastic4s#1398]
{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown` key for a VALUE_STRING in [preference].","line":1,"col":30}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [preference].","line":1,"col":30},"status":400}

The problem is that the preference is set in the request body but it should be a query param
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html

**Comment by sksamuel** [comment]
Fixed in 6.3.0
