### ISSUE TITLE
Hit._source is null when searching with storedFields 

### ISSUE THREAD

**Issue by dcram** [sksamuel/elastic4s#1405]
Using elastic4s 6.2.2, I get a NPE due to hit's `_source` field being null when reading results with HitReader.

The search query code:

```scala
    val resp = client.execute {
      search("myindex") query {
        qDef
      } limit 100 storedFields ("a")
    }.await
```

The response reading code:

```scala
  implicit object MyHitReader extends HitReader[MyCls] {
    override def read(hit: Hit): Either[Throwable, MyCls] = {
      val map = hit.sourceAsMap
      // map is NULL
    }
  }
```

Of course, the field `a` is well defined on the returned document. Everything is fine again when passing `List.empty` instead of `"a"` to `storedField(...)`.

Am I doing anything wrong ?

Thx

**Comment by sksamuel** [comment]
When you use storedFields, the source will not be included by default. So you just need to add .fetchSource(true) to your request.
