### ISSUE TITLE
Allow to recover the total hits when going through the stream.

### ISSUE THREAD

**Issue by fmeriaux** [sksamuel/elastic4s#1420]
The elasticsearch scroll API returns the total hits during the search. But elastic4s does not recover this information. 

Instead of returning a stream directly, it should be wrapped in an object containing more information about the response.

**Comment by sksamuel** [comment]
Agreed.

A PR for master is welcome, otherwise I will pick it up when I have chance.

**Comment by sksamuel** [comment]
Which part of the API are you using. The `SearchIterator` ?

**Comment by fmeriaux** [comment]
I use Reactive Stream (http), with publisher. 

```
val publisher = client.publisher(search in "myindex" query "sometext" scroll "1m")
```

Then I transform the publisher into an Akka source.

**Comment by sksamuel** [comment]
I think the best thing here is to write a proper akka streams source and sink. Then we can return a materialized value which gives more control.

**Comment by fmeriaux** [comment]
I agree.

**Comment by fmeriaux** [comment]
Still relevant!

**Comment by fmeriaux** [comment]
Still relevant!

**Comment by fmeriaux** [comment]
Still relevant!
