### ISSUE TITLE
Multiple unboundedFrom/unboundedTo ranges in DateRangeAggregation

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#1424]
Date range aggregation in Elasticsearch supports multiple `unboundedTo`/`unboundedFrom` ranges (like normal ranges). However, elastic4s supports only one `unboundedTo` and one `unboundedFrom` range per aggregation. That is wrong because there should be no difference in support for all the range types.

Please add support for multiple `unbounbedTo`/`unbounderFrom` ranges in `DateRangeAggregation`.

And that is a regression bug; elastic4s 5.x supports them fine.

**Comment by sksamuel** [comment]
I have changed this but coming to write a test and I'm thinking, how does having multiple unbounded make sense. If you have an unbounded to, then that's everything less than the value, so if you have two where do the values go?

**Comment by maxcom** [comment]
We use facets with overlapping ranges like "today", "this week", "this
month" and so on. They all uses unbounded from.

вс, 24 июн. 2018 г., 16:42 Stephen Samuel <notifications@github.com>:

**Comment by sksamuel** [comment]
Ok.

**Comment by sksamuel** [comment]
Fixed in 6.3.0

**Comment by ayyappanramamuniappa** [comment]
@sksamuel Why not do the same for other range aggregations as well? We have similar requirement for double field. Why can't we have same kinda interface for all type of range aggregations?
