### ISSUE TITLE
Support for custom queries

### ISSUE THREAD

**Issue by kraanerk** [sksamuel/elastic4s#1429]
Currently QueryBuilderFn supports a strictly fixed set of classes extending Query.
Why not to add an abstract CustomQuery which allows its implementations provide the XContentBuilder suitable for their needs?

```
trait CustomQuery extends Query {
  def buildQueryBody() : XContentBuilder
}
```

**Comment by sksamuel** [comment]
Because prior to the current master, it was complicated by the fact the TCP and HTTP implementations both shared the core definitions.

Now we can do exactly this.

**Comment by sksamuel** [comment]
This is supported in 7.0
