### ISSUE TITLE
SocketTimeoutException when using bulk index

### ISSUE THREAD

**Issue by xudongzhang** [sksamuel/elastic4s#1433]
We get `java.net.SocketTimeoutException `from `com.sksamuel.elastic4s.http.JavaClientExceptionWrapper` while doing bulk index. In the ES Java REST client, there is a place to set the socket timeout value via RequestConfigBuilder. Where can I do this in the `elastic4s` http API?

**Comment by sksamuel** [comment]
When you make the ElasticClient you can pass in a callback which allows you to configure the client.

**Comment by t83714** [comment]
@xudongzhang 
Had the similar issue in my project when upgrading from v5.6.0.
Here is one example to change the settings and hope it helps:
https://github.com/magda-io/magda/blob/77e21ee22231de2d6485dd4ef113782b51a937a6/magda-scala-common/src/main/scala/au/csiro/data61/magda/search/elasticsearch/ClientProvider.scala#L34

**Comment by xudongzhang** [comment]
@t83714 Thanks!
