### ISSUE TITLE
Question: HTTP compatibility

### ISSUE THREAD

**Issue by fmeriaux** [sksamuel/elastic4s#1434]
Hello,
We use an Elasticsearch 5.6.x, and in our application we use elastic4s with the same series.

My question is, since the REST APIs are normally backward compatible (with the exception of the announced changes (https://www.elastic.co/guide/en/elasticsearch/reference/6.1/breaking_60_rest_changes.html) its a good idea to upgrade elastic4s in the latest version (6.x) to take advantage of SDK improvements, without upgrading Elasticsearch cluster ?

**Comment by sksamuel** [comment]
It won't hurt your cluster to try. Worst case scenario is that a request will give an error on the elasticsearch side, but I think 99% of requests should be fine as long as you don't try to use a new feature which isn't supported by your cluster.

**Comment by sksamuel** [comment]
I should add, ES are quite good about keeping the HTTP syntax backwards compatible as it's the interface for all the non-Java-TCP clients (ie almost everything).

**Comment by fmeriaux** [comment]
Ok, that's what I thought. Thank you for your quick reply.
