### ISSUE TITLE
SearchResponse.completionSuggestion throws NPE when there are no suggestions

### ISSUE THREAD

**Issue by litalt** [sksamuel/elastic4s#1435]
Hi, 

We recently migrated to 6.1.1 version and see that when there are no suggestions for specific suggester, suggest map is null instead of empty. Since "suggest" is private val in SearchResponse, we can't even access it and wrap it with Option(...).getOrElse(Map.empty) but have to wrap the searchResponse.completionSuggestion with try catch block.

Can this be fixed to empty map instead of null?

**Comment by sksamuel** [comment]
Fixed in 6.3.1
