### ISSUE TITLE
Support for typed_keys in Search and MultiSearch

### ISSUE THREAD

**Issue by DeepakMohan** [sksamuel/elastic4s#1436]
It looks like SearchHandler constructs ElasticRequest with params, but the Search- and MultiSearch Definition does not allow to pass additional query params. I was looking for an option to include `typed_keys` to the request but could not find it. Any pointers or enhancement would be greatly appreciated.

`ElasticRequest("POST", "/_msearch", params.toMap, entity)`

**Comment by sksamuel** [comment]
We will need to add a parameter to `MultiSearchRequest` and `SearchRequest`. And then handle that in `SearchHandler` and `MultiSearchHandler`.

PR Welcome.

**Comment by DeepakMohan** [comment]
Thanks for the reply @sksamuel. I will submit a PR shortly.
