### ISSUE TITLE
6.3.0/6.3.1: no public release

### ISSUE THREAD

**Issue by Dbzman** [sksamuel/elastic4s#1438]
Hey,

when we wanted to use elastic4s 6.3.0 we noticed that there's no public release yet for the mentioned versions.
Would be nice if you could release it as it seems there are some useful fixes in it for us. 😋 

Thanks a lot!

**Comment by sksamuel** [comment]
Yeah it was missing but went out this morning. 6.3.1 is out too now. You can see them in maven central here:
http://repo1.maven.org/maven2/com/sksamuel/elastic4s/elastic4s-http_2.12/

**Comment by Dbzman** [comment]
Thank you very much! 👍
