### ISSUE TITLE
Path prefix client configuration

### ISSUE THREAD

**Issue by nicholastmosher** [sksamuel/elastic4s#1439]
Hi all. I'm trying to use the elastic4s http client to access an elasticsearch instance which is mounted at `/elasticsearch/` on my application server (i.e. a query would go to `/elasticsearch/my_index/my_type/_search`). The Javascript client has a host configuration section where one of the options is a "path" variable ([found here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/host-reference.html#_params)) which adds a path prefix to all of the requests, but I'm unable to find a similar configuration in elastic4s. Is this currently supported or is there another name for the configuration? Any help with this would be greatly appreciated.

**Comment by sksamuel** [comment]
I've updated the way the URIs is created for the next release (6.3.3). So you'll be able to specify the path prefix by using a uri like `http(s)://host:port,host:port/prefix?options`

**Comment by sksamuel** [comment]
Try 6.3.3
