### ISSUE TITLE
SearchHit `.highlight` can be null

### ISSUE THREAD

**Issue by yannick-cw** [sksamuel/elastic4s#1444]
If I have no highlights in the `SearchHit` and access the `highlight` field, it is null.

Can we make `highlights` map optional or an empty map by default?

[here](https://github.com/sksamuel/elastic4s/blob/65ce0d8b46e45c2ea0ee7d3191fb7a33194b6b00/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/responses.scala#L25)

version `6.2.6`

**Comment by sksamuel** [comment]
Fixed in master.
