### ISSUE TITLE
Access to SubAggregation Data

### ISSUE THREAD

**Issue by deepakmohanakrishnan1984** [sksamuel/elastic4s#1452]
It looks like the sub-aggregation response data that does exist in most of the `Aggregations` response are private to `elastic4s` package. Is there any way to access it outside the package in my application. Or could you please make it not private?

For e.g.: 
```case class TermBucket(key: String, override val docCount: Long, private[elastic4s] val data: Map[String, Any])```

Any pointers or samples to access this `data` field would be greatly appreciated.

**Comment by sksamuel** [comment]
We could add a method to make it available, that way we can check if it's null and make it map.empty. PR welcome.

**Comment by deepakmohanakrishnan1984** [comment]
Addressed in PR #1478
