### ISSUE TITLE
GetTaskStatus

### ISSUE THREAD

**Issue by asedghi** [sksamuel/elastic4s#1454]
If a task errors out for some reason,  there is no way to tell something went wrong.  Ideally GetTaskStatus should also return error. This is provided by Elasticsearch when making a task request.

Thanks

**Comment by sksamuel** [comment]
The documentation doesn't cover the format for errors. Do you have a sample of the json ?

**Comment by sksamuel** [comment]
I cannot add the feature without sample errors, so closing for now.
