### ISSUE TITLE
Significant terms aggregation result is missing in elastic4s-http

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#1458]
Significant terms aggregation result is missing in elastic4s http client:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html

**Comment by sksamuel** [comment]
Do you want to add a PR ?

**Comment by sksamuel** [comment]
Addressed by https://github.com/sksamuel/elastic4s/pull/1485
