### ISSUE TITLE
TermsSetQuery not working inside bool query

### ISSUE THREAD

**Issue by cristinaluengoagullo** [sksamuel/elastic4s#1461]
Hi,

First of all thanks for the great work you've done with this library! I'm using the release 6.x and I just started using the termsSetQuery function, but I get errors when I try to use it inside a must, filter, etc. I saw that it doesn't inherit from QueryDefinition, could that be the case why it doesn't let me use it inside a must for instance?
Thanks!

**Comment by cristinaluengoagullo** [comment]
Any insight on this please?

**Comment by sksamuel** [comment]
Yep, it should extend 'Query'. I've pushed a change, will do a release soon. This is the 6.3.x release.

**Comment by sksamuel** [comment]
Try 6.3.6

**Comment by cristinaluengoagullo** [comment]
Ok thank you very much!! Once it's available in mvn repository I'll try it.

**Comment by sksamuel** [comment]
It's there now.
http://repo1.maven.org/maven2/com/sksamuel/elastic4s/elastic4s-http_2.12/

Those UI sites take a lot longer to update than the actual repository.

**Comment by cristinaluengoagullo** [comment]
Hi @sksamuel,

Thanks for the very fast reply! Unfortunately I wasn't able to make the query work :( I first tried with the api (termsSetQuery), which accepts the field name and the terms to look for. It returned me the following error:

"caused_by": {
            "type": "illegal_state_exception",
            "reason": "No minimum should match has been specified"
          }

Then I tried building the query without the api, calling TermsSetQuery with minimumShouldMatchScript and a very simple script, but the resulting query didn't have the minimum_should_match_script field. I checked the code, and perhaps it has to do with this (if not, please let me know!):

object TermsSetQueryBodyFn {
  def apply(t: TermsSetQuery): XContentBuilder = {
    val builder = XContentFactory.jsonBuilder().startObject("terms_set")
    builder.startObject(t.field)
    **builder.array("terms", t.terms.map(_.toString).toArray[String])
    t.minimumShouldMatchField.foreach(builder.field("minimum_should_match_field", _))**
    builder.endObject().endObject()
  }
}

It seems to build the "minimum_should_match_field" if present, but it doesn't add the "minimum_should_match_script" field. Then I tried setting the "minimumShouldMatchField", but since it only accepts an Option[Int], I can't make it point to any field in the documents (for what I understand, the minimum_should_match_field's value should be the name of a field). 

Again, thank you so much for your work and diligence! And if there's anything wrong in what I said please let me know!

**Comment by sksamuel** [comment]
Seems like the query needs to be updated to generate the proper JSON. If you do a PR I'll do a release.

**Comment by cristinaluengoagullo** [comment]
Ok thanks!!

**Comment by cristinaluengoagullo** [comment]
I already did the PR (#1505 ), thanks again!

**Comment by cristinaluengoagullo** [comment]
Hi! Just wanted to ask, is there any prevision on when the next release will be? thanks so much!

**Comment by sksamuel** [comment]
I've released 3.6.7

**Comment by cristinaluengoagullo** [comment]
Thanks so much!!

**Comment by cristinaluengoagullo** [comment]
Sorry, I meant when release 6.3.7 will be available. Thanks so much again!

**Comment by cristinaluengoagullo** [comment]
Sorry to insist, but it's on in the maven repository yet right? Thanks so much!!

**Comment by sksamuel** [comment]
Hmmm it's not there. Let me do another release.

**Comment by cristinaluengoagullo** [comment]
Thanks again and sorry for the inconvenience!!

**Comment by sksamuel** [comment]
It's there now:
http://repo1.maven.org/maven2/com/sksamuel/elastic4s/elastic4s-http_2.12/

**Comment by cristinaluengoagullo** [comment]
Thanks a lot for everything!!
