### ISSUE TITLE
SearchRequest 'version' set to true if not defined by the user

### ISSUE THREAD

**Issue by ali-h** [sksamuel/elastic4s#1462]
When building a `SearchRequest`, I would assume that if I don't explicitly set the `version` parameter (leaving it to the default of `None`) it shouldn't be included in the request sent to Elasticsearch.

Current behaviour is to set it to true by default 
https://github.com/sksamuel/elastic4s/blob/ac137de93cf301f517c39f913afcd28338ed5d5b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/SearchBodyBuilderFn.scala#L22
and eventually override that by the user provided value, if any.
https://github.com/sksamuel/elastic4s/blob/ac137de93cf301f517c39f913afcd28338ed5d5b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/SearchBodyBuilderFn.scala#L25

Is this on purpose ?

**Comment by sksamuel** [comment]
Bug for sure.
