### ISSUE TITLE
GeoShapeQueryDefinition not implemented for the TCP client.

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#1470]
Hi Samuel, how are you!

I was wondering to use GeoShapeQueryDefinition under TCP client but I have found that the type of query is only implemented for Http client. I'm using 6.2.10 version. Is there a chance that you can include this query definition also for the TCP client?

I don't know how to achieve this because the QueryBuilderFn is not extensible, so I think the only way is to register the correspondent query builder:
"case q: GeoShapeQueryDefinition => GeoShapeQueryBodyFn(q)"

I would appreciate any help yo can bring me!

Regards,
Patricio.

**Comment by sksamuel** [comment]
TCP is deprecated. I'll merge a PR and release but I'm not doing further updates to it.

**Comment by pgorin** [comment]
Thanks a lot man. I will make the PR.

Another question, I' ve tried a few opportunities to migrate to the HTTP client wrapper, but I have found that the DSL was not yet fully implemented, at least at the same level that the the TCP client is.
Is right now the HTTP client a bit more completed in that way? Because I can try again to replace the TCP and start using finally the HTTP client.

Thanks!

**Comment by sksamuel** [comment]
The HTTP overall is better than the TCP client and has been since about version 6.0.0 really. Of course there are still some small functions that haven't been migrated that if you need, you could do a PR for very quickly.

**Comment by pgorin** [comment]
Samuel, nice to meet you again!

I have almost migrated to HTTP client :)!!!!!
The only issue I've already found is trying to retrieve reverseNestedAgg from search response.
I see that all (or most) aggs can be accessed using the correspondent agg result holder, but in the case for a reverse nested I could not found any helper or case class at all.

Due a reverse nested agg is conceptually a wrapper, I don't know if this is missing or not yet implemented or if I have to implement retrieval code in another way.

Thanks again for all your help and work!

Regards,
Patricio.

**Comment by sksamuel** [comment]
It just needs to be added like the others. Quickest way is a PR to add what you want, just copy n paste the others.

**Comment by sksamuel** [comment]
Ok to close this ?
