### ISSUE TITLE
Elastic4s 6.3.5 Documentation

### ISSUE THREAD

**Issue by Touzii** [sksamuel/elastic4s#1486]
Hello,

Is there any official documentation of the 6.3.5 version?
I have noticed that there is a lot of changes between the latest version and the one I used a few months ago (6.1.X)

**Comment by sksamuel** [comment]
Not at the moment.

The biggest change is the return types. You don't get an Either anymore.

**Comment by Touzii** [comment]
But I can't find the package "import com.sksamuel.elastic4s.ElasticDSL" in this version.

**Comment by sksamuel** [comment]
You're upgrading to the http client yes?
You need the module called `elastic4s-http`
And the import is com.sksamuel.elastic4s.http.ElasticDsl

**Comment by ztouzi** [comment]
I think that a lot of things has changed.

How could I create an HTTP client from an ElasticNodeEndpoint instance?  since ElasticsearchClientUri is deprecated

Could I use elastic4s 6.1.4 with elasticsearch 6.3.X ?
