### ISSUE TITLE
Missing _routing field on Inner Hit

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#1489]
Sometimes ES (v6.3.3) returns _routing field on nested inner hit, but in weird situations this field is missing from ES search response. I have found the error reported to ES but it is not resolve for the search I am performing.

I was wondering if _routing field can be handled optionally when deserializing InnerHits object.
The class InnerHit (package com.sksamuel.elastic4s.http.search) requires a string value for it.

Perhaps we can handle an empty string for this case o refactor the case class in order to hold an Option[String].

I am sorry that I can not be more precise in order to reproduce the bug, but I need to resolve this issue when reading inner hits using HTTP Client.

Stephen, if you approve this change, I can make a PR. Please let me know if we can deal with an empty string or the option approach is more clear.

Regards!

**Comment by pgorin** [comment]
Great, working on it!

Thanks!

**Comment by pgorin** [comment]
Stephen, another question. Is there a public repo with snapshot versions available?
Thanks again!

**Comment by sksamuel** [comment]
6.3.6 released.

**Comment by pgorin** [comment]
Thanks again!
