### ISSUE TITLE
Implicit Handler

### ISSUE THREAD

**Issue by Touzii** [sksamuel/elastic4s#1508]
Hello,
Could we have an example of creating an index using the latest version of elastic4s.
This is my code so far :

`
def setupIndex(indexName: String) = { httpClient.execute { createIndex(indexName).alias(inProgressIndexAlias) }.flatMap{ case res: RequestSuccess[CreateIndexResponse] => Future.successful( res.result ) case err: RequestFailure => Future.failed(new Throwable(err.error.reason)) } }
`

I have the following error :

> could not find implicit value for parameter handler: com.sksamuel.elastic4s.http.Handler[com.sksamuel.elastic4s.indexes.CreateIndexRequest,U]

How could I define the implicit Handler.
Thank you guys for considering my request.

**Comment by sksamuel** [comment]
You need to import ElasticDsl._

**Comment by Touzii** [comment]
Thank you (y)
