### ISSUE TITLE
Get RequestFailure on ScrollPublisher

### ISSUE THREAD

**Issue by brunoballekens** [sksamuel/elastic4s#1510]
Would be nice if we could get the `RequestFailure` on a `ScrollPublisher` if the search fails. 
This could be done giving the subscriber an exception (a subclass of RuntimeException?) "wrapping" the RequestFailure iso now giveing a RuntimeException with as message the `toString()` of RequestFailure (see elastic4s-http-streams/src/main/scala/com/sksamuel/elastic4s/streams/ScrollPublisher.scala#L151)

I would like this to be able to give better error message to end-user if something fails .
Now I need to parse the toString of a case class

**Comment by sksamuel** [comment]
ScrollPublisher could do with a re-write. Are you using it with akka streams ?

**Comment by brunoballekens** [comment]
Yes indeed

**Comment by sksamuel** [comment]
What I really want to do is a add a specialised akka streams source and sink, replacing the generic reactive streams one.

**Comment by francisdb** [comment]
Can we un-stale this one? We are still doing some ugly string parsing to find out there was a `Batch size is too large` error.
