### ISSUE TITLE
Incorrect phrase suggestion field name in release/5.6.x

### ISSUE THREAD

**Issue by jcoster** [sksamuel/elastic4s#1525]
In branch `release/5.6.x`, `SearchBodyBuilderFn` sets an incorrect field name for phrase suggestion queries. The field is set as "max_error" but should be "max_errors" (as documented here: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-suggesters-phrase.html). Here is the code in question: https://github.com/sksamuel/elastic4s/blob/release/5.6.x/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/SearchBodyBuilderFn.scala#L138. This causes the query to error out when the `phrase.maxErrors` field is set.

This has been fixed in future releases compatible with Elasticsearch 6.x, but it would be good to have this fixed for Elasticsearch 5.x clusters.

Fixed in PR #1524

**Comment by sksamuel** [comment]
Merged
