### ISSUE TITLE
Is there a way to perform a truly raw query?

### ISSUE THREAD

**Issue by mcross1882** [sksamuel/elastic4s#154]
Right now the search dsl provides a way to execute `rawQuery` statements however this call wraps the raw query with some boilerplate json. Is there a way to execute queries without the extra json? For instance passing something like this into the raw query call will fail...

``` json
{
    "size" : 0,
    "query" : {
        "filtered" : {
            "query" : { "match_all" : {}},
            "filter" : {
              ...
            }
        }
    },
    "aggs" : {
       ...
    }
}
```

because it gets translated into this...

``` json
{ "query" : {
{
    "size" : 0,
    "query" : {
        "filtered" : {
            "query" : { "match_all" : {}},
            "filter" : {
              ...
            }
        }
    },
    "aggs" : {
       ...
    }
}
}}
```

I haven't dived too deep into the Java API but maybe that might be the solution here or maybe the DSL already supports this either way any help would be much appreciated!

Best,
Matt

**Comment by l15k4** [comment]
Hey, what are you guys using to perform raw json request/response handling? Did you end up with entirely custom implementation including http connection and json serialization/deserialization? I just need to use elasticsearch-cloud-aws plugin for s3 backup... Thank you
