### ISSUE TITLE
Release new version and automate snapshot releases

### ISSUE THREAD

**Issue by Dbzman** [sksamuel/elastic4s#1555]
Hey there, 😃 

back in September there was a fix regarding a warning #1517. Since then no release has happened. It would be nice if you could release a new version, please. Also I would propose again to think about some automated process for that to at least release snapshot versions. Currently for us the only way to get the fix would be to build elastic4s manually and upload it to our internal repositories. This is something we would like to avoid.

BTW: Keep up the good work, man! 👍 

Cheers and many thanks!
Timo

**Comment by sksamuel** [comment]
I've just done this for KotlinTest so I think it should be easy enough to do here too.

**Comment by sksamuel** [comment]
Snapshot releases are now published to https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/elastic4s/ on every commit to master.
