### ISSUE TITLE
Parsing terms aggregation fails for large datasets

### ISSUE THREAD

**Issue by wrwills** [sksamuel/elastic4s#1556]
In an index containing many documents it is possible to have so many documents that the document count will be a long.

This is reflected in lines like the following in aggresponses.scala:
map("doc_count").toString.toLong,

However, terms aggregations try to parse "sum_other_doc_count" as an Int:
data("sum_other_doc_count").toString.toInt 

This should be changed to convert to a Long as it is likely if the entire document count is a long then sum_other_doc_count will also be a long.

**Comment by sksamuel** [comment]
Pr welcome.
If you change it I'll release.

**Comment by wrwills** [comment]
PR forthcoming

**Comment by wrwills** [comment]
Should one do a PR for other branches -- eg 6.2 6.1 as well?

**Comment by sksamuel** [comment]
Would be good yes!
