### ISSUE TITLE
Invalid build in Maven repo

### ISSUE THREAD

**Issue by sunilpes** [sksamuel/elastic4s#1560]
https://mvnrepository.com/artifact/com.sksamuel.elastic4s/elastic4s 
download the latest Jar file. It has 276Bytes. 

It has invalid build for the latest releases like 1.6.0. Please check and revert

**Comment by sunilpes** [comment]
Is there anyone using this library worried about this issue?

None of the Maven builds after v1.5.14 has proper build.

**Comment by sksamuel** [comment]
What do you mean by "proper build" ?

**Comment by sunilpes** [comment]
@sksamuel Please check this jar file. It is of no use.
http://central.maven.org/maven2/com/sksamuel/elastic4s/elastic4s_2.11/1.6.0/elastic4s_2.11-1.6.0.jar

**Comment by sksamuel** [comment]
You want elastic-http:

https://search.maven.org/search?q=elastic4s-http

That is one place the docs are up to date.

**Comment by sunilpes** [comment]
i tried with elastic4s-core along with elastic4s-http but test cases were
not sufficient to figure it out the usage.

btw may i know what that elastic4s package has ??

**Comment by sksamuel** [comment]
Tests are located here:
https://github.com/sksamuel/elastic4s/tree/master/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s
