### ISSUE TITLE
sample code doesn't work

### ISSUE THREAD

**Issue by sunilpes** [sksamuel/elastic4s#1561]
I'm new to this library and I have found that sample examples in this repo are outdated and in the `readme.md` file. Please help me to find a good example to use this library.

**Comment by sksamuel** [comment]
The unit tests are the best way.

**Comment by sunilpes** [comment]
I would be of great help if u could update the example.

**Comment by sksamuel** [comment]
I plan to, but not today.

**Comment by sunilpes** [comment]
Thank u :)
