### ISSUE TITLE
Type support in ElasticSearch 6 Query String Queries

### ISSUE THREAD

**Issue by CarterWilliam** [sksamuel/elastic4s#1565]
Thanks for the great library!

As of ElasticSearch 6 Query String Queries support a `type` field for allowing different behaviour for matches across multiple fields ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-query-string-query.html#_multi_field)). I don't believe that elastic4s supports this parameter yet and can't think of a way to replicate this behaviour without manipulating the query string. If I implement this and raise a PR will you consider merging it?

**Comment by sksamuel** [comment]
Absolutely
