### ISSUE TITLE
No way to access underlying java client.

### ISSUE THREAD

**Issue by jrouly** [sksamuel/elastic4s#1579]
The docs [mention that it's possible](https://github.com/sksamuel/elastic4s#dsl-completeness) to access the underlying java client by using `.java`.

However, I've been unable to find any evidence of this -- nowhere can I find `.java` implemented.

Is the documentation out of date? Or am I missing the correct way to call `.java`?

**Comment by sksamuel** [comment]
Yes its out of date, that was when it was the TCP driver we were wrapping. Now it's a clean room implementation of the HTTP protocol.
