### ISSUE TITLE
High level rest client? 

### ISSUE THREAD

**Issue by haorlin** [sksamuel/elastic4s#1581]
Looks like the elastic4s-http library uses the Elasticsearch low level REST client so there's no request/response marshalling. The API that I've been working on has been relying on the specific objects that the TCP client used to return. 

Are there any plans to use the high level REST client for HTTP in the future?

**Comment by sksamuel** [comment]
No, the HTTP rest client was very basic when I started HTTP support for elastic4s.
I suppose if at some point in the future there's parity then we could switch over to it, but right now is there any benefit ?

**Comment by haorlin** [comment]
The biggest benefit for my use case was that it was easier to parse/extract information from a nested aggregation if I could tell what type of aggregation the response was vs just a Map[String, Any].

Just wondering, what kind of features is the current high level API missing?

**Comment by sksamuel** [comment]
I haven't looked at the high level api in a few releases. The other downside is we'd have to use all the awful java classes (if its still the same implementation as it was back in 5.4 or whatever they started it).

Whatever they are doing to "detect" the aggregation type, we can do the same.

**Comment by haorlin** [comment]
Yeah, thats true, I think they are still the same implementations since 5.6.

I'll look into it when I have time to see if it would be easy to do. Thanks for the reply!
