### ISSUE TITLE
Where are the monix instances?

### ISSUE THREAD

**Issue by thobson** [sksamuel/elastic4s#1584]
Hi, I'm trying to use Monix Task as my F. but `com.sksamuel.elastic4s.monix.instances._` is not found. 
I tried the 6.5.0 and 6.2.10 releases. Which dependency do I need? Currently I'm using

```
    "com.sksamuel.elastic4s" %% "elastic4s-core" % elastic4sVersion,
    "com.sksamuel.elastic4s" %% "elastic4s-http" % elastic4sVersion,
    "com.sksamuel.elastic4s" %% "elastic4s-embedded" % elastic4sVersion,
    "com.sksamuel.elastic4s" %% "elastic4s-circe" % elastic4sVersion
```

Thanks!

**Comment by sksamuel** [comment]
You need "com.sksamuel.elastic4s" %% "elastic4s-monix" % elastic4sVersion
