### ISSUE TITLE
Missing script handling in percentile aggregation

### ISSUE THREAD

**Issue by napgab** [sksamuel/elastic4s#1585]
Percentile aggregation works only on a field. 
The script definition is not serialized at all in the PercentilesAggregationBuilder.
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/aggs/PercentilesAggregationBuilder.scala

The same issue was already submitted past year, resolved and tagged as closed, but seems still unresolved.
https://github.com/sksamuel/elastic4s/issues/948

**Comment by sksamuel** [comment]
If you add a PR I will do a release with the fix thanks.

**Comment by napgab** [comment]
PR created. Because this issue is a bit old, will be great integrate this fix also in older versions, not only on the latest release.

**Comment by sksamuel** [comment]
If there's a version you need the fix releasing against, please make a PR against that version and I will do a release.
