### ISSUE TITLE
Current terms aggregation include/exclude does not handle exact match set-of-1 case.

### ISSUE THREAD

**Issue by c-dante** [sksamuel/elastic4s#1627]
Elastic Search [6.x] supports 2 methods of filtering values in a terms aggregation, by regex or by exact values:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_3

The RegEx format has the `"include"` and `"exclude"` properties as a string. Exact value matches has them as arrays.

The current logic for building the terms aggregation treats all sets of 1 as the regex form:
https://github.com/sksamuel/elastic4s/blob/23b22490b9381423cf3f6571b4decdef436551c5/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/searches/aggs/TermsAggregationBuilder.scala#L19-L30

Specifically, `case include :: Nil => builder.field("include", include)` is the logic that won't fly.

Could patch it with an explicit flag on the TermsAggregate to treat IncludeExclude as exact or regex instead of forcing it in the size-of-1 case.

I'm not sure how many other places are using the IncludeExclude bundle to do this. Also, while it is "useless", it is a valid ES query to send an empty array along in the include/exclude exact match. You get empty buckets, but the rest of the application logic won't need to handle edge cases if the query is allowed to be built like that.

I can hack around it for now by putting in a bogus item into the set if it's a size of 1

**Comment by sksamuel** [comment]
Thanks for the bug report. I've vastly improved this for 7.0 to allow specifiying regex or exact of size 1.
