### ISSUE TITLE
Add missing word_delimiter_graph in TokenFilter

### ISSUE THREAD

**Issue by ZanonEdoardo** [sksamuel/elastic4s#1628]
In `com.sksamuel.elastic4s.analyzers.TokenFilter` miss `word_delimiter_graph`.
WordDelimiterTokenFilter uses `word_delimiter` that is deprecated in favour of `word_delimiter_graph` in lucene and works bad in elasticsearch 6.2.x +

Can be useful?

ref: 
- https://github.com/elastic/elasticsearch/issues/28474
- https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-graph-tokenfilter.html

**Comment by sksamuel** [comment]
I've added this to 7.0.1
