### ISSUE TITLE
Noop not working for update request

### ISSUE THREAD

**Issue by 0lejk4** [sksamuel/elastic4s#1640]
https://github.com/sksamuel/elastic4s/blob/9b1cdfabb84a1d1a7d6f819be83eb98bb5af5c27/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/update/UpdateBuilderFn.scala#L43
You always set detectNoop to true and if it is None you leave it not set and default value in elasticsearch for noop is true, so there is no way to set it to false in elastic4s.

**Comment by sksamuel** [comment]
Thanks for the fix.
