### ISSUE TITLE
Support to ElasticSearch 6.6

### ISSUE THREAD

**Issue by napgab** [sksamuel/elastic4s#1652]
It is expected to release a new version with support to ES 6.6? I don't see any milestone related

**Comment by sksamuel** [comment]
I will release one soon, but you can just use the 6.5 client - the actual JSON has barely changed.

**Comment by t83714** [comment]
@sksamuel 
Can I use 6.3 client with 6.5 / 6.6 ElasticSearch?

**Comment by sksamuel** [comment]
Yes, although there may be some places where the json changed (can't think
of any off the top of my head).

**Comment by fabriziofortino** [comment]
@sksamuel any ETA for the next release? I am really looking forward to see #1629 fixed. Thank you

**Comment by sksamuel** [comment]
The 7.0 release is out, and will work with 6.6 as well.
