### ISSUE TITLE
What will the embedded module be replaced with?

### ISSUE THREAD

**Issue by cloudjohnson** [sksamuel/elastic4s#1656]
I'm working through the local test example in the README.md, and the `LocalNode` is coming up as deprecated, "The elasticsearch embedded module will be removed in 7.0". There is no indication of an alternative. What should we be transitioning to for local testing?

```scala
val localNode = LocalNode("mycluster", "/tmp/datapath")
```

**Comment by sksamuel** [comment]
Docker I would suggest.

The Local Node has been a hack for a while. Elastic don't make it available
for easy use.
There's always this as well
https://github.com/allegro/embedded-elasticsearch

**Comment by cloudjohnson** [comment]
Great, thank you!
