### ISSUE TITLE
"source" field on SearchHit and InnerHit is Map[String, AnyRef]

### ISSUE THREAD

**Issue by edubrovski** [sksamuel/elastic4s#1659]
Working with fields of type Map[String, AnyRef] is annoying and not Scala way. It'd be great to have a way to get source as a JSON AST. Ideally, I'd like to do something like this:
`import play.json.api.libs.json._
import com.sksamuel.elastic4s.playjson._
val jsonReads: Reads[MyScalaClass] = ... 
val hit: SearchHit = ...
hit.sourceAsJson // returns JsValue from play-json
hit.sourceAs[MyScalaClass] // returns MyScalaClass by getting JsValue and converting it using defined Reads[MyScalaClass]`

**Comment by sksamuel** [comment]
You can use HitAs for this.

**Comment by edubrovski** [comment]
We can also do the following:
```
val raw = SourceAsContentBuilder(innerHit.source).string() // or just hit.sourceAsString in case of SearchHit
val parsed = Json.parse(raw).as[MyScalaClass]
```
But JSON is parsed twice in this sample.

**Comment by sksamuel** [comment]
So you want to marshall the response from elastic directly into your own type?
If so, you could make an implicit handler and bring that into scope.

**Comment by edubrovski** [comment]
I think I got it. After importing `com.sksamuel.elastic4s.playjson._` I can do `hit.to[MyScalaClass]`. This is great, but only SearchHit has to and safeTo methods. Can we do the same for InnerHit? If not, I can add some methods to InnerHit and create a PR.

**Comment by sksamuel** [comment]
Of course please do.

**Comment by edubrovski** [comment]
I wanted to extend Hit trait with InnerHit and use HitReader typeclass for reading inner hits, but I couldn't because of version and score fields on Hit. So I've added a convenience method for converting Map[String, Any] to json string.
