### ISSUE TITLE
Parsing full query json to Query object

### ISSUE THREAD

**Issue by batchenoz** [sksamuel/elastic4s#1664]
Hi,
I'm trying to get a Query object out of Kibana raw  elasticsearch query. I'm adding here below an example  of such query, taken from kibana 6.

I would like to automatically be able to parse json strings into Queries.
I've tried to use RawQuery for the query list in 'bool' but it didn't work.
Also, using `source` prevent me from using search features such as scroll and slice (using elastic4s library).

Is there currently a way to parse this json into Query as I described?

If not, will you be interested I'll develop such feature?

Thanks.
```
{
  "version": true,
  "size": 500,
  "sort": [
    {
      "@timestamp": {
        "order": "desc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "_source": {
    "excludes": []
  },
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "30s",
        "time_zone": "Asia/Jerusalem",
        "min_doc_count": 1
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    },
    {
      "field": "applicationUserCreationDate",
      "format": "date_time"
    },
    {
      "field": "departure date",
      "format": "date_time"
    },
    {
      "field": "departure date #1",
      "format": "date_time"
    },
    {
      "field": "departure date #2",
      "format": "date_time"
    },
    {
      "field": "return date",
      "format": "date_time"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*",
            "default_field": "*"
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1552296155584,
              "lte": 1552297055584,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  },
  "highlight": {
    "pre_tags": [
      "@kibana-highlighted-field@"
    ],
    "post_tags": [
      "@/kibana-highlighted-field@"
    ],
    "fields": {
      "*": {}
    },
    "fragment_size": 2147483647
  }
}
```

**Comment by sksamuel** [comment]
If you take the json after "query", eg ```{
    "bool": {
      "must": [
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*",
            "default_field": "*"
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1552296155584,
              "lte": 1552297055584,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }```

And pass that into RawQuery it should work.

If you want the system to parse this full json, extracting just  the query part as a RawQuery, then yeah that would need to be added. And you could do a PR?
