### ISSUE TITLE
Builds for Scala 2.13 (-M5) in Central Maven Repo

### ISSUE THREAD

**Issue by unoexperto** [sksamuel/elastic4s#1668]
Could you please push builds for Scala 2.13 (-M5) to Central Maven Repo ?

**Comment by sksamuel** [comment]
I'll publish 2.13 once the final is released and all deps are available. Should be only a matter of a few days now as RC1 has been out a while.

**Comment by AurimasAnskaitis** [comment]
Could you please take a look at 2.13 support?

**Comment by unoexperto** [comment]
@sksamuel Hi Stephen! Any updates on this ?

**Comment by sksamuel** [comment]
No monix no cats yet.

**Comment by unoexperto** [comment]
Oh, I didn't even know you use monix. But monix is required for only `elastic4s-monix` module (which not everyone uses). `cats` for 2.13 has been published to Maven last week.

**Comment by sksamuel** [comment]
Oh I couldn't see cats when I looked. I'll do a release without monix then.

**Comment by rkrzewski** [comment]
@sksamuel I'm wondering if you made some progress with 2.13 build already? I made the classic mistake and started tinkering with it before checking the issue tracker. I can post a PR with the work I did so far if you are interested.

**Comment by sksamuel** [comment]
@unoexperto all I can see is a cats 2.0 milestone release for 2.13? I can't see any final release of 1.x for 2.13. Please link me if I'm mistaken.

@rkrzewski You can yes. I can't release until cats is ready though.

**Comment by unoexperto** [comment]
@sksamuel Correct, it's only milestone. Not sure when they're going to push release.

**Comment by sksamuel** [comment]
7.0.3 is now released for 2.13

**Comment by sksamuel** [comment]
7.1.0 is also released with 2.13 support.

**Comment by jtjeferreira** [comment]
@sksamuel would you be open to a PR with 2.13 support for 6.x branches?

**Comment by sksamuel** [comment]
Yep

**Comment by unoexperto** [comment]
@sksamuel What about `spray-json` and `http` modules ? Will the be published for 7.x ?

**Comment by sksamuel** [comment]
They've been renamed. See maven or the readme.

**Comment by jtjeferreira** [comment]
> @sksamuel would you be open to a PR with 2.13 support for 6.x branches?

I have pushed a PR https://github.com/sksamuel/elastic4s/pull/1793 against 6.5.x
