### ISSUE TITLE
Add possibility to create a client with sniffing

### ISSUE THREAD

**Issue by yannick-cw** [sksamuel/elastic4s#1678]
Hi :wave: 
When I want to use cluster sniffing with the client now, I have to create the sniffing through the java api
```
    val restClient: RestClient = RestClient
      .builder(new HttpHost"host", "port", "http"))
      .build()
    Sniffer.builder(restClient).build()
    val client = ElasticClient.fromRestClient(restClient)
```
with adding the `elasticsearch-rest-client-sniffer` dependency.

Do you think it could be possible to integrate the sniffing into elastic4s or into a elastic4s.sniffing module? If yes I would be happy to help out.

**Comment by yannick-cw** [comment]
Actually I just run into a prod bug, as I was using the Sniffing client wrongly :/
The java mutable api was confusing me. So I'll create a small scala package now with a sniffing client. If there is place for it in elastic4s please let me know :)

**Comment by sksamuel** [comment]
Please do make a PR.
