### ISSUE TITLE
Support to ElasticSearch 7

### ISSUE THREAD

**Issue by lozenko** [sksamuel/elastic4s#1689]
ElasticSearch has released its 7 version https://www.elastic.co/blog/elasticsearch-7-0-0-released I would like to get any information about plans for supporting that. 

Additionally, this topic can be used for watching and following any updates upon this.

**Comment by sksamuel** [comment]
On the agenda for a week's time I'd say

**Comment by sksamuel** [comment]
This is in progress now.

**Comment by ASravanthi** [comment]
Hi @sksamuel, is there any tentative release date for support of elastic search 7?

**Comment by sksamuel** [comment]
7.0 is now released. Thanks all for your patience.
