### ISSUE TITLE
ava.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps

### ISSUE THREAD

**Issue by Mdios** [sksamuel/elastic4s#1694]
i get this error 
at org.elasticsearch.spark.sql.DataFrameFieldExtractor$$anonfun$extractField$1.apply$mcVI$sp(DataFrameFieldExtractor.scala:34)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.spark.sql.DataFrameFieldExtractor.extractField(DataFrameFieldExtractor.scala:30)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.hadoop.serialization.field.ConstantFieldExtractor.field(ConstantFieldExtractor.java:36)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.write(AbstractBulkFactory.java:103)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.writeTemplate(TemplatedBulk.java:80)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:56)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:74)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.spark.scheduler.Task.run(Task.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:405)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m

**Comment by larochef** [comment]
As a first thought, it looks like you have scala-library in version 2.11.x  but use a version `_2.12` for the elastic4s jars.
@Mdios

**Comment by sksamuel** [comment]
elastic4s isn't even in the stack trace. Closing.
