### ISSUE TITLE
ScriptSort is setting lang for stored script

### ISSUE THREAD

**Issue by javierab** [sksamuel/elastic4s#1696]
I'm using release 6.5.1, and using elastic4s-http. 

I am doing this query, trying to use my stored script:

```
val mySearch = search("myIndex").size(125) sortBy{
        scriptSort(script("myScript")
          .scriptType(ScriptType.Stored)
          .params(Map("p" -> [1,2,3])))
        .typed("number")
        .order(SortOrder.Desc)}
```

When I print mySearch, I get this body:

```
StringEntity(
  {"size":125,"sort":[
  {"_script":{"script":{
    "stored":"myScript",
    "lang":"painless",
    "params":{"p":[1,2,3]}},
  "type":"number","order":"desc"}}]},
  Some(application/json))
```

Which throws the following error: 
`Request Failure ElasticError(x_content_parse_exception,[1:162] [_script] failed to parse field [script],None,None,None,List(ElasticError(x_content_parse_exception,[1:162] [_script] failed to parse field [script],None,None,None,null,None)),Some(CausedBy(illegal_argument_exception,illegally specified <lang> for a stored script,Map())))`

So painless is getting set as default language even when lang is not specified. Seems related to #1162, but that fix looks like it was only for tcp. 

I can definitely work on this if someone can give me some guidance!

**Comment by sksamuel** [comment]
Thanks, fixed in 7.0. If you need it in an earlier release let me know.
