### ISSUE TITLE
timeout with akka-http client doesn't on aliasExists

### ISSUE THREAD

**Issue by larochef** [sksamuel/elastic4s#1704]
I'm getting timeouts when doing some `aliasExists` requests with the akka-http client.

After looking at the code, my feeling is that it's an issue with the HEAD requests that will not give any content in the response entity, and so, the source merging, to retrieve the response just waits indefinitely, since there is nothing to read.

what do you think about it?

**Comment by sksamuel** [comment]
Do you mean line 61. You would assume that entity.dataBytes, which returns a source, returns an empty source if it's a HEAD ?

**Comment by larochef** [comment]
Yes, I was talking about this line 61

After some more investigation, I saw the issue:

```
curl -v -XHEAD localhost:9200/_alias/idea
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> HEAD /_alias/idea HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< content-type: application/json; charset=UTF-8
< content-length: 45
< 
```

The response states a content-length of 45, but since it's a HEAD method, nothing is sent by elasticsearch.
I think it's why the stream expects to receive something and waits until it fails.
