### ISSUE TITLE
TaskStatus contains typo which causes misleading deserialisation

### ISSUE THREAD

**Issue by csandeman-craik** [sksamuel/elastic4s#1708]
File com.sksamuel.elastic4s.http.task.TaskHandlers contains TaskStatus defined thus -

`case class TaskStatus(total: Long, updated: Long, Created: Long, deleted: Long, batches: Long)
`

'Created' should be 'created' because it silently breaks the deserialisation of the JSON (which is all lowercase) and gives an incorrect count of zero.

**Comment by sksamuel** [comment]
Fixed thanks.
