### ISSUE TITLE
Extend SearchRequest to support plugin specific json

### ISSUE THREAD

**Issue by TactiC** [sksamuel/elastic4s#1716]
We are using the LTR plugin for model based ranking and we are running into some issue.
In order to return the feature scores we need to add some additional code to the query, making it look something like this.
```json
{
"query": {},
"rescore": [],
"ext": {
    "ltr_log": {
        "log_specs": {
            "name": "log_entry1",
            "named_query": "logged_featureset"
        }
    }
}
}
```
Does it make sense to add an additional field to _SearchRequest_ in which we can put json code like in the snippet above?
Or is what I want already possible and am I completely missing something?

**Comment by sksamuel** [comment]
You could make your own Handler instance for SearchRequest and bring that into scope. It could extend the existing one.

**Comment by sksamuel** [comment]
So just write `implicit val myHandler = new Handler[SearchRequest, SearchResponse] { }` and implement the json builder in there. Then make sure this is in scope before you call client.execute and your handler will be used.
