### ISSUE TITLE
Create Migration Guide for 6.x to 7.0

### ISSUE THREAD

**Issue by philvarner** [sksamuel/elastic4s#1723]
I don't know what the plans are for a migration guide between elastic4s 6.x to 7.x, but here's a short list of the things I had to change to upgrade to 7.x that might be useful in creating that documentation. 

1. package names:   
    1. elastic4s-spray-json => elastic4s-json-spray
    2. elastic4s-aws => elastic4s-client-aws
    3. elastic4s-http => elastic4s-client-esjava
    4. elastic4s-embedded => ???

1. Package changes:
    1. constructor `com.sksamuel.elastic4s.http.ElasticClient` => `com.sksamuel.elastic4s.http.JavaClient`, but returns an object of type `com.sksamuel.elastic4s.ElasticClient`
    2.  `com.sksamuel.elastic4s.http.ElasticProperties` =>  `com.sksamuel.elastic4s.ElasticProperties`
    3. `com.sksamuel.elastic4s.http.ElasticDsl` => `com.sksamuel.elastic4s.ElasticDsl`
    4. `com.sksamuel.elastic4s.http.bulk.BulkResponse` => `com.sksamuel.elastic4s.requests.bulk.BulkResponse`
    5. `com.sksamuel.elastic4s.indexes.IndexRequest` => `com.sksamuel.elastic4s.requests.indexes.IndexRequest`
    6. import `com.sksamuel.elastic4s.http.{RequestFailure, RequestSuccess}` => `import com.sksamuel.elastic4s.{RequestFailure, RequestSuccess}`
2. Remove all `type` references
   1. IndexRequest - first argument is only index name (foo_index), rather than index and type (foo_index/bar_type)
3. typed mappings are no longer allowed:
```
createIndex(index)
            .mappings(
              mapping("item").fields(
      geoshapeField("geometry"),
      dateField("properties.datetime"),
      geopointField("properties.aac:centroid")
    ))
```
==>
```
createIndex(index)
  .mapping(
    properties(
      geoshapeField("geometry"),
      dateField("properties.datetime"),
      geopointField("properties.aac:centroid")
    ))
```

**Comment by sksamuel** [comment]
This is awesome.
I was literally doing the release for 7.0.0 but I've cancelled that upload,
and I will clarify the JavaClient vs ElasticClient thing before I release.

**Comment by sksamuel** [comment]
In the final release, you need to do:

`val esclient = ElasticCilent(some client here)`
like
`val esclient = ElasticClient(JavaClient(ElasticProps(...)))`

**Comment by Fraer** [comment]
Also what to do if some one use elastic4s-circe ? Will it work ?

**Comment by sksamuel** [comment]
Nothings should have changed there.

**Comment by reynoldsm88** [comment]
@sksamuel I ran into this recently when migrating from 6.x to 7.x and didn't see anything updated in the docs? Does this mean that one would always need `elastic4s-client-esjava` unless they are providing their own HttpClient implementation?

**Comment by JamesHutchisonPremise** [comment]
How do we deal with them changing the default behavior of hits.total from a long to an object? Is there a way to plug in the `rest_total_hits_as_int` argument? The 6.x client is incompatible with the 7.x server and the 7.x server is incompatible with the 6.x client. If I"m upgrading I do one at at a time and in my case embedded elasticsearch doesn't have a 7.x version (yet).

**Comment by lespea** [comment]
elastic4s-jackson is now elastic4s-json-jackson

**Comment by diogocanut** [comment]
If you guys find this useful, I just updated the http sample code with the changes you mentioned here. This helped me a lot to start with elastic4s on ES7
```
import com.sksamuel.elastic4s.{ElasticClient, ElasticProperties, Response}
import com.sksamuel.elastic4s.http.JavaClient
import com.sksamuel.elastic4s.requests.common.RefreshPolicy
import com.sksamuel.elastic4s.requests.searches.SearchResponse


object HttpClientExampleES7 extends App {
  import com.sksamuel.elastic4s.ElasticDsl._
  val client = ElasticClient(JavaClient(ElasticProperties("http://localhost:9200")))

  client.execute {
    bulk(
      indexInto("myindex").fields("country" -> "Mongolia", "capital" -> "Ulaanbaatar")
    ).refresh(RefreshPolicy.WaitFor)
  }.await

  val response: Response[SearchResponse] = client.execute {
    search("myindex").matchQuery("capital", "ulaanbaatar")
  }.await

  println(response.result.hits.hits.head.sourceAsString)

  

client.close()
```
