### ISSUE TITLE
Support for elastic4s-http version 7.0 for ES 7.X

### ISSUE THREAD

**Issue by satishdash** [sksamuel/elastic4s#1738]
Hi,
I find elastic-4s-core has an updated version of 7.0.1 as of latest to support ES 7.X.
Is there a tentative date for elastic4s-http  7.0.X release ?

**Comment by ASravanthi** [comment]
Waiting for this one, request to release elastic4s-http support for ES7 as soon as possible

**Comment by sksamuel** [comment]
I just need to update the docs. You need `elastic4s-client-esjava` instead now.  @ASravanthi @satishdash

**Comment by ksceriath** [comment]
Hi @sksamuel ,

We were using elastic4s-http-5.4.3 (as a cluster-aware es client).
We are now migrating to Elasticsearch 7.0. 

Can you please confirm if elastic4s-client-esjava is the correct replacement for this? If so, can you point to some docs elaborating the change in the apis?

**Comment by ksceriath** [comment]
To be more specific, we are using "com.sksamuel.elastic4s.http.HttpClient" from elastic4s-http-5.4.3.

**Comment by sksamuel** [comment]
Yes use `elastic4s-client-esjava`
Until I update the docs, check out the tests.

**Comment by ksceriath** [comment]
Okay. We've been trying that, but ran into the issue mentioned here: https://github.com/sksamuel/elastic4s/issues/1723#issuecomment-495811999

Is there any way around this ? (providing additional query params in some way?)

**Comment by pacman899** [comment]
Hey @sksamuel,
is there a plan to support the 7.x versions? if so, when do you expect it to happen?

**Comment by DenisNovac** [comment]
Isn't it now part of core package? I guess, i've managed to find instances for `http.bulk.BulkHandlers` in core.

**Comment by sksamuel** [comment]
Docs have been updated to make things a lot clearer.
