### ISSUE TITLE
cat indices api for wildcard indices

### ISSUE THREAD

**Issue by ksceriath** [sksamuel/elastic4s#1741]
I'm not sure if this is covered elsewhere, but I couldn't find it in the apis.

Elasticsearch provides a facility to get a list of indices matching a certain wildcard pattern:

`curl -X GET "localhost:9200/_cat/indices/twi*?v&s=index"
`

How can this be accomplished using the catIndices api?

**Comment by sksamuel** [comment]
If you wanted to raise a PR for any changes I can do a release.

**Comment by ksceriath** [comment]
Hi @sksamuel , I have raised a PR : https://github.com/sksamuel/elastic4s/pull/1742

**Comment by ksceriath** [comment]
@sksamuel : Can you do a release for version 5.6.10?

**Comment by sksamuel** [comment]
Yes, do you want this PR in it? If so you'll need to target the
release/5.6.x branch

**Comment by ASravanthi** [comment]
@sksamuel when is the tentative release date for elastic4s-http 5.6.10 with this PR #1742

**Comment by ksceriath** [comment]
@sksamuel - these changes have been pushed to release/5.6.x, release/6.5.x and master branches through PRs: #1742, #1743 and #1744 

It would be helpful to have releases in 5.6 and 7.0 with these changes.

Let me know what needs to be done from my end in this regard. Can you elaborate:
> you'll need to target the release/5.6.x branch

**Comment by sksamuel** [comment]
Ok I can do a release tonight or tomorrow.

**Comment by sksamuel** [comment]
7.0.2 has been released.

**Comment by sksamuel** [comment]
5.6.10 released.
