### ISSUE TITLE
Missing extensions for 7.x

### ISSUE THREAD

**Issue by napgab** [sksamuel/elastic4s#1746]
Additional modules, like [elastic4s-jackson](https://search.maven.org/search?q=elastic4s-jackson) or [elastic4s-json4s](https://search.maven.org/search?q=elastic4s-json4s), are still not avaiable for versions 7.x.
Are the v6.5.x modules compatibile with the last version of elastic4s? 
In any case, probably, is better to deploy an artifact with the same version of elastic4s, even if its code is unchanged.

**Comment by lespea** [comment]
They are now elastic4s-json-jackson and elastic4s-json-json4s

**Comment by sksamuel** [comment]
Please see the full list of modules in the root source.
