### ISSUE TITLE
'missing' property type of ExtendedStatsAggregation should be Option[AnyRef] instead of a Option[Double]

### ISSUE THREAD

**Issue by angusdavisadobe** [sksamuel/elastic4s#1752]
The StatsAggregation 'missing' property type is Option[AnyRef] but for ExtendedStatsAggregation, the 'missing' property type is Option[Double]. This means that a missing value cannot be provided when the type of the elasticsearch field is a boolean.

**Comment by sksamuel** [comment]
Thanks. Please PR and I will include it in the release.

**Comment by gurkankaymak** [comment]
@sksamuel this issue could be closed since #1756 is merged
