### ISSUE TITLE
Buffer handling in the GraphStage implementation - Akka streams

### ISSUE THREAD

**Issue by maciej-adamiak** [sksamuel/elastic4s#1770]
I am checking the Akka streams implementation and encountered a [code fragment](https://github.com/sksamuel/elastic4s/blob/f37a050becf4116ebba9468693478dbd66648c28/elastic4s-streams-akka/src/main/scala/com/sksamuel/elastic4s/akka/streams/ElasticSource.scala#L54) that I would like to discuss. It looks like we will encounter a `NoSuchElementException` in case the scroll result acquired from elasticsearch is empty i.e. no hits present. Initially the buffer will be an empty `Queue` and the output port will be available to push. This will result in dequeuing an empty queue.

**Comment by sksamuel** [comment]
Fixed in master. Thanks for the bug report :+1:
