### ISSUE TITLE
case classes serialized as Product

### ISSUE THREAD

**Issue by Tomassino** [sksamuel/elastic4s#1779]
Hi, I have a problem with serialization of case classes that have a custom `toString` method. In previous versions of the library, when I had e.g. a `termsQuery` with values belonging to a case class with a custom `toString` method, the custom string representation was used in the query. However with version 7.1.0 the case classes are serialized as `Product`, giving an invalid query as result. This is due to the new `case Product` in XContentBuilder.autovalue:

https://github.com/sksamuel/elastic4s/blob/061d1945d560a27f25748c593b6a5956dde209f2/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/XContentBuilder.scala#L194

To give an example: if you have something like this:

```scala
case class A(a: Int, b: Int) {
  override def toString = s"${a}:${b}"
}

...

termsQuery("fname", List(A(1, 2), A(2, 3)))
```

the resulting query in the previous versions was:

```json
...
{
  "terms": {
    "fname": ["1:2", "2:3"]
  }
}
```

while with the new version it is something like this, that is of course invalid:

```json

{
  "terms": {
    "fname": [[1, 2],[2, 3]]
  }
}
```
(to be honest my test was a bit different, but this should be the result for the example here)

I'm not sure whether this is the expected behavior or not, if it is I think it is important to make it clear that there has been a change. If I'm not mistaken this change has been included recently by this commit: https://github.com/sksamuel/elastic4s/commit/b3c1dc76dbfd71333090bf21cc490860979f1d93

**Comment by sksamuel** [comment]
I think replying on toString is a bit fragile.
Have you seen Indexable? That is the preferred way of doing it.

**Comment by Tomassino** [comment]
I tend to agree with you on `toString`, it is just that our code is currently written like that :-). What is important for me now is that serialization with Product is the expected behaviour, so I'll fix my code. I'll also have a look at `Indexable` more closely, I thought that it was used only to index full documents.

Thanks for your answer!

**Comment by sksamuel** [comment]
You could write an indexable that just delegates to the string method.

```
class GenericIndexable extends Indexable[Any] }
  def toJson(any:Any) = any.toString()
}
```
