### ISSUE TITLE
DateHistogramAggregation `interval` deprecated in 7.2 in favor of`calendar_interval` and `fixed_interval`

### ISSUE THREAD

**Issue by philvarner** [sksamuel/elastic4s#1782]
DateHistogramAggregation `interval` is now deprecated in favor of`calendar_interval` and `fixed_interval`.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html

**Comment by sksamuel** [comment]
Would you mind contributing a PR
