### ISSUE TITLE
Creating custom analyzer fails in 7.x

### ISSUE THREAD

**Issue by peri4n** [sksamuel/elastic4s#1795]
# Problem description

Adding a tokenizer to the Analysis (introduced in 7.x) does not work.The generated Json has an extra level of nesting in which the name of the the tokenizer is listed twice.

For example:

```
{"settings": {
	"analysis":
		{"analyzer":{
			"header_analyzer":{"type":"standard","stopwords":[],"max_token_length":255},
			"sequence_analyzer":{"type":"custom","tokenizer":"test"}},
		"tokenizer":{
			"test":{"test":{"type":"nGram","min_gram":4,"max_gram":5}}}}},
	"mappings":{
		"properties":{
			"header":{"type":"text","analyzer":"header_analyzer"},
			"sequence":{"type":"text","analyzer":"sequence_analyzer"}}}}
```

Note, that the name of the tokenizer ("test") is duplicated.

**Comment by peri4n** [comment]
Looking at the code, I'd say that the root cause is using `rawField` intead of `rawValue`.

**Comment by peri4n** [comment]
I created a PR #1797

**Comment by sksamuel** [comment]
Please try latest release with the above fix.
