### ISSUE TITLE
Client request is slow as compared to curl

### ISSUE THREAD

**Issue by writeaditya** [sksamuel/elastic4s#1801]
Hi,
I'am making 1000 request in single go using elastic4s client and it takes around 7-8 seconds but with curl query same request taking 1-2 sec.

Following is my query - 

[SampleQry.txt](https://github.com/sksamuel/elastic4s/files/3405474/SampleQry.txt)

System Configuration -
3 node cluster 
8 GB RAM on each node
4 Core

Suggestions on this slowness. What else information you need to analyse.

**Comment by writeaditya** [comment]
Any Update ?

**Comment by sksamuel** [comment]
You do that same query 1000 times in a loop ?
