### ISSUE TITLE
term composite aggregations are missing `missingBucket` parameter

### ISSUE THREAD

**Issue by c-dante** [sksamuel/elastic4s#1805]
The `DateHistogramValueSource` has it, but the others don't.

The abstract `ValueSource` should include that `missingBucket`: https://github.com/sksamuel/elastic4s/blob/8340ddae2780572e539053e5ae45f9c78dc54d5e/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/searches/aggs/CompositeAggregation.scala#L7-L10

And get handled here: https://github.com/sksamuel/elastic4s/blob/8340ddae2780572e539053e5ae45f9c78dc54d5e/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/searches/aggs/CompositeAggregationBuilder.scala#L13-L19

**Comment by c-dante** [comment]
Is there any intention to add this?

**Comment by sksamuel** [comment]
Yes

**Comment by sksamuel** [comment]
This has been added to master.
