### ISSUE TITLE
Missing document for Alternative Executors

### ISSUE THREAD

**Issue by i4never** [sksamuel/elastic4s#1809]
I'm working on a project with monix and elastic4s but find no doc or example on ``com.sksamuel.elastic4s.monix``. What's the schedule for document updating? Is there any usage example? Thanks.

**Comment by i4never** [comment]
For now I just build an observable from search result. Get task from monix wrapper maybe a more proper way.

**Comment by sksamuel** [comment]
No docs. Maybe you could add some, that would be great.
