### ISSUE TITLE
elastic4s version 6.7 for scala 2.13

### ISSUE THREAD

**Issue by zettelmj** [sksamuel/elastic4s#1813]
Hi,

If I am not mistaken the version of elastic4s and the elasticsearch version needs to be in sync.
Since the AWS elasticsearch version lags a bit behind I need to use elastic4s with scala 2.13.
I have patched version of 6.7.1 that builds and runs with scala 2.13.

Therefore my two questions would be: Did I just do a lot of unnecessary work and can i submit these changes as pull request?

Thank you
Jens

**Comment by sksamuel** [comment]
If you pr i can release.

**Comment by zettelmj** [comment]
Will do

**Comment by zettelmj** [comment]
The MR is in. Is there anything I need to do?

**Comment by sksamuel** [comment]
6.7.2 has been released with 2.13 support.

**Comment by zettelmj** [comment]
Thank you
