### ISSUE TITLE
Sorting on Inner Hit returns entire FieldSortDefinition in query. (5.5.6)

### ISSUE THREAD

**Issue by cropper-tim** [sksamuel/elastic4s#1848]
I'm trying to apply a fieldSort to an innerhit, and the entire FieldSortDefinition is being returned.

**inner hit query:**
```
.inner(innerHits("<inner_hits>").from(startIndex).size(itemsPerPage).sortBy(fieldSort("<field.innerfield.sortfield>")))
```
**sort field of executed query:**
```
"sort": [
    "FieldSortDefinition(<field.innerfield.sortfield>,None,None,None,None,None,asc)" 
]
```
**expected sort field in query:**
```
"sort":[
    {
        "<field.innerfield.sortfield>":{
            "order":"asc"
        }
    }
]
```
Thanks, and let me know if I can provide any additional information.

**Comment by cropper-tim** [comment]
After some digging, it looks like the root of the problem is in InnerHitQueryBodyFn.scala and XContentBuilder.java. Sorts are of type SortDefinition which XContentBuilder does not recognize as a class, and therefore calls toString on the object. 

SearchBodyBuilderFn.scala handles sorts properly using SortContentBuilder.scala, so maybe implementing that in InnerHitQueryBodyFn.scala could solve the issue.

As an immediate fix, I made a new case class that extends SortDefintion and overrode the toString method to return just the field.

**Comment by sksamuel** [comment]
This has been fixed since 2018 it looks like, so i guess only the 5.6 branch needs to be patched. Feel free to open a PR.
