### ISSUE TITLE
upgrade from 6.7.3 t0 7.1.2

### ISSUE THREAD

**Issue by mkeshav** [sksamuel/elastic4s#1853]
`Error:(41, 7) Symbol 'type com.sksamuel.elastic4s.searches.queries.term.BuildableTermsQuery' is missing from the classpath.
This symbol is required by 'method com.sksamuel.elastic4s.http.search.SearchHandlers.BuildableTermsNoOp'.
Make sure that type BuildableTermsQuery is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'SearchHandlers.class' was compiled against an incompatible version of com.sksamuel.elastic4s.searches.queries.term.
      clusterHealth()`

I get the above error when i try upgrading

my build.sbt

`
 "com.sksamuel.elastic4s" %% "elastic4s-core" % "7.1.2",

  "com.sksamuel.elastic4s" %% "elastic4s-client-esjava" % "7.1.2",

  "com.sksamuel.elastic4s" %% "elastic4s-json-circe" % "7.1.2",

  "com.sksamuel.elastic4s" %% "elastic4s-cats-effect" % "6.7.3",
`

I also see a lot of
`Error:(40, 16) could not find implicit value for parameter handler: com.sksamuel.elastic4s.http.Handler[com.sksamuel.elastic4s.requests.cluster.ClusterHealthRequest,U]
    es.execute {`

imports i have are
`import com.sksamuel.elastic4s.cats.effect.instances._
import com.sksamuel.elastic4s.http.ElasticClient
import com.sksamuel.elastic4s.http.ElasticDsl._`
I am pretty sure i am missing some import. Can some one pls help?

**Comment by igoverdovsky** [comment]
I have the same issue

**Comment by sksamuel** [comment]
You can't mix and match different versions of e4s. In 7.x the typea
functionality changed.
