### ISSUE TITLE
“No implicits found for parameter handler: Handler[IndicesExistsRequest, U_]

### ISSUE THREAD

**Issue by RPGambit2** [sksamuel/elastic4s#1861]
![image](https://user-images.githubusercontent.com/22600634/64888112-26dc5f80-d638-11e9-8f44-89dd007f36bf.png)

**Comment by lmserrano** [comment]
The error you are getting seems related to be the same mentioned here https://github.com/sksamuel/elastic4s/issues/1853

**Comment by sksamuel** [comment]
Please see the latest docs which should make things clearer.
