### ISSUE TITLE
Support Elastic 5.6.X with Scala 2.13 ?

### ISSUE THREAD

**Issue by nhiguchi** [sksamuel/elastic4s#1862]
I use Scala 2.13 for new products.
However, elastic4s cannot be used because the target Elastic is 5.6.X.
Can Scala 2.13 support be higher than Elastic5.6.X?

**Comment by jeffrey-aguilera** [comment]
Similar issue, but Elastic 6.5+

**Comment by nhiguchi** [comment]
I see.
