### ISSUE TITLE
Is there any way to modify score function on elastic4s?

### ISSUE THREAD

**Issue by mehmetgunturkun** [sksamuel/elastic4s#187]
I couldn't find any way to modify score function - 

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_score_functions

Thanks

**Comment by timcharper** [comment]
Which, was killed here: https://github.com/sksamuel/elastic4s/commit/87886eafe62232bbe629be811010d596edca6109 :(

I'm able to access it at the prior commit; are these tests going away forever?

https://github.com/sksamuel/elastic4s/blob/87886eafe62232bbe629be811010d596edca6109^/src/test/scala/com/sksamuel/elastic4s/SearchDslTest.scala#L603

**Comment by sksamuel** [comment]
Removing those tests was a complete mistake. Thanks for pointing it out.
