### ISSUE TITLE
why elastic4s-client-aws gets removed

### ISSUE THREAD

**Issue by yunj** [sksamuel/elastic4s#1883]
Can someone please explain why the aws client gets removed in master? Any plan to add it back in the future?

Thanks.

**Comment by chikei** [comment]
Quote from https://github.com/sksamuel/elastic4s/issues/1873#issuecomment-538152888 (which I believe is suppose to answer this issue)



> 
> 
> Hi,
> 
> Because you can use any HTTP client with elastic4s since version 7, and just attach the AWS headers to that. There's no reason for it to be a specific part of e4s anymore.
