### ISSUE TITLE
Support Users & Roles API

### ISSUE THREAD

**Issue by MVJosh** [sksamuel/elastic4s#1886]
Feature request:

- It would be useful for elastic4s to support the Elasticsearch users & roles API (part of xpack/security, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api.html)

If work on this is not already in progress, I'd be happy to submit a pull request

**Comment by sksamuel** [comment]
Great, please do.

**Comment by MVJosh** [comment]
See PR: https://github.com/sksamuel/elastic4s/pull/1899

**Comment by tobiatesan** [comment]
PR merged, is this still open?

Thanks

**Comment by MVJosh** [comment]
> PR merged, is this still open?
> 
> Thanks

Thanks for the reminder - should be closed!
