### ISSUE TITLE
Unsupported PercolateQuery Http Client (6.3.5)

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#1901]
Hi Samuel, how are you!
I'm currently using elastic4s 6.3.5 version and I've found that percolate query is not supported over http client.
Is this query already implemented on a newest version? If so, I can check if I can upgrade my client. If not I see that another user already implemented over version 5.4.x:
https://github.com/sksamuel/elastic4s/pull/1482

What can you suggest me in order to solve this issue?
Thanks a lot for your time!

Regards,
Patricio.

**Comment by pgorin** [comment]
Hi again!
I've made a PR:
https://github.com/sksamuel/elastic4s/pull/1902

But Travis is failing, any idea?
Thanks!

**Comment by pgorin** [comment]
Thanks Samuel for merging de PR!
Is there a chance to make a new 6.3.9 release?

Thanks again!

**Comment by sksamuel** [comment]
I can make a release, it will be this weekend.

**Comment by pgorin** [comment]
Great! Thanks a lot!

**Comment by pgorin** [comment]
Samuel, is this already released? Thanks!

**Comment by sksamuel** [comment]
6.3.9 is out now.

**Comment by DemonTPx** [comment]
This problem is fixed in 6.3.9, but all the following later version branches from 6.4.x onward do not feature this fix.

I've tried 6.7.4 and 7.3.5 and they both give me the `PercolateQuery has not yet been implemented for the HTTP client` error
