### ISSUE TITLE
Unexpected deserialization error on total hits for particular number of results

### ISSUE THREAD

**Issue by RichardSmithONS** [sksamuel/elastic4s#1912]
Testing my 7.3.1 upgrade I stumbled on this problem (which I can also get with 5.6.7). I get the error below but it seems to be only when there are exactly 43627 results. If I tweak the query slightly (it has a range clause so I can make a small change to lat or lon) to increase or decrease the number of hits it works.

`Cannot construct instance of `com.sksamuel.elastic4s.requests.searches.Total` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (43627)  at [Source: (StringReader); line: 1, column: 96] (through reference chain: com.sksamuel.elastic4s.requests.searches.SearchResponse["hits"]->com.sksamuel.elastic4s.requests.searches.SearchHits["total"])`

**Comment by Garnek20** [comment]
Hello, I'm having the exact same issue. I've seen some people already encountered this problem too. Is there any update on it?

**Comment by Garnek20** [comment]
If anyone still has the following issue, I figured out the problem.
Verify that the `elastic4s` version and your cluster go along. 👍

**Comment by RichardSmithONS** [comment]
I have investigated this further following the information above. Seems I actually have two problems. My old Elasticsearch 5 deployment throws the deserialization error above and it is running a much newer version of E4S (6.1.4) than ES (5.6.7) on the cluster so that is probably why.

Meanwhile, my new Elasticsearch 7 deployment has the same version of ES and E4S (7.3.1) and the query actually fails for a different reason. It is a problem in my application's code which occurs if the distance in metres returned by ES is 0.0 - i.e. when the input lat / lon is exactly the same as the found document's.
