### ISSUE TITLE
Creating and reading ingest processors?

### ISSUE THREAD

**Issue by alexklibisz** [sksamuel/elastic4s#1926]
Hi, I'm working on a project that leverages [ES ingest processors](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-processors.html).

I looked through the various request types in this lib and couldn't find anything for making and retrieving processors. I'm wondering if maybe I'm overlooking them somewhere?

If not, would it be valuable to contribute them to the library? I have a working `Handler` in my code that I could pull out and PR into elastic4s. LMK if that would be helpful, and if so, which package they should go in.

**Comment by sksamuel** [comment]
A PR would be fantastic, thank you.

**Comment by ckcedrickeller** [comment]
Hi,
also looking for pipelines.
I would like to use existing processors, but I would need to be able to use pipelines : [ES Date Index Name Processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-index-name-processor.html).

Is it possible to use pipelines with the actual version of elastic4s ? didn't find how.
Any pointer would be very much appreciated.

**Comment by alexklibisz** [comment]
@ckcedrickeller I haven't had the time to integrate it in the elastic4s codebase, but this is how I'm doing it in my project:

```
  case class Processor(name: String, opts: ProcessorOptions)
  case class Pipeline(description: String, processors: Seq[Processor])
  case class PipelineRequest(name: String, pipeline: Pipeline)
  case class PipelineResponse(acknowledged: Boolean)

  object PipelineRequest {
    implicit object PipelineRequestHandler extends Handler[PipelineRequest, PipelineResponse] {
      override def build(t: PipelineRequest): ElasticRequest = {
        // See: https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-processors.html
        val body: Json = Json.fromJsonObject(
          JsonObject(
            "description" -> Json.fromString(t.pipeline.description),
            "processors" -> Json.fromValues(t.pipeline.processors.map { p =>
              Json.fromJsonObject(
                JsonObject(p.name -> JsonFormat.toJson(p.opts))
              )
            })
          ))
        val endpoint = s"_ingest/pipeline/${t.name}"
        ElasticRequest("PUT", endpoint, HttpEntity(body.noSpaces))
      }
    }
  }
```

The `Json` types are coming from circe, which I'm using for Json in my project. `ProcessorOptions` is a custom case class actually defined in Protobuf, so I'm using the scalapb-circe project to serialize it to Json (the `JsonFormat.toJson` line).

The summary here is: define case classes for `PipelineRequest` and `PipelineResponse` and all of their members according to the structure in the ES docs. Then define an `implicit object PipelineRequestHandler extends Handler[PipelineRequest, PipelineResponse] {` with a single `override def build` which converts your `PipelineRequest` to an `ElasticRequest`.
