### ISSUE TITLE
Expose timeout and master_timeout options in the API

### ISSUE THREAD

**Issue by jbotto94** [sksamuel/elastic4s#1950]
Several Elastic requests expose a timeout and master_timeout URL parameters. These were only documented from about version 7.0 onwards as follows:

- timeout (Optional, time units) Specifies the period of time to wait for a response. If no response is received before the timeout expires, the request fails and returns an error. Defaults to 30s.

- master_timeout (Optional, time units) Specifies the period of time to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error. Defaults to 30s.

For example, these paramters already existed back in v5, but were not on the official documentation:
https://github.com/elastic/elasticsearch/blob/v5.0.0/core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestCreateIndexAction.java#L52-L53
These timeouts are defaulted to 30 seconds, which is normally more than enough except when the mater node is particularly busy.

Would it be possible to expose these variables? I'd be happy to have a stab at a PR if it's something you'd be willing to support in the library.

**Comment by sksamuel** [comment]
I think it's definitely worth adding. Pr would be most welcome.

**Comment by TopSpoofer** [comment]
how can i set  timeout  to wait for a response in version: 6.2.4?

**Comment by sksamuel** [comment]
I've added an implicit `CommonRequestOptions` parameter to the client.execute method, which includes master node timeout, and timeout. This could also be used for other common parameters, like routing, in the future.

**Comment by sksamuel** [comment]
Now included in 7.7.0
