### ISSUE TITLE
getMapping returns only properties but not meta fields

### ISSUE THREAD

**Issue by an-tex** [sksamuel/elastic4s#1956]
It's possible to retrieve the meta fields using `getIndex(...).mappings.meta`, but shouldn't `getMapping` return those fields as well?

The `getMapping` handler returns only the `properties`:
https://github.com/sksamuel/elastic4s/blob/13f1810502429a2788e1c95f2de15cc32c41f425/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/indexes/MappingHandlers.scala#L22

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/mapping-fields.html

**Comment by an-tex** [comment]
Hey @sksamuel , I'd be happy to contribute. I just wanted to clarify beforehand if this makes sense. Cheers

**Comment by sksamuel** [comment]
Yes it makes sense to return the fields as well.
