### ISSUE TITLE
Auto Date Histogram aggregation

### ISSUE THREAD

**Issue by fdevillard** [sksamuel/elastic4s#1964]
Hi there,

I didn't find any mention of [auto_date_histogram](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-aggregations-bucket-autodatehistogram-aggregation.html). 

Am I missing something? If not, is there any plan to add it to elastic4s?

Thanks a lot for you work !
Flo

**Comment by sksamuel** [comment]
Added to master, will be included in next 7.6 release.

**Comment by sksamuel** [comment]
Included in latest release.
