### ISSUE TITLE
6.5/6.6 release for scala 2.13

### ISSUE THREAD

**Issue by chikei** [sksamuel/elastic4s#1982]
Since scala 2.13 support for 6.5/6.6 has been merged for a while, can we get new releases of 6.5/6.6 for scala 2.13 ? 😃

**Comment by chikei** [comment]
Sorry that I didn't realize v6.5.4 also have artifacts for 2.13. 
For 6.6 branch, while we got tag v6.6.1, it seems didn't get published into maven central.

**Comment by sksamuel** [comment]
6.6.3 has been released with 2.13 support.
