### ISSUE TITLE
7.3.5: NoSuchElementException when creating an index with no "analyzer"

### ISSUE THREAD

**Issue by rogueai** [sksamuel/elastic4s#1992]
When upgrading from `7.3.1` to `7.3.5` we found that creating an index with settings, but no analyzer, results in a `NoSuchElementException` being thrown, and index creation fails.

Upon investigation it looks like the following is the root cause:
https://github.com/sksamuel/elastic4s/blob/f3341d9491eb4c64dc0db58b8e119cebdee4a809/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/indexes/IndexTemplateHandlers.scala#L85

Thanks!

**Comment by tarangbhalodia** [comment]
I would like to work on this.

**Comment by sksamuel** [comment]
Please do.

**Comment by tarangbhalodia** [comment]
@sksamuel 
PR: https://github.com/sksamuel/elastic4s/pull/2004 is ready for review
