### ISSUE TITLE
Missing `flattened` field datatype

### ISSUE THREAD

**Issue by rogueai** [sksamuel/elastic4s#1993]
Hi, ElasticSearch introduced the [`flattened` field datatype](https://www.elastic.co/guide/en/elasticsearch/reference/master/flattened.html) in version 7.3.0, however it doesn't seem to be available in elastic4s out of the box for dynamic mappings.

We're thinking about creating our own `dynamicFlattenedField` extending `BasicField`.
Please advise if there's a better way to do that while we wait for that to get introduced.

Thanks!

**Comment by sksamuel** [comment]
Aded in master, will be included in next 7.6 releaed.

**Comment by sksamuel** [comment]
Is included in 7.7.0
