### ISSUE TITLE
GetFieldMappingRequest does not support all query parameter options

### ISSUE THREAD

**Issue by c-dante** [sksamuel/elastic4s#2008]
Elastic search has a good set of request parameters that the field mapping request case class does not satisfy:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html

https://github.com/sksamuel/elastic4s/blob/1d6f06346be9cd7acd167976d03df2107eec8819/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/indexes/MappingHandlers.scala#L67-L80

Specifically, the other query parameters:
allow_no_indices, expand_wildcards, include_type_name, ignore_unavailable, local, master_timeout

**Comment by tarangbhalodia** [comment]
I would like to work on this.

**Comment by sksamuel** [comment]
Please do.
