### ISSUE TITLE
How works connection (ElasticClient) ?

### ISSUE THREAD

**Issue by ubourdon** [sksamuel/elastic4s#2022]
Hi to create my ES conneciton i do this : 
`protected lazy val es: ElasticClient = ElasticClient.remote(host, port)`

What is the behaviour of ElasticClient ?
Is it a pool of connection ? 
Should it be the only ref or can i use def instead of lazy val ?
What happend if all the connections are overloaded ?
Are they released ?
What are the good practices here ?

**Comment by sksamuel** [comment]
The elastic client has no threads of it's own. It uses the threads from the underlying http client. So if you're using the JavaClient then whatever the official es library does.
