### ISSUE TITLE
Issue with Custom Field Type example

### ISSUE THREAD

**Issue by pierre-borckmans** [sksamuel/elastic4s#2023]
Hi there,

Using the example here: https://github.com/sksamuel/elastic4s/blob/master/docs/src/main/tut/docs/document/index.md#custom-field-types

Fails with `scala.MatchError: CustomDateFieldValue(occured_on,2020-03-02T06:24:07.087+01:00)`.

And indeed, looking at `XContentFieldValueWriter`, there does not seem to be case for custom subtypes of `FieldValue`.
https://github.com/sksamuel/elastic4s/blob/538a6bfc2f663a2684e86a287c56a1e1b4eab6ad/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/XContentFieldValueWriter.scala#L4

Is the doc outdated, or am I missing something?

Thanks!

**Comment by DenisNovac** [comment]
Hi there. I've had similar problem on 6.7.4 and managed to workaround it through defining custom FieldBuilderFn (and all the modules above it from the bottom to `elasticClient.execute()`). There i define all my custom fields.
