### ISSUE TITLE
Better way to create own analyzers with filters?

### ISSUE THREAD

**Issue by DenisNovac** [sksamuel/elastic4s#2040]
Hello. I am running elastic4s 6.7.4.

There is a CustomAnalyzerDefinition class with filters field. When it is processed - filters inside it extracted and created.

I tried to create own AnalyzerDefinition (since it is not case class and have no `def build(source: XContentBuilder): Unit` definition) with filters - but i got stuck on errors:

```
Error message: ElasticError(illegal_argument_exception,Custom Analyzer [no_analyzer] failed to find filter under name [russian_stop],None,None,None,List(ElasticError(illegal_argument_exception,Custom Analyzer [no_analyzer] failed to find filter under name [russian_stop],None,None,None,null,None)),None)"
```

There is pattern matching on CustomAnalyzerDefinition in AnalysisDefinition class which collects filters only if gets instance of CustomAnalyzerDefinition. 

Is there another way to create own Analyzers (personally i need to create custom body) with filters? Maybe it would make sense to have something with filters but yet without body?

I managed to workaround this trouble for now by extending an `AnalysisDefinition` and overriding it's pattern matching with my custom class with filters and custom body.

**Comment by sksamuel** [comment]
The filters was rewritten in 7+. You could try that.

**Comment by DenisNovac** [comment]
Is it for Elastic 7?

**Comment by sksamuel** [comment]
You could use it on 6.

**Comment by DenisNovac** [comment]
Thanks, maybe we'll try it.
