### ISSUE TITLE
Weird default limit on search query

### ISSUE THREAD

**Issue by MarcinAman** [sksamuel/elastic4s#2043]
Hi,

as far as i can tell every search query is limited to 10 results. Right now Elasticsearch is limiting it's queries by 10.000 which is far more then library. 

0) Am i missing something in that regard?
1) Is there a way to remove a default limit and stick to what elastic is giving? I know i can hard-code 10 000 but this is a silly solution
2) If not, can this be a feature?

This topic was mentioned in: https://github.com/sksamuel/elastic4s/issues/288

Here is some basic info about versions i am using:
```
"com.sksamuel.elastic4s" %% "elastic4s-client-esjava" % "7.3.5"
```

**Comment by sksamuel** [comment]
https://stackoverflow.com/questions/41803232/limit-the-number-of-results-returned-by-elastic-search/41803358
 ?

**Comment by MarcinAman** [comment]
I think that i wasn't clear in my question:

1) am i right that by default all queries using elastic4s are limited to 10 records?
2) Is there a way to remove that limitation OTHER than explicitly ask for 10 000 records in EVERY query? I'd like to say that this instance of elasticsearch client would fetch all records (up to ElasticSearch limits of course)

So basically instead of this:

```
for {
      records <- esClient.execute {
        search(index).termQuery("productUuid", productId.uuid).limit(10000)
      }
    } yield records.result.to[Entity]
```

i'd like to have this:

```
for {
      records <- esClient.execute {
        search(index).termQuery("productUuid", productId.uuid)
      }
    } yield records.result.to[Entity]
```

**Comment by sksamuel** [comment]
The limit is in elastic seach not elastic4s.

**Comment by MarcinAman** [comment]
Ok, thanks for your answer :)

i'll keep digging in ES documentation then
