### ISSUE TITLE
conflicting akkaVersion when using with play-ws

### ISSUE THREAD

**Issue by bowerth** [sksamuel/elastic4s#2050]
Hello,

Many thanks for continued development of elastic4s.
I was testing to upgrade from 7.3 to 7.6 and received an error related to the version of akka-stream:

```
Possibly conflicting versions [2.5.23, 2.6.4] in libraries [akka-protobuf:2.5.23, akka-actor:2.6.4, akka-stream:2.5.23]
```

Previously, I was using elastic4s version 7.3.0 and play-ws version 2.0.7
The latest play-ws version 2.1.2 is using akka-stream 2.6.1 and the master branch on github is using akka-stream 2.6.3. Would you have any suggestions how play-ws could still be used with elatic4s 7.3 or higher?

**Comment by sksamuel** [comment]
Can you just add those dependencies to your build directly with the higher
version ?

**Comment by bowerth** [comment]
great, this worked! many thanks for the prompt reply!
```
libraryDependencies += "com.typesafe.akka" %% "akka-stream" %  "2.6.4"
```
