### ISSUE TITLE
Documentation needs a major update

### ISSUE THREAD

**Issue by crockpotveggies** [sksamuel/elastic4s#2053]
Myself and another experienced member of my team have tried to use the recent `7.x` versions of this library but are having significant difficulty determining how to use even the basic dependencies. I'd be glad to open a PR myself to update the docs if someone could work with me on it.

**Comment by sksamuel** [comment]
I would help.

**Comment by crockpotveggies** [comment]
@sksamuel glad to accept it, let me set up an external channel on our slack. can you send me an email to justin.long@yoppworks.com so i can respond with an invite? thanks

**Comment by crockpotveggies** [comment]
Did the slack invite going to work? If you prefer to open up a Discord I'm happy to chat on there, too

**Comment by sksamuel** [comment]
I prefer slack. I can't get it to work though, it wants to add me to some
kind of shared channel, to an existing workspace, but it doesn't appear.

**Comment by crockpotveggies** [comment]
Sent a new invite, the old one was a cross-team invite but this new one is for you specifically as a standalone account.

**Comment by sksamuel** [comment]
If you want to, I can move the docs out of tut as well. No one is maintaining that microsite thing that was  added. It's easier to just use markdown.

**Comment by crockpotveggies** [comment]
I think the docs are suitably updated for someone to use all of the basic functionality. Closing :)
