### ISSUE TITLE
Compiling elastic4s 6.x versions with Jackson 2.10

### ISSUE THREAD

**Issue by dope9967** [sksamuel/elastic4s#2056]
Ran into this when updating to Akka 2.6 - it uses Jackson 2.10 and the issue is that jackson-module-scala 2.10 is not binary compatible with 2.9, my guess is because of this change https://github.com/FasterXML/jackson-module-scala/commit/408b5bf259bd23db67f3ddc104326dc422499dfc#diff-0afb6b3f61931ec676d2e2c2a98ffb02. Would it be an option to compile and publish 6.x versions with Jackson 2.10? I could submit PRs.

**Comment by sksamuel** [comment]
Yes, if you make the PRs I will release.

**Comment by dope9967** [comment]
@sksamuel I've created all the PRs, skipped `6.7.x` because it already depends on Jackson 2.10. Didn't include version bumps as I assume that you are doing those yourself when releasing.

**Comment by domantas-petrauskas-visma** [comment]
@sksamuel Could you provide an update on when you are planning to release these? Don't want to bother you too much, but these releases would solve a few headaches of mine.

**Comment by dope9967** [comment]
@sksamuel Could you provide an update on when you are planning to release these? Don't want to bother you too much, but these releases would solve a few headaches of mine.

**Comment by sksamuel** [comment]
6.2.12 and 6.310 have been released. More to follow.

**Comment by sksamuel** [comment]
6.5.7 and 6.6.4 also now released.

Sorry for the huge delay in releasing these and thank you for the PRs.
