### ISSUE TITLE
Problem when parsing search results

### ISSUE THREAD

**Issue by thompbil** [sksamuel/elastic4s#2058]
Hi,

I am running ElasticSearch 7.6.2 on Windows 10
and my application is using elastic4s-http-streams 7.6.0 for Scala 2.12

My application issues a search request against the elastic instance, and the following exception is raised:

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `long` out of START_OBJECT token

at [Source: (StringReader); line: 1, column: 185] (through reference chain: com.sksamuel.elastic4s.http.search.SearchResponse["hits"]->com.sksamuel.elastic4s.http.search.SearchHits["total"])

When I issue the search request natively using curl, the following is returned 

{"_scroll_id":"DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAAQWUVZ0dlJ0ZE5UcnVEQ2VwZ1RaeUlBZw==","took":6,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":41,"relation":"eq"},"max_score":1.0,"hits":[{"_index":....

So it looks to me like the json fragment which is causing the issue is : 
"hits":{"total":{"value":41,"relation":"eq"},"max_score":1.0,"hits":[{"_index":

where hits.total is indeed an object not a long. Is this a compatibility issue? 

Regards,

Bill

**Comment by thompbil** [comment]
I have discovered this is a compatibility issue with a breaking change introduced in elastic search 7.0 . See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#breaking_70_search_changes for detail. Workaround suggested is: "You can also retrieve hits.total as a number in the rest response by adding rest_total_hits_as_int=true in the request parameter of the search request. "

**Comment by sksamuel** [comment]
I think the object in elastic4s should be updated to reflect the new
structure in elasticsearch.
Do you want to make the change ?

**Comment by sksamuel** [comment]
Actually looking at the source, total is already an object: `case class Total(value: Long, relation: String)`

Are you using a recent version of elastic4s ?
