### ISSUE TITLE
ArtistIndex example doesn't compile

### ISSUE THREAD

**Issue by fancellu** [sksamuel/elastic4s#2065]
I am pulling in

libraryDependencies += "com.sksamuel.elastic4s" %% "elastic4s-client-esjava" % "7.6.1"

I pull in as many other obvious imports which don't get mentioned, but still have a problem

```Error:(30, 25) value / is not a member of String
    indexInto("artists" / "modern").fields("name" -> "L.S. Lowry").refresh(RefreshPolicy.Immediate)
```

Any chance of having some sample code that compiles?

Thanks

**Comment by sksamuel** [comment]
Thanks I've updated the readme.
