### ISSUE TITLE
Is there a way to index a JSON String directly _label:quesiton

### ISSUE THREAD

**Issue by soumyasd** [sksamuel/elastic4s#208]
I've a JSON String that I want to index directly into ElasticSearch ? Is this possible with elastic4s

**Comment by ksilin** [comment]
For all those finding this and wondering why it does not work - use JsonDocumentSource instead of StringDocumentSource. Here is the ref about sources: https://github.com/sksamuel/elastic4s/blob/master/guide/source.md

**Comment by RPGambit2** [comment]
Hi SK.   I am having an issue attempting to write a scala JSON string to Elasticsearch using 5.2.11 elastic4s.  I've tried everything I can think of and have seen in examples.   The index gets created, but with no data.  Here is a sample I am trying...

      var JSONDataRecord1: String =
        """{
        "_source": {
          "RunId": "b2ab4c11-fb59-4a02-a93a-3b0f7a8b1d07",
          "CreatedOnTimestampMS": 1472759158162,
          "EndTimeTimestamp": 1495027786000,
          "CreatedBy": "T@ibm.com",
          "Topic": "PollenPollen_Content_1",
          "JobId": "125",
          "SerializationFmt": "",
          "CreatedOnTimestamp": 1472759158162,
          "EndTimeTimestampMS": 1495027786000,
          "ReversePubFlag": false,
          "StartTimeTimestampMS": 1495027783000,
          "SourceURL": "jdbc:sqqqlserver://databaseName=SDDI",
          "StartTimeTimestamp": 1495027783000,
          "TargetDBString": "jdbc",
          "StatusDescription": "Complete",
          "TargetURI": "",
          "DataTable": "Pollen_Content",
          "TargetURL": "jdbc:sqqqlserver://awssql01p.cqq9jezwumm3v.us-east-1.rds.amazonaws.com;databaseName=poll",
          "DataFeed": "POLLEN",
          "Client": "POLLEN_AWSSQL01P",
          "TargetDriverClass": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
          "Status": 2,
          "RecordsCount": 2573,
          "Records2Count": 2573
        },
        "fields": {
          "StartTimeTimestamp": [
          1495027783000
          ],
          "CreatedOnTimestamp": [
          1472759158162
          ],
          "Duration": [
          3000
          ],
          "scripted-Status": [
          "Complete"
          ],
          "EndTimeTimestamp": [
          1495027786000
          ]
        },
        "sort": [
        1495027783000
        ]
      }"""

    // Write to Elasticsearch!!!!!!!!!!
    EIGenericElasticSetupMessage.client.execute (
      indexInto(EIGenericElasticSetupMessage.elasticIndex, EIGenericElasticSetupMessage.elasticType) doc (JSONDataRecord1)
    )

**Comment by ihrimech** [comment]
If you're in 2020 and looking at this thread, `src` is replace by `source`

The example given before would be :

```scala
val req = docs.map(doc => index into "index"->"type" source doc )
client execute { bulk { req } }
```
