### ISSUE TITLE
elastic4s-play-json and elastic4s-http upgrade to 7.x.x

### ISSUE THREAD

**Issue by scalamat** [sksamuel/elastic4s#2088]
Hi, 
wanted to use the 7.6.1 version and saw that the both packages above are still availabe als 6.x.x package. Is their a date when it will upgraded? Or is their a explanation how I can use the 7.x.x package without the both above packages?

Thank you

**Comment by sksamuel** [comment]
The packages have changed in 7.x +. Please see the docs on the main page.
