### ISSUE TITLE
Use of await method is discouraged in documentation

### ISSUE THREAD

**Issue by ksceriath** [sksamuel/elastic4s#2094]
Hi,

I noticed at several places in documentation that the use of `await` method (e.g. `client.execute { } .await`) has been discouraged in real code.

Am I missing something? I would like to understand if there is some other way to ensure the consistency of the transaction.

My typical usage is this: I have a spark job which does some time-consuming computations on a cluster of nodes, and towards the end persists the results into several data stores, including ES. For this I would use the elasticsearch bulk insert/update apis -- and if there are failures while writing some documents, I would retry the update/insert again.

I feel that I do not have any other choice than to `await` for the ES call to succeed or fail. Even if I use `onComplete` method on the `Future` returned by the execute method,  the job finishes before all the `Future`s are able to execute; so instead I would anyway end up waiting on those `Future`s at the end of my main thread (which also makes the code a little ugly).

Am I doing this wrong? Is there some other idiomatic way to handle this?

**Comment by sksamuel** [comment]
I guess in your case you need to wait for the future because that's the end
of the task.

This kind of advice - to not use await - is not specific to elastic4s but
just generally speaking good advice for using futures.
