### ISSUE TITLE
`RandomScoreFunction` not compatible with < ES6.0

### ISSUE THREAD

**Issue by dontgitit** [sksamuel/elastic4s#2131]
ES 6.0 changed the API to require `field` if providing `seed` (https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-function-score-query.html#function-random), and your library supports that perfectly

However, the API previous to 6.0, such as 5.6, only supports `seed`, and doesn't support a custom `field`: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-function-score-query.html#function-random
Attempting to pass in a value for `field` produces the following 400: 
```
{"error":{"root_cause":[{"type":"parsing_exception","reason":"random_score query does not support [field]","line":1,"col":193}],"type":"parsing_exception","reason":"random_score query does not support [field]","line":1,"col":193},"status":400}
```

Would you be open to changing
```scala
case class RandomScoreFunction(seed: Long, fieldName: String = "_seq_no", weight: Option[Double] = None, override val filter: Option[Query] = None)
``` 
to something like
```scala
case class SeedAndField(seed: Long, fieldName: String = "_seq_no")
case class RandomScoreFunction(seedAndField: Option[SeedAndField] = None, weight: Option[Double] = None, override val filter: Option[Query] = None)
```

This would allow users to call `RandomScoreFunction()` on older versions of <ES6, while still providing correct behavior on >=ES6. It won't allow older versions to use `seed`, but that's ok for my use case 😅 

Happy to provide a PR if you think this is acceptable. If not... is there any other way around the issue (other than upgrading ES versions...)? I would love to just override `RandomScoreFunctionBuilderFn`, but that's not possible....

**Comment by sksamuel** [comment]
Can we just change it in an earlier version of elastic4s?

**Comment by dontgitit** [comment]
That could work... can I do it in a 6.5.x or up branch?

**Comment by sksamuel** [comment]
Can do it in any branch that makes sense. If it only works < 6 then a
release/5.x.y branch might be best. If you raise the PR I'll do the release.

**Comment by dontgitit** [comment]
5.x branch is definitely the most logical place to put this.... however, we're on 6.x because things were missing from 5.x iirc... don't remember what it was exactly though...

**Comment by sksamuel** [comment]
Well we can't merge a PR that breaks things for 6.x users. If you can do
something backwards compatible, that defaults to the correct state for 6.x
users, then all good.

**Comment by dontgitit** [comment]
it wouldn't break functionality - `seed` is still optional in 6+. It would however create compilation issues since I would require changing the member type...

**Comment by sksamuel** [comment]
See if you can come up with something else. Even a
separate implementation of the function.

**Comment by dontgitit** [comment]
Actually, I think I can do this in a way that doesn't break compilation:
```scala
case class SeedAndField(seed: Long, fieldName: String = "_seq_no")
case class RandomScoreFunction(seedAndField: Option[SeedAndField], weight: Option[Double], override val filter: Option[Query])
    extends ScoreFunction 

object RandomScoreFunction {
  def apply(seed: Long, fieldName: String = "_seq_no", weight: Option[Double] = None, filter: Option[Query] = None): RandomScoreFunction = new RandomScoreFunction(Some(SeedAndField(seed, fieldName)), weight, filter)
}
```

Of course, if anyone is directly using `RandomScoreFunction().seed/field` that won't compile anymore

Only other thing I can think of is adding a new case class, `RandomScoreFunctionES5`

**Comment by dontgitit** [comment]
Or maybe introduce another param like `ignoreField: Boolean = false` that the `RandomScoreFunctionBuilderFn` can check? still seems very hacky :(

**Comment by sksamuel** [comment]
Yeah I guess trying to do this in the 6.x branch isn't ideal. Can you
cherry-pick back to the 5.x branches to get what you want ?

**Comment by dontgitit** [comment]
It's certainly possible...

Is there any reason you're against the `Option[SeedAndField]` change? Your library currently forces users to set a `seed` if they want want to use `random_score`, even though `seed` isn't actually required by the API.

**Comment by sksamuel** [comment]
No, actually I think that's fine.

**Comment by dontgitit** [comment]
I opened a PR here: https://github.com/sksamuel/elastic4s/pull/2133

Let me know if you want me to open it against 6.7.x instead

**Comment by dontgitit** [comment]
I saw you released a new artifact for 7.x, any chance you could also make one for 6.x when you find the time? Thank you!

**Comment by sksamuel** [comment]
@dontgitit sorry for missing this. Will release this weekend.

**Comment by dontgitit** [comment]
Awesome, thank you!

**Comment by sksamuel** [comment]
Which brand specifically ?

**Comment by dontgitit** [comment]
It's on 6.7.x release branch I believe?
https://github.com/sksamuel/elastic4s/pull/2138

**Comment by sksamuel** [comment]
6.7.7 has been released.

**Comment by dontgitit** [comment]
Awesome, thank you so much!

**Comment by sksamuel** [comment]
Thank you for your patience!
