### ISSUE TITLE
akka-http client authentication

### ISSUE THREAD

**Issue by mrooding** [sksamuel/elastic4s#2145]
Hi

I'm trying to set up elastic4s in combination with the akka-http client. I'm able to get the connection set up without authentication by using the typesafe configuration property path `com.sksamuel.elastic4s.akka.hosts` but I'm not able to supply credentials for the connection.

I've tried setting the host strings in the following format but that doesn't seem to do anything (the library seems to not execute any request at all since no logs are being produced): `$user:$pass@$host:$port`.

Can you tell me how to properly provide basic authentication credentials in combination with the akka-http client? I'd be willing to open a PR to provide this as a feature to elastic4s-akka-http if it's not possible just yet.

Thanks!

**Comment by mrooding** [comment]
Closed since #2146 is merged

**Comment by wuservices** [comment]
I found a bug in #2146. I submitted a PR with a fix in #2195.
