### ISSUE TITLE
mapping support for _timestamp

### ISSUE THREAD

**Issue by fehmicansaglam** [sksamuel/elastic4s#215]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html

**Comment by l15k4** [comment]
Please would you mind adding [support](https://github.com/elastic/elasticsearch/issues/8893) for setting `_timestamp` as `doc_values` ?

Usually when people `sort` huge datasets, the field being sorted on must be `doc_values` and it usually is sorted by `_timestamp`... WDYT ?
