### ISSUE TITLE
CompletionSuggestionBuilderFn + regex = scala.NotImplementedError

### ISSUE THREAD

**Issue by samzilverberg** [sksamuel/elastic4s#2151]
on line 27

https://github.com/sksamuel/elastic4s/blob/8e2f2a0d10bb30a24b36d67cf1ffd438ac0cf036/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/searches/suggestion/CompletionSuggestionBuilderFn.scala#L25-L34

git blame suggests it happened here:

https://github.com/sksamuel/elastic4s/commit/538a6bfc2f663a2684e86a287c56a1e1b4eab6ad

probably while merging and updating 10^700 imports 😆 

i didn't open a pr because wasn't sure it was OK to delete that `???`, maybe you had something in mind to put there?

**Comment by sksamuel** [comment]
Yeah I think we can remove that :)
