### ISSUE TITLE
Client performance issue

### ISSUE THREAD

**Issue by amerpersonal** [sksamuel/elastic4s#2157]
Hi,

I'm using ordinary get document in my code, using elastic4s.  I'm timing operations and locally it lasts beteen **150 - 200 ms**, but on our dev environment it takes around **1 second.**

Wondering what happens. Of course, our dev environment is much more in use, so I guess client has many more opened connections.

Here is my code:

` execRequest("get document", {
    val getReq = get(id).from(index)
      if(fields.isEmpty) getReq else getReq.fetchSourceInclude(fields)
    }).flatMap { getResponse: GetResponse =>
      if(getResponse.found) Future.successful(mapResponse(getResponse))
      else Future.failed(new NoSuchElementException("Document not exists"))
   }
}`

Here is execRequest method:

`  def execReq[T, U](event: String, req: => T)(implicit function: Functor[Future], execution: Executor[Future], handler: Handler[T, U], manifest: Manifest[U]): Future[U] = {
    val f = httpClient.execute {
      req
    }

    f.flatMap { response =>
      response match {
        case RequestSuccess(status, body, headers, result) => Future.successful(result)
        case RequestFailure(status, body, headers, error) => {
          logger.error(s"Failure on ES request: ${body}")
          Future.failed(new Throwable(error.reason))
        }
      }
    }
  }`

I'm instantiating client inside object EsClient as following (and then use it in all places):

` val client = AkkaHttpClient(AkkaHttpClientSettings(esHosts.map(h => s"${h}:9200")))(as)

 ElasticClient(client)`

1. Is this the best way to instantiate client?

2. How about tunning connection. In source code, I see that it accepts config 

com.sksamuel.elastic4s.akka

Does this mean I can tweak it in application.conf as this

` com {
  sksamuel {
    elastic4s {
       akka {
           queue-size: <value>
      }
  }
}`

Also, how about tuning connection poll settings? Which are default values and how to do that?

Please advise, since this is really bothering me for some time now.
I mean, one get request should definitely not last for 1 second. Even on postgres

Thanks in advance,

Amer

**Comment by amerpersonal** [comment]
Now I notice this same call on DEV env takes around 150 ms to complete. Yesterday it was 800-900 ms. Ordinary get call. Do you have idea why its happening? It's constant execution time when I run GET request from postman directly to ES.

**Comment by amerpersonal** [comment]
Another update. I isolated the code and am executing it now on my local machine. First request is really slow - 1500 ms, each subsequent much faster - around 150 ms.

Can you advise anything related to this?

**Comment by sksamuel** [comment]
You could try using the normal rest client rather than the akka http one.

**Comment by amerpersonal** [comment]
@sksamuel thank you very much mate, you saved my day!

I introduced RestClient. First request now lasts for 300 ms and each next around 70 ms. Much faster!

However, it is a bit cumbersome to use:

`al httpHosts = esHosts.map(host => new HttpHost(host, 9200))
  val restClientBuilder = RestClient.builder(httpHosts: _*)
  val restClient = restClientBuilder.build()

  def getDocRest(index: String, id: String) = {
    val req = new Request("GET", s"${index}/_doc/${id}")

    val p = Promise[Map[String, Any]]()
    restClient.performRequestAsync(req, new ResponseListener {
      override def onFailure(exception: Exception): Unit = {
        p.failure(exception)
      }

      override def onSuccess(response: client.Response): Unit = {
        p.success(Map.empty)
      }
    })

    p.future
  }`

Is there any way to create Request instance in a better way that this above @sksamuel ?

Thanks

**Comment by amerpersonal** [comment]
So the main issue with RestClient is that everything need to be handled manually vice requests and responses. That makes search code really cumbersome. I also tried high level rest client (needed to include additional dependency), but it is also totally in Java style, so a lot of conversions needs to be done when creating requests etc.

What do you recommender/prefer ?

**Comment by sksamuel** [comment]
You use the rest client and pass that into elastic4s client.
Eg,

```
val props = ElasticProperties("http://host1:9200")
val client = ElasticClient(JavaClient(props))
```

Then the client can be used like,

```
val f = client.execute { search("foo") 
```
