### ISSUE TITLE
Cross compatibility between ES6 elastic4s v6.2.8 and ES7 elasticsearch-rest-high-level-client

### ISSUE THREAD

**Issue by ashu-vedi** [sksamuel/elastic4s#2158]
We have a scala project and two elasticsearch clusters running on elasticsearch 6.2(using sksamuel/elastic4s v6.2.8) and elasticsearch 7.2 using .
We need to query both elasticsearch clusters the same sbt project as follows. 
val elastic4sVersion = "6.2.8"
```
libraryDependencies ++= Seq(
  "com.sksamuel.elastic4s" %% "elastic4s-core" % elastic4sVersion,
  // for the http client
  "com.sksamuel.elastic4s" %% "elastic4s-http" % elastic4sVersion,
)
```

```
libraryDependencies +="org.elasticsearch" % "elasticsearch" % "7.2.0"
libraryDependencies += "org.elasticsearch.client" % "elasticsearch-rest-high-level-client" % "7.2.0"
```

While doing this org.elasticsearch.client can be taken from either elasticsearch 6 or 7 and being overwritten. Please suggest what are our options to achieve this without rewritting a lot of queries from elastic 6 to 7 .

**Comment by sksamuel** [comment]
What you're asking is how to have two dependencies of the same type in the same project. I don't think that's possible.
