### ISSUE TITLE
Support for GeoTile Grid Aggregation

### ISSUE THREAD

**Issue by jdcohen220** [sksamuel/elastic4s#2160]
It would be nice to have support for GeoTile Grid Aggregations. 

This was pretty easy as the aggregation body and results are very similar to the existing GeoHashGridAggregation.

I opened PR: #2159

**Comment by jdcohen220** [comment]
@sksamuel thanks for merging! When do you think an artifact will be released on maven?

**Comment by sksamuel** [comment]
I can release another 7.8 one tonigh.

**Comment by jdcohen220** [comment]
That would be great! Thanks so much.

**Comment by sksamuel** [comment]
7.8.1 released
