### ISSUE TITLE
Do you support elastic 6.8?

### ISSUE THREAD

**Issue by idankWix** [sksamuel/elastic4s#2165]
In your readme, you go from 6.7 to 7.0
wanted to know if it is an oversight in the documentation or you don't support it

**Comment by sksamuel** [comment]
There was no explicit release for that version, but you could use the 6.7 version of elastic4s. The json formats are the same, bar any new features added in 6.8.

**Comment by idankWix** [comment]
Great thanks for the update. 
Last question is 6.7 backward compatible for elastic version 6?

**Comment by sksamuel** [comment]
Yes.
