### ISSUE TITLE
Fix in documentation

### ISSUE THREAD

**Issue by kbakha** [sksamuel/elastic4s#2177]
Recently needed to get aware of this useful library. 
Noticed some mistakes maybe in the following example:
`A full example:
val resp = client.execute {
  search("gameofthrones").query("kings landing")
}.await // don't block in real code

// .to[Character] will look for an implicit HitReader[Character] in scope
// and then convert all the hits into Characters for us.
val characters: Seq[Character] = resp.to[Character]`

I believe it's `val characters: Seq[Character[ = resp.result.to[Character]` ?

**Comment by sksamuel** [comment]
Yes thank you, updated.
