### ISSUE TITLE
maxAgg shortcut requires a mandatory field but internally is optional

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#2183]
Hi, a little detail!

@deprecated("use maxAgg", "7.7")
def maxAggregation(name: String): MaxAggregation = MaxAggregation(name)
def maxAgg(name: String, field: String): MaxAggregation = MaxAggregation(name).field(field)

**maxAggregation** has been deprecated but is still valid to instantiate a MaxAggregation with no field, like when using scripting.

Regards,
Patricio.

**Comment by sksamuel** [comment]
Fixed in master.
