### ISSUE TITLE
Authenticating sttp-client requests

### ISSUE THREAD

**Issue by radutoev** [sksamuel/elastic4s#2188]
From what I can tell atm there is no way of adding authentication to requests when using the sttp clent (like aws headers for example). 
Would it make sense to extend the client to allow setting headers on the request?

**Comment by sksamuel** [comment]
Yes I think so.

**Comment by radutoev** [comment]
Mind if I give it a shot? I think I'll some free time in the next couple of days.

**Comment by sksamuel** [comment]
Yeah that would be great.

**Comment by radutoev** [comment]
Does elastic4s have a discord/slack channel? Got a couple of questions :)

**Comment by sksamuel** [comment]
No, I'm active on the kotlinlang one :)
Scala really could do with a slack.
