### ISSUE TITLE
Support remove_index alias action

### ISSUE THREAD

**Issue by jmaasing** [sksamuel/elastic4s#2194]
It would be nice to have support for the remove_index action on /_aliases

`{
  "actions" : [
    { "remove_index" : { "index" : "deleteme" } }
  ]
}
`

Our use case is that when we re-index our database we write to a new index, when complete we remove the alias from old indices (there can be several), set the alias to the new index and drop old indices (according to some policy where we keep the last three et c). It's pretty nice to be able to do all that with one request to ES.

[https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html](ES API reference)

**Comment by sksamuel** [comment]
So this operation not only removes the aliases but drops the index at the same time ?

**Comment by jmaasing** [comment]
remove_index is just like Delete index (I think internally in ES it's the same operation) but can be used inside alias actions.
`
{
  "actions" : [
    { "add":  { "index": "test_3", "alias": "test" } },
    { "remove" : { "index" : "test2", "alias" : "test" } },
    { "remove_index": { "index": "test1" } }  
  ]
}
`

This would 'move' the alias to point to test3, keep the test2 index in ES and drop the test1 index.

**Comment by sksamuel** [comment]
I see, nice.
