### ISSUE TITLE
seq_no_primary_term in search

### ISSUE THREAD

**Issue by ErikWallin** [sksamuel/elastic4s#2213]
I am about to migrate to ES 7.9 from 6.8 and I try out the elastic4s version 7.9.0.

I have used "version" for optimistic concurrency control, but since 6.7 it is deprecated, and in ES version 7 (7.9) it gives an error: "internal versioning can not be used for optimistic concurrency control. Please use `if_seq_no` and `if_primary_term` instead;"

I have used version(true) on the SearchRequest case class, but cannot find a way to set the seq_no_primary_term in the search request in elastic4s. Is there a way I have missed? Otherwise I think this is a highly needed requirement for elastic4s.

Thanks for a great product.

**Comment by ErikWallin** [comment]
Pull request: https://github.com/sksamuel/elastic4s/pull/2214

**Comment by sksamuel** [comment]
We should add the if_seq_no and if_primary_term parameters to the request now.

**Comment by ErikWallin** [comment]
Thanks. Do you have a date for 7.9.1?

**Comment by sksamuel** [comment]
7.9.1 has been released, I forgot to come back and mention that.

**Comment by izzyreal** [comment]
Could we have this fix backported to 7.8.x?

And for the time being is there a workaround?
