### ISSUE TITLE
Do not throw RuntimeException in OptionImplicits

### ISSUE THREAD

**Issue by bsenyshyn** [sksamuel/elastic4s#2222]
Current realization of getOrError throws RuntimeException in 7.9.0 version.

`  
implicit class RichOption[T](option: Option[T]) {
    def getOrError(message: String): T = option.getOrElse(sys.error(message))
}
`

Could this be changed to just giving None, without throwing exception?

**Comment by sksamuel** [comment]
The name itself says it will throw an error, that's the whole point of the method.

If it returned a None, or a Some, then that's just the option you started with.
