### ISSUE TITLE
com.sksamuel.elastic4s.http.JavaClient doesn't always invoke the callback

### ISSUE THREAD

**Issue by tomerbendror** [sksamuel/elastic4s#2226]
Hi,

The issue I face is that when using AWS Elasticsearch, when using the 'underlying' client to create an index, the callback is never invoked, the reason is that Elasticsearch will not always returns a response with charset, and in this case the next line will result a null (JavaClient.fromResponse(..)):
`val contentCharset = Option(ContentType.get(entity)).fold(Charset.forName("UTF-8"))(_.getCharset)`

and as a result this call will throw an Exception: 
`val body = Source.fromInputStream(contentStream).mkString`

In order to reproduce it:
```
object EsBug extends App{
  val props = ElasticProperties("https://search-a205917-...-west-1.es.amazonaws.com:443")
//  val props = ElasticProperties("http://localhost:9200")
  val esClient: ElasticClient = ElasticClient(JavaClient(props))
  val request = ElasticRequest("PUT", "my-index", HttpEntity("{}"))
  esClient.client.send(request, {
    case Right(value) =>
      println(s"Right: $value")
      esClient.close()
    case Left(value) =>
      println(s"Left: $value")
      esClient.close()
  })
}
```

BTW - the same will work using `http://localhost:9200` OR by changing "my-index" into "/my-index"

**Comment by horwreed** [comment]
I'm running into the same issue. How was this was resolved @tomerbendror?

**Comment by tomerbendror** [comment]
Just add the / char before the index name as I did
