### ISSUE TITLE
RestoreSnapshotResponse is not congruent with ES response

### ISSUE THREAD

**Issue by eilite** [sksamuel/elastic4s#2229]
`RestoreSnapshotResponse(acknowledged: Boolean)` should be changed to `RestoreSnapshotResponse(accepted: Boolean)` because the restore snapshot api returns `accepted` .

**Comment by tarangbhalodia** [comment]
@eilite What is the version you are on?

**Comment by eilite** [comment]
I'm running `6.3.10` but I think it's the same on the latest versions
