### ISSUE TITLE
Add the wildcard field to the ElasticDsl

### ISSUE THREAD

**Issue by alexwlchan** [sksamuel/elastic4s#2236]
We use the ElasticDsl to define our index mappings, e.g.

```scala
import com.sksamuel.elastic4s.ElasticDsl._

val fields: Seq[FieldDefinition] =
  Seq(
    keywordField("name"),
    keywordField("place")
  )
```

It would be useful if we could define wildcard fields using the DSL. I can see some support was merged in #2217, but there's no DSL support.

I think this would involve:

* Creating a new case class WildcardField, a la [TextField](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/mappings/TextField.scala) and [KeywordField](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/mappings/KeywordField.scala)
* Updating the DSL in [TypesApi](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/TypesApi.scala)
* Adding the new WildcardField to [CommonFieldBuilder](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/mappings/CommonFieldBuilder.scala)
* Adding tests for the above

~Currently I'm inlining a FieldDefinition for wildcard, but it would be nice to have this in the core library.~ I quickly discovered this doesn't work unless I want to vendor way more stuff.

I could write a patch if you're interested and have time to review.

(Part of https://github.com/wellcomecollection/platform/issues/4859, https://github.com/wellcomecollection/platform/issues/4855)

**Comment by sksamuel** [comment]
Patch would be great.

**Comment by alexwlchan** [comment]
I haven't had a chance to use this yet, but I believe this was finished in #2237.
