### ISSUE TITLE
upsert UpdateRequest strips empty upsert docs

### ISSUE THREAD

**Issue by meitemarkymark** [sksamuel/elastic4s#2238]
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/update/UpdateBuilderFn.scala#L33

It's valid in ES to have an empty upsert doc (i.e. no document field updates), if one is providing a `script`. This is especially useful in scripted upserts, where the script is always run. However, it's also valid to simply choose to use painless scripting to construct the upserted document.

In either scenario, an empty `upsert` doc is needed to tell ES that the update is an upsert. The `UpdateBuilderFn` is stripping the upsert marker if the doc is empty.

A valid request that fails with e4s might look like this:
```
{
 "script": {
    "source": "...",
    "lang": "painless"
  },
  "upsert": {}
}
```

I would recommend simply removing the `nonEmpty` guard around this JSON rendering such that `"upsert": {}` is preserved. Our workaround for now is to simply add a dummy field in the `upsert` document.

**Comment by tarangbhalodia** [comment]
I'd like to work on this one.

**Comment by sksamuel** [comment]
Please do.

**Comment by tarangbhalodia** [comment]
@meitemarkymark 

> I would recommend simply removing the nonEmpty guard around this JSON rendering such that "upsert": {} is preserved. Our workaround for now is to simply add a dummy field in the upsert document.

We cannot simply remove the guard around because, if we do, strict update request will also become an upsert request. So, to fix this, I have added an additional check on `docAsUpsert` in my PR: #2280 .

If `docAsUpsert` is set to `true` then an empty upsert field will not be stripped.

**Comment by Marko131** [comment]
I think now update by id with script will create document if it doesn't exists. So
