### ISSUE TITLE
Documentation - Failover

### ISSUE THREAD

**Issue by baitmbarek** [sksamuel/elastic4s#2278]
Hi !
I've been facing a problem when declaring multiple Elasticsearch nodes like in the documentation (I'm using the 7.6.1 release) :
```scala
val nodes = ElasticProperties("http://host1:9200,http://host2:9200,http://host3:9200")
val client = ElasticClient(JavaClient(nodes))
```
When I removed the `http://` prefix from `host2` and `host3`, failover started working as expected.
I think the Readme.md should be updated in order to give the correct syntax :
```scala
val nodes = ElasticProperties("http://host1:9200,host2:9200,host3:9200")
val client = ElasticClient(JavaClient(nodes))
```

In the ElasticProperties object and its apply method, we use the following Regex to extract the `protocol` and the `hoststr` which is the splitted using a comma:
```scala
val Regex = "(http|https)://(.*?)/?(/.*?)?(\\?.*?)?".r
```
The same protocol is then used for each `ElasticNodeEndpoint`.

A documentation update would be great so the community can benefit from this update. Declaring the hosts with the http prefix for each one doesn't raise a Runtime exception until the first node goes down.

I'd also want to thank you for all your work :slightly_smiling_face:
Regards.

**Comment by qiweigoh** [comment]
+1

**Comment by qiweigoh** [comment]
+1 for the documentation update required. 

@baitmbarek I would like to check if you do face an issue with multiple nodes. 
I have set up multiple nodes in this manner:
```
val nodes = "http://node1:9200,node2:9200,node3:9200,node4:9200,node5:9200"
val client: ElasticClient = ElasticClient(JavaClient(ElasticProperties(nodes)))
```
 
But when I execute a search request with the client, I only get a response from the first node that is defined instead of all the nodes. Do you face the same issue?
