### ISSUE TITLE
ElasticProperties should use the HTTPS port if no port specified

### ISSUE THREAD

**Issue by ridrum** [sksamuel/elastic4s#2306]
Hi ✌️ 

**Issue/Rationale** : 

The default port used by the `ElasticProperties` is :9200 even if the HTTPS protocol is specified in the endpoint url. Here is the piece of code: 

https://github.com/sksamuel/elastic4s/blob/d43c3144258510302cfbcaef87cfc524479d6dd5/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/ElasticProperties.scala#L22

**Suggestion** : 

If the endpoint specified in the ElasticProperties contains the HTTPS protocol (and the port is not specified), instead of using `:9200` as the default port we could use `:443`. 

Wdyt ?

**Comment by danslapman** [comment]
[Enabling TSL in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html) does not change conenction port by default, so, IMHO, silently changing default port (:9200) is undesired in general
though being pretty counterintuitive

**Comment by ridrum** [comment]
@danslapman thanks for your feedback. That's a good point. I'm not familiar with ES that's why I'm kind of supprised with this default behavior.

**Comment by sksamuel** [comment]
Yeah it's weird but how they've done it. I'll close this as no action.
