### ISSUE TITLE
How to cancel single task in version 7.3.0

### ISSUE THREAD

**Issue by amerpersonal** [sksamuel/elastic4s#2314]
Hi,

I don't see a function for canceling single task in version 7.3.0

```
def cancelTasks(): CancelTasksRequest                             = cancelTasks(Nil)
def cancelTasks(first: String, rest: String*): CancelTasksRequest = cancelTasks(first +: rest)
def cancelTasks(nodeIds: Seq[String]): CancelTasksRequest         = CancelTasksRequest(nodeIds)
```

So any of these passes nodeIds it receives to cancel all tasks on single node. However, is it possible to cancel single task?

Thanks

**Comment by danslapman** [comment]
Hi @amerpersonal, the second one allows You to pass a single string because the second argument (rest) is vararg

**Comment by sksamuel** [comment]
As @danslapman says.
