### ISSUE TITLE
How to specify custom execution context in version 7.3.0

### ISSUE THREAD

**Issue by amerpersonal** [sksamuel/elastic4s#2321]
Hi,

I want to experiment with query performances when I change execution context to custom one, i.e. increase number of threads using.

I saw this thread https://github.com/sksamuel/elastic4s/issues/559 and its possible on newer versions, using httpClient.

I see `execute` method of http client accepts a parameter `executor`, which is created of execution context:

```
 implicit def FutureExecutor(implicit ec: ExecutionContext = ExecutionContext.Implicits.global): Executor[Future] =
    new Executor[Future] {
      override def exec(client: HttpClient, request: ElasticRequest): Future[HttpResponse] = {
        val promise = Promise[HttpResponse]()
        val callback: Either[Throwable, HttpResponse] => Unit = {
          case Left(t)  => promise.tryFailure(t)
          case Right(r) => promise.trySuccess(r)
        }
        client.send(request, callback)
        promise.future
      }
    }
```

So is it enough to specify custom implicit executor before calling execute method, as following

```
implicit val executor = Executor.FutureExecutor(ec)

    val f = httpClient.execute {
      req
    }
```

where ec is  my custom ExecutionContext?

Thanks

**Comment by KadekM** [comment]
@amerpersonal that should be fine. But there is even simpler way, all you need to provide is the custom EC, i.e.:
```scala
implicit val ec: ExecutionContext = scala.concurrent.ExecutionContext
  .fromExecutorService(java.util.concurrent.Executors.newCachedThreadPool()) // or whathever you want
client.execute {
...
```

**Comment by sksamuel** [comment]
Yep either of these works, but like @KadekM says, you can just provide the implicit execution context like you can to any other scala future method.
