### ISSUE TITLE
Using back-pressure with zio

### ISSUE THREAD

**Issue by mbaechler** [sksamuel/elastic4s#2337]
Hi there,

I have a job that insert a lot of entries into ElasticSearch and unless I introduce throttling into my zio ZStream, it overloads my server to the point it is blacklisted by elastic4s.

I can obviously introduce some throttling but I was wondering how I could leverage back-pressure to achieve optimal performance.

Any idea if it's doable with the reactivestream interop or any other solution?

**Comment by sksamuel** [comment]
There is the akka streams impl, but if you're using zio stream seems like they'd be doing the same thing.
