### ISSUE TITLE
updateById with script always upserts

### ISSUE THREAD

**Issue by Tasssadar** [sksamuel/elastic4s#2344]
Hello, due to fix for #2238 ([commit](https://github.com/sksamuel/elastic4s/commit/307777b1b331a9f9f5acd40e051456f626fe7254#diff-71e19d3f006416bcee1a014e3517de72511bb4fd46177f831c3a3759e9df1f5dR33)), whenever an `updateById` query contains a script, it will always work like an upsert and will create empty document if it is not present.

This may be undesirable, and can't be prevented in any way using the elastic4s API. Perhaps tie the condition to `&& scripted_upsert == true` as well?

**Comment by sksamuel** [comment]
Good idea, would you have time to create a PR ?
