### ISSUE TITLE
URL encoding change

### ISSUE THREAD

**Issue by ievalu** [sksamuel/elastic4s#2352]
Hi,

there was a breaking change introduced in ElasticSearch v7.4. The plus sign encoding in URLs changed. 
It seems like in elastic4s `UrlEncoder` is used which is not universal, i.e. applicable only for a specific content type.
It affects ES `_id`s which have spaces in them because `UrlEncoder` encodes spaces as plus signs while spaces should be encoded as `%20`. 

_Example situation_:
Indexing document with `_id` = `test id`. The actual document's `_id` in ElasticSearch index will be `test+id`. The expected behaviour is for `_id` to be `test id`.

Refs: 
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/breaking-changes-7.4.html#_changes_to_encoding_plus_signs_in_urls
https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html

**Comment by ievalu** [comment]
Could I work on this issue?

**Comment by sksamuel** [comment]
Of course.
