### ISSUE TITLE
Using ES 6.5.3 and elastic4s 6.3.7 -> How do specify basic auth credentials?

### ISSUE THREAD

**Issue by eswenson1** [sksamuel/elastic4s#2381]
I see how, using post elastic4s 7.X releases, to specify basic auth credentials to ES, but I don't see any documentation on how to do this for elastic4s 6.X.  I also don't see any info on the main page as to where to submit questions or get help using elastic4s, so I enter this ticket.

How do you specify basic auth credentials in version 6.X of elastic4s?  Since we're constrained to use ES 6.5.3, I assume we cannot upgrade to elastic4s 7.X?

**Comment by eswenson1** [comment]
Looking at the sources for elastic4s, I see an undocumented approach:

```val callback = new HttpClientConfigCallback {
        override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder): HttpAsyncClientBuilder = {
          val creds = new BasicCredentialsProvider()
          creds.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials("username", "password"))
          httpClientBuilder.setDefaultCredentialsProvider(creds)
        }
      }
      ElasticClient(props, requestConfigCallback = NoOpRequestConfigCallback, httpClientConfigCallback = callback))
      ```
I'm going to try that.

**Comment by sksamuel** [comment]
Yes, that works, you just pass that callback into the apache http builder.

**Comment by eswenson1** [comment]
The example you provide in the doc, says to use ElasticClient(JavaClient, props, ...).  There is no JavaClient class in elastic4s 6.x, which is why I couldn't initially figure it out until I looked at the 6.x sources.

Can I use later releases of elastic4s with earlier releases of ES (if we're stuck with 6.X ES, am I stuck with elastic4s 6.x)?

**Comment by sksamuel** [comment]
You can use 7.x if you want, you just need to not to use any features added in 7.x or it will give you an error.
