### ISSUE TITLE
Issues with v7.4.1

### ISSUE THREAD

**Issue by ievalu** [sksamuel/elastic4s#2386]
I've tried to use v7.4.1 in our project and it seems like it was released incorrectly, maybe you could check it out https://github.com/sksamuel/elastic4s/compare/v7.4.0...v7.4.1

**Comment by sksamuel** [comment]
I can just release 7.4.2 tomorrow.
What is the issue?

**Comment by ievalu** [comment]
It seems like it was released from the wrong branch,  from `master`

**Comment by sksamuel** [comment]
That was a bit silly of me.
