### ISSUE TITLE
IpField MatchError v7.12.0 

### ISSUE THREAD

**Issue by acteek** [sksamuel/elastic4s#2389]
When I gonna use ip field I see the follow match error:

`scala.MatchError: IpField(ip,None,List(),None,None,List(),None) (of class com.sksamuel.elastic4s.fields.IpField)
[info]   at com.sksamuel.elastic4s.fields.builders.ElasticFieldBuilderFn$.apply(ElasticFieldBuilderFn.scala:8)
[info]   at com.sksamuel.elastic4s.fields.builders.ObjectFieldBuilderFn$.$anonfun$build$3(ObjectFieldBuilderFn.scala:18)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at com.sksamuel.elastic4s.fields.builders.ObjectFieldBuilderFn$.build(ObjectFieldBuilderFn.scala:17)
[info]   at com.sksamuel.elastic4s.fields.builders.ElasticFieldBuilderFn$.apply(ElasticFieldBuilderFn.scala:27)
[info]   at com.sksamuel.elastic4s.requests.mappings.MappingBuilderFn$.$anonfun$build$12(MappingBuilderFn.scala:80)
[info]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[info]   at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[info]   at com.sksamuel.elastic4s.requests.mappings.MappingBuilderFn$.build(MappingBuilderFn.scala:79)`

It's happening because file `com.sksamuel.elastic4s.fields.builders.ElasticFieldBuilderFn` doesn't contain the case for IpField.

**Comment by sksamuel** [comment]
Correct, it will be added for next release.
Or please make a PR if you need it sooner.
