### ISSUE TITLE
Is Deletehandler which moved to handlers module available in elastic4s 7.1.0

### ISSUE THREAD

**Issue by tusharInsightful** [sksamuel/elastic4s#2409]
Currently I am using elastic4s 7.1.0 and Scala 2.11. I need deletehandler to perform delete_by_query on elasticsearch. The deletehandler has been moved to handlers module. So this new change will be available in elastic4s 7.1.0 or I need to move to latest version.

**Comment by sksamuel** [comment]
In master, the handlers have just been moved, so it will exist in the core module in 7.1.0

**Comment by tusharInsightful** [comment]
Okay. It seems jar has not been updated in mvn repository.

![image](https://user-images.githubusercontent.com/68445896/116787117-ee64f000-aabf-11eb-9513-7b3d13dde6ff.png)

Where can I find the latest jar of elastic4s core 7.1.0?

**Comment by sksamuel** [comment]
7.1.2 is the latest
https://search.maven.org/artifact/com.sksamuel.elastic4s/elastic4s-core_2.13/7.1.2/jar

**Comment by tusharInsightful** [comment]
But this jar is not compatible with scala 2.11. It means this is blocker for scala 2.11 project and I have to upgrade it to scala 2.12/2.13

**Comment by sksamuel** [comment]
Now I understand. I missed the bit about Scala 2.11
The last release of Scala 2.11 was 4 years ago. I no longer support it in elastic4s.
You're best off forking and releasing internally your own version if you still need it.

**Comment by tusharInsightful** [comment]
Thanks Sam
