### ISSUE TITLE
is version 7.8 backward compatible to elastic version 6?

### ISSUE THREAD

**Issue by idankWix** [sksamuel/elastic4s#2460]

**Comment by sksamuel** [comment]
"Mostly". If you don't use any 7.x features then you will be fine as the JSON is almost exactly the same.

**Comment by idankWix** [comment]
When upgrading client I use core (elastic4s-core_2.12)+ http (elastic4s-http_2.12) 
but I see only core has version 7.12
http max version is 6.7.8
I getting a similar issue like https://github.com/sksamuel/elastic4s/issues/1853
is there anyway around it?

**Comment by idankWix** [comment]
> "Mostly". If you don't use any 7.x features then you will be fine as the JSON is almost exactly the same.

so I made it to upgrading to v7.3.1 
however I when calling elastic v6 I get:
`Cannot construct instance of `com.sksamuel.elastic4s.requests.searches.Total` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (0)`
so is it not backward compatible or am I missing something?

**Comment by sksamuel** [comment]
I guess that response type isn't no. You could add a handler for just that call, and use the default 7.3.1 handlers for the rest.

**Comment by spenes** [comment]
I guess one of the parts it is not backward compatible is mapping types. Mapping types are completely removed in the 7.x version of elastic4s therefore it gives `type is missing` error during document indexing. Potential solution to make it compatible with 6.x is to introduce document type again but making it optional. What do you think @sksamuel ?
