### ISSUE TITLE
Can't index number fields

### ISSUE THREAD

**Issue by mfirry** [sksamuel/elastic4s#247]
Suppose one of my index field is a number, if I do something like this for some reasons I do not find the field indexed.

```index into "family" -> "soprano" fields (
  "boss" -> Map(
    "name" -> "tony",
    "age" -> 56
  )
)```

Am I doing something wrong?

**Comment by sksamuel** [comment]
Are you setting the field to be a nested or object type?

**Comment by sksamuel** [comment]
Added a test to show that numbers can be indexed ok.
