### ISSUE TITLE
AWS Signature mismatch only on ElasticSource + Akka Stream

### ISSUE THREAD

**Issue by DavidPuleri** [sksamuel/elastic4s#2476]
```
val searchQuery = search(indexName)
      .scroll("1m")
      .query(termQuery("history.affiliationSource", name))
    val elasticSource = new ElasticSource(client, SourceSettings(searchQuery, 10, warm = true))
```

    akka.stream.scaladsl.Source.fromGraph(elasticSource).runForeach(println)`
    
I get "{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}"

` client
      .execute(searchQuery)` works fine. It is the same client in both situations. Any idea of where to look? Thank you for your help!

**Comment by sksamuel** [comment]
Sounds like your credentials to connect to AWS are off.
