### ISSUE TITLE
Allow setting a mapping without creating a new index

### ISSUE THREAD

**Issue by le-doude** [sksamuel/elastic4s#251]
I am using ElasticSearch with couchbase and my index had to be already created to set up ES to replicate my DB.
Long story short I cannot recreate the index. So it be better to allow setting a mapping as its own command.
Right now I am stuck creating a json mapping and using the HTTP api (not difficult but I'd like to interact with ES using the same tool across my app)

**Comment by sksamuel** [comment]
I've added some tests to show how it could be done with the Put Mapping API.

https://github.com/sksamuel/elastic4s/blob/a3a8f80c7197b5979e1794e7d6c161820d1398f5/src/test/scala/com/sksamuel/elastic4s/MappingTest.scala#L41

**Comment by le-doude** [comment]
thanks a lot.
