### ISSUE TITLE
How to sign requests for AWS ES

### ISSUE THREAD

**Issue by onsah** [sksamuel/elastic4s#2543]
Not sure if this is the correct place to ask, but how can we sign the requests for AWS ES instance using this library? In the [AWS docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html) they point to https://github.com/amazon-archives/aws-request-signing-apache-interceptor but it is an archived repository so I am hesitant to depend on it. I found that there was [support in the past](https://github.com/sksamuel/elastic4s/issues/1883) but now there isn't since we can just add the http headers.

So I am wondering which library can be used (except the archived one I mentioned above) to generate those headers and how it can be wired?

**Comment by sapka12** [comment]
I have a similar problem like @onsah, I'd like to connect from local or from an ec2 with AWS accesskey/secretkey to an ES cluster on AWS. can you show me an example of how to connect with elastic4s?

**Comment by onsah** [comment]
@sapka12 Probably it's too late for you but you need to use https://github.com/inreachventures/aws-signing-request-interceptor and add it to your `ElasticSearchClient` as interceptor. It will automatically sign your requests provided that you gave correct credentials. Also be aware of https://github.com/sksamuel/elastic4s/issues/2721.
