### ISSUE TITLE
Icu Collation Keyword

### ISSUE THREAD

**Issue by HilariGomezAgilogy** [sksamuel/elastic4s#2550]
Newer elastic versions no longer support the  icu_collation token filter and now make use of icu_collation_keyword, wich is a type of elastic field. Could this ElasticField be added in future versions or is there any possibility to build a custom ElasticField? Thanks in advance for your attention.

**Comment by sksamuel** [comment]
Yep, can add that. Do you want to make a PR ?

**Comment by HilariGomezAgilogy** [comment]
Sure, will do!

**Comment by HilariGomezAgilogy** [comment]
I have the changes in a local branch, can you grant me access to push in order to create a new pull request please?

**Comment by sksamuel** [comment]
The usual way for open source is you fork the repo, and push to your fork,
then github makes it easy to create a PR from your fork to the original.
