### ISSUE TITLE
Help using elastic4s with bonsai.io

### ISSUE THREAD

**Issue by mfirry** [sksamuel/elastic4s#256]
I'm trying to use my elastic4s (with play on heroku) using one of their Elasticsearch addons provided by bonsai.io.

When you add the addon they give you a single url that looks like this:
https://USER:PASSOWRD@YOURAPP.bonsai.io:443/

I was wondering how I can use such a url with elastic4s

**Comment by sksamuel** [comment]
That's HTTP. Elastic4s is a wrapper around the TCP client. You need to use
a REST interface client (wasabi?)

**Comment by mfirry** [comment]
Thanks a lot

**Comment by mfirry** [comment]
I guess you meant http://gphat.github.io/wabisabi/

**Comment by sksamuel** [comment]
I did yes. The http clients I am not familar with as most people use tcp,
but things like herkou don't allow it

**Comment by mfirry** [comment]
Awesome. Thanks again.
