### ISSUE TITLE
Why is the source field not supported in the implementation of MultiSearchBuilderFn？

### ISSUE THREAD

**Issue by lxycomeon** [sksamuel/elastic4s#2563]
When I use the multi search API and define query json in each search request, I find that it does not work.  the request body discarded 
every query json statement。
Why not support query json in MultiSearchBuilderFn ？

**Comment by sksamuel** [comment]
Can be yes. If you open a PR I will do a release.

**Comment by sksamuel** [comment]
Once this is green I will release: https://github.com/sksamuel/elastic4s/pull/2564

**Comment by sksamuel** [comment]
7.15.4 released with your fix.
