### ISSUE TITLE
Span Field Masking Query Support

### ISSUE THREAD

**Issue by hellhoundmipt** [sksamuel/elastic4s#2567]
Almost all span queries are implemented aside from [span field masking query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-field-masking-query.html#query-dsl-span-field-masking-query). As far as I understand, you cannot construct custom span queries either.

**Comment by sksamuel** [comment]
Good spot. If you can open a PR I can do a release.

**Comment by sksamuel** [comment]
7.15.5 is out
