### ISSUE TITLE
Delete doc by nested fields.

### ISSUE THREAD

**Issue by dhangad** [sksamuel/elastic4s#257]
I want to delete a doc by field value, so for no luck. Any help appreciated. 

The below syntax doesn't work.
client.execute { delete id autoCompleteSP.spId from "autocomplete/suggestion" } 

I use 0.90.5.0 elastic4s and 0.90.X elasticsearch.

{
  "_shard": 1,
  "_node": "zcd2y1fWRkuJa0x3BoBn6Q",
  "_index": "autocomplete",
  "_type": "suggestion",
  "_id": "ddzcd2y1fWRsdJa0x3BoBn6Q",
  "_score": 0.076713204,
  "fields": {
    "id": 1041973,
    "text": "Mike, Dr. Mark F",
    "weight": 1,
    "displayText": "Mike, Dr. Mark F",
    "type": "service_provider",
    "status": "ACTIVE"
  },

**Comment by sksamuel** [comment]
Delete an index by query? Or do you mean delete doc by query.

**Comment by dhangad** [comment]
delete the doc.

**Comment by dhangad** [comment]
also please share the link for 0.90.5.0 documents. Thank You.

**Comment by dhangad** [comment]
client.execute { delete id "1041973" from "autocomplete/suggestion" } - for clarity hardcoded the id.

**Comment by sksamuel** [comment]
I can't find a 0.90.5 version on maven, the 0.90.2.x versions are 18 months old. Are you able to upgrade to a non beta version of Elasticsearch?
