### ISSUE TITLE
Implementation of weightFactorFunction

### ISSUE THREAD

**Issue by adalovelace** [sksamuel/elastic4s#261]
Hi, 

I have seen that the method factorFunction used for function score queries is deprecated in Java[http://javadoc.kyubu.de/elasticsearch/v1.4.2/org/elasticsearch/index/query/functionscore/ScoreFunctionBuilders.html] and in turn in elastic4s. However, the method weightFactorFunction which seems to be the alternative to factorFunction is not implemented in elastic4s. Is there a reason why? Is there a better alternative to do it in elastic4s?

Thanks!

**Comment by sksamuel** [comment]
We just need to add it, I guess it was missed. If you want to do it and raise a PR feel free, otherwise I can pick it up later this week.
