### ISSUE TITLE
Add missing parameters in word_delimiter_graph in TokenFilter

### ISSUE THREAD

**Issue by rtancman** [sksamuel/elastic4s#2613]
In `com.sksamuel.elastic4s.analyzers.TokenFilter` miss some parameters for `word_delimiter_graph`. See bellow the undefined list:

- `protected_words`
- `protected_words_path`
- `type_table`
- `type_table_path`

Can be useful?

ref:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-graph-tokenfilter.html

**Comment by sksamuel** [comment]
Definitely, we should add that. Would you like to raise a PR ?
