### ISSUE TITLE
Support for composable templates

### ISSUE THREAD

**Issue by sdudzin** [sksamuel/elastic4s#2617]
It would be great to have support for composable templates, namely:

* support for `composed_of` keyword to be able to refer to template components
* support for component templates, located at: `/_component_template/`

(as per https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html)

This will allow to have reusable components when some template parts need to be managed outside elastic4s.

**Comment by sksamuel** [comment]
If you'd like to raise a PR I will perform the release.
