### ISSUE TITLE
Add missing parameters in AnnotatedTextField

### ISSUE THREAD

**Issue by rtancman** [sksamuel/elastic4s#2625]
In `com.sksamuel.elastic4s.fields` miss some parameters for `AnnotatedTextField `. See bellow the undefined list:

- `copy_to`

Can be useful?

Refer:
- https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-annotated-text-usage.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/copy-to.html#copy-to

**Comment by sksamuel** [comment]
Definitely worth adding
