### ISSUE TITLE
Cross-version support for ES 6.8 to ES 7.1

### ISSUE THREAD

**Issue by tlandelin** [sksamuel/elastic4s#2626]
We are upgrading Elasticsearch from 6 to 7, and want to know which version of elastic4s we should upgrade to before upgrading ES. We see elastic4s has v6.7.8 and v7 builds. It also looks like ES7 has breaking changes, such as parsing hits:

```  
    "hits": {
    "total": {. // ES 7 returns this as an object, but ES6 returns a Long value
      "value": 10,
      "relation": "eq"
    },
```
Is elastic4s 7.x going to be backwards compatible? How do you recommend we proceed with an ES upgrade?

We are currently using elastic4s 6.2.12 and running ES 6.8.6.

**Comment by kaushalshah45** [comment]
we have the same issue too, @sksamuel do you have any recommendation?

**Comment by q-willboulter** [comment]
If you have a layer between elastic4s and your library you can solve the specific problem above by defaulting all searches to use the `track_total_hits=true` URL parameter. I think you can also set it via the search payload, see https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-request-track-total-hits.html
