### ISSUE TITLE
Default Jackson serialization prevents other serialization patterns

### ISSUE THREAD

**Issue by jtanner** [sksamuel/elastic4s#263]
Recently we upgraded elastic4s from version 1.2.1.3 to 1.4.11. This upgrade broke our json serialization.

We were using the following implicit pattern to serialize using Play Json. The doc method takes a DocumentSource. Any data of type T which has an implicit serializer Writes[T] in scope can be serialized at index.

```
implicit class JsonElasticSearchSerialization[T](data: T)(implicit writes: Writes[T]) extends DocumentSource {
  def json = Json.prettyPrint(Json.toJson(data))
}
val snapshot: Foo = ...
implicit val serializer: Writes[Foo] = ...
index into ENTITY_INDEX -> TYPE doc snapshot id ID
```

In ElasticDsl the following was added which causes the implicit pattern above to silently fail. All of our code immediately started serializing incorrectly. This implicit is broad in scope and supersedes any other implicit we have tried putting in scope.
```
implicit def product2source(obj: Product): ObjectSource = ObjectSource(obj)
```

This should be considered bad behavior, as anyone importing the ElasticDsl en mass with an underscore will also bring in this broad scope serializer. Pulling in everything but this implicit is verbose in the extreme. Worst case, this should be a separate import in another object that can optionally be imported as necessary. While trying to support a good default case is admirable, this removes the ability of anyone to specify their own serialization, especially using implicits. Even worse, aggressive implicits like this silently fail with the wrong behavior if no serialization was intended. Even if we were to manually apply our json serialization, there is no immediate failure if the serializer is not in scope, rather it silently falls back to this serializer. Our experience has been that allowing the compiler to fail if no serializer is available allows users to better reason about their serialization.

**Comment by sksamuel** [comment]
Fair point, the import shouldn't be pulled in by default. I'll change it.

**Comment by jtanner** [comment]
Thank you :D

**Comment by sksamuel** [comment]
I've replaced the implicit for version 1.5-snapshot. I've also added in a typeclass based alternative. See https://github.com/sksamuel/elastic4s/blob/2672b5daaa086889b952a0f67172d45e244f3395/src/test/scala/com/sksamuel/elastic4s/IndexTest.scala#L52-L68
