### ISSUE TITLE
SearchDefinition is not a member of object com.sksamuel.elastic4s.ElasticDsl

### ISSUE THREAD

**Issue by kuhnen** [sksamuel/elastic4s#264]
If I try to update from 1.4.1  to 1.4.11  or 1.4.10  I get this error, and the compiler can not find any of the packages com.sksamuel.
Any idea?

Thanks a lot for this nice DSL

**Comment by kuhnen** [comment]
Sorry,  just fixed it

**Comment by SourceSink** [comment]
I have the same problem. Can you tell me how you fixed it? Thanks

**Comment by kuhnen** [comment]
If I remember well  it was a library problem,  if you updated your version  it should be in some other package,  but it was long time ago so I am not sure/

**Comment by SourceSink** [comment]
Thanks a lot for the tip!!
The Problem actual was, that the old version could be imported with:
"com.sksamuel.elastic4s" %% "elastic4s"  % "1.5.10"
While the new version requires the core package:
"com.sksamuel.elastic4s" %% "elastic4s-core"  % "1.5.17"

**Comment by sksamuel** [comment]
Yes, that's mentioned on the readme, but thanks for letting us know as now
I know what to suggest if someone asks in the future!
