### ISSUE TITLE
Update Elastic to 8.1.0

### ISSUE THREAD

**Issue by rtancman** [sksamuel/elastic4s#2650]
Add support for elastic 8.1.0

**Refer:**
- https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.1.html#breaking-changes-8.1

**Comment by hagay3** [comment]
+1 
Search API is broken in elastic 8.1.0
@sksamuel can you assist?

**Comment by sksamuel** [comment]
8.0 is released.

8.1.0 to follow.

**Comment by hagaiovadia** [comment]
@sksamuel 
Thanks for the quick help!
