### ISSUE TITLE
Update `doc` with `NestedFieldValue`

### ISSUE THREAD

**Issue by euronymous** [sksamuel/elastic4s#2656]
Hi,

Long story short:

Documentation: https://github.com/sksamuel/elastic4s/blob/master/docs/update.md#updates
```scala
client.execute {
  updateById("scifi", "14").docAsUpsert(
    NestedFieldValue("captain", Seq(SimpleFieldValue("james", "kirk")))
  )
}
```

Code:
https://github.com/sksamuel/elastic4s/blob/a7f80c710a911b763c0fdc408f1c8cd23780976a/elastic4s-domain/src/main/scala/com/sksamuel/elastic4s/requests/update/UpdateRequest.scala#L54
```scala
  // Sets the field to use for updates when a script is not specified.
  //def doc(value: FieldValue): UpdateDefinition = copy(documentSource = Seq(value))
```

There is only one function that I could apply `FieldValue` and it is commented out.
But maybe I'm just blind.
Am I missing sth?

Cheers

**Comment by sksamuel** [comment]
Was removed in later version and docs out of date I guess.
