### ISSUE TITLE
Add support for nested JSON in `_meta`

### ISSUE THREAD

**Issue by rney-lookout** [sksamuel/elastic4s#2678]
The current implementation of 'Mapping' in IndexHandlers.scala only support single level JSON. Have meta setup such as
```
      "_meta": {
        "presto": {
          "testDoc": { 
            "isArray": true
          }
        }
      }
```
will not parse and the `getIndex` request will return an error

**Comment by sksamuel** [comment]
Yep, bug. Can you open a PR and I'll release.
