### ISSUE TITLE
It's not possible to set reindex batch size parameter

### ISSUE THREAD

**Issue by via119** [sksamuel/elastic4s#2681]
I would like to change the default batch size of reindex (1000) but it seems that it's not possible to do it with elastic4s. 

The current version puts the `size` parameter outside of the `source` object which limits the number of processed documents. Putting it inside the `source` object would result limiting the number of documents to index per batch.

Current behavior: `'{"size":2,"source":{"index":["old"],"query":{...}},"dest":{"index":"new"}}'`
Expected behavior: `'{"source":{"size":2,"index":["old"],"query":{...}},"dest":{"index":"new"}}'`

I've found a [commit](https://github.com/sksamuel/elastic4s/pull/1127/commits/113e915d41c324c6cd28cc603bf2c68779f27ff7) changing this behavior, but it seems that it was never merged.

This parameter was recently renamed to "max_docs" for the 8.x version which I think is the correct name for this functionality.
I'm using Elasticsearch 7.17.1.
I can try adding this parameter to ReindexRequest, but I'm not sure what's the best way to handle the different versions.

**Comment by sksamuel** [comment]
Hi,

If you need this in a specific 7.x version, then you can PR to that release branch and I'll release a new version.

**Comment by via119** [comment]
Hi,

Yes, I can make a PR to 7.17.x, my concern is naming and not making any braking change.
In the elasicsearch reindex [api](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-api-request-body), `max_docs` (or `size`) parameter (outside the source object) limits the number of processed documents and the `size` parameter (inside the source object) limits the number of documents to reindex per batch. 
In elasic4s, the parameter which limits the number of documents being processed is called `size` (in 7.17.x) and it is outside of the `source` object. The other limitation is not implemented.
My suggestion would be to rename the `size` parameter to `max_docs` as it was done in elastic4s 8.x and add the `size` parameter as the new functionality. It would mean that if somebody used `size` to limit the number of processed documents, when upgrading to the new version, it would create a different reindex request. Is that OK?

**Comment by via119** [comment]
I added the [PR](https://github.com/sksamuel/elastic4s/pull/2696)

**Comment by sksamuel** [comment]
I released 8.2.2

**Comment by via119** [comment]
I need this in a specific 7.17.x version, the commit was merged to release/7.12.x branch, not master. I believe a new 7.17.3 version is needed for this change.

**Comment by sksamuel** [comment]
I'll release 7.17.x

**Comment by sksamuel** [comment]
7.17.3 is out.

**Comment by via119** [comment]
Hi,

Thank you for the release, but it seems that some commits for the different elastic4s versions got mixed up. 
7.17.3 was released from the master branch and it contains 8.3.2 elasticsearch and client for testing instead of 7.17.3.

The [PR](https://github.com/sksamuel/elastic4s/commit/f35797248b7bd8e011e6052173a10b6d92278791) that I made for this issue is not available in 7.17.3.

If it helps, I can open a new PR rebased to v7.17.2 tag so you can release a new 7.17.x version from that.

**Comment by sksamuel** [comment]
Ugh what a mess I've made of this.

So your original PR went into release/7.12.x. If you want to remake it for
7.17.x like you say, then I will release that. No need to rebase anything,
I can just delete that tag.

**Comment by via119** [comment]
Hi,

Thanks for taking a look at this again.
No need to remake anything, just release from release/7.12.x branch.
