### ISSUE TITLE
Simple elastic4s example does not shut down !

### ISSUE THREAD

**Issue by sebastianharko** [sksamuel/elastic4s#269]
This program works but simply does not shut down, simply does not exit. I'm using elastic4s version 1.3.3 and Scala version 2.11.1 ; java version 1.7.0_71. 

        import com.sksamuel.elastic4s._
        import com.sksamuel.elastic4s.ElasticDsl._
        import org.elasticsearch.action.index.IndexResponse
        import scala.concurrent.{Await}
        import scala.concurrent.duration._
        import org.elasticsearch.common.settings.{ImmutableSettings}

        object Hello {
            def main(args:Array[String]):Unit = {
                val client: ElasticClient = ElasticClient.local
                val resp = client.execute { index into "bands/rock" fields ("name"->"coldplay", "debut"->"parachutes") }
                val await: IndexResponse = Await.result(resp, 10.seconds)
                client.close()
            }
        }

**Comment by sksamuel** [comment]
There was a bug that was fixed in 1,4.2
http://stackoverflow.com/questions/27603676/elastic4s-does-not-exit
