### ISSUE TITLE
Range aggregation DSL doesn't allow unbounded ranges

### ISSUE THREAD

**Issue by mai00cmi** [sksamuel/elastic4s#270]
It would be cool if `RangeAggregationDefinition` would allow unbounded ranges (see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html). Something like `def range(from: Option[Double], to: Option[Double])`.

**Comment by sksamuel** [comment]
I've followed the java api rather than use options, as you could pass in None, None, which seems a bit odd.
