### ISSUE TITLE
Bug: PutPipelineRequestHandler missing a leading slash in the URI

### ISSUE THREAD

**Issue by grcanosa** [sksamuel/elastic4s#2701]
I believe this line is missing a leading slash in the URI making the request fail. 

https://github.com/sksamuel/elastic4s/blob/72aaa55a4a5b0fde70ad711b880cf3da31d03d09/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/ingest/IngestHandlers.scala#L68

Do you want me to create a PR?

**Comment by sksamuel** [comment]
Yes PR would be awesome.
