### ISSUE TITLE
How to disable date detection in mapping ?

### ISSUE THREAD

**Issue by qpiny** [sksamuel/elastic4s#272]
Hi,

I'm trying to disable date detection using dateDetection method. If I set it to false, the field is not inserted in mapping. It is inserted only if the value is true (but not with the value I expect).
Date detection is enable by default in ElasticSearch (AFAIK), so how can I disable it ?

Numeric detection probably has the same issue.

Regards.

**Comment by qpiny** [comment]
Hi,

As date detection is enabled by default in Elasticsearch and numeric detection is disabled, I propose the following patch.
```date_detection``` and ```numeric_detection``` is initialized by default value in Elasticsearch and if their value changes, related fields in mapping is added.

```Diff
--- a/src/main/scala/com/sksamuel/elastic4s/mappings/mappings.scala
+++ b/src/main/scala/com/sksamuel/elastic4s/mappings/mappings.scala
@@ -61,8 +61,8 @@ class MappingDefinition(val `type`: String) {
 
   var _all = true
   var _source = true
-  var date_detection = false
-  var numeric_detection = true
+  var date_detection = true
+  var numeric_detection = false
   var _size = false
   var dynamic_date_formats: Iterable[String] = Nil
   val _fields = new ListBuffer[TypedFieldDefinition]
@@ -179,7 +179,7 @@ class MappingDefinition(val `type`: String) {
     if (dynamic_date_formats.size > 0)
       source.field("dynamic_date_formats", dynamic_date_formats.toArray: _*)
 
-    if (date_detection) source.field("date_detection", date_detection)
+    if (!date_detection) source.field("date_detection", date_detection)
     if (numeric_detection) source.field("numeric_detection", numeric_detection)
 
     source.field("dynamic", _dynamic match {
```

Regards.

**Comment by sksamuel** [comment]
We prob want elastic4s to default to whatever the java client is doing, so allow for a 3 way state - not set (es default), or true / false. I'll try and add this this weekend.
