### ISSUE TITLE
elastic4s release for 7.12.x branch

### ISSUE THREAD

**Issue by PeterHajdu** [sksamuel/elastic4s#2720]
Hi Sam!

Just noticed that v7.17.4 tag was added again to the top of the master branch. (commit: 4211ff45b)
Unfortunately we need a release from an older branch so that we can use it with elasticsearch 7.17.1.
Can you please make a release from the branch "release/7.12.x" (commit: f35797248)?

Thanks in advance.

_Originally posted by @PeterHajdu in https://github.com/sksamuel/elastic4s/issues/2710#issuecomment-1234173420_

**Comment by sksamuel** [comment]
I released again, with 7.17.4
I checked 20 times I released from the right branch :)
If it fails again then something is wrong with the script - can you confirm @PeterHajdu ?

**Comment by PeterHajdu** [comment]
Hi Sam.
The tag seems to point to the same commit: 4211ff4
Maybe updating an existing tag is the issue?  Would you consider releasing 7.17.5 on the correct commit: f357972

**Comment by sksamuel** [comment]
The script must be wrong then because I'm releasing the head of the release/7.17.x branch
So let me look into that.

**Comment by PeterHajdu** [comment]
Thank you for your extra efforts.

**Comment by L3v** [comment]
> The script must be wrong then because I'm releasing the head of the release/7.17.x branch So let me look into that.

Hi @sksamuel, could you please give this a second look? :) 
I truly appreciate your time.
