### ISSUE TITLE
CatHealth goes limbo when calling AWS OpenSearch with stale credentials

### ISSUE THREAD

**Issue by sikinmettugi** [sksamuel/elastic4s#2721]
The correct way to fix this is to refresh the credentials but I want to check if this behavior is intended.

elastic4s version: `7.10.9`
Amazon OpenSearch version: `1.2.0` (compatible with ElasticSearch `7.10` IIRC)

We're calling `client.execute { catHeahth() }` to Amazon OpenSearch, and when the credential expires the future causes timeout, from failing JSON marshaling to `CatHealthResponse`. I'd like to check 1) how I can make the future not recovered in this case and 2) if the `client.execute` result not producing `RequestFailure` is intentional design. 

The health check definition is like below:
```
  def doHealthCheck(): Future[Either[Throwable, String]] = {
    client.execute {
      catHealth()
    } map {
      case response: RequestSuccess[CatHealthResponse] => Right(response.result.status)
      case failure: RequestFailure => Left(failure.error.asException)
    } recover {
      // in the credential expired cases, this recover is not invoked
      case e: Throwable => Left(e)
    }
  }
```

and we're calling this function within akka-http route as below:
```
        val healthCheckFuture = esService.doHealthCheck().map {
          case Right(r) => Right(HealthResponse(r))
          case Left(e) => Left(HealthResponse(e.getMessage))
        }

          onComplete(healthCheckFuture) {
            // NOTE: in the credential expired case, the code never reaches here within configured timeout of 10s and akka-http shows "Request timeout encountered for request [GET /path EMPTY]"
            case Success(Right(r)) => complete(StatusCodes.OK, r)
            case Failure(ex) =>
              ctx.log.error(ex,"health check failed: {}", ex.getMessage)
              complete(StatusCodes.ServiceUnavailable, ex)
            case Success(Left(r))  =>
              ctx.log.error("health check failed: {}", r.openSearch)
              complete(StatusCodes.ServiceUnavailable, r)
          }
```

we use an apache client with an interceptor, required to call AWS hosted ElasticSearch/OpenSearch:
```
    val interceptor = new AwsRequestSigningApacheInterceptor(signer, params)
    val callback = new HttpClientConfigCallback {
      override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder): HttpAsyncClientBuilder = {
        httpClientBuilder
      }.addInterceptorLast(interceptor)
    }
    val props = ElasticProperties(esHost)
    val client = ElasticClient(JavaClient(props, requestConfigCallback = NoOpRequestConfigCallback,
      httpClientConfigCallback = callback))
```

when a given credential gets stale e.g. session token being expired, calling `GET /_cat/health?format=json&v= ` returns `401` with string `Unauthorized` which is not a `Seq[CatHealthResponse]`, and looks like this gets `ResponseHandler.fromResponse[Seq[CatHealthResponse]]` in `com.sksamuel.elastic4s.requests.cat.CatHealthHandler` to fail - https://github.com/sksamuel/elastic4s/blob/aa1bd6c0c0b71bcfd9763e2fcb1cd72ab698a484/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/cat/CatHandlers.scala#L79

The application does not show any exception messages from elastic4s unfortunately.

I wonder how we can catch the exception and return the correct failure response in this case?

**Comment by onsah** [comment]
I am working around this issue by setting a timeout limit to the request on the client side. But it definitely makes things harder. Would appreciate if we get error instead.

**Comment by sksamuel** [comment]
Seems like you would have this error with any http client that uses credentials ? Like, is it just a "how do I refresh creds in my http client" question ?
