### ISSUE TITLE
Question: Long-term plans for OpenSearch support

### ISSUE THREAD

**Issue by dorranh** [sksamuel/elastic4s#2735]
Hi @sksamuel, we are currently using this library at Tweag for some of our projects and the question recently came up regarding whether there were any plans for `elastic4s` to maintain compatibility with OpenSearch given that long-term its API may start to diverge from that of Elasticsearch. I was wondering whether this was something you had already considered?

**Comment by sksamuel** [comment]
I had thought about it, but last time I checked there wasn't a lot of activity on open search. https://github.com/opensearch-project/OpenSearch/commits/main

**Comment by dorranh** [comment]
Sorry for the delayed response. That is a good point, and I'm not sure what the long-term roadmap for OpenSearch is. One other concern would be that given the continued development of ElasticSearch, we could reach a point where backwards-compatibility with older API versions such as the one that OpenSearch was forked from is no longer guaranteed.

**Comment by hughsimpson** [comment]
I'm also interested in this.. I wonder if it's worth adding opensearch to the ci matrix for the time being? At least that way we'd have a demarcation point for when support diverged

**Comment by sksamuel** [comment]
That's a good idea @hughsimpson

**Comment by maxcom** [comment]
What version of Elastic4s is best/recommended for latest OpenSearch, 2.4.1? I use Elastic4s 7.13.0 and it works. But it would be nice to see new features like Scala 3 support.

**Comment by jcostian-canter** [comment]
Open search seems to be quite active and pushing out new versions. Any new thoughts on elastic4s compatibility with open search?

**Comment by renghen** [comment]
hi @maxcom,
may I get an example of how you made it work with opensearch, locally the code works brilliantly, but on the cloud another ball game, we have  our container on aws aznd the opensearch is https://xxxxxx-west-2.es.amazonaws.com/
are there some particulars to do in the code?
The opensearch version is 2.3.0
 Elastic4s 7.10.3

**Comment by renghen** [comment]
I got it to work

**Comment by remo87** [comment]
Hi @renghen, What steps did you had to follow to have the client work with OpenSearch?

**Comment by renghen** [comment]
I used the version 7.* of elastic4s and it worked.

**Comment by sean-eero** [comment]
@renghen do you have more information perhaps? I have been struggling to get this to work, just getting 403's right now, though it works with my ES 6.5 cluster (using elastic4s 7.10.11) - did you use an interceptor to pass the authentication to the client, or another way?
