### ISSUE TITLE
Streaming From ElasticSearch

### ISSUE THREAD

**Issue by igalbenardete** [sksamuel/elastic4s#275]
I was wondering if its possible to stream data from elastic search. I am going to directly use this with to stream data form Play.

**Comment by sksamuel** [comment]
Can you link me to the api you need to use to stream? Is it Iterees or something?

**Comment by igalbenardete** [comment]
This is not a public api. I am using Spark to generate data and then I store these results in elasticsearch. So at this point I want to stream these results from the elastic search to the client using Play

**Comment by sksamuel** [comment]
Api wise i meant what does play offer you. I think it has iterees ? I've
never used play.

You could look at the scroll api that elastic offers

**Comment by sksamuel** [comment]
I'm happy to help but you need to let me know how you want to stream the data out. Eg are you using  https://www.playframework.com/documentation/2.0/Iteratees

**Comment by igalbenardete** [comment]
This part is not exactly set yet, it can be changed depending on what is required from the elastic end.

**Comment by sksamuel** [comment]
You need to take your streaming api (iterators, or whatever) and take them in batches, and every batch use the bulk api.

https://github.com/sksamuel/elastic4s/blob/master/guide/bulk.md
