### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by vooolll** [sksamuel/elastic4s#276]
I just started using this lib 2 weeks ago, I want to give you feedback about the documentation. It is cool and descriptive in terms of api. I have some php background, and we used http to communicate with elasticsearch.
I installed elasticsearch and did `val client = ElasticClient.local` then I did as usual `curl -XGET 'http://127.0.0.1:9200/catalogs/_search?pretty=1'`. There was no index created, when I test this code with specs2 the data returned. I was a bit confused. Then I notice the data directory in my project, it was strange. Finally I figure out that I should use remote. Then I did val client = ElasticClient.remote("127.0.0.1", 9200) , but actually I should use 9300 - transport tcp port instead of http port. I think it would be better to match it somehow in documentation, for developers with different background.

**Comment by sksamuel** [comment]
Thanks, updated.
