### ISSUE TITLE
Release 8.4.4 depends on RC version of play-json

### ISSUE THREAD

**Issue by brunoballekens** [sksamuel/elastic4s#2760]
PR https://github.com/sksamuel/elastic4s/pull/2736 (scala3 support) introduced a dependency to an RC version of play-json.
That's probably not what you want for production ready code (or at least not for code compiled vs scala 2.x) ?

Workaround is to exclude the transitive dependency to by changing the dependency to :
```
"com.sksamuel.elastic4s" %% "elastic4s-json-play" % elastic4sVersion exclude ("com.typesafe.play", "play-json_2.13")
```

**Comment by hughsimpson** [comment]
My bad, sorry. Should have excluded it from the scala 3 build but got carried away
