### ISSUE TITLE
Inference, knn and hybrid search

### ISSUE THREAD

**Issue by RichardSmithONS** [sksamuel/elastic4s#2762]
Having not done much with Elastic4s for a while I have just upgraded to 8.4 and am looking at ML and NLP functions such as vector search. What support, if any, is there for this in Elastic4s? It may be too new, or I might be looking in the wrong place!

This is an example of what I'm playing with.
A model imported via Eland is used to reindex an existing index, adding a dense vector field
To perform a similarity match, use the _infer function on the input string as follows:
```
POST _ml/trained_models/poetry_model_v1/deployment/_infer

{
  "docs": {
    "text_field": "I wandered lonely as a cloud"
  }
}
```

Then use the returned vector in a knn search, either on its own or combined with a BM25 query using the new hybrid search functionality, e.g. 
```
GET poetry_reindexed_index/_search
{
  "knn": {
    "field": "poem_text_embedding.predicted_value",
    "query_vector": [
      -0.11911506950855255,
      -0.26070910692214966,
...
      -0.06270520389080048,
      -0.0440506674349308
    ],
    "k": 10,
    "num_candidates": 100,
    "boost": 1,
    "filter": [
      {
        "terms": {
          "country": [
            "UK"
          ]
        }
      }
    ]
  },
  "query": {
...
```

**Comment by RichardSmithONS** [comment]
The infer step can be run using the low-level RestClient (synchronous example below)

```
  def infer(sentence: String, modelName: String) : Response = {
    val bodyJson: String = "{  \"docs\": { \"text_field\": \"" + sentence + "\"  }}"
    val rBody: NStringEntity = new NStringEntity(bodyJson,ContentType.APPLICATION_JSON)
    val request: Request = new Request("POST","_ml/trained_models/" + modelName + "/_infer")
    request.setEntity(rBody)
    myRestClient.performRequest(request)
  }

  val iResponse: Response = infer(mySentence, myModelName)
  val myVector: String = EntityUtils.toString(iResponse.getEntity)
```

I tried to run the kNN hybrid search with a RawQuery but it doesn't like the knn block being inside a query block. Error:
    "type": "illegal_argument_exception",
    "reason": "[knn] queries cannot be provided directly, use the [knn] body parameter instead"

**Comment by paul-butcher** [comment]
You can use `source` rather than `rawQuery` to make the KNN search.

**Comment by RichardSmithONS** [comment]
Thanks Paul, that helps a lot.
Getting the kNN search to run quickly does require some tweaking (see https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-knn-search.html) in addition to things you can do in the query such as reduce k and num_candidates and include a filter to limit the number of documents tested.
See also https://www.elastic.co/guide/en/elasticsearch/reference/current/start-trained-model-deployment.html for running inference jobs.
