### ISSUE TITLE
Question: Could you apply an update to the 7.X versions?

### ISSUE THREAD

**Issue by Kdenboon** [sksamuel/elastic4s#2780]
As asked in https://github.com/sksamuel/elastic4s/pull/2753 we would like to have this in the 7.X versions, specifically 7.10.X.
Would this be possible?

**Comment by abyszkin** [comment]
Hello, as asked earlier - could we have https://github.com/sksamuel/elastic4s/pull/2753 merged to version 7? 
Thank you.

**Comment by IAmMonmoy** [comment]
@abyszkin You should create a PR targetting the 7.10.X branch with this commit.

**Comment by abyszkin** [comment]
Should have thought about it earlier... thanks for the hint!
Created https://github.com/sksamuel/elastic4s/pull/2848

**Comment by sksamuel** [comment]
7.10.11 was released.
