### ISSUE TITLE
Adding elements to an array in a document

### ISSUE THREAD

**Issue by igalbenardete** [sksamuel/elastic4s#279]
{
    "_index": "reports",
    "_type": "report",
    "_id": "4d9e4fd3-7fdf-41c8-8c29-45c5acaf78b1",
    "_score": 1,
    "_source": 
                {
                    "reportStatus": "REPORT_COMPLETED",
                    "reportOutputType": "MissingImageReport",
                    "elasticData": [ ]
                }
            }
        ]
    }
}

I have the following structure in my elasticsearch. My aim is to add multiple items into elasticData part (since it is an array) one by one. How is this done ?

**Comment by sksamuel** [comment]
This isn't an issue with the library but a help question. Can you ask on StackOverflow and more people will see it to help.

**Comment by igalbenardete** [comment]
This is an issue, because the script does not work properly.

**Comment by sksamuel** [comment]
What does not work. You've not posted any code !!!!

**Comment by igalbenardete** [comment]
val resp = client.execute {
        update id reportID in "reports/report" script "ctx._source.elasticData += output" params Map("output" -> Array(iterator.next.toStringifiedJson))
      }

**Comment by sksamuel** [comment]
You have the array. Why not just do a normal update. Why the script?

**Comment by igalbenardete** [comment]
I don't have the array I have the iterator because otherwise the whole data will consume way too much memory

**Comment by igalbenardete** [comment]
And update does not add it just changes the curren value

**Comment by sksamuel** [comment]
Perhaps if your array is too big for memory, then it sounds like you shouldn't be putting it into a single document. I'd rethink the design and have multiple documents. You could look at using the parent fields to link them.

**Comment by igalbenardete** [comment]
It has 200 elements

**Comment by igalbenardete** [comment]
For scalability pruposes it is with an iterator, since new features will require more elements. However even with 200 hundred I could not manage to add them one by one.

**Comment by igalbenardete** [comment]
Is there a way to add elements to an array ? the code above does not work and it does not work with await either. I have tried many combinations

**Comment by igalbenardete** [comment]
The script does not work without 
libraryDependencies += "org.codehaus.groovy" % "groovy-all" % "2.4.1"
adding this to build.sbt
