### ISSUE TITLE
Geo Shape Type - index properties

### ISSUE THREAD

**Issue by muuki88** [sksamuel/elastic4s#280]
I'm trying to create a index with a field typed to `GeoShapeType`. The code (thanks for a really smooth API here) looks like this

```scala
client.execute {
    create index MEDIAQ_INDEX mappings {
        MEDIAQ_TYPE as (
            "videoId" typed StringType,
            "trajectory" typed GeoShapeType
        )
    }
}
```

Now I want to add `precision` and the `tree` field to the properties. How can I achieve this or is this currently not supported? [Elasticsearch documentation](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-shape-type.html#_example_4)

```json
{
    "properties": {
        "location": {
            "type": "geo_shape",
            "tree": "quadtree",
            "precision": "1m"
        }
    }
}
```

**Comment by sksamuel** [comment]
Yep, just do

```
client.execute {
    create index MEDIAQ_INDEX mappings {
        MEDIAQ_TYPE as (
            "videoId" typed StringType,
            "trajectory" typed GeoShapeType tree PrefixTree.Quadtree precision "1m"
        )
    }
}
```
