### ISSUE TITLE
Elastic4s returned incorrect data and only 10 rows

### ISSUE THREAD

**Issue by pep-papig** [sksamuel/elastic4s#2829]
Hello! I have the query  to Elasticsearch
`

    "query": { 
    "bool": {
      "must": [],
      "filter": [
        {
          "range": {
            "timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2023-02-14T16:48:00.684Z",
              "lte": "2023-02-14T20:48:00.000Z"
            }
          }
        },
        {
          "match_phrase": {
            "service": "serviceName"
          }
        },
        {
          "match_phrase": {
            "type": "typeOne"
          }
        }
      ], ...`
 I don't understand what's wrong with the following query with Elastic4s
`
  
    client.execute {
    search("*myIndex*") query {
      matchPhraseQuery("service", "serviceName")
      matchPhraseQuery("type", "typeOne")
      rangeQuery("timestamp") gte "2023-02-14T16:48:00.684Z"  lte "2023-02-14T20:48:00.000Z" format "strict_date_optional_time"
    }}.await 
`
because as a result:
1 - returned to me only 10 records
2 - with other "types" from type fields

Would you help me, please?

**Comment by flavienbert** [comment]
Both matchPhraseQuery are ignored, you return only the rangeQuery. you should wrap your queries in a boolQuery : 
 ` boolQuery().must( )` 

And for the only 10 records maybe you can use the size field?

**Comment by pep-papig** [comment]
> And for the only 10 records maybe you can use the size field?

what size to indicate if I want to return all rows in my query and I don't know how many rows I need?

**Comment by pep-papig** [comment]
> Both matchPhraseQuery are ignored, you return only the rangeQuery. you should wrap your queries in a boolQuery : ` boolQuery().must( )`
like that  =>  boolQuery().must(matchPhraseQuery("service", "serviceName"))
if so, the data is still incorrect =(
> And for the only 10 records maybe you can use the size field?
what size to indicate if I want to return all rows in my query and I don't know how many rows I need?

**Comment by flavienbert** [comment]
The simplest method of pagination uses the from and size parameters available in Elasticsearch's search API. By default, from is 0 and size is 10, meaning if you don't specify otherwise, Elasticsearch will return only the first ten results from your index. 

Check the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html

**Comment by pep-papig** [comment]
> By default, from is 0 and size is 10
understand thank you for your answer!

**Comment by pep-papig** [comment]
but how to scroll when a count of rows > 10000
if I get from the first request scrollId

```
 val response = client.execute {
    search("*myIndex*") query {
      boolQuery().must(rangeQuery("timestamp") gte "2023-02-14T16:48:00.684Z" lte "2023-02-14T20:48:00.000Z" format "strict_date_optional_time",
        termQuery("service", "serviceName"))
    } scroll "1m" size 500
  }.await
```
 next request return null

```
   val resp2 = client.execute {
    searchScroll(response.result.scrollId.get)
  }.await
```
Can you show a code example of how scroll uses, please?
