### ISSUE TITLE
Not possible to add metadata to PutMappingDefinition (e.g. parent)

### ISSUE THREAD

**Issue by Ashalynd** [sksamuel/elastic4s#286]
PutMappingDefinition does not allow to specify a parent (it only accepts a sequence of TypedFieldDefinition objects with predefined types). Also other metadata (which MappingDefinition does support) can't be specified. This makes it cumbersome to add new mappings.

**Comment by sksamuel** [comment]
I'm not familiar with parent on put mapping, can you give me an example of what you mean in terms of either the json api or the java api ?

**Comment by sksamuel** [comment]
I've updated put mapping to support all the same options that mapping supports. This will be in release 1.5.5
