### ISSUE TITLE
Delete request should support ignore_unavailable

### ISSUE THREAD

**Issue by chitran96** [sksamuel/elastic4s#2861]
DeleteByQueryRequest https://github.com/sksamuel/elastic4s/blob/master/elastic4s-domain/src/main/scala/com/sksamuel/elastic4s/requests/delete/DeleteByQueryRequest.scala#L10
ES document for delete by query shows that it does support `ignore_unavailable` https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-api-query-params

**Comment by paggiorowarda** [comment]
+1
