### ISSUE TITLE
Search Default limit

### ISSUE THREAD

**Issue by igalbenardete** [sksamuel/elastic4s#288]
Why Search has a default limit of 10 ? How can I remove it ?

**Comment by sksamuel** [comment]
You can change the limit by using the keyword `limit` on your search. See
https://github.com/sksamuel/elastic4s/blob/master/guide/search.md

**Comment by igalbenardete** [comment]
I already know that but what if I want to have all the SearchHits ?

**Comment by sksamuel** [comment]
0 should disable it.

**Comment by igalbenardete** [comment]
Nope it doesn't work...
