### ISSUE TITLE
DeleteByQueryResponse should have failures field

### ISSUE THREAD

**Issue by azolotko** [sksamuel/elastic4s#2883]
According to [Elasticsearch's documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-delete-by-query.html#docs-delete-by-query-api-response-body), `DeleteByQueryResponse` is supposed to have `failures` field, but it doesn't have one at the moment.

**Comment by azolotko** [comment]
The same applies to [UpdateByQueryResponse](https://artifacts.elastic.co/javadoc/co/elastic/clients/elasticsearch-java/7.17.1/co/elastic/clients/elasticsearch/core/UpdateByQueryResponse.html#failures()).

**Comment by sksamuel** [comment]
If you have the time to make a PR, I can make the release.
