### ISSUE TITLE
Add support for "enabled" field

### ISSUE THREAD

**Issue by richardhundt** [sksamuel/elastic4s#29]
Hi, I can't see support for the `enabled` field in the mappings definition. Have I missed it or is it NYI?

**Comment by yonran** [comment]
I think this is still open. You can disable a particular field `createIndex(indexName).mappings(mapping("_doc").fields(objectField("o").enabled(false))`, but I don’t think you can disable indexing all fields of the document e.g. `createIndex(indexName).mappings(mapping("_doc").enabled(false))`. [Elasticsearch documentation: mapping enabled](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html)
