### ISSUE TITLE
Filtered KNN search not supported

### ISSUE THREAD

**Issue by tlandelin** [sksamuel/elastic4s#2903]
As described in the [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#knn-search-filter-example), when pre-filtering is needed for KNN search, a filter query section is supplied. The filter is not currently supported by [elastic4s](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-domain/src/main/scala/com/sksamuel/elastic4s/requests/searches/knn/Knn.scala)

**Comment by sksamuel** [comment]
Hi,
If you can provide a PR I would be happy to make the release.

**Comment by tlandelin** [comment]
Thanks! I opened the PR [here](https://github.com/sksamuel/elastic4s/pull/2904)
