### ISSUE TITLE
Page Validate was deleted

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [sksamuel/elastic4s#295]
I have opened [main page](https://github.com/sksamuel/elastic4s) and try to open link [Validate](https://github.com/sksamuel/elastic4s/blob/master/guide/validate.md) - get 404.

Link Validate is placed in operation table in head [Syntax](https://github.com/sksamuel/elastic4s#syntax)

Could you please fix it?

**Comment by sksamuel** [comment]
Done cheers.
