### ISSUE TITLE
Support filter-level tokenizer for synonym token filter

### ISSUE THREAD

**Issue by jeantil** [sksamuel/elastic4s#300]
Hi!

It isn't very clear in elastic search's documentation but filters actually support a custom tokenizer attribute which is absolutely necessary when trying to use multiword synonyms ona keyword analyzed field. 

see http://stackoverflow.com/questions/25207158/elasticsearch-multi-word-keyword-tokenized-synonym-analysis

Please add  a tokenizer field on `com.sksamuel.elastic4s.SynonymTokenFilter`

**Comment by sksamuel** [comment]
We also don't support synonyms only synonyms_path

**Comment by jeantil** [comment]
Just tested this too : works like a charm, though using Option[Boolean] feels a bit weird.

Thanks

**Comment by sksamuel** [comment]
We use options all over the dsl becauee there's three states - true false
and whatever es default is. They're just usually hidden. I'll do a `synonym
filter ...` style dsl at some point which will hide that.

**Comment by jeantil** [comment]
True :)

Le mar. 28 avr. 2015 19:47, Stephen Samuel <notifications@github.com> a
écrit :

> We use options all over the dsl becauee there's three states - true false
> and whatever es default is. They're just usually hidden. I'll do a `synonym
> filter ...` style dsl at some point which will hide that.

**Comment by sksamuel** [comment]
I've started a DSL for token filters (and soon char filters). What do you think:
https://github.com/sksamuel/elastic4s/blob/master/src%2Ftest%2Fscala%2Fcom%2Fsksamuel%2Felastic4s%2FAnalyzerDslTest.scala

**Comment by jeantil** [comment]
looks pretty good to me I'll ask my coworker to pitch in tomorrow
