### ISSUE TITLE
Elasticsearch server version for tests is not up-to-date and tests are failing when updating

### ISSUE THREAD

**Issue by joelvim** [sksamuel/elastic4s#3000]
Currently, the lib is built on elasticsearch client version [`8.11.4`](https://github.com/sksamuel/elastic4s/blob/9127dc4199ed22d16cddef3b13326cbe3527def3/project/Dependencies.scala#L12) but the docker-compose file allowing to launch an elasticsearch server to run tests in local launches the [`8.8.0`](https://github.com/sksamuel/elastic4s/blob/9127dc4199ed22d16cddef3b13326cbe3527def3/docker-compose.yml#L5) and the github actions are launching a server in version [`8.5.3`](https://github.com/sksamuel/elastic4s/blob/9127dc4199ed22d16cddef3b13326cbe3527def3/.github/workflows/master.yml#L29).

When I upgrade the docker-compose to 8.11.4, some tests are failing:
```sh
[info] *** 6 TESTS FAILED ***
[error] Failed tests:
[error] 	com.sksamuel.elastic4s.requests.snapshots.SnapshotTest
[error] 	com.sksamuel.elastic4s.search.SearchTest
[error] 	com.sksamuel.elastic4s.requests.searches.aggs.PercentilesAggregationTest
[error] 	com.sksamuel.elastic4s.requests.indexes.IndexExistsTest
```

**Comment by joelvim** [comment]
There is a change in the behaviour of the API responses:

## For snapshot
* 8.5 :
```json
{
	"error": {
		"root_cause": [
			{
				"type": "repository_missing_exception",
				"reason": "[repo] missing"
			}
		],
		"type": "repository_missing_exception",
		"reason": "[repo] missing"
	},
	"status": 404
}
```
* 8.11
```json
{
	"snapshots": [],
	"failures": {
		"repo": {
			"type": "repository_missing_exception",
			"reason": "[repo] missing"
		}
	},
	"total": 0,
	"remaining": 0
}
```

## For search : 

it now returns the fields in the order they were indexed while it seems that previously it returned them in alphabetical order

## For indices exist API:

previously, if wildcard `expand_wildcards` was set to none, while `allow_no_indices`was set to true, it returned a 200, now it returns a 404. ES default value for `expand_wildcards` is set to open, while `elastic4s` puts it to none.

**Comment by sksamuel** [comment]
👍🏻
