### ISSUE TITLE
StandardAnalyzerDefinition : Bad maxTokenLength default value

### ISSUE THREAD

**Issue by nonontb** [sksamuel/elastic4s#308]
Hello, 

The documentation state a default value to 255.
https://www.elastic.co/guide/en/elasticsearch/reference/1.5/analysis-standard-analyzer.html

Default value is set to 0.
 https://github.com/sksamuel/elastic4s/blob/master/src/main/scala/com/sksamuel/elastic4s/Analyzer.scala
```scala
case class StandardAnalyzerDefinition(override val name: String,
                                      stopwords: Iterable[String] = Nil,
                                      maxTokenLength: Int = 0) extends AnalyzerDefinition(name) {
  def build(source: XContentBuilder): Unit = {
    source.field("type", "standard")
    source.field("stopwords", stopwords.toArray[String]: _*)
    source.field("max_token_length", maxTokenLength)
  }
}
```
ElasticSearch throw an Exception if maxTokenLength is equal to zero 
[1554]: index [xxxxxx], type [xxxx], id [AU1rmVKvumO1006htYo_], message [IllegalArgumentException[maxTokenLength must be greater than zero]]

**Comment by sksamuel** [comment]
Thanks for bug report; fixed now
