### ISSUE TITLE
issue with search with query and term

### ISSUE THREAD

**Issue by mfirry** [sksamuel/elastic4s#309]
So I have this index like this: http://pastie.org/10200080

I'm trying to query for a word in the `body` and a specific `language`.

Using `elastic4s` I'm doing something like this: 
`search in index -> "input" query { bool { must (query(q), term("language", l)) } } start from limit size`

For now I only have documents in two languages: `it` and `hu`.

If the language is, say `hu`, I keep getting results with `language` field set to `it` (while the opposite doesn't seem to happen - but I've got way more `it` documents than `hu`.

What am I doing wrong?

Thanks!

**Comment by sksamuel** [comment]
Can you make a stand alone example that I can run that shows this. Then if its a bug I can turn that into a test.

**Comment by mfirry** [comment]
I'm working on it. Thanks so much! It might not be a bug though... it might be me :)

**Comment by sksamuel** [comment]
How did you get on.

**Comment by sksamuel** [comment]
Closing this. I can't fix it without a test that duplicates it.
