### ISSUE TITLE
Morelike this cannot be filterable

### ISSUE THREAD

**Issue by rkommineni77** [sksamuel/elastic4s#310]
Currently, it is not possible to filter to more like this results.  Using filtered queries, we can filter results of more like this. Take a look at here:
http://stackoverflow.com/questions/23960921/how-to-add-filter-to-a-more-like-this-query-in-elastic-search

**Comment by sksamuel** [comment]
Looks like we should allow a query to be set on more like this.

**Comment by sksamuel** [comment]
This should do the trick, but do you want to write a test to make sure ?

**Comment by rkommineni77** [comment]
sorry about the delay.. please let me know if you still need help with the
test

rajesh
