### ISSUE TITLE
How to delete some data and then preform bulk opertation

### ISSUE THREAD

**Issue by vooolll** [sksamuel/elastic4s#311]
I have list of Catalogs, each of them have owner_id, I need to delete his previous catalog, and then insert new to the index. How to do it anync way?

It is my implementation but it looks weird, and I use await, so block the thread until catalog deleted. 

```scala
def bulkInsert(catalogs: List[Catalog]) = {
    val tasks = catalogs.map{
      (catalog: Catalog) =>
        client.execute{
          delete from catalogIndex where "id:" + catalog.owner_id
        }.await
        catalog.goods.map((g: Good) => index into catalogIndex doc g)
    }
    tasks.foreach(t =>client.execute{ bulk(t) })
    catalogs
  } 
```

Please help to getting started with working asynchronous way with elastic search.

**Comment by sksamuel** [comment]
Something like

```scala
val deletes = catalogs map { catalog =>  delete from catalogIndex where "id:" + catalog.owner_id }
val inserts = catalogs flatMap { catalog => catalog.goods.map { g => index into catalogIndex doc g }
client.execute {
  bulk { deletes } 
} map { _ =>
  client.execute {
    bulk { inserts }
  }
}
```

**Comment by vooolll** [comment]
@sksamuel thanks a lot :+1:

**Comment by vooolll** [comment]
@sksamuel My compiler said that it is only available com.sksamuel.elastic4s.DeleteByIdDefinition, is it actually motivation to bulk delete by query or it is slow, or impossible in elasticsearch?

**Comment by sksamuel** [comment]
Ok if you can't do bulk delete by queries, then do

val deletes = catalogs map { catalog =>  delete from catalogIndex where "id:" + catalog.owner_id }
val inserts = catalogs flatMap { catalog => catalog.goods.map { g => index into catalogIndex doc g }

val futures = deletes map { delete => client.execute { delete } }
Future.sequence(futures) map { _ =>
  client.execute {
    bulk { inserts }
  }
}
