### ISSUE TITLE
morelike cannot be part of boolean query

### ISSUE THREAD

**Issue by jaksky** [sksamuel/elastic4s#312]
morelike cannot be part of bool query, full usecase descibed on SO https://stackoverflow.com/questions/30577140/elasticsearch-more-like-this-in-elastic4s-boolean-query

I am not sure if this is duplicit to issue #310 , but seems as a different context at least to me. Thanks for any opinion, suggestion, ...

**Comment by sksamuel** [comment]
You're creating a morelike this "request" when you use "more like id ...".
What you need is a 'morelikeThisQuery`.

**Comment by sksamuel** [comment]
You're creating a morelike this "request" when you use `morelike id ...`
What you need is a `morelikeThisQuery`
