### ISSUE TITLE
Adding the stopwords_path functionality

### ISSUE THREAD

**Issue by apanimesh061** [sksamuel/elastic4s#315]
I don't this in the latest version `stopwords_path` has been included for `StopTokenFilters`. Would 
```scala
case class StopTokenFilterPath(name: String,
                           			stopwords_path: String,
                           			enablePositionIncrements: Boolean = false,
                           			ignoreCase: Boolean = false)
    extends TokenFilterDefinition {

  val filterType = "stop"

  override def build(source: XContentBuilder): Unit = {
    source.field("stopwords_path", stopwords_path)
    if (enablePositionIncrements) source.field("enable_position_increments", enablePositionIncrements)
    if (ignoreCase) source.field("ignore_case", ignoreCase)
  }
}
```
work if it is added to `TokenFilter.scala`?

**Comment by apanimesh061** [comment]
I have added the `stopwords_path` functionality to the API in the repo I forked from yours. Please check if it is ok. I even have built it using Travis and till now all tests have passed.

**Comment by sksamuel** [comment]
Can you make a PR. A PR will show the differences automatically, and its very easy for you to make one.

**Comment by sksamuel** [comment]
This is included now
