### ISSUE TITLE
Type exists missing

### ISSUE THREAD

**Issue by xxBedy** [sksamuel/elastic4s#318]
Please implement functionality to check if type exists in index.

Described at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-types-exists.html

Thank you

**Comment by stringbean** [comment]
This has already been implemented:

```scala
val existsFuture = client.execute {
  types exist "tweet" in "twitter"
}.

val typeExists = existsFuture.await.isExists
```

**Comment by xxBedy** [comment]
Great, thank you!
btw: Is it documented somewhere ? I can't found it.

**Comment by sksamuel** [comment]
Probably not. Do you you want to do a PR for the main page list of
operations?

**Comment by xxBedy** [comment]
OK. I will do it.
