### ISSUE TITLE
more debug options

### ISSUE THREAD

**Issue by jackpoll** [sksamuel/elastic4s#321]
I'm using very much your library, but missing some debug options:

1. I want to see the compilation of the query to ES - like that I can debug my errors.

2. A more detailed error trace when getting an ES error.

**Comment by sksamuel** [comment]
See Json section on readme on front page for this added feature.

**Comment by tiancheng0307** [comment]
Is this `client.show` only available in elastic4s version 5.2.x? Is it available for 2.2.x?

**Comment by sksamuel** [comment]
it's in 2.x (can't remember if its 2.2 or 2.3) but its not on the client, you invoke it on the request.

**Comment by tiancheng0307** [comment]
from the README, the show method is invoked on the client and passed in a particular request. I tried using 2.2.0 / 2.3.0 but don't seem to find a `show` method on the client.

val json = client.show {
  search("music" / "bands") query "coldplay"
}
println(json)

**Comment by sksamuel** [comment]
The readme is for 5.x, 2.2 is years old. In that version you called .show on the request.

**Comment by tiancheng0307** [comment]
got it, thanks!
