### ISSUE TITLE
Possibility to update node and cluster settings [feature-request]

### ISSUE THREAD

**Issue by l15k4** [sksamuel/elastic4s#322]
Hi,

would you please add an option to update node and cluster settings in `SettingsDsl`? It is already implemented for [updating index settings](http://stackoverflow.com/a/29291387/306488).

For instance I'm trying to figure how to set `indices.store.throttle.type: none` before batch indexing and then turn it on afterwards.

**Comment by sksamuel** [comment]
Can you something like

`cluster transientSettings map persistentSettings map`

or

`clusterTransientSettings(map).persistentSettings(map)`

**Comment by l15k4** [comment]
I see I missed that, it does what I needed. Thank you

**Comment by sksamuel** [comment]
No, that doesn't exist yet. I'm saying I can add it :)
