### ISSUE TITLE
Error "could not find implicit value for parameter executable: com.sksamuel.elastic4s.Executable" on multisearch

### ISSUE THREAD

**Issue by sdiwu** [sksamuel/elastic4s#324]
Just trying the multisearch:

      val resp = client.execute(
        search in "facebook/user",
        search in "twitter/user"
      )

I got compile error on that line:

```
could not find implicit value for parameter executable: com.sksamuel.elastic4s.Executable[(com.sksamuel.elastic4s.SearchDefinition, com.sksamuel.elastic4s.SearchDefinition),R]
```

Checking from Intellij, the type of `resp` is `Future[Nothing]`, not `Future[MultiSearchResponse]` as written in the [documentation](https://github.com/sksamuel/elastic4s/blob/master/guide/multisearch.md).

Is there something I missed here?

FYI I'm using elastic4s v1.5.13.

**Comment by sdiwu** [comment]
Never mind, I found the solution. Just wrap the search with `multi`

```
  val resp = client.execute(
    multi(
      search in "facebook/user",
      search in "twitter/user"
    )
  )
```

I guess your documentation needs to be updated.

**Comment by sksamuel** [comment]
Thanks, updated.
