### ISSUE TITLE
_id mapping should support path

### ISSUE THREAD

**Issue by n0rb3rt** [sksamuel/elastic4s#327]
The mapping DSL does not appear to support the following path directive for the _id field:

"_id": {"path": "other.field"}

Would be nice if I could specify in a mapping defintion:

id path "other.field"

**Comment by sksamuel** [comment]
It's actually been deprecated in 1.5 that. I don't think we should add it retrospectively. What do you think.

**Comment by n0rb3rt** [comment]
Ah yes, in favor of copy_to. Hard to keep up with all the 1.5 changes. But keep up I will.

**Comment by n0rb3rt** [comment]
I tried this.  I see the "copy_to" for the GEOID field when I get the mapping, but still end up with random _id's when I index documents.  Is this right?

client.execute {
  put mapping ES_INDEX / EsType as Seq(
    "type" typed StringType index NotAnalyzed,
    "geometry" typed GeoShapeType precision "25m",
    "properties" inner(
      "NAME" typed StringType,
      "GEOID" typed StringType index NotAnalyzed copyTo "_id"
    )
}

**Comment by sksamuel** [comment]
Looks right, but maybe you can't use _id in copy to ?

**Comment by n0rb3rt** [comment]
Apparently not according to:
https://github.com/elastic/elasticsearch/issues/6730

Gotta happen client side now, which is what I ended up doing.

**Comment by sksamuel** [comment]
Ah ok
