### ISSUE TITLE
Error handling in elastic4s

### ISSUE THREAD

**Issue by sdiwu** [sksamuel/elastic4s#328]
I did a test like this when elastic server is not running:

```
        client.execute(index into "bands/artists" fields "name" -> "coldplay" id 11) map { resp =>
          println("isCreated: " + resp.isCreated)
        } recover {
          case e => println("Error happened: " + e.getMessage)
        }
```

Surprisely no exception happened at all and no text printed out at all. I thought it would fall into `recover` part, and it didn't fall into `map` part too. So the client just silently returns without error.

Is there something I missed here? What is the correct way to handle error or failure in elastic4s?

**Comment by sksamuel** [comment]
Need to see the rest of your program. Is the program terminating before the future is completed.

**Comment by sdiwu** [comment]
Ok, I found out that if using `ElasticClient.local`, it will not throw any exception, but using `ElasticClient.remote` will throw exception.

I'm curious, what's the equivalent of `ElasticClient.local` in the Java API: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html ?

**Comment by sksamuel** [comment]
If you look at the source for ElasticClient you can see what its doing.
It's just creating a local d

**Comment by sksamuel** [comment]
If you look at the source for ElasticClient you can see what its doing.
It's just creating a local node that stores data.

**Comment by sdiwu** [comment]
Ok, seems when using .local, it has connection but still wonder why the `map { }` part doesn't get executed.

I have a little question about the elastic behaviour. I have this sample code:
```
      val resp = client.execute(index into "bands/artists" fields "name" -> "coldplay" id 11).await
      println("isCreated="+resp.isCreated)

      val resp2 = client.execute(search in "bands/artists").await
      println("resp2="+resp2)
```

Assumed the record with id = 11 is not exist yet, the result printed is:

```
isCreated=true
resp2={
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

So the search doesn't return any result despite the data is successfully created, but when I checked from curl, I can see the data is exist (or run again the client search).

So it seems when the index request return, the data hasn't been inserted yet , thus when the search request is called, it returns nothing. I wonder if this behaviour is coming from elastic search itself or elastic4s?

Do you have solution for this? Currently I put `Thread.sleep(1000)` between the request.

**Comment by MLnick** [comment]
The default index refresh is 1s if I recall - you should be able to specify refresh in the client request to force an index refresh after the index operation 



—

**Comment by sksamuel** [comment]
Yep mlnick has the reason. I answer this question once a week at least so I
think its time for a FAQ.

**Comment by sdiwu** [comment]
Thanks. But I failed to refresh the index with elastic4s:

`client.execute(refresh index "bands").await`

But using java method, it works:

`client.admin.indices().prepareRefresh("bands").execute().actionGet()`

Is this because elastic4s doesn't support admin side yet?

**Comment by MLnick** [comment]
I'm away from laptop now but in the actual index request you should be able to specify a refresh param (in the DSL), I think 



—

**Comment by sdiwu** [comment]
Did you mean this way?

`client.execute(index into "bands/artists" fields "name" -> "coldplay" id id refresh true).await`

**Comment by MLnick** [comment]
Yup that should force a refresh and subsequent search request should get hits 



—
