### ISSUE TITLE
XPUT not working :Windows

### ISSUE THREAD

**Issue by rpalsaxena** [sksamuel/elastic4s#329]
I am using win7 with curl
PS C:\Users\Saxena> curl -XPUT localhost:9200/test/type/1 -d '{"test" : "value"}'
{"error":"MapperParsingException[failed to parse]; nested: JsonParseException[Unrecognized token 'value': was
('true', 'false' or 'null')\n at [Source: [B@591265d6; line: 1, column: 15]]; ","status":400}PS C:\Users\Saxe
calhost:9200/test/_mapping?pretty=1
{
  "test" : {
    "mappings" : {
      "type" : {
        "_source" : {
          "enabled" : false
        },
        "properties" : { }
      }
    }
  }
}

Getting the above mentioned error.
Please suggest me some solution

**Comment by sksamuel** [comment]
You're not using elastic4s if you're using curl. Elastic4s is a Scala client. You're using something else.
