### ISSUE TITLE
geohash_grid

### ISSUE THREAD

**Issue by jackpoll** [sksamuel/elastic4s#330]
I don't see any option to geohas_grid aggregation like here : https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html#search-aggregations-bucket-geohashgrid-aggregation

**Comment by jackpoll** [comment]
Is there a due date?

Thank you,

**Comment by sksamuel** [comment]
If you need it urgently best thing to do is a PR and we can do a release.

**Comment by sksamuel** [comment]
Will be included in 1.6.5
