### ISSUE TITLE
bad jar for 1.5.14 on maven central

### ISSUE THREAD

**Issue by vbehar** [sksamuel/elastic4s#332]
Hi,

the jar for 1.5.14 on maven central is bugged : https://repo1.maven.org/maven2/com/sksamuel/elastic4s/elastic4s_2.11/1.5.14/elastic4s_2.11-1.5.14.jar

279 bytes, contains only the manifest.mf file

**Comment by sksamuel** [comment]
You need the -core jar now. See readme on github.com/sksamuel/elastic4s for
details

**Comment by sksamuel** [comment]
But.. I see -core hasn't made it to central either. Hmmmm

**Comment by sksamuel** [comment]
1.5.15 is up there now, and you need elastic4s-core

**Comment by sksamuel** [comment]
@vbehar

**Comment by vbehar** [comment]
thanks!
