### ISSUE TITLE
Mapper Attachments Type for Elasticsearch

### ISSUE THREAD

**Issue by apanimesh061** [sksamuel/elastic4s#338]
[Here](https://github.com/elastic/elasticsearch-mapper-attachments) a plug-in is given that adds `attachment` data type to ES. You already have that but some changes have to made in that so that it works with this plug-in. I have made that code but as separate mapping as `NewAttachmentField`. How should I go about it? Should I change the name or merge it with the `AttachmentField` mapping?

**Comment by sksamuel** [comment]
Are both plugins the same or compatible ?

**Comment by apanimesh061** [comment]
If we use "attachment" without the plugin it will work but the data won't
be searchable. With this plugin we can search within any kind of attachment
be it PDFs/Docs/RTFs etc.

On Thu, Jun 18, 2015 at 2:47 PM, Stephen Samuel <notifications@github.com>
wrote:

> Are both plugins the same or compatible ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sksamuel/elastic4s/issues/338#issuecomment-113255028>.
>



-- 
Thanks and regards,
Animesh Pandey
Graduate Student
Northeastern University
Boston, MA, USA

**Comment by sksamuel** [comment]
Closing this unless someone wants to do a PR.
