### ISSUE TITLE
Problems with published package (v1.6.0)

### ISSUE THREAD

**Issue by JD557** [sksamuel/elastic4s#339]
I think that the version of elastic4s published at https://oss.sonatype.org/content/repositories/releases/com/sksamuel/elastic4s/elastic4s_2.11/1.6.0/ is not working (the .jar appears to be empty). Could you have a look at it?

**Comment by sksamuel** [comment]
@JD557 you need the elastic4s-core module now, I added a section to the readme but maybe I should bold that :)

**Comment by sksamuel** [comment]
https://oss.sonatype.org/content/repositories/releases/com/sksamuel/elastic4s/elastic4s-core_2.11/1.6.0/
