### ISSUE TITLE
Please add Implicit conversion for getAliasResponse

### ISSUE THREAD

**Issue by garyfrost** [sksamuel/elastic4s#340]
client.execute {
      get alias "somealias_*" on "_all"
    }

returns a 
org.elasticsearch.action.admin.indices.alias.get.GetAliasesResponse
which has a getAliases() which is of type o.e.common.collect.ImmutableOpenMap, they keys are Strings but the values are o.e.common.collect.SingletonImmutableList<o.e.cluster.metadata.AliasMetaData>

Consequently trying to use map/flatmap on the GetAliasesResponse.getAliases() is impossible.

**Comment by sksamuel** [comment]
You can use `.asScala` as a workaround, to turn the map into a scala map, import `import scala.collection.JavaConverters._` first

**Comment by sksamuel** [comment]
Added, and will be included in release 1.6.1.
