### ISSUE TITLE
Completion suggester payload is not being updated

### ISSUE THREAD

**Issue by lenniboy** [sksamuel/elastic4s#343]
Hi,

I'm having a problem with elastic4s' completion suggester feature.

I'm adding a payload to my suggestion which I change later. However this update to the payload is not propagated to the suggestion index.

I've written a reproduction case to illustrate the problem. It is also in a self contained repository: https://github.com/lenniboy/es-suggest-reproduction

```scala
import com.sksamuel.elastic4s.ElasticDsl._
import com.sksamuel.elastic4s.mappings.FieldType.{CompletionType, StringType}
import com.sksamuel.elastic4s.source.StringDocumentSource
import com.sksamuel.elastic4s.{ElasticClient, SimpleAnalyzer}
import org.scalatest.{FlatSpec, Matchers}

class PayloadSpec extends FlatSpec with Matchers {

  behavior of "Elasticsearch payloads"

  it should "elastic search reproduction case" in {
    val client = ElasticClient.remote("localhost", 9300)
    val indexName = "bands"

    client.execute { delete index indexName }.await

    val createRes = client.execute { create index indexName }.await
    createRes should be('acknowledged)

    client.execute {
      put mapping "bands" / "band" as Seq(
        field name "name" withType StringType,
        field name "suggest" withType CompletionType
          analyzer SimpleAnalyzer
          indexAnalyzer SimpleAnalyzer
          payloads true
      )
    }.await

    val insertJson = """
      |{
      |  "name" : "Queen",
      |  "suggest" : {
      |    "input" : ["Queen"],
      |    "output" : "Queen",
      |    "payload" : {
      |      "country" : "GB"
      |    }
      |  }
      |}
    """.stripMargin
    client.execute { index into indexName / "band" id "1" doc StringDocumentSource(insertJson) }.await

    val payloadUpdateJson = """
      |{
      |  "suggest" : {
      |    "payload" : {
      |      "country" : "new updated country"
      |    }
      |  }
      |}
    """.stripMargin
    client.execute { update id "1" in indexName / "band" doc StringDocumentSource(payloadUpdateJson) }.await

    Thread.sleep(1000) //wait for the indexing to finish
    val searchRes = client.execute { search in indexName / "band" }.await
    println("Search response:")
    println(searchRes)

    val resp = client.execute {
      search in indexName types "bands" suggestions(
        suggest.using(completion).as("suggest").text("Queen").from("suggest")
      )
    }.await
    println("")
    println("Suggest response:")
    println(resp)
  }
}
```

If you run this code, you will see that the payload in the suggest response remains at the initial state (`GB`) rather than reflect the update (`new updated country`).

You may reject this as an ES problem itself and you'd be quite sensible to do so. However, and here comes the crazy part, if you do all the steps via the HTTP API, the update of the payload works!

```
DELETE /t 
PUT /t
PUT /t/_mapping/t
{
  "properties": {
    "name": {
      "type": "string"
    },
    "suggestions": {
      "type": "completion",
      "index_analyzer": "simple",
      "search_analyzer": "simple",
      "payloads": true
    }
  }
}

GET /t/_search
PUT /t/t/1
{
  "genre": "name",
  "suggestions": {
    "input": [
      "Queen"
    ],
    "output": "Queen",
    "payload": {
      "country": "GB"
    }
  }
}

POST /t/t/1/_update
{
  "doc": {
    "suggestions": {
      "payload": {
        "meta": "baz"
      }
    }
  }
}

GET /t/_search
GET /t/_suggest
{
  "s1": {
    "text": "Queen",
    "completion": {
      "field": "suggestions"
    }
  }
}
```

It seems that elastic4s (probably via the Java client) does something different than the HTTP API does.

Do you have any idea what could be causing this?

**Comment by sksamuel** [comment]
I'll have to look into it, but out of curiosity, have you tried the Java client (just to confirm its that and not something e4s is doing wrong when wrapping it).

**Comment by sksamuel** [comment]
I do get the same issue as you, and I think its something to do with the completion index not updated when you update the regular index. There is something along those lines in the docs: `
The suggest data structure might not reflect deletes on documents immediately. You may need to do an Optimize for that. You can call optimize with the only_expunge_deletes=true to only cater for deletes or alternatively call a Merge operation.` 
I can get the optimize to work if I add:
```scala
    client.execute {
      optimizeIndex(indexName).flush(true).maxSegments(1)
    }.await
```
But forcing your index to a single segment each time you do an update isn't feasible.

**Comment by sksamuel** [comment]
@lenniboy  I do get the same issue as you, and I think its something to do with the completion index not updated when you update the regular index. There is something along those lines in the docs:  The suggest data structure might not reflect deletes on documents immediately. You may need to do an Optimize for that. You can call optimize with the only_expunge_deletes=true to only cater for deletes or alternatively call a Merge operation. 
I can get the optimize to work if I add:

    client.execute {
      optimizeIndex(indexName).flush(true).maxSegments(1)
    }.await
But forcing your index to a single segment each time you do an update isn't feasible.

**Comment by sksamuel** [comment]
Actually their suggestion works as well:

```scala
    client.execute {
      optimizeIndex(indexName).onlyExpungeDeletes(true)
    }.await
```

So I guess that's it (and probably what the HTTP side is doing). Do all your updates, then call that after.

**Comment by lenniboy** [comment]
Thanks for the quick reply!

What is the performance impact of calling `optimizeIndex(indexName).onlyExpungeDeletes(true)` for every update? Is there one?

**Comment by sksamuel** [comment]
A lot. So it would only be a viable solution if you do a lot of updates at
once, then can refresh after.

Other than that, we would need to ask ES in general what the solution is.

**Comment by lenniboy** [comment]
Thanks for your help.

I'm going to close the issue since I also believe that the issue is with the java client. Once I get a spare minute I will write a reproduction case in Java and open a ticket with elasticsearch.

**Comment by sksamuel** [comment]
Ok that would be useful.
