### ISSUE TITLE
Local Node cannot be configured to run dynamic groovy script

### ISSUE THREAD

**Issue by talgendler** [sksamuel/elastic4s#350]
Setting "false" value to indicate that I want to enable dynamic script (in tests for example) here:
```
ImmutableSettings.settingsBuilder().put("script.disable_dynamic", false)
```
Seems to be ignored in Local Node. It's reproducible in current test-kit code. The script I'm trying to run is inside the ScriptSortDefinition:
```
new ScriptSortDefinition(s"if (_source.containsKey('arrayField')) _source['arrayField'].size() else 0")
```

**Comment by sksamuel** [comment]
Can you do a PR to add a full test - then I'll add a fix. Deal ? :)

**Comment by talgendler** [comment]
Sure, I'll do that.

**Comment by talgendler** [comment]
I can't reproduce this using latest "master" branch, so I added the example anyway. If you like you can merge it.
```scala
"script sort" - {
    "sort by name length" in {
      val sorted = client.execute {
        search in "script/tubestops" query matchall sort {
          script sort """if (_source.containsKey('name')) _source['name'].size() else 0""" order SortOrder.DESC typed "number"
        }
      }.await
      sorted.hits(0).sourceAsMap("name") shouldBe "south kensington"
      sorted.hits(3).sourceAsMap("name") shouldBe "bank"
    }
  }
```

**Comment by sksamuel** [comment]
I've merged it, but I guess the answer is upgrade to 1.6.5 if you can (or
try the latest 1.5.x release).
