### ISSUE TITLE
Count with rawQuery

### ISSUE THREAD

**Issue by AlexandreBP** [sksamuel/elastic4s#351]
Hello,

I am using the query dsl from elastic search (import org.elasticsearch.index.query._) to build the query as a string from a list of user input.
I can easily use the search method from elastic4s with rawQuery to search an index in elastic search. 
```scala
search in index rawQuery q limit limit start offset
```
However, the rawQuery method doesn't seem to be supported on count and the query method doesn't accept my string q which is exactly the same than the one I used for searching.
```scala
count from index query q
```
Example of raw query which return everything that is contained in my index:
```
query: {
  "filtered" : {
    "query" : {
      "bool" : {
        "should" : {
          "match_all" : { }
        }
      }
    },
    "filter" : {
      "bool" : {
        "should" : {
          "match_all" : { }
        }
      }
    }
  }
}
```

Am I missing something?
Thank you in advance

**Comment by MLnick** [comment]
Are you actually wanting to use match_all or is that an example?




 You can just do count from index query matchall




No need for a raw query for that



—

**Comment by sksamuel** [comment]
As @MLnick say, if you need to use the raw query then the DSL is failing you.

**Comment by AlexandreBP** [comment]
Thank you for your quick reply and action.

@MLnick yes it was just an example sorry if that was not clear. I need to do much more complicated query. I just wanted to show an example of the format that I use which is a plain JSON.
@sksamuel thank you for adding the function to the DSL so quickly! I forgot to mention that I am using the latest version 1.6.4. Any chance to see that change added to that version soon?

**Comment by sksamuel** [comment]
@AlexandreBP   1.6.5 and 1.5.18 will be released tomorrow.
Also can you tell me why you are using json over the dsl. Is the dsl not powerful enough/

**Comment by AlexandreBP** [comment]
@sksamuel great! Thank you.

I am building the query with the java QueryBuilder and FilterBuilder from elastic search. The DSL in elastic4s might not have had the functionality that I needed when I started my project last year or it might have been harder for me to use since I started learning Scala around September last year. When I have some time, I will try to translate my code to the DSL version and get back to you if I encounter any problem. How does that sound?

**Comment by sksamuel** [comment]
Yeah that's fine. I was just asking in case there was something major
missing that I could have added.

**Comment by AlexandreBP** [comment]
I pulled the new release 1.6.5 and tried the ```count``` function from the DSL with ```rawQuery``` but the ```getCount``` method returns 0. If I use the ```search``` function from the DSL with ```rawQuery``` and the same query, I get the expected results.

Here is an example:

```
20:10:42.551 [play-akka.actor.default-dispatcher-5] DEBUG m.elastic_search.query.ESEnquirer - {
  "filtered" : {
    "query" : {
      "bool" : {
        "should" : {
          "match_all" : { }
        }
      }
    },
    "filter" : {
      "bool" : {
        "must" : {
          "terms" : {
            "id" : [ 77914514, 77914510 ]
          }
        },
        "should" : {
          "match_all" : { }
        }
      }
    }
  }
}
20:10:42.573 [play-akka.actor.default-dispatcher-5] DEBUG m.elastic_search.query.ESEnquirer - Count using the count function: 0
20:10:42.592 [play-akka.actor.default-dispatcher-5] DEBUG m.elastic_search.query.ESEnquirer - Count using the search function: 2
```

and the code:
```scala
def getResultSize(params: ProductLookForm) = {
    val query = queryBuilderProvider.get().build(params)
    logger.debug(query)
    val count1 = client.execute { count from ESCatalog rawQuery query }.await(20.seconds).getCount
    logger.debug(s"Count using the count function: $count1")
    val count2 = client.execute { search in ESCatalog rawQuery query}.await(20.seconds).getHits.getTotalHits
    logger.debug(s"Count using the search function: $count2")
    count2
  }
```

Am I missing something?
Thank you in advance.
