### ISSUE TITLE
Too many daemon threads

### ISSUE THREAD

**Issue by iroh** [sksamuel/elastic4s#355]
I am using elastic4s client in my play-framework app. I populate the index in a separate batch job and the app only queries the index (read only). But the app server has been crashing frequently and is always at a 75+ % CPU. Looking into the matter revealed that elasticsearch is running ~3k daemon threads in the jvm. Why would the client need so many daemon threads?

**Comment by sksamuel** [comment]
These are created by the elasticsearch java client I assume? Can you paste in some of the thread names.

**Comment by raam86** [comment]
You might be creating a client for each request

**Comment by sksamuel** [comment]
It could be a bug in the shutdown of the local client. But without more details from @iroh there's not much we can do to find it. Closing. Please re-open if you want to supply more details.
