### ISSUE TITLE
Add support for setting fields during update requests

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [sksamuel/elastic4s#362]
See my question at [stackoverflow](http://stackoverflow.com/questions/31578688/how-return-document-from-elasticsearch-after-update/31585751#31585751). The problem is elasticsearch supports returning `_source` field after update, but UpdateDefinition do not have any api for setting this parameters.

**Comment by sksamuel** [comment]
What is this option, beacuse I cannot see it in the Java client.

**Comment by C-h-e-r-r-y** [comment]
"I cannot see it in the Java client." - very strange.

The option is used to "tell" elasticsearch that it should return updated document via UpdateResponse. See [parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_3) in update documentation.

P.S. Also you can run my example from stackoverflow (question is answered) and see output from original version and after patching.

**Comment by sksamuel** [comment]
Thanks for the clarification. I'll add this to elastic4s now.

**Comment by tioback** [comment]
Would you be so kind as to provide an example at the docs?
