### ISSUE TITLE
local = false in `ElasticClient.local()`

### ISSUE THREAD

**Issue by avdv** [sksamuel/elastic4s#365]
Hi.

At https://github.com/sksamuel/elastic4s/blob/1.5.17/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/ElasticClient.scala#L171. In version 1.6.0 this seems to be fixed, but I'm still using ElasticSearch 1.5.x.

Just my 2cents.

**Comment by sksamuel** [comment]
Thanks fixed, don't know how that was there for so long (4th june)
