### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Maatary** [sksamuel/elastic4s#370]
Have you used it in production already. I want to, i just want to be sure that it is enough battle test, because i'm on a short short development time.

**Comment by andrestc** [comment]
I'm using it in production for over 8 months. It works greatly.

**Comment by sksamuel** [comment]
I'm using it in production too (HSBC Bank)

**Comment by MLnick** [comment]
Using in production over a year - client & DSL is great and must say probably the most responsive and fast-moving project I've encountered!



—

**Comment by sksamuel** [comment]
I should do a little "used by" page or something?

**Comment by mrwiggles** [comment]
We (Shazam) have been using it in production for quite some time to power our public facing search engine

**Comment by Maatary** [comment]
that would be great indeed

**Comment by sksamuel** [comment]
Barclays Bank use it too

**Comment by sksamuel** [comment]
I updated the readme to contain a "used by" section at the bottom. If anyone wants to PR to add themselves, feel free.
