### ISSUE TITLE
StackOverflowError in MappingDefinition.templates

### ISSUE THREAD

**Issue by sjoerdmulder** [sksamuel/elastic4s#371]
When using a `templates` or `dynamicTemplates` with multiple items you get a StackOverflowError.

This makes sense when looking at https://github.com/sksamuel/elastic4s/blob/1.7.0/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/mappings/MappingDefinition.scala#L141 but is not the desired behavior i think.

Testcase:
```scala
client.execute {
  create template "foobar" pattern "logstash-*" mappings (
    dynamicTemplates(
      template("string_foo") matching "*foo" matchMappingType "string" mapping {
        field typed StringType index NotAnalyzed
      },
      template("string_bar") matching "*bar" matchMappingType "string" mapping {
        field typed StringType index NotAnalyzed
      }
    )
  )
}
```

**Comment by sksamuel** [comment]
Its recursing instead of calling the right overloaded method.

**Comment by sjoerdmulder** [comment]
Whoah quick response: btw using Scala 2.11.6

**Comment by sksamuel** [comment]
You could get around it for now by putting the templates in a List and
passing that in. I'll fix for next release.

**Comment by sjoerdmulder** [comment]
Putting it in a List doesn't help because that also calls the method with the Iterable.

**Comment by sksamuel** [comment]
Ah yes

**Comment by sjoerdmulder** [comment]
Actually got it working now, i was using `dynamicTemplates` (as in the testcase) but switching to `templates` does work.
