### ISSUE TITLE
Geo distance filter - swapped latitude and longitude

### ISSUE THREAD

**Issue by sejkorat** [sksamuel/elastic4s#375]
Hi,

I was playing with geoDistance filter and I found that latitude and longitude are swapped in output query:

`val req = search ....... 
      postFilter(geoDistance("adresa.souradnice.geopoint") 
      lat souradnice.getLatitude.doubleValue() 
      lon souradnice.getLongitude.doubleValue()           
      distance(30, DistanceUnit.KILOMETERS))

println(req)
println("lon =  " + s.getLongitude.doubleValue() )
println("lat =  " + s.getLatitude.doubleValue() )
`
results in 

  "post_filter" : {
    "geo_distance" : {
      "adresa.souradnice.geopoint" : [ 16.3074883, 49.86739129999999 ] ,
      "distance" : "30.0km"
    }

   lon =  16.3074883
   lat =  49.86739129999999

And it's incorrect because result should be "adresa.souradnice.geopoint" :  [ 49.86739129999999, 16.3074883 ]. Please swap lat and lon.

Thanks,
Tomas

**Comment by martin-g** [comment]
Please provide more complete/correct code example.
Thanks!

**Comment by sejkorat** [comment]
Hi,

There is more complete example: 

def findSimilar(id: String, type :String, typPozadavku: Option[String], town: Option[String], point: GeoPoint): Future[SearchResponse] = {
    client.execute{
       val q = new BoolQueryDefinition {
         must(
          morelikeThisQuery("desc") ids (id)
         ) 
         if(!town.isEmpty) {
           must(matchQuery(field = "town", value = town.get))
         }
       }
       val req =search in s"index/${type}" query q sourceInclude("adress.town", "address.street")       postFilter(geoDistance("adresss.geopoint") lat point.getLatitude lon point.getLongitude distance(20,   DistanceUnit.KILOMETERS))
       println(req)
       req
    }
  }

and this method prints ES query :

{
  "query" : {
    "bool" : {
      "must" : [ {
        "mlt" : {
          "fields" : [ "desc" ],
          "like_text" : null,
          "ids" : [ "H-5965723" ]
        }
      }, {
        "match" : {
          "town" : {
            "query" : "TestTwon"
          }
        }
      } ]
    }
  },
  "post_filter" : {
    "geo_distance" : {
      "adresss.geopoint" : [ 16.311062, 49.870523 ],
      "distance" : "20.0km"
    }
  },
  "_source" : {
    "includes" : [ "adress.town", "address.street" ],
    "excludes" : [ ]
  }
}

Pproblem is in geo_distance filter. There is incorrect order of latitude and longitude: (in our case GeoPoint contains latitude = 49.870523 and longitude 16.311062 )
First should be latitude and then longitude but the current order is [lon, lat] in our case "adresss.geopoint" should contain [ 49.870523, 16.311062 ]

I hope this helps.

Thanks,
Tomas

**Comment by martin-g** [comment]
According to https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-filter.html#_lat_lon_as_array_4:
`the order of lon/lat here in order to conform with GeoJSON`.

Everything looks correct to me.

**Comment by sksamuel** [comment]
Yeah elasticsearch has them the other way than you might normally do it.

**Comment by sejkorat** [comment]
I'm sorry it's my fault. It looks like that the order was changed in version 1.7 and we are still running 1.6 version where [lat, lon] works.
