### ISSUE TITLE
Any plan for supporting termvector api?

### ISSUE THREAD

**Issue by daeheehan** [sksamuel/elastic4s#376]
I wonder if you have any plan for termvector API (https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-termvectors.html) and also mtermvector (https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-multi-termvectors.html).

**Comment by sksamuel** [comment]
I will add it.

**Comment by johann-abraham** [comment]
+1
