### ISSUE TITLE
If publisher query doesn't have the scroll parameter, throw an exception

### ISSUE THREAD

**Issue by rauanmaemirov** [sksamuel/elastic4s#401]
Before creating ScrollPublisher, this method should check whether SearchDefinition has a scroll: https://github.com/sksamuel/elastic4s/blob/master/elastic4s-streams/src/main/scala/com/sksamuel/elastic4s/streams/ReactiveElastic.scala#L33

Without a scroll, publisher will be unbound and endlessly return first batch. Check might help devs to avoid getting wrong results.

**Comment by andrestc** [comment]
Working on this.
