### ISSUE TITLE
Add 'missing' parameter to Field Value Factor

### ISSUE THREAD

**Issue by andrestc** [sksamuel/elastic4s#405]
The Field Value Factor now supports a 'missing' parameter:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-field-value-factor

If I'm right, its just a matter of adding to [FieldValueFactorDefinition](https://github.com/sksamuel/elastic4s/blob/49f60518d6f08527b5b7be6f9ec3b9823766f171/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/scorers.scala#L53).

Will submit a PR when I can.

**Comment by sksamuel** [comment]
Ok cool
