### ISSUE TITLE
RichSearchResponse and RichSearchHit

### ISSUE THREAD

**Issue by ddispaltro** [sksamuel/elastic4s#406]
You could make those (or similar classes) inherit from AnyVal and they won't incur a Runtime cost, detailed here [1].  

[1] http://www.scala-lang.org/api/current/index.html#scala.AnyVal

**Comment by martin-g** [comment]
Duplicates #396

**Comment by ddispaltro** [comment]
I would say this is more focused on performance (aka less runtime cost) than actually anything user facing.

**Comment by sksamuel** [comment]
@ddispaltro It's a good point, and one I'll use when/if I make the rich responses.

**Comment by sksamuel** [comment]
I've updated the description of #396 to include this, rather than have a separate ticket.
