### ISSUE TITLE
No way to get a list of all index names using elastic4s

### ISSUE THREAD

**Issue by ddsr17** [sksamuel/elastic4s#407]
Please provide any help if possible,I want a list of all indices in elasticsearch rather than the documents.

**Comment by luismfonseca** [comment]
I'm using the following:
`esClient.execute(get segments query).map(_.getIndices.keys.toSeq)`, where `query` could be `*`.

**Comment by ddsr17** [comment]
Thanks a lot

**Comment by sksamuel** [comment]
You can use indexStats for this. I've added some sugar in 2.0 which makes it easier. See next commit.

**Comment by RPGambit2** [comment]
sk,

I am attempting to get all of the elastic indexes.   I am having trouble with indexStats on how to use it.  Is there an example of how I can use this to return to me all the indexes?

Thanks!
