### ISSUE TITLE
Mapping should detect fields with same name but diff types

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#410]
In 2.0 mappings in the same index that use a field with the same name but different types is disallowed. We should detect this in the DSL and throw a nice exception while the query is parsed (unless the Java client will do this for us).
See https://www.elastic.co/blog/great-mapping-refactoring

**Comment by martin-g** [comment]
As far as I understood the article the Java client will do the check at indexing time and complain early.

**Comment by sksamuel** [comment]
I'll leave this ticket to remind me to check once the 2.0 is released.
