### ISSUE TITLE
index exists DSL doesn't work with "index/type" or "index/type/id" pattern

### ISSUE THREAD

**Issue by sdiwu** [sksamuel/elastic4s#411]
Assume you have inserted a record of index/type of "bands/artists" with id = 10 into ES.

Code 1: 

      val res = client.execute(index exists "bands").await
      println(res.isExists)    // print true

Code 2:

      val res = client.execute(index exists "bands/artists").await
      println(res.isExists)    // print false

Code 3:

      val res = client.execute(index exists "bands/artists/10").await
      println(res.isExists)    // print false

But if I use curl:

Curl 1:

    $ curl -XHEAD "http://localhost:9200/bands" -i
    HTTP/1.1 200 OK
    Content-Type: text/plain; charset=UTF-8
    Content-Length: 0

Curl 2:

    $ curl -XHEAD "http://localhost:9200/bands/artists" -i
    HTTP/1.1 200 OK
    Content-Type: text/plain; charset=UTF-8
    Content-Length: 0

Curl 3:

    $ curl -XHEAD "http://localhost:9200/bands/artists/10" -i
    HTTP/1.1 200 OK
    Content-Type: text/plain; charset=UTF-8
    Content-Length: 0

All returns 200 (OK).

So it seems `index exists` DSL doesn't work with "index/type" or "index/type/id" pattern. 
Or could be I missed something here?

**Comment by andrestc** [comment]
Your last curl is actually an [Get API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html) and not an index exists.

So, you should use the [DSL for that](https://github.com/sksamuel/elastic4s/blob/master/guide/get.md).

**Comment by sdiwu** [comment]
Oh ok. How about the 2nd curl? Is it Get API too?

**Comment by andrestc** [comment]
For the second curl, there is the type exists DSL:

```scala
types exists <types> in <index>
```

Elastic4s uses the java [Transport Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html) to connect directly to the cluster. It doesn't issue http requests, so you cant choose to do HEAD/POST/GET etc. But I belive its faster for most of the cases (or even all of them). I belive @sksamuel can correct me if im wrong.

**Comment by sksamuel** [comment]
Always faster because doesn't have to parse the json. And if you use a node
client you save 1 hop everytime.

**Comment by sdiwu** [comment]
Thank you for the explanation.

Is `ElasticClient.local` equal to node client and `ElasticClient.remote` is equal to transport client?

**Comment by sksamuel** [comment]
No, local is a node client which is local only, remote is transport, if you
want a non-local node, you must configure it and call ElasticClient.fromNode
