### ISSUE TITLE
Allow an option to refresh bulk op in streaming subscriber

### ISSUE THREAD

**Issue by rauanmaemirov** [sksamuel/elastic4s#413]
Currently, subscriber creates bulk op directly from array buffer and then executes it, there's no way to change bulk op config.

I have a use case for bulk indexing documents in one stream, and then reading it almost instantly in another sub-stream. Unless I change auto-refresh config on the elastic server-side, substream won't see all the updates.

**Comment by sksamuel** [comment]
Voila 26f7082b8a14a9623e14fc734ad1fd60bd1d277a

**Comment by rauanmaemirov** [comment]
Checked, seems to be working. :+1:

**Comment by sksamuel** [comment]
Cool

**Comment by rauanmaemirov** [comment]
When explicitly setting `refresh_interval` to `-1` in my index settings, afterRefreshOp doesn't refresh index every time, i.e. not all the items are present in index. (my ResponseListener and errorFn are silent)

Is it something concerning elasticsearch itself?

**Comment by sksamuel** [comment]
Can you PR a unit test that shows this behaviour ?

**Comment by rauanmaemirov** [comment]
I'd love to! But how can I reproduce backend behaviour with `refresh_interval`?
Could you give me some guide where to start?

**Comment by sksamuel** [comment]
You're seeing some issue in your prod code so just write a small contained example that does the same thing, and the error should be there right?

**Comment by rauanmaemirov** [comment]
Nope, that's the thing. There are no errors, just elastic index not showing valid count of docs without manually doing refresh request (with curl).

Let me check everything carefully and I'll get back with some definite answer.

**Comment by rauanmaemirov** [comment]
I'm not sure yet, but I think I found the issue.
Could you take a look at this line? https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/bulk.scala#L37

Even though BulkDefinition already has a BulkRequest, you're creating a new one anyway and _adding only the requests_ with no options (including refresh flag).

The fix should be pretty simple, but I'm not confident in my scala skills. Can I try submitting a PR? Want to start participating in development. :)

**Comment by sksamuel** [comment]
I think you're spot on. And the other Executable above it too. So yeah a PR
is welcome :)

**Comment by rauanmaemirov** [comment]
Which branch should I patch? master or release/1.7.x?

**Comment by sksamuel** [comment]
Both :) Do 1.7.x and then I will cherry-pick it onto master.
