### ISSUE TITLE
Strange behaviour during search

### ISSUE THREAD

**Issue by salceson** [sksamuel/elastic4s#415]
Hi,

I'm trying to execute a quite simple search using elastic4s.

I have an Elastic Search instance (1.7.1) running locally (on 127.0.0.1) on default ports (9200 for HTTP, 9300 for TCP).

I'm using elastic4s v. 1.7.1.

I'm creating the client like this:
```scala
val client = ElasticClient.remote("127.0.0.1", 9300)
```

then I'm executing the search like this:
```scala
client.execute { val q = search in "profiles" / "management" query {
    bool {
      must(
        matchQuery("question.intervention.name", s"${intervention.getOrElse("")}*"),
        matchQuery("question.comparison.name", s"${comparison.getOrElse("")}*"),
        matchQuery("question.healthProblemOrPopulation.name",
            s"${healthProblemOrPopulation.getOrElse("")}*")
      )
    }
  }
  println(q.show)
  q
}
```

The values `intervention`, `comparison`, `helathProblemOrPopulation` are `Option[String]`.

The query does match my expectation (doing the `println(q.show)` displays:
```
{
  "query" : {
    "bool" : {
      "must" : [ {
        "match" : {
          "question.intervention.name" : {
            "query" : "medicine*",
            "type" : "boolean"
          }
        }
      }, {
        "match" : {
          "question.comparison.name" : {
            "query" : "medicine*",
            "type" : "boolean"
          }
        }
      }, {
        "match" : {
          "question.healthProblemOrPopulation.name" : {
            "query" : "*",
            "type" : "boolean"
          }
        }
      } ]
    }
  }
}
```

The problem is that when I run this query using the elastic4s (so the TCP client), I have 0 hits while running the same query with the REST client gives me 1 hit (which is correct as there is one document that does match the conditions above).

Why the elastic4s can't find any documents? (There is no exception, just there are no hits).

**Comment by sksamuel** [comment]
What do you think the * is doing? Are you trying to use that as a wildcard?

**Comment by salceson** [comment]
Yes, I think that I was trying to do this as a wildcard. It seems that I don't really understand this. The wildcards are only permitted in a wildcard query?

**Comment by sksamuel** [comment]
Yes, or you can do a prefix query which is equivalent to what you're doing
here. But they're slower than normal queries.

**Comment by salceson** [comment]
Ok, thanks for the advice. Though I still don't understand why the REST API did behave differently.

Prefix query is indeed working like a charm.

**Comment by sksamuel** [comment]
I don't know the REST api myself, so it might be more forgiving on special
characters.

**Comment by salceson** [comment]
Never mind, it does not relate with this library. Thanks for answers. :+1:
