### ISSUE TITLE
Deadletter encountered when calling onComplete()

### ISSUE THREAD

**Issue by sjoerdmulder** [sksamuel/elastic4s#420]
When i'm done with processing a logfile to elasticsearch using reactive streams i want to graceful shutdown the system so i call `onComplete` and after that system.shutdown() but somehow i see dead letter messages. This happens after the `completionFn` of the subscriber is called.

```
Message [com.sksamuel.elastic4s.streams.BulkActor$ForceIndexing$]
from Actor[akka://log2es/user/$a#1002928747] 
to Actor[akka://log2es/user/$a#1002928747] was not delivered.
[1] dead letters encountered.```

**Comment by sksamuel** [comment]
It's because when you shut down the actor with onComplete other messages might still be sent later. There's no way in an actor system to do "is the actor still alive".

**Comment by sjoerdmulder** [comment]
Yes i understand that :)

Maybe the Actor can already `cancel` the `flushInterval` in the `BulkActor.Completed` case? Since the actor itself is in a kind of "shutting down" phase. So it would't make sense to have the `ForceIndexing` message delivered after a `Completed` message

**Comment by sksamuel** [comment]
Yes that makes sense. It won't stop all dead letters, as there's always the
chance some messages come back after the actor has died, but that will help.
