### ISSUE TITLE
Indices Stats and Clear Indices with ambiguous implicit

### ISSUE THREAD

**Issue by luismfonseca** [sksamuel/elastic4s#424]
I can't run the following code:
`esClient.execute(index stats(indexName))`

Error:
```
ambiguous implicit values:
[error]  both object IndicesStatsDefinitionExecutable in trait IndexAdminDsl of type com.sksamuel.elastic4s.ElasticDsl.IndicesStatsDefinitionExecutable.type
[error]  and object ClearIndicesCacheResponseExecutable in trait IndexAdminDsl of type com.sksamuel.elastic4s.ElasticDsl.ClearIndicesCacheResponseExecutable.type
[error]  match expected type com.sksamuel.elastic4s.Executable[com.sksamuel.elastic4s.admin.IndicesStatsDefinition,R,Q]
```

I think the line `com/sksamuel/elastic4s/admin/IndexAdminDsl.scala:56` is using `IndicesStatsDefinition` where it should be using something like `ClearIndiciesDefinition` to avoid this confusion.

If you believe this might be the fix the problem, I can make a pull request.

**Comment by sksamuel** [comment]
Yes sounds right.
