### ISSUE TITLE
Version 1.7.2 seems to be missing features

### ISSUE THREAD

**Issue by andrestc** [sksamuel/elastic4s#428]
Hi,

I've downloaded version 1.7.2 from maven repository but its seems to be outdated; some features that were in version 1.7.1 seem to be missing, e.g, this [change](https://github.com/sksamuel/elastic4s/commit/b29e66569c72797ad077aad3ca1cc3708bedc270) and this [change] (https://github.com/sksamuel/elastic4s/commit/58c01f3934224741f817ba262690343cb1165b78).

Those are still in master. Maybe there were some problem when generating the version.

**Comment by sksamuel** [comment]
Prob weren't copied across to master by me before release. I'll add those
two in, any others you're missing?

**Comment by andrestc** [comment]
I've came across those two, only.

Thanks!

**Comment by andrestc** [comment]
Strange thing is that they were in release 1.7.1.

**Comment by rauanmaemirov** [comment]
#368 and #401.
I was just going to report on 368, but noticed it had already been fixed earlier.

**Comment by sksamuel** [comment]
1.7.3 is going up to maven now.

**Comment by sksamuel** [comment]
1.7.3 is released
