### ISSUE TITLE
Validation of mapping parameters

### ISSUE THREAD

**Issue by andrestc** [sksamuel/elastic4s#430]
Currently, I can define the following field mapping:

``` scala
"tags" typed CompletionType analyzer "standard"
```

Since [CompletionFieldDefinition](https://github.com/sksamuel/elastic4s/blob/952fe4dea4001bee700873b459357e35a5d15d6b/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/mappings/fields.scala#L480) doesn't inherit from AttributeAnalyzer, that attribute will be ignored when generating the mapping.

I see two issues here (I can separate them into 2 different issues in github, but wanted to create this for discussion):
1. I believe we could do some kind of validation and warn the user when it tries to set an unsupported parameters. I can work on this, but would like to discuss the best approach.
2. I opened an [issue on elasticsearch](https://github.com/elastic/elasticsearch/issues/13584) because although its not documented, I was able to create an completion type using the "analyzer" parameter. So if it is indeed supported, we should add this to CompletionFieldDefinition. I can work on this once its confirmed.

**Comment by andrestc** [comment]
As mentioned in the issue and stated in [2.0 docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-suggesters-completion.html) "index_analyzer" is deprecated so we should deprecate these and use only "search_analyzer" and "analyzer".

**Comment by sksamuel** [comment]
The deprecation can be added very quickly.

**Comment by sksamuel** [comment]
Where does it say index_analyzer is deprecated btw ?

**Comment by andrestc** [comment]
Yea, I [mentioned in my elasticsearch](https://github.com/elastic/elasticsearch/issues/13584#issuecomment-140496185) issue that they missed it in 1.7 docs. But in 2.0 docs you can see that [index_analyzers are not there anymore](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-suggesters-completion.html). And  its not on [mapping parameters docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-params.html) anymore.

**Comment by sksamuel** [comment]
I see yes.

**Comment by sksamuel** [comment]
Might be worth making a new issue to track that.

**Comment by sksamuel** [comment]
I've updated 2.0 upgrade guide to explain this too as the deprecation will come too late for a lot of people.

**Comment by andrestc** [comment]
Okay, i created an issue for the removal of ```indexAnalyzer``` for the 2.0 release.

What do you think about the validation of the mapping params, mentioned in this issue? Any idea on how can we tackle this?

**Comment by sksamuel** [comment]
TBH I don't understand what you mean about the mapping params being invalid.

**Comment by andrestc** [comment]
Let me try to elaborate again (im still using the analyzer example although its not a valid example since indexAnalyzer is deprecated):

Defining the following mapping compiles fine:

```scala
"tags" typed CompletionType analyzer "standard"
```

But, when building the request, the ```analyzer "standard"``` part gets completely ignored because the ```CompletionFieldDefinition``` doesnt inherit from ```AttributeAnalyzer``` and doesnt call ```    super[AttributeAnalyzer].insert(source)```.

Maybe we could do better and instead of ignoring those parameters we could fail in compile time or warn the user.

**Comment by sksamuel** [comment]
Ok so you're just talking about this competition field, rather than in
general?

**Comment by andrestc** [comment]
In general, actually. For example, unless im missing something (can't run the following example now):

```scala
 "attach" typed AttachmentType analyzer "standard"
```

Would also ignore the ```analyzer "standard"```, since it only does ```super[AttributeFields].insert(source)```

**Comment by sksamuel** [comment]
Ok, these seem like bugs rather than anything else ?

**Comment by andrestc** [comment]
Kind of. [Attachment type](https://github.com/elastic/elasticsearch-mapper-attachments) indeed doesn't support the ``analyzer`` parameter. IMO the main problem is ignoring an invalid mapping parameter instead of failing in compile time or warning the user.

**Comment by sksamuel** [comment]
We should just update our types to not include the method if elasticsearch
doesn't support it, then there's no way a user can call that method. I
think its just a symptom of it trying to be too generic, and we just need
to make it less generic.

**Comment by andrestc** [comment]
I agree, ill try drafting something for this.

**Comment by sksamuel** [comment]
If you still want to work on this we can add something for 2.1
