### ISSUE TITLE
filtered query filter gets translated to post_filter

### ISSUE THREAD

**Issue by jaksky** [sksamuel/elastic4s#442]
Folowing dsl search spec. gets translated incorrectly.
` search in storage_folder searchType SearchType.Count query filteredQuery query(matchPhraseQuery("adresa.mesto", mesto)) filter(
        bool(
          must(termFilter("active",true))
          must(termFilter("duplicitniNemovitosti.primary",true))
        )
        )aggregations( ...)`

Gets translated incorrectly to post_filter

`{
  "query" : {
    "match" : {
      "adresa.mesto" : {
        "query" : "Litomyšl",
        "type" : "phrase"
      }
    }
  },
  "post_filter" : {
    "bool" : {
      "must" : [ {
        "term" : {
          "active" : "true"
        }
      }, {
        "term" : {
          "duplicitniNemovitosti.primary" : "true"
        }
      } ]
    }
  }, .... `

Expected output should be as follows>

`{
    "query": {
        "filtered": {
           "query": {
           "match_phrase": {
              "adresa.mesto": "Litomyšl"
           }
           },
           "filter": {
               "bool" : {
                   "must" : [{
                       "term": {
                            "active": {"value": "true"}
                        }
                   },{
                       "term": {
                            "duplicitniNemovitosti.primary": {"value": "true"}
                        }
                   }
                   ]
               }
           }
        }
    }, .... `

**Comment by sksamuel** [comment]
I think the 2nd query is being added to the search object, if you try putting parens around the filteredQuery definition it should work.
