### ISSUE TITLE
use elasticsearch 1.7.2 instead of 1.7.1

### ISSUE THREAD

**Issue by sonenko** [sksamuel/elastic4s#448]
according to release notes of elasticsearch 1.7.2, in previous version was not shadowed joda-convert. original issue is here https://github.com/elastic/elasticsearch/issues/13356
On our project it was not possible to assemble, because other libraries also used joda-convert.

Workaround - include elasticsearch 1.7.2 to your project.

**Comment by sksamuel** [comment]
Thanks for report.
