### ISSUE TITLE
Range queries with elastic4s

### ISSUE THREAD

**Issue by ganeshvasudevan** [sksamuel/elastic4s#450]
Hi,

I was trying to do a range query as explained in the elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-range-query.html

The issue is that I dont find a matching DSL in the elastic4s. So my question is how to do date range search in elastic4s?

Should the way forward is to use raw query? I tried with raw query for the date range search and it seems to work but combining that with other query and creating a json dynamically doesnt looks the straightforward way to get it working.

Any help on this issue is greatly appreciated.

thanks and regards
Ganesh

**Comment by MLnick** [comment]
You can do a range query or range filter using the DSL:

```scala
object RangeQuery extends App {
  import com.sksamuel.elastic4s.ElasticDsl._
  import com.sksamuel.elastic4s.ElasticClient
  
 val esClient = ElasticClient.local

  // range query
  esClient.execute {
    search in "index" / "type" query {
      rangeQuery("field") from "now-30d" to "now"
    } 
  }

  // range filter
  esClient.execute {
    search in "index" / "type" query {
      filteredQuery query {
        matchall
      } filter {
        rangeFilter("field") from "now-30d" to "now"
      }
    }
  }

}
```

**Comment by ganeshvasudevan** [comment]
Hi,

Thanks a lot, it works as expected.
I will close the issue.

thanks and regards
Ganesh

**Comment by budzynski** [comment]
It seems like it is broken in the new version 2.1.1 though - I had to use rawQuery.

**Comment by sksamuel** [comment]
Do you have a test case I can use to see what's happening?

**Comment by budzynski** [comment]
Sorry, I thought it was not working but after reading some elastic documentation I finally made it work - it just took me a while to figure out the proper construction. Maybe it was a confusing transition from 1.x APIs. Thanks for your response though.

For all who are looking for some reference - here is how to apply a range filter on time and term filter on symbol value with v. 2.1.1:
> search(name) types(name) fields(
> "symbol", "bid", "time" ) size(10000) query(
> filter( rangeQuery("time") gte(start) lte(end), termQuery("symbol", symbol) ) )
