### ISSUE TITLE
add backpressure on indexing

### ISSUE THREAD

**Issue by clescot** [sksamuel/elastic4s#453]
Hi,
like elastic4s has got a reactive stream implementation, is there any feature which permit to have a backpressure on consumer in case of elasticsearch bulk indexing?
i use elastic4s to stream from kafka to ElasticSearch, and i've got some errors if my import is too fast.
Some rejections in bulk response would be used to backpressure the kafka import, like advised on the elasticsearch documentation:
https://www.elastic.co/guide/en/elasticsearch/guide/current/_monitoring_individual_nodes.html#_threadpool_section

best regards,

Charles.

**Comment by sksamuel** [comment]
This is a really good and needed feature. I will include this in 2.0 release.
