### ISSUE TITLE
Histograms support for minDocCount

### ISSUE THREAD

**Issue by ddispaltro** [sksamuel/elastic4s#454]
Can we add histograms support for min_doc_count? I see it's present for terms aggregation.

Thanks for the library!

**Comment by MLnick** [comment]
@ddispaltro I took a quick look and this is a fairly simple PR - I have something just about ready. @sksamuel master is not compiling - is it broken? If so which branch should I PR against?

**Comment by sksamuel** [comment]
Master is for 2.0 work. you can still put it there if u want or 1.7 branch

**Comment by MLnick** [comment]
Ok will use 1.7



—

**Comment by MLnick** [comment]
@ddispaltro can close this per #455

**Comment by ddispaltro** [comment]
thanks
