### ISSUE TITLE
Patricio Gorin

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#458]
I have one question. I couldn't found any wrapper in order to delete a cache filter entry. I'm using a terms lookup filtering specifying a cache key as in this example:

```json
curl -XGET localhost:9200/tweets/_search -d '{
  "query" : {
    "filtered" : {
      "filter" : {
        "terms" : {
          "user" : {
            "index" : "users",
            "type" : "user",
            "id" : "2",
            "path" : "followers"
          },
          "_cache_key" : "user_2_friends"
        }
      }
    }
  }
}
```
(I'm using declaring the cache key using DefinitionAttributeCacheKey)

And it will be greatfull is there is a wrapper for the following action:
localhost:9200/tweets/_cache/clear?filter_keys=user_2_friends

I looked around in your code but only found cache index clearing, without cache key specification. Perhaps it is implemented but I didn't found it :(.

**Comment by pgorin** [comment]
Thanks!
