### ISSUE TITLE
how to upsert with parent id in bulk

### ISSUE THREAD

**Issue by JackWang917** [sksamuel/elastic4s#460]
My code as following:

var seqBulkDef = Seq[BulkCompatibleDefinition]()  
seqBulkDef = seqBulkDef:+request(sha256,parentId,indexMap,ES_INDEX,ES_INDEX_TYPE)
val resp = client.execute (bulk (seqBulkDef)).await(duration)

def request(sha: String, parentId: String, indexMap: Map): BulkCompatibleDefinition = {
  update(sha) in INDEX/INDEX_TYPE docAsUpsert indexMap parent parentId
}

The upsert works, but it seems the above code didn't recognize the parameter ParentId.
How should I modify the syntax please.

**Comment by sksamuel** [comment]
More details please.

**Comment by JackWang917** [comment]
Thanks Sksamuel, I modified my question with more details, I appreciate your kind help.

**Comment by JackWang917** [comment]
I seems there is a bug, it doesn't work with parentID

**Comment by sksamuel** [comment]
Does this work with the java client do you know ?

**Comment by sksamuel** [comment]
Should work in 5.0.0
