### ISSUE TITLE
Delete only a particular field and value

### ISSUE THREAD

**Issue by 208rishabh** [sksamuel/elastic4s#461]
Hi,

I want to delete only one particular field and value in elasticsearch using elastic4s library. However, all I see everywhere is different mechanisms to delete the whole document. Can anyone help? is this supported?

**Comment by sksamuel** [comment]
You can do an update setting it to null, or replace the document with another with the field removed.

**Comment by 208rishabh** [comment]
Will setting it to null remove the field? or will it just mean that the field has 0 or null as a value?

**Comment by sksamuel** [comment]
I'm not sure actually. But all the update api does is a delete and replace
on the entire document, it just saves a round trip.

**Comment by 208rishabh** [comment]
All right. I tried this:

client.execute {
      update(txId).in(indexName / typeOfIndex) docAsUpsert (
        "txAmount" -> null)
    }

it puts "null" as the value of txAmount.

**Comment by sksamuel** [comment]
This can do it "script" : "ctx._source.remove(\"name_of_field\")" }'
