### ISSUE TITLE
DSL cannot produce mappings for indexing the _id field

### ISSUE THREAD

**Issue by franckrasolo** [sksamuel/elastic4s#462]
In order to allow all documents to be sorted by `_id` by default, `_id` needs to be indexed as follows:
```
create index _index source
  """{
    |  "mappings": {
    |    "_default_": {
    |      "_id": { "index": "not_analyzed" }
    |    }
    |  }
    |}""".stripMargin
```
This approach works because it uses raw mappings.

I tried a pure DSL version:
```
create index _index mappings {
  "_default_" as (
    id typed StringType index NotAnalyzed,
    "metadata" typed NestedType
  )
}
```
however the resulting mappings end up wrapping the `"_id"` object inside a `"properties"` object, and therefore documents cannot be sorted by `_id`:
```
{
  "mappings": {
    "_default_": {
      "properties": {
        "_id": { "index": "not_analyzed" }
      }
    }
  }
}
```

What am I missing to produce the expected mappings?

**Comment by sksamuel** [comment]
We need to add support for this.

**Comment by sksamuel** [comment]
mapping("my_type") id IdField("not_analyzed") fields (...fields)
