### ISSUE TITLE
Completion suggestion result not including payload Suggetion Option case class

### ISSUE THREAD

**Issue by dileepbapat** [sksamuel/elastic4s#468]
I couldnt find an easy or ideal way to access play load from suggestion, 
calling  SuggestionEntry.options looses payload information from original backing java CompletionSuggetionEntry. Is this how expected? I had to access underlying java object and cast to get payload.

If you could give directions, I can implement it. (if its truly missing)

**Comment by sksamuel** [comment]
You have to cast, but I'm going to add some sugar for 2.1, unless you want to get in first.
See
https://github.com/sksamuel/elastic4s/issues/155
