### ISSUE TITLE
rangeQuery lte doesn't look correct

### ISSUE THREAD

**Issue by slydon-apixio** [sksamuel/elastic4s#470]
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/queries.scala#L1158

and

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/queries.scala#L1143

I'll just use the boolean flags for now.

**Comment by sksamuel** [comment]
Good post thanks.
