### ISSUE TITLE
"filter" in bool query

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#473]
Elasticsearch 2.0 has "filter" clause in bool query, however it is missing in elastic4s api.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by sksamuel** [comment]
Thanks.

**Comment by maxcom** [comment]
Please port this to 2.0 branch too. `filter` clause in bool query is needed to get away from deprecated `filteredQuery`:

```
  @deprecated("Use boolQuery instead with a must clause for the query and a filter clause for the filter", "2.0.0")
  def filteredQuery = new FilteredQueryDefinition
```

**Comment by sksamuel** [comment]
Yep

**Comment by maxcom** [comment]
Thanx. What is the preferred way to create bool query that has only "filter" clause? I found this way:

```
new BoolQueryDefinition().filter(termQuery("is_comment", "false"), termQuery("tag", tag))
```

**Comment by sksamuel** [comment]
Ah yes, that's an oversight. You can do it the way you suggested but I've just added filter(queries) too.
