### ISSUE TITLE
Signature of "termsQuery"

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#475]
Can't compile `termsQuery("tag", tags:_*)` any more because termsQuery signature was changed to `termsQuery(field: String, first: AnyRef, rest: AnyRef*)`.

**Comment by sksamuel** [comment]
I will backport this commit to 2.0.1 as well.

**Comment by rbordon** [comment]
This also happened to me when upgrade version **2.3.0** to **5.5.3**

Could you add a method like the old way?
