### ISSUE TITLE
Use HitAs[T] in get method

### ISSUE THREAD

**Issue by tpraizler** [sksamuel/elastic4s#477]
Is there a way to use as[MyClass] on a get query response?

Something like this:

```
 client.execute(get id id from indexName / documentType).
 map(result => result.as[MyClass])
```

I want to retrieve a specific document with its source, and convert it from a hit to MyClass.

**Comment by sksamuel** [comment]
This is missing at the moment, but I will add this as part of #472

**Comment by tprizler** [comment]
This is great. Thanks.
Is there a workaround at the moment?

**Comment by sksamuel** [comment]
You can take the source as a string and feed it into your choice of json
parser, that's what I do. There's jackson and json4s one available as a
elastic4s module.

**Comment by tprizler** [comment]
Cool, Thanks!

**Comment by kpashka** [comment]
+1

**Comment by sksamuel** [comment]
Supported in https://github.com/sksamuel/elastic4s/issues/601
