### ISSUE TITLE
Delete from index doesn't work using query.

### ISSUE THREAD

**Issue by tprizler** [sksamuel/elastic4s#478]
I am using elastic4s version 2.0.0.
Looks like is no implementation to delete from an index.

Base on the following : https://github.com/sksamuel/elastic4s/blob/master/guide/delete.md the code should compile, but it doesn't:
         
    client.execute(ElasticDsl.delete from "myIndex" / "myType" where "email:my@gmail.com")

But only id works:

    client.execute(ElasticDsl.delete id "30" from myIndex" / "myType")

Make sense?

**Comment by MLnick** [comment]
ES 2.0.0 removed delete by query- 


https://www.elastic.co/guide/en/elasticsearch/reference/1.6/docs-delete-by-query.html




—

**Comment by sksamuel** [comment]
I need to update the docs to reflect that.

**Comment by tprizler** [comment]
:+1: great!
