### ISSUE TITLE
UpdateResponse expose GetResult which is null

### ISSUE THREAD

**Issue by tprizler** [sksamuel/elastic4s#480]
Is there a way that UpdateResponse can provide the GetResult?
I am updating a document, and want to have the updated document back, is this possible?

**Comment by sksamuel** [comment]
You can specify the fields to return from your document when doing an update.

**Comment by tprizler** [comment]
Oh!

I used this:

     client.execute {
        update(id) in indexName / documentType source myData includeSource
     }

And it worked perfectly.
Thanks!

**Comment by sksamuel** [comment]
Yeah includesource brings back the _source field

**Comment by tprizler** [comment]
Thanks!
