### ISSUE TITLE
Merge fields and inner document fields, when updating a document.

### ISSUE THREAD

**Issue by tprizler** [sksamuel/elastic4s#483]
I have the following document in my index:

    {
        "id": 123,
        "name": "myName",
        "age": 12
        "data": {
            "field1": "value"
        }
    }

I want to update it with the following document:

    {
        "id": 123,
        "age": 11
        "data": {
            "field2": "value2"
        }
    }

And expect the result will be: 

    {
        "id": 123,
        "age": 11
        "data": {
            "field": "value"
            "field2": "value2"
        }
    }

I use the following code:

    client.execute {
        update(id) in indexName / documentType source person
      }

But it override my source.
Is there a way to merge the documents?

**Comment by sksamuel** [comment]
Set `doc` rather than `source` because source overrides _source, and _source is always the "source of record" in es.

**Comment by tprizler** [comment]
doc only have the following signatures:

       def doc(fields: (String, Any)*)
       def doc(iterable: Iterable[(String, Any)])
       def doc(map: Map[String, Any])
       def doc(source: DocumentSource)
       def doc(value: FieldValue)

While I want to update my own case class Person.
Do I have to implement the DocumentSource here? although I implemented Indexable[Person]
?

**Comment by tpraizler** [comment]
help??:(

**Comment by sksamuel** [comment]
You can't do it using indexables (addressed by the commit I just did).
In the meantime you could make a DocumentSource using the indexable:
`JsonDocumentSource(TIndexable.json(t))` where `TIndexable` is your implementation of `Indexable` and `t` is your instance.

**Comment by tpraizler** [comment]
Works! Thank you!:)

**Comment by an-tex** [comment]
Has that changed? source(..) in the UpdateDsl is now also calling setDoc on the builder, so doc(..) and source(..) in update behave the same way.
The effect is that I can ONLY do partial updates, but not e.g. removing a field.

**Comment by an-tex** [comment]
ok never mind, apparently the underlying java client doesn't support that. to e.g. remove a field you have to stick to the script approach https://github.com/sksamuel/elastic4s/issues/461
