### ISSUE TITLE
ClassCastException when using BulkIndexingSubscriber [elastic4s 2.1.0]

### ISSUE THREAD

**Issue by franbh** [sksamuel/elastic4s#484]
It seems there is a bug in BulkIndexingSubscriber (elastic4s 2.1.0). The actor expects bulk responses as BulkResult type. Nevertheless, with the current bulk execution, the responses are of BulkResponse type. 
If a BulkResponse is received, it will enter in the t: T case (due to type erasure) and will be stored in the buffer as it were a T object. Then if buffer.size == batchSize, the content of the buffer is mapped into a bulk request of T and therefore a java.lang.ClassCastException is thrown. 
On the other hand, if the specified batchSize is less than concurrentRequests, the actor will just not send any other batch (no BulkResult is received, so no request to upstream is done).

You can reproduce the exception by using batchSize=2 and concurrentRequests=2 (for example) in BulkIndexingSubscriberIntegrationTest. The other issue can be reproduced by using batchSize=5 and concurrentRequests=2.

A quick fix is to use BulkCompatibleDefinition instead of BulkDefinition, because the former produces Future[BulkResult].

The exception trace is the following:

Dec 03 15:50:41 : [ERROR] [12/03/2015 15:50:41.429] [iam-akka.actor.default-dispatcher-25] [akka://iam/user/$s] org.elasticsearch.action.bulk.BulkResponse cannot be cast to com.tecsisa.wr.domain.iam.dao.User
Dec 03 15:50:41 : java.lang.ClassCastException: org.elasticsearch.action.bulk.BulkResponse cannot be cast to com.tecsisa.wr.domain.iam.dao.User
Dec 03 15:50:41 : at com.tecsisa.wr.domain.iam.streams.digestion.ElasticRequestBuilders$ElasticRequestBuilder$.request(CassandraRequestBuilders.scala:172)
Dec 03 15:50:41 : at com.sksamuel.elastic4s.streams.BulkActor$$anonfun$2.apply(BulkIndexingSubscriber.scala:174)
Dec 03 15:50:41 : at com.sksamuel.elastic4s.streams.BulkActor$$anonfun$2.apply(BulkIndexingSubscriber.scala:174)
Dec 03 15:50:41 : at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
Dec 03 15:50:41 : at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
Dec 03 15:50:41 : at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
Dec 03 15:50:41 : at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
Dec 03 15:50:41 : at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
Dec 03 15:50:41 : at scala.collection.AbstractTraversable.map(Traversable.scala:104)
Dec 03 15:50:41 : at com.sksamuel.elastic4s.streams.BulkActor.com$sksamuel$elastic4s$streams$BulkActor$$index(BulkIndexingSubscriber.scala:174)
Dec 03 15:50:41 : at com.sksamuel.elastic4s.streams.BulkActor$$anonfun$receive$1.applyOrElse(BulkIndexingSubscriber.scala:143)
Dec 03 15:50:41 : at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
Dec 03 15:50:41 : at com.sksamuel.elastic4s.streams.BulkActor.aroundReceive(BulkIndexingSubscriber.scala:89)
Dec 03 15:50:41 : at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
Dec 03 15:50:41 : at akka.actor.ActorCell.invoke(ActorCell.scala:495)
Dec 03 15:50:41 : at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
Dec 03 15:50:41 : at akka.dispatch.Mailbox.run(Mailbox.scala:224)
Dec 03 15:50:41 : at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
Dec 03 15:50:41 : at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Dec 03 15:50:41 : at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Dec 03 15:50:41 : at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Dec 03 15:50:41 : at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by sksamuel** [comment]
Thanks, will release 2.0.2 and 2.1.1 with these fixes.

**Comment by lwolters** [comment]
Hi Steven,

Any information when to release the 2.1.1 release? We're currently in desperate need of above fix. Or do you also release snapshots releases on sonatype?

Thanks in advance,

Leonard

**Comment by sksamuel** [comment]
I'll do it now

**Comment by lwolters** [comment]
Steven,

Thanks. Really appreciated.

Leonard

**Comment by sksamuel** [comment]
Ok 2.1.1 is on maven central.
