### ISSUE TITLE
Sub aggregations structuring with metric aggregations

### ISSUE THREAD

**Issue by belerophon** [sksamuel/elastic4s#486]
Hi there,

Basically, I'm trying to group by two fields, and calculate a value. This `aggregation` object seems to work for me when searching directly on elasticsearch:

```
{  
   "aggregations":{  
      "field1_agg":{  
         "terms":{  
            "field":"field1"
         },
         "aggregations":{  
            "field2_agg":{  
               "terms":{  
                  "field":"field2"
               },
               "aggregations":{  
                  "agg_bucket":{  
                     "sum":{  
                        "field":"integer-field"
                     }
                  }
               }
            }
         }
      }
   }
}
```

I've been trying to write different versions of this using the elastic4s DSL, but I not having any success on correctly structuring the `Sum` inside another `aggregations` object on the last `terms`.

**Does the DSL support this?**

Thanks!!

**Comment by MLnick** [comment]
The following should work:

```scala
  client.execute {
    search in "index"/ "type" query matchall aggs (
      agg terms "field1_agg" field "field1" aggs (
        agg terms "field2_agg" field "field2" aggs (
          agg sum "agg_bucket" field "integer-field"
          )
        )
      )
  }
```

**Comment by belerophon** [comment]
Indeed!

Although I had already tried that, I was dynamically building the aggregations from a list of specifications, without success. Upon your comment, I realized I had a precedence problem when working that list using a `foldLeft`. 

That was it. `foldRight` works nicely :)

Thank you!
