### ISSUE TITLE
How can I use range aggregation with scripts

### ISSUE THREAD

**Issue by sndaergg** [sksamuel/elastic4s#487]
RangeAggregationDefinition has no script api like AvgAggregationDefinition
How I implement range aggregations like:
{
    "aggs" : {
        "price_ranges" : {
            "range" : {
                "script" : "doc['price'].value",
                "ranges" : [
                    { "to" : 50 },
                    { "from" : 50, "to" : 100 },
                    { "from" : 100 }
                ]
            }
        }
    }
}

**Comment by alexshadow007** [comment]
Fixed by #492
