### ISSUE TITLE
What is equivalent DSL in Elastic4s for Bool query's must_not?

### ISSUE THREAD

**Issue by sdiwu** [sksamuel/elastic4s#491]
What is equivalent DSL in Elastic4s for Bool query's `must_not`?
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

There is `not` DSL but I'm not sure if that's equivalent to `must_not`.

**Comment by sksamuel** [comment]
Yes it is, not is must_not in the bool query

**Comment by sdiwu** [comment]
Ok, thanks.
