### ISSUE TITLE
BulkIndexingSubscriber infinite loop

### ISSUE THREAD

**Issue by peterrosell** [sksamuel/elastic4s#494]
When using a subscriber to do indexing and the producer send two documents to index where the second document cause a failure due to non matching mapping I get an infinite loop.

The problem is that the send method is called when a Success response is returned from the execution, but it contains failures. Then the request is send again and it will failure and it continues to loop.

I'm not sure how to handle it. One idea is to throw an exception and cancel, just like a Failure. Made a pull request, #493, that does that. Merge it if it's a wanted behavior.

Snippet from https://github.com/sksamuel/elastic4s/blob/master/elastic4s-streams/src/main/scala/com/sksamuel/elastic4s/streams/BulkIndexingSubscriber.scala#L167

``` scala
    def send(req: BulkDefinition): Unit = {
      client.execute(req).onComplete {
        case Failure(e) => self ! e
        case Success(resp: BulkResult) if resp.hasFailures => send(req)
        case Success(resp: BulkResult) => self ! resp
      }
    }
```

**Comment by sksamuel** [comment]
I agree something needs to be done for this case. In your PR though if the request has failures, then we won't re-process the messages, which goes against the way ES recommend we add backpressure. See https://www.elastic.co/guide/en/elasticsearch/guide/current/_monitoring_individual_nodes.html#_threadpool_section. Perhaps we could have it fail after 5 unsuccessful attempts or something (configurable).

**Comment by peterrosell** [comment]
Now I understand why the ```send(req)``` is called again. It's done to handle the back pressure when the bulk queue is filled up. Maybe it's possible to distinguish between rejections, due to a full queue, and other fatal errors.
The bulk request is not performed in a transaction so those operations that are successful will be indexed in the first ```send(req)``` and they shall not be included in the repeated call.
ES provides a list of steps to handle back pressure from a full queue:

1. Pause the import thread for 3–5 seconds.
2. Extract the rejected actions from the bulk response, since it is probable that many of the actions were successful. The bulk response will tell you which succeeded and which were rejected.
3. Send a new bulk request with just the rejected actions.
4. Repeat from step 1 if rejections are encountered again.

I think it's a good idea to limit the number of failed attempts due to back pressure with a config.

How to handle the fatal error might be more up to suggestions. The simplest solution is to just throw an exception, like in my PR. Another idea is to provide a callback that get the list of failed operations and returns a boolean, that tells if an exception shall be thrown or not. If an exception isn't thrown the fatal operations are ignored and we continue to process the stream.

**Comment by sksamuel** [comment]
I'll add something that allows for customizable error handling via some function I think, like your last suggestion.
