### ISSUE TITLE
Question about filter with bool query : elastic4s : version 2.1.1

### ISSUE THREAD

**Issue by ganeshvasudevan** [sksamuel/elastic4s#495]
I write the query as below

val queryForDebugging = search in "items" query { 
bool {
      must (
                matchQuery("name", "tom")
              )
      filter (
                rangeQuery("date") from "now/d" to DateTime.now.plusYears(1),
                geoDistanceQuery("distance") distance ("50km") geohash (hash)
              )
        }
}

and generates
{
  "query" : {
    "bool" : {
      "filter" : [ {
        "range" : {
          "when" : {
            "from" : "now/d",
            "to" : "2016-12-27T08:21:04.373Z",
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }, {
        "geo_distance" : {
          "hash" : "ud9x901f",
          "distance" : "50km"
        }
      } ]
    }
  }
}

Why is the generated query missing the matchQuery for the name completely?

If I wrote the query like below,
'''
val queryForDebugging = search in "items" query { 
bool {
      must (
                matchQuery("name", "tom"),
               filter (
                     rangeQuery("date") from "now/d" to DateTime.now.plusYears(1),
                     geoDistanceQuery("distance") distance ("50km") geohash (hash)
              )
            )
        }
}'''

Then it seems to generate the query with the matchQuery included. 
What is wrong with the first query? Is that the correct way to write or is the 2nd query the right one.

Thanks and regards
Ganesh

**Comment by alexshadow007** [comment]
@ganeshvasudevan  You should rewrite your query to this:
```
val queryForDebugging = search in "items" query { 
  bool {
    must (
      matchQuery("name", "tom")
    ) filter (
      rangeQuery("date") from "now/d" to DateTime.now.plusYears(1),
      geoDistanceQuery("distance") distance ("50km") geohash (hash)
    )
  }
}
```

**Comment by ganeshvasudevan** [comment]
Thanks for the answer, the query that you proposed was the one I tried and complained not generating the correct query towards elastic. For some reason the generated query doesnt have the matchQuery for the name.

**Comment by alexshadow007** [comment]
I ran my query and got:
```
{
  "query" : {
    "bool" : {
      "must" : {
        "match" : {
          "name" : {
            "query" : "tom",
            "type" : "boolean"
          }
        }
      },
      "filter" : [ {
        "range" : {
          "date" : {
            "from" : "now/d",
            "to" : "2016-12-28T19:59:56.564Z",
            "include_lower" : true,
            "include_upper" : true
          }
        }
      }, {
        "geo_distance" : {
          "distance" : "ud9x901f",
          "distance" : "50km"
        }
      } ]
    }
  }
}
```

**Comment by ganeshvasudevan** [comment]
Thanks a zillion, after some investigation and fixing the query again I got it working.

thanks for the help.

_Ganesh
