### ISSUE TITLE
Client settings via elasticsearch URI

### ISSUE THREAD

**Issue by mariussoutier** [sksamuel/elastic4s#499]
It would be very convenient to allow setting certain cluster options via the elasticsearch URI, especially the cluster name is part of the connection string IMHO.

So it should be possible to specify the cluster name via the URI directly, e.g. `elasticsearch://localhost:9300?clusterName=MyCluster`.

**Comment by sksamuel** [comment]
Yes that's a great idea

**Comment by sksamuel** [comment]
Supported in 3.0.0 (pending).

**Comment by mariussoutier** [comment]
Thanks!
