### ISSUE TITLE
Class com.vividsolutions.jts.geom.GeometryFactory not found - continuing with a stub.

### ISSUE THREAD

**Issue by sjoerdmulder** [sksamuel/elastic4s#507]
Since upgrade from 1.7.4. to 1.7.5 i have this anyoying warnings in the build, how to fix it? I don't have any (or want any) dependency on vividsolutions

```
[WARNING] warning: Class com.vividsolutions.jts.geom.GeometryFactory not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Geometry not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: Class com.vividsolutions.jts.geom.Coordinate not found - continuing with a stub.
[WARNING] warning: there were three feature warnings; re-run with -feature for details
[WARNING] 10 warnings found
```

**Comment by sksamuel** [comment]
It's only on there as a test dependency. Are you building from source?

**Comment by sksamuel** [comment]
https://github.com/sksamuel/elastic4s/blob/release/1.7.x/project/Build.scala#L40

**Comment by sjoerdmulder** [comment]
No, that's the strange thing. It's a maven project with dependencies to test-kit as test and core / stream as normal dependencies.

**Comment by sksamuel** [comment]
That is very odd.

**Comment by sjoerdmulder** [comment]
But i do have this option enabled: http://davidb.github.io/scala-maven-plugin/add-source-mojo.html will why it's there ;)

**Comment by sksamuel** [comment]
lol there you are

**Comment by sjoerdmulder** [comment]
Well... testing it without that option doesn't make a difference, still seeing it

**Comment by sksamuel** [comment]
This doesn't happen in 2.0+ FYI so we could consider it closed?

**Comment by longcao** [comment]
I'm getting this in 1.7.6 now since the revert at https://github.com/sksamuel/elastic4s/commit/753650a8d73d2d4a63d7be6e33f27ef1b80a7763 to fix the build on Travis, it's puzzling since this is in the "test" scope and shouldn't be causing problems.

**Comment by longcao** [comment]
FWIW, adding the following dependency in project fixes the compile issue, albeit feels dirty:

`"com.vividsolutions" % "jts" % "1.13"`

**Comment by sksamuel** [comment]
What about if we add that with test scope?

**Comment by longcao** [comment]
With test scope, it still causes the same compiler error, with a clean
build between iterations

On Tuesday, February 16, 2016, Stephen Samuel <notifications@github.com>
wrote:

> What about if we add that with test scope?
>
> On 16 February 2016 at 21:40, Long Cao <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > FWIW, adding the following dependency in project fixes the compile issue,
> > albeit feels dirty:
> >
> > "com.vividsolutions" % "jts" % "1.13"
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sksamuel/elastic4s/issues/507#issuecomment-184884848
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sksamuel/elastic4s/issues/507#issuecomment-184942770>.
>


-- 
Long

**Comment by JD557** [comment]
This seems to be related with this issue: https://github.com/elastic/elasticsearch/issues/9891

**Comment by sksamuel** [comment]
This has gone away with 5.0.0

**Comment by jCalamari** [comment]
> This has gone away with 5.0.0

Not really, I've just encountered this issue while upgrading to 5.0.0..

**Comment by sksamuel** [comment]
I've seen it to now. Seems I closed the ticket too early. Are you seeing it when you try to build elastic4s from source, or just having elastic4s in your project is enough to trigger it? Either way, it's an issue with elasticsearch itself, so not much I can do unless they fix it.

**Comment by jCalamari** [comment]
@sksamuel 
elastic4s as compile time dependecy triggers the issue. Yeah, its a dependency on elastic search itself. I tried adding missing dependency myself with no luck..

**Comment by juanjovazquez** [comment]
Also suffering from this. As a workaround, adding the missing dependency works.

**Comment by aroberts** [comment]
+1 also hitting this with 5.1.2

**Comment by jCalamari** [comment]
@juanjovazquez  What dependency and version did you add?

**Comment by sksamuel** [comment]
I've added 1.13 to the latest elastic4s build. I'll release 5.1.4 with it now.

**Comment by jCalamari** [comment]
@sksamuel Thanks. This is one of the things which held me back with upgrading to 5.0..

**Comment by sksamuel** [comment]
It's because they have set all the dependencies to compile, which is a bit odd.
