### ISSUE TITLE
how to update/index data in Sync 

### ISSUE THREAD

**Issue by JackWang917** [sksamuel/elastic4s#508]
I know the following code will index the data in Async, but I do need a Sync way to make sure the data is successfully inserted and then return back, how can I make the API in Sync please.
`client.execute(index into ES_INDEX / ES_INDEX_TYPE id theKey fields yaraMap).await()`

Thanks a lot!

**Comment by sksamuel** [comment]
You can add refresh true to the insert request.

**Comment by JackWang917** [comment]
Will it be very slow? because refresh will refresh the Index, but I just wanna the WAL finished for sure then return back to client. Thanks a lot!

**Comment by sksamuel** [comment]
Yes slower. You could do a bulk request, and then the bulk response has a list of errors, telling if any of the requests failed to queue.

**Comment by alexshadow007** [comment]
@JackWang917 
https://www.elastic.co/guide/en/elasticsearch/reference/2.x/index-modules-translog.html
```
In fact, Elasticsearch will only report success of an index, delete, update, or bulk request to the client after the transaction log has been successfully fsynced and committed on the primary and on every allocated replica.
```

**Comment by JackWang917** [comment]
@alexshadow007 I doubt about "**on every allocated replica**" , for sync API consistency policy, there are three options: 1,quorum and all. if we set one or quorum, it will return success after one or a quorum number finish committed, right please? Thanks a lot!

**Comment by alexshadow007** [comment]
@JackWang917
With index write consistency policy you can control how many copies of the data need to be available in order for a write operation to be permissible. But index operation only returns after **all active shards** within the replication group have indexed the document.

**Comment by JackWang917** [comment]
@alexshadow007 Got it! And also the IndexReader need to be reopen for new docs visible.So that called Lucene NearRealTime, right please :)
