### ISSUE TITLE
feature request: remote client ready

### ISSUE THREAD

**Issue by MasseGuillaume** [sksamuel/elastic4s#509]
I have a `ElasticClient.remote(host, port)` somewhere in my code. I use docker compose to start a bunch of docker container at the same time. The remote client will not wait until the elasticsearch is available. Is it possible to change `ElasticClient.remote` to return `Future[Client]` when it's connected to the server?

**Comment by sksamuel** [comment]
The remote(host, port) creates a transport client that connects to the
server. There's no way to tell the java client to wait. We could add a
looped retry (with a max) that use a Future. You could also consider using
a node client, which will be fine waiting for the cluster to come up

**Comment by MasseGuillaume** [comment]
it's also weird that you dont get any exception until you try to execute a command.

**Comment by sksamuel** [comment]
There's nothing I can do here as the java client doesn't support the functionality you need.
