### ISSUE TITLE
1.7.x releases after 1.7.1 missing several commits

### ISSUE THREAD

**Issue by longcao** [sksamuel/elastic4s#510]
Hey there @sksamuel!

In my quest to figure out why synonym filters with more than one synonym field wasn't working for me (see: https://github.com/sksamuel/elastic4s/pull/372), I noticed in releases after `1.7.1` that elastic4s is missing several commits (18 in total):

Checking the commits not in `release/1.7.x` but in `1.7.1`, where things seemed to have diverged...
```
$ git log 1.7.1 --not release/1.7.x --pretty=oneline --no-merges
7ed547d84432ba843b2478eaaa99236224e9fb43 Release 1.7.1
342b2853c3abe381dfc40ec0787e35ab17decbdd Added term vector dsl test #376
49d06482199e0ad0efefa6f6f05ba0e9cf3a3619 Added term vector dsl #376
d7d85eb299126211ad43a173e8c304b712d857fd Updated term query to support collections
083289c2b9905965a0c978785f1748257e89f3b7 adding validation to token filter definition
b29e66569c72797ad077aad3ca1cc3708bedc270 Refactor: SynonymTokenFilter as case class
83f15773af83d3cd77055769deb5de23d5fc6afb Update README.md
b956dbc23f03d87d52394b574a9c5e740e3b14bf Update README.md
e84e190915b2bc9f4b3ec74dd31bf4f7d9b0bb15 Update README.md
07f15e1a66cdaae37585da518f167c7d8c032907 Fixes #378 - Converts scala collections to java collection in script params
58c01f3934224741f817ba262690343cb1165b78 Adding helper test method to block until a document has an specific version.
683a2d32ab80e09af9b29808a60c6c8eed66dc52 Update ElasticSearch to latest & greatest 1.7.1
e1d68734317c16996c176dcb77eb8468da4faa60 Show the bad value of the index/type for better feedback
9e77002d5e8bf52d19433b503d6b6641a7da315d Fixes #371 - Delegate the call to #templates(DynamicTemplateDefinition*)
8f5126dd8701713410c9afb6d103f230feabd854 bugfix: Proper creation of synonyms filter.
b56dcb726a8607dd390aeb7a3620f6b0ab51c277 Remove a trailing dash from index name
1011af5fd1e68521b65fe4cee96e65f981aeed88 Fixes #368 - Fix refresh index DSL
3b6db5e9af54408b2af0c9f99d8d53b69c6a7f61 Add an optional periodic forced bulk indexing to BulkIndexingSubscriber. This ensures that all elements are indexed, even if the last batch size is lower than batch size (important when the publisher will never complete.
```

I'm still using `1.7.4`/`1.7.5` for my client dependency and will obviously need one of the fixes here for the synonyms filter. I've checked and this condition (18 missing commits) is true for tags `1.7.3`, `1.7.4`, and `1.7.5`.

I'd be happy to submit a PR depending on how you want to handle this (perhaps a branch with these cherry-picked commits PRed to the `release/1.7.x` branch), but I'm not 100% sure what your branching or release workflow needs. If you'd prefer to handle this yourself and cut a new release that is cool with me too.

**Comment by sksamuel** [comment]
If you can do a PR to the release/1.7.x branch with the missing commits,
then I can do a 1.7.6 release.

**Comment by longcao** [comment]
@sksamuel I attempted a PR here: https://github.com/sksamuel/elastic4s/pull/511
