### ISSUE TITLE
bulk delete doesn't work in production

### ISSUE THREAD

**Issue by tpraizler** [sksamuel/elastic4s#517]
I am sorry for posting this here, but you are my only hope.
I have the following code:
   
     val deleteDefinitions = ids.map(id => DeleteByIdDefinition(indexName /    documentType, id))
    client.execute(bulk{deleteDefinitions})
      .map(r => {
        Logger.info(s"Delete response: $r")
        r.getItems.size
      })

This basically run a bulk delete. 
When I test it, with local in memory cluster is work perfectly, but from some reason in production is hang..! And I don't have any idea why..

When I switch to this code it works!:

     Futures.sequence(ids.map(id => 
           client.execute(ElasticDsl.delete(id) from indexName / documentType)
              .map(deleteResult => deleteResult.isFound)) 

Here it is just creating lots of futures instead of using one.
Can you think of any reason why this can happen?
Or maybe an Idea how to address this?

Thank you!

**Comment by sksamuel** [comment]
how many items are you deleting?

**Comment by tpraizler** [comment]
38

**Comment by sksamuel** [comment]
So not a lot

**Comment by sksamuel** [comment]
What do you mean by hang. Does the future never return? Or just returns with an error.

**Comment by tpraizler** [comment]
The future never return, which is very weird, because it is should take couple of millis.. I have a feeling like it is blocked from some reason.. no idea why..

I run on heroku, so my request is timing out after 30 seconds, can't execute it longer.

I added a timer to this future, while the future never return it doesn't get to the part the write the metric..:-|

This is my measure code for refference:

      def measureFuture[R](metric: String)(block: => Future[R]): Future[R] = {
         val t0 = System.nanoTime()
         val result = block.map( r => { 
             val t1 = System.nanoTime() //It never get to this section..
             measure(metric, t1 - t0)
            r 
         })
         result
     }

**Comment by sksamuel** [comment]
Does heroku still block ports ie no 9300 for TCP ?

**Comment by tpraizler** [comment]
I am running all my queries already using a transport client connected to port 9343 with elastic4s, So I guess not? :-|
Is there a difference between the port used in "regular" queries to bulk queries?

**Comment by sksamuel** [comment]
no its the same port, just sometimes people try using the client without
realizing its not HTTP based.

**Comment by tpraizler** [comment]
I see. so what do you suggest? maybe shield is fucking it up? is there a way to debug it? maybe for start see the last request sent by elasic4s to elasticsearch? something else? on elasticsearch side?

**Comment by sksamuel** [comment]
Try doing a bulk request with just one action at a time.

**Comment by tpraizler** [comment]
OK! I am back. 

I tried your interesting suggestion! I run the bulk api, with only one id to delete.
So this is the code:

    override def delete(ids: List[String]): Future[Long] = {
       Logger.info(s"About to delete: $ids")
       val deleteDefinitions = ids.map(id => DeleteByIdDefinition(indexName / documentType, id))
       client.execute(bulk{deleteDefinitions})
        .map(r => {
          Logger.info(s"Delete response: $r")
          r.getItems.size
        })
    }

I called this method with this code:

    myDao.delete(List(id))

This result in timeout again!!

What do you think?

**Comment by sksamuel** [comment]
What happens if you remove the logger.info and / or remove the
r.getItems.size calls

**Comment by tpraizler** [comment]
Meaning remove the mapping part?
Like this:

    override def delete(ids: List[String]): Future[Long] = {
         Logger.info(s"About to delete: $ids")
         val deleteDefinitions = ids.map(id => DeleteByIdDefinition(indexName /     documentType, id))
         client.execute(bulk{deleteDefinitions})
    }

Or leave it but don't call Logger and getItems?

**Comment by tpraizler** [comment]
So I removed the mapping and code looks like this:

    override def delete(ids: List[String]): Future[BulkResponse] = {
         Logger.info(s"About to delete: $ids")
         val deleteDefinitions = ids.map(id => DeleteByIdDefinition(indexName / documentType, id))
         client.execute(bulk{deleteDefinitions})
    }

And my api endpoint code looks like this:

    def deleteTest(id: String) = AsyncStack() { implicit request =>
        service.read(id, loggedIn).flatMap {
               case Some(entity) =>
                  service.delete(List(entity.id)).map {
                      case _ => {
                         Logger.error(s"finished bulk delete request for: ${entity.id}")
                         Ok
                      }
                  }
              case None => Future.successful(NotFound)
        } recover {
             case e@(_: IllegalArgumentException | _: IllegalStateException) =>     BadRequest(e.getMessage)
        }
     }

Still get timeout! what do you suggest?
Thanks a lot for your help!

**Comment by tpraizler** [comment]
@sksamuel Any idea? :-|

**Comment by sksamuel** [comment]
Try this:

override def delete(ids: List[String]): Future[BulkResponse] = {
     Logger.info(s"About to delete: $ids")
     val deleteDefinitions = ids.map(id => DeleteByIdDefinition(indexName / documentType, id))
     client.execute(bulk{deleteDefinitions}).map { resp =>
         Logger.info("I HAVE COMPLETED")
         resp
    }
}

And see if it prints out that message.

**Comment by tpraizler** [comment]
Tried it, the request timeout, and doesn't print this log message.
What do you think?

**Comment by tpraizler** [comment]
@sksamuel Do you have any other suggestions?

**Comment by sksamuel** [comment]
Not really :(

**Comment by tpraizler** [comment]
This is me with some more information and attempts, maybe you will have an idea. @sksamuel 

I tried again to run the bulk operation, now I did it locally giving it a 3 minutes timeout.
Plus did some thread dumps during the process was stuck.

So after less then 3 minutes I got the following exception:

     "main" #1 prio=5 os_prio=31 tid=0x00007f8d16001800 nid=0x1703 waiting on   condition [0x0000700000218000]
      java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000077091c9f0> (a scala.concurrent.impl.Promise$CompletionLatch)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:208)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)

While producing the stack trace I got this:


     "elasticsearch[Icarus][scheduler][T#1]" #13 daemon prio=5 os_prio=31 tid=0x00007f8d15273000 nid=0x5b03 waiting on condition [0x000070000185e000]
      java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0014d48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    "elasticsearch[Icarus][[timer]]" #11 daemon prio=5 os_prio=31 tid=0x00007f8d16216800 nid=0x5903 waiting on condition [0x000070000175b000]
       java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.elasticsearch.threadpool.ThreadPool$EstimatedTimeThread.run(ThreadPool.java:581)

And this: 

     "Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f8d1481e000 nid=0x3803 in Object.wait() [0x0000700000d3a000]
      java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0025d68> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0025d68> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

    "Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f8d15040000 nid=0x3603 in Object.wait() [0x0000700000c37000]
     java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c000c0b0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000006c000c0b0> (a java.lang.ref.Reference$Lock)

    "main" #1 prio=5 os_prio=31 tid=0x00007f8d16001800 nid=0x1703 waiting on condition [0x0000700000218000]
     java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000077091c9f0> (a scala.concurrent.impl.Promise$CompletionLatch)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:208)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)


The real difference between an execution of bulk to none bulk is those 2 lines:
In the Finalizer thread:
       
    - waiting on <0x00000006c0025d68> (a java.lang.ref.ReferenceQueue$Lock)

And in the Reference Handler thread:
 
    - waiting on <0x00000006c000c0b0> (a java.lang.ref.Reference$Lock)

Does it make sense? Any idea pops up? any thing I can try?
As you can see I really want to use the bulk api..:)

**Comment by sksamuel** [comment]
Can you make a stand alone example that fails - one that I can run. Change
whatever domain classes you need to, to protect internal code, but make
sure it has the same issues and I'll fix it for you

**Comment by tpraizler** [comment]
Thanks @sksamuel this will be great!
I created a simple example here : https://github.com/tpraizler/playground/tree/master/bulkOpStuckExample
There is sbt file with the dependency and a main class.
You just need to change the username, password and cluster id.

Thanks again!!

**Comment by sksamuel** [comment]
I'll get to this this weekend.

**Comment by tpraizler** [comment]
@sksamuel Hey! any news about that?

**Comment by tpraizler** [comment]
@sksamuel Did you find time to look at it?

**Comment by MadeInChina** [comment]
seems that you need refresh the index.

**Comment by tpraizler** [comment]
@MadeInChina how is refreshing the index is related to bulk operation?

**Comment by MadeInChina** [comment]
@tpraizler i remember that when i using embedded elastic search it must refresh then could works.
```
class StoreIndexRepositoryITest extends Specification with EmbeddedElasticsearch with Logs {
  sequential

  var storeIndexRepository: StoreIndexRepository = new StoreIndexRepository()

  implicit class RichFuture[T](future: Future[T]) {
    def await(implicit duration: Duration = Duration.create("10 seconds")) = Await.result(future, duration)
  }

  storeIndexRepository.client = elasticsearchClient
  step {
    elasticsearchServer.start()
    elasticsearchServer.createIndex("poi")
    elasticsearchClient.execute {
      put mapping "poi" / "st" as Seq(
        field name "storeId" typed StringType nullValue "",
        field name "tags" typed StringType nullValue "",
        field name "geo" withType GeoPointType
      )
    }

  }
  "ResourceIndexRepository" should {
    "return resource id test" in {
      val storeIndex = StoreIndex(storeId = "test", tags = Array[String]("tags1", "tags2"), geo = GeoIndex(30.548115, 104.068354), images = Nil)
      storeIndexRepository.client.execute {
        index into "poi/st" doc ObjectSource(storeIndex)
      }.await
      elasticsearchServer.refresh("poi")

      val storeIndexList = storeIndexRepository.client.execute {
        search in "poi/st" query matchall
      }.await.getHits.getHits().map(data => {
        data.sourceAsString().fromJsonString[StoreIndex]
      })
      storeIndexList(0).storeId shouldEqual "test"
    }
  }

  step {
    elasticsearchServer.stop()
  }

}
```

**Comment by tpraizler** [comment]
@MadeInChina Thanks for the example, but I don't see any bulk operation in it. 
@sksamuel sorry for nagging, but trying my luck again. any news on this? Am I missing anything?

**Comment by sksamuel** [comment]
@tpraizler looking now

**Comment by sksamuel** [comment]
@tpraizler can I remove the shield stuff ?

**Comment by sksamuel** [comment]
@tpraizler there's no delete operations in your standalone code. What I am testing here?

**Comment by tpraizler** [comment]
@sksamuel thanks for looking into it.
I am afraid the shield stuff is causing this, but lets try it without it. Because when running as part of an integration test, the bulk operation works, but in production it does not. but it may be something else.

In my code there is this line: 

`client.execute(reindex(firstIndex, secondIndex)).await`

This code underneath execute Bulk operation. which hangs.
My problem is that any Bulk operation hangs, no matter if it is a delete create or anything else.

**Comment by sksamuel** [comment]
All I can do is try it on my local machine, I don't have access to your
production obviously :)

**Comment by tpraizler** [comment]
Is it possible to load the local ES (integration test) with Shield?

**Comment by sksamuel** [comment]
I've never used shield

**Comment by tpraizler** [comment]
:(

I think that shield is a must in production environment, and if this is indeed the reason, more people will need it, sounds like a bug that need to be fixed.

Help me help you ( which will help me) :), tell me what to do. I need the bulk operation, soon I will have more traffic, and bulk operation is my only option!

Really appreciate your help.

But anyway, my example worked for you? if it did, then sounds like it's indeed shield.

**Comment by sksamuel** [comment]
Can you try this:

```scala
override def delete(ids: List[String]): Future[BulkResponse] = {
     Logger.info(s"About to delete: $ids")
     val fs = ids.map { id =>
        client.execute(bulk{DeleteByIdDefinition(indexName /  documentType, id)})
     }
     Future.sequence(fs)    
}
```
That will tell you if its the bulk operation or not as in the above you're just wrapping each single request in a bulk.

We don't use shield in prod, we protect it via a firewall.

**Comment by tpraizler** [comment]
Tried it - still hangs...:-|

We use here at our company, elastic cloud. To secure my access to it I must use shield.

**Comment by tpraizler** [comment]
@sksamuel Is it possible to load the local cluster with shield enabled, and test against it?

**Comment by sksamuel** [comment]
I don't have shield locally. Why don't you try it.

**Comment by tpraizler** [comment]
I don't know how to say it, but this was a configuration problem.
All I needed to do was to add this proeprty `("action.bulk.compress", false)` to the connection settings.

Hope this help the poor souls that read up to here.
@sksamuel Thanks fir your help and patience!

**Comment by sksamuel** [comment]
What was the outcome.

**Comment by tpraizler** [comment]
What do you mean? when added this property the bulk operation did not hang any more and got executed.

**Comment by sksamuel** [comment]
I see. Glad you got there in the end!
