### ISSUE TITLE
NIO or not when talking to Elastic.

### ISSUE THREAD

**Issue by dy8000** [sksamuel/elastic4s#521]
Does this project use TransportClient or Native interface , or HTTP to talk to Elastic?
More want to know if this library is blocking or NIO?

**Comment by sksamuel** [comment]
It is a native wrapper

**Comment by dy8000** [comment]
I am under the impression the native client can block. Cannot seem to find a definitive answer, may be your know.

**Comment by sksamuel** [comment]
You can block in the native client on tbe future but you can do that with
the scala client.
