### ISSUE TITLE
java.lang.IllegalStateException: path.home is not configured

### ISSUE THREAD

**Issue by TylerPachal** [sksamuel/elastic4s#523]
I am trying to connect to my cluster via: 
`val client = ElasticClient.local`

My Scala app running on Machine A, which has an `SSH` tunnel to Machine B, and the elasticsearch is on Machine B.

I tunnel from A to B via port `9000`, and then elastic search is accessed via the usual port `9200`.  What value should I use for my `path.home` ?

```
val settings = ImmutableSettings.settingsBuilder()
      .put("path.home", "???")
val client = ElasticClient.local(settings.build)
```

**Comment by sksamuel** [comment]
How are you creating the client?

**Comment by TylerPachal** [comment]
The error ended up being for mismatching versions (I have two different clusters, and I forgot to check to see that they were the same version).

Thanks!
