### ISSUE TITLE
Source filtering with get

### ISSUE THREAD

**Issue by alfonsovng** [sksamuel/elastic4s#526]
Maybe I wasn't able to find it, but I found this functionality with the search api, but not with the get. The source filtering is described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html

Thanks.

**Comment by alfonsovng** [comment]
Direct link: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#get-source-filtering

**Comment by alexshadow007** [comment]
@alfonsovng 
You can user method `fetchSourceContext`

For example
```
get id 1 from "index" fetchSourceContext false
```

**Comment by alfonsovng** [comment]
I didn't explain well. I was talking about _source_include & _source_exclude: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#get-source-filtering

**Comment by alexshadow007** [comment]
You can do it with this method
```
get id 1 from "index" fetchSourceContext new FetchSourceContext("field1", "field2")
```

**Comment by alfonsovng** [comment]
Ah, ok. I'll try. Thanks a lot. I'm going to close this.
