### ISSUE TITLE
How to load mapping from a String / Input stream / Json object?

### ISSUE THREAD

**Issue by vivri** [sksamuel/elastic4s#527]
Is there a way to load a mapping that's loaded from a String / Input stream / Json object (I'm using the Play Json lib) without duplicating it in the DSL and without resorting to an HTTP call?

**Comment by mai00cmi** [comment]
It used to be possible in version 1.4 with
```
      val mappingDefinition: PutMappingDefinition = put mapping indexName / typeName
      mappingDefinition._builder.setSource(mappingString)
```
but got removed in later versions.

**Comment by vivri** [comment]
thank you. that's too bad, though. i hope it'll come back in the future. what was the reason for it?

**Comment by sksamuel** [comment]
The method that was removed was removed by the underlying Java client.
