### ISSUE TITLE
Sorting is messed up when using pagination

### ISSUE THREAD

**Issue by sergioasantiago** [sksamuel/elastic4s#529]
Hi,

I m using elasticsearch 1.5 and elastic4s 1.7 (I tried with version 1.5.+ but I m getting the same error).

My test case I need to query my ES instance by page and sort the returned result. Everything works pretty good, until I introduce a new feature to my code. I m caching queries in Redis, so when I query for the first page, I got the results correct, but when I cache for the second page (using my query stored in Redis) the results are completely messy.

Here some code:
First page query:

```
{
  "from" : 0,
  "size" : 25,
  "query" : {
    "function_score" : {
      "query" : {
        "filtered" : {
          "query" : {
            "bool" : { }
          },
          "filter" : {
            "bool" : {
              "must" : {
                "nested" : {
                  "filter" : {
                    "exists" : {
                      "field" : "categories"
                    }
                  },
                  "path" : "categories"
                }
              }
            }
          }
        }
      },
      "functions" : [ ],
      "score_mode" : "sum"
    }
  },
  "sort" : [ {
    "purchase_links.sale_price" : {
      "order" : "asc"
    }
  } ]
}
```

Second page query:
```
{
  "from" : 25,
  "size" : 25,
  "query":{
    "function_score" : {
      "query" : {
        "filtered" : {
          "query" : {
            "bool" : { }
          },
          "filter" : {
            "bool" : {
              "must" : {
                "nested" : {
                  "filter" : {
                    "exists" : {
                      "field" : "categories"
                    }
                  },
                  "path" : "categories"
                }
              }
            }
          }
        }
      },
      "functions" : [ ],
      "score_mode" : "sum"
    }
  },
  "sort" : [ {
    "purchase_links.sale_price" : {
      "order" : "asc"
    }
  } ]
}
```

If I run both using curl, I got the results correctly. But when I try to use elastic4s I got the second page sorting wrong.

Scala code:

Storing my query in Redis.
```scala
private def sanitizedQuery(query: String) = {
    val regex = """\{[ ,\n]*"query"[ ]*:""".r
    regex.replaceFirstIn(query, "").trim.dropRight(1).trim
}

RedisAdapter.instance.set(uuid, sanitizedQuery(searchDefinition._builder.toString))
```
In this [stackoverflow link](http://stackoverflow.com/questions/31943172/how-to-serialize-elastic4s-queries-for-reuse) I explain how I save my query in Redis.

Recreating search definition from my cached query retrieve from Redis
```scala
// cachedQuery is the raw string retrieved from Redis exactly as it has been saved in the previous step
val searchDefinition = search.in(s"$indexName/$docType").rawQuery(cachedQuery)
```

How I run the final query
```scala
logger.debug(s"Query: ${searchDefinition._builder.toString}")
val searchResponse = ElasticSearchAdapter.client.execute(searchDefinition).await
```

How I build my products. The buildProduct function only retrieves the information from sourceMap field by field.
```scala
searchResponse.getHits.hits.foreach { h =>
        val product = buildProduct(h.getSource)
        product.setScore(h.getScore)
        products.add(product)
}
```

#### Opening questions:
- Does ```searchResponse.getHits.hits.foreach``` can be breaking my sorting? 
- Does ```search.in(s"$indexName/$docType").rawQuery(cachedQuery)``` can be caching something in elastic4s scope which makes my sorting in second page broken?

Please can you drive me how to figure out why it's happening?

**Comment by rennhak** [comment]
+1

**Comment by dmigous** [comment]
+1

**Comment by sksamuel** [comment]
Setting a raw query will not set the sort. It will just set the query part. So when you re-run it you're executing a non-sorted query.

**Comment by sergioasantiago** [comment]
So, is it a bug, or it's an expect behavior?

**Comment by sksamuel** [comment]
It just means you're not doing it right. The raw query is for the query-not-the-sort part.

**Comment by sksamuel** [comment]
Like when you re-make the query, you need to do,

val searchDefinition = search.in(s"$indexName/$docType").rawQuery(cachedQuery).sort(addsortagain)

**Comment by sergioasantiago** [comment]
:+1:  perfect, thank you very much for your answer. I ll give it a try soon, but I do believe that it's the solution.
