### ISSUE TITLE
This is probably a silly question but does this library not support remote connections via http REST API or am I missing something?

### ISSUE THREAD

**Issue by geekpete** [sksamuel/elastic4s#530]
Does this library support remote connections via http 9200 or only via tcp 9300?

**Comment by sksamuel** [comment]
The library is a wrapper around the Java client, which is TCP only. Elasticsearch don't provide a HTTP client. If you want a scala HTTP client then there is this: https://github.com/gphat/wabisabi but I've never used it so can't vouch for how good it is.

**Comment by geekpete** [comment]
Chers, thanks for the info.
