### ISSUE TITLE
elastic4s-testkit_2.11-2.2.0 artifact missing?

### ISSUE THREAD

**Issue by an-tex** [sksamuel/elastic4s#533]
Hi,
I've tried to update to 2.2.0 but the testkit_2.11-2.2.0 artifact seems to be missing in maven.

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22elastic4s-testkit_2.11%22

Cheers

**Comment by sksamuel** [comment]
Yes you're right. You can use the 2.2.1 release of testkit.
