### ISSUE TITLE
How to enable logging

### ISSUE THREAD

**Issue by TylerPachal** [sksamuel/elastic4s#538]
How do I enable logging for the library?

I took a look at the underlying Java library and tried adding:

```
import org.elasticsearch.common.logging.ESLoggerFactory

...

ESLoggerFactory.getRootLogger.setLevel("debug")
```

But that didn't seem to enable any logging.

**Comment by sksamuel** [comment]
Are you looking for logging from elastic4s or from the java client ?

**Comment by sksamuel** [comment]
This has changed in 5.0.0 anyway, so closing this.

**Comment by 123avi** [comment]
How can I enable logging from elastic4s (2.x and 5.x) ?
