### ISSUE TITLE
No search result with local client

### ISSUE THREAD

**Issue by ndelaforge** [sksamuel/elastic4s#544]
Hi,

I am experiencing issues with the search API on a local node since I updated my code from 1.7.5 to 2.2.1.

```
class BasicSearchTest extends FlatSpec with Matchers {

  val indexName = "gameofthrones"
  val docType = "characters"

  behavior of "BasicSearch"

  val settings: Settings = Settings.settingsBuilder.put("http.enabled", false).put("path.home", "./index").build
  val client: ElasticClient = ElasticClient.local(settings)

  it should "retrieve inserted documents" in {
    try {
      client.execute(deleteIndex(indexName)).await
    }
    finally {
      client.execute(create index indexName).await
    }

    client execute {
      index into indexName / docType id "1" fields(
        "name" -> "Jon Snow",
        "location" -> "The Wall"
        )
    } await

    client execute {
      index into indexName / docType id "2" fields(
        "name" -> "Eddard Stark",
        "location" -> "King's Landing"
        )
    } await

    val getResp = client execute {
      multiget(
        get id "1" from indexName / docType,
        get id "2" from indexName / docType
      )
    } await

    getResp.responses.length should === (2)

    val resp = client execute {
      search in indexName / docType
    } await

    println(resp)
  }
}
```

Output : 
```
RichSearchResponse({
  "took" : 22,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
})
```
The multiget works fine but the search query gives me no hit.
Any clue ?

**Comment by sksamuel** [comment]
The reason is that the inserts are not indexed by the time you run the search query. You need to put a delay in there as by default its 1 second before documents are available to be searched. Or you can put in a `refresh index` call. The multiget works because it doesn't go via the search indexes, but straight to the doc. I've no idea why it worked on 1.7.x as the behaviour has always been the same.

**Comment by ndelaforge** [comment]
OK, it works now. Thank you. :+1: 
I thought that awaiting for the server IndexResult would be enough to execute a search query.
I tried the same query with native Java API and it required no delay.
Why is it different ?

**Comment by sksamuel** [comment]
The java api should be exactly the same, as the scala code just calls the java code. So you must be doing something subtly different. When you wait on the index result, you're just waiting for an ack that the server got your index request.
https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html
