### ISSUE TITLE
MultiMatchQueryDefinition seems missing functionality

### ISSUE THREAD

**Issue by jacool** [sksamuel/elastic4s#545]
It seems MultiMatchQueryDefinition doesn't fully represent ElasticSearch functionality.
For example I indented to do this:
`multiMatchQuery(term).matchType(PHRASE).field(Field1, 2).field(Field2).slop(1)`
However could not find the option to set individual field boost and no option for slop.

Ended up doing this:

```
val multiMatch = multiMatchQuery(term).matchType(PHRASE).fields(Field1+"^2", Field2)
multiMatch.builder.slop(1)
```

**Comment by ericjohnston1989** [comment]
I believe this method of boosting using the carrot is what is used with the underlying elasticsearch builder as well. See:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html

A multimatch query is actually just a series of match queries wrapped in a boolean query. So if you want to set the boosts in a more elastic4s way you can do this and add boost/slop parameters in each clause.

**Comment by sksamuel** [comment]
In 5.0 I've added this method.
`def field(name: String, boost: Float)`
