### ISSUE TITLE
Missing "_field_names" in MappingDefinition

### ISSUE THREAD

**Issue by kutchar** [sksamuel/elastic4s#546]
Seems like "_field_names" is missing in MappingDefinition. See:

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-field-names-field.html

**Comment by sksamuel** [comment]
It always works using a standard terms query,

```
client.execute {
      search("space").query(termsQuery("_field_names", "name"))
    }
```

In 5.0 I've added a `fieldNamesQuery` helper.
