### ISSUE TITLE
How to authenticate url string with username and password

### ISSUE THREAD

**Issue by TylerPachal** [sksamuel/elastic4s#548]
My connection string looks like:

`elasticsearch://username:password@host:port`

But this is causing problems for the `ElasticsearchClientUri` which assumes that the connection string has one colon, and is of the form:

`hostname:port`

How can I pass my username and password along with the TCP connection?

**Comment by sksamuel** [comment]
Is this for shield?

**Comment by maziyarpanahi** [comment]
Hi @sksamuel,

I have the same question for Elasticsearch cluster behind Nginx which is accessible simply by: username:password@host:port

Many thanks.

**Comment by sksamuel** [comment]
HTTP or TCP

**Comment by maziyarpanahi** [comment]
It is HTTP

**Comment by sksamuel** [comment]
The library is TCP only (as its a wrapper of the Java library). For HTTP you'll need to roll your own to use another library.

**Comment by maziyarpanahi** [comment]
many thanks @sksamuel

**Comment by malcolmgreaves** [comment]
Hi! What about for TCP connections?
