### ISSUE TITLE
Sporadic NoNodeAvailableException related to version? 

### ISSUE THREAD

**Issue by backender** [sksamuel/elastic4s#550]
Hi all,

We are running an older Elasticsearch Server (Version 1.4.4). Our dependencies are: 

```
"com.sksamuel.elastic4s" %% "elastic4s-core" % "1.7.0",
"com.sksamuel.elastic4s" % "elastic4s-streams_2.11" % "1.7.1"
```

Now we are running into troubles by getting a `org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []` now and then. After trying everything imaginable I struggle with the idea that the elastic4s, or the underlying elasticsearch client may just not be compatible with our elasticsearch server for some tiny parts.

So my question would be: what is the version to use for our 1.4.4 server?

**Comment by sksamuel** [comment]
Use the 1.4.x versions. Generally speaking there's no guarantee of compatibility between 1.x versions in elasticsearch.
