### ISSUE TITLE
readme: "Using Elastic4s in your project" is missing

### ISSUE THREAD

**Issue by etaty** [sksamuel/elastic4s#551]
That's a little annoying when you just want to quickly copy-paste de deps

https://github.com/sksamuel/elastic4s/commit/7220e1888a58c24f5e400591c61d55723d12fb7a

**Comment by sksamuel** [comment]
There's links at top now taking you to maven central with latest version.

**Comment by etaty** [comment]
Oh I see, thanks. I using the same badge myself in rediscala haha.
I guess I have been educated to find the `dependencies +=` in the readme.

I still think you should keep the `dependencies` inside the readme, other projects are doing it that way.

Anyway, nice project
