### ISSUE TITLE
ElasticSugar ensureIndexExists function race condition

### ISSUE THREAD

**Issue by luismfonseca** [sksamuel/elastic4s#552]
This function checks if the index exists and then creates it if it doesn't. This is a race-condition: the index can be created in the time it takes between that check and the create index instruction.

I have some specs that do not work with this because for this reason (unless I force them to run sequentially).

This approach doesn't have this issue:
```
    client.execute {
      create index indexName
    }.recover {
      case _: IndexAlreadyExistsException => // Ok, ignore.
    }.await
```

I can make a MR if you agree with this changes :).

**Comment by sksamuel** [comment]
Yes please make the change, thank you.
