### ISSUE TITLE
ElasticCleint create too many connection to port 9300

### ISSUE THREAD

**Issue by ningjun** [sksamuel/elastic4s#553]
I have the following function to save a collection of documents to ElasticSearch. I have open and close connection to ES tcp port 9300 in this function.

Then fundtion is executed repeatedly by multiple threads. it create a lot of connections to port 9300 which are not close quickly (on Windows). I run the windows command "netstat -a" repeatedly and found the number of connections keep on increase increase from 300 to 11000 and finally windows throw exception.

What is wrong with this code? I do close the connection in finally method. Is there anyway to limit the maximum number of connection so windows will not fail?

def saveDocs(docs: Seq[Document]) = { 
 val esClient  = ElasticClient.remote(settings, "127.0.0.1", 9300)
 val bulkOps = docs.map(dv =>
        ElasticDsl.index into "myindex/mytype" id dv.id.toString fields(
          "id" -> dv.id,
          "isExample" -> false,
          "loadid" -> 30
          )
      ).toSeq
      val resp = client.execute {
        bulk(bulkOps)
      }.await(esReqWaitTime)
    }
    finally {
      client.close()
    }
}

**Comment by sksamuel** [comment]
Don't open a client per operation. That will be slow and have problems like
you experienced. Keep the connection open.
