### ISSUE TITLE
Remove custom re-index in favour of built in re-index

### ISSUE THREAD

**Issue by bkhadige** [sksamuel/elastic4s#556]
Hello,

I noticed a missing entry after a reindex on a single Elastic node using Elastic4s version 2.3.0

source index : "hits": { "total": 3034813, ...}
targetIndex index : "hits": { "total": 3034812, ...}

Code :
client.execute {
    reindex("ref", "ref-backup")
} 

Did i miss something ?

Regards,

**Comment by ajrnz** [comment]
I see the same thing:

    green open devicelog-2016-05-04  5 1 25000 0 17.3mb 8.5mb 
    green open devicelog-2016-05-04b 5 1 24998 0 17.6mb 8.8mb 
    green open devicelog-2016-05-04c 5 1 24998 0 18.2mb 8.9mb 
    green open devicelog-2016-05-04d 5 1 24988 0 17.6mb 8.8mb 

The b, c & d are all copies of the first. There are always a couple of records missing.

**Comment by sksamuel** [comment]
I can remove the reindex functionality anyway in favour of the one built into the latest versions of elasticsearch.
