### ISSUE TITLE
ExecutionContext / Executor

### ISSUE THREAD

**Issue by carymrobbins** [sksamuel/elastic4s#559]
Is it possible to specify an ExecutionContext or Executor for the `client.execute { .. }` calls, or something similar?  I'd like to limit the threads and work queue during indexing (or any task for that matter) with my own ThreadPoolExecutor (or ExecutionContext).

Does this need to be configured when you instantiate the client?

**Comment by sksamuel** [comment]
It doesn't use an ExecutionContext because the threading is all configured internally by the java Elasticsearch client that this wraps. The client is a node as well, so this page will help https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html

**Comment by ches** [comment]
This probably warrants some coverage in documentation now in the move toward HTTP client, there is [an Executor trait][1] with a `Future` implementation using the default global `ExecutionContext`, and instances for cats-effect `IO`, Monix and scalaz `Task` in the modules with their namesakes.

[1]: https://github.com/sksamuel/elastic4s/blob/022b56d01d37945ff6b697b33ec1567732aae33b/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/Executor.scala
