### ISSUE TITLE
can not execute multi-phrase match query using the DSL

### ISSUE THREAD

**Issue by minisaw** [sksamuel/elastic4s#560]
i have an elasticsearch index with a field key1 of type (string, index: analyzed).

imagine there are the following values:
doc1.key1 = "one two three"
doc2.key1 = "two three four"
doc3.key1 = "three four five"

the problem:
i can not issue a matchQuery("key1", "\\"one two three\\" \\"two three four\\"") that would find me doc1 and doc2, but not doc3.

this is due to that the field is analyzed (e.g. the word "three" matches all 3 values), and elastic4j does not seem to correctly forward the \" symbols that would otherwise instruct elasticsearch to perform a multi-phrase match, not just query match.

note that this is perfectly possible with a raw query with this exact JSON:

```
{  
   "query":{  
      "filtered":{  
         "query":{  
            "query_string":{  
               "query":"key1 = \"one two three\" \"two three four\""
            }
         }
      }
   }
}
```

**Comment by sksamuel** [comment]
So in this example, a query string is parsed into a multi phrase match or just a match depending on if it has quotes or not. When using the programmatic API you just choose to use whichever one you prefer, so `boolQuery().should(matchPhraseQuery("key1", "one two three"), matchPhraseQuery("key1", "two three four"))`

**Comment by sksamuel** [comment]
This test shows it in action.
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core-tests/src/test/scala/com/sksamuel/elastic4s/search/BoolQueryTest.scala#L60-L68
