### ISSUE TITLE
delete index / type

### ISSUE THREAD

**Issue by szymonwartak** [sksamuel/elastic4s#567]
Deleting an entire index is already possible but not deleting just one type in an index. 

http://stackoverflow.com/questions/23917327/delete-all-documents-from-index-type-without-deleting-type

**Comment by sksamuel** [comment]
Hi,

You can do this:

`delete(id).from(index / type)`

**Comment by adridadou** [comment]
I may not understand the issue correctly but your solution didn't work for me.
Here is what I've used (for ppl who might look for a solution):
deleteIn(indexAndType).by(matchAllQuery())
