### ISSUE TITLE
sourceExcludes in inner hits

### ISSUE THREAD

**Issue by ChetanBhasin** [sksamuel/elastic4s#571]
In ElasticSearch query DSL, you can do the following to limit the data returned in the inner hits.

```json
    "inner_hits" : {
        "size" : 5,
        "name" : "innerFields",
        "_source" : {
            "includes" : ["name"]
        }
      }
```

However, I have found no way in the driver to do this.

The best we can do is:

```scala
 query {
      nestedQuery("innerFields") inner {
        inner hits "innerFields" size 5
      }
  }
```

It would be nice to add sourceIncludes and sourceExcludes to inner hits.

**Comment by jacool** [comment]
This has been fixed by the pull request #575
