### ISSUE TITLE
Support better typing for index / types

### ISSUE THREAD

**Issue by matanster** [sksamuel/elastic4s#581]
We have this code in the library:

```
def into(indexType: IndexAndTypes): IndexDefinition = {
      require(indexType != null, "indexType must not be null or empty")
      new IndexDefinition(indexType.index, indexType.types.head)
}
```

I guess this is meant to avoid hitting elastic without specifying a type within the index. However clearly this is not accomplishing that intent. I've hit this by noticing that a type is missing through a downstream exception, which that `require` might have meant catching up-stream:

> .util.NoSuchElementException: head of empty list
>   at scala.collection.immutable.Nil$.head(List.scala:420)
>   at scala.collection.immutable.Nil$.head(List.scala:417)
>   at com.sksamuel.elastic4s.ElasticDsl$index$.into(ElasticDsl.scala:317)

Not 100% sure this is all correct, but I thought I would rather post it here. Otherwise not entirely sure why would the DSL allow this error to trickle down to elastic.

**Comment by sksamuel** [comment]
The require should probably just be updated to check for both an index and a type.

**Comment by matanster** [comment]
A thought ― would it not actually be preferable to change the function prototype to require an index type, rather than enforce the requirement at runtime?

**Comment by sksamuel** [comment]
Yes probably. But that IndexTypes is used everywhere now, with the implicits to convert from things like "index" / "type.

Personally, I would just urge you to use indexInto("index", "type") which is the alternative.

**Comment by sksamuel** [comment]
I've made a lot of changes around this for the next major release. I'm in two minds as to whether deprecate all magic implicit usage or not.

**Comment by sksamuel** [comment]
Bumping to 5.1 as I want to get 5.0.0 out ASAP and this requires some thinking.

**Comment by sksamuel** [comment]
Most of the requests now support `IndexAndType` or `IndexAndTypes` and other variations so you can use those rather than String implicits if desired.

**Comment by matanster** [comment]
Thanks, lost track of some details right now, but must be helpful!
