### ISSUE TITLE
DLS Match Query selecting subfields is not working

### ISSUE THREAD

**Issue by raman-mnit** [sksamuel/elastic4s#586]
I am trying to pull sub-fields from the search results.

val pcon = client.execute { search in "index_name" query matchQuery("ind.content", "Reglatory") sourceExclude("ind.content")}.await

It throws me the whole "ind".

If i use below way, still it is not working
val pcon = client.execute { search in "index_name" query matchQuery("ind.content", "Reglatory")}.await

pcon.getHits.getAt(0).getSource.get("ind.name")

My ind mapping is below
 ind: {
                    type: 'attachment',
                    fields: {
                      author: { store : true },
                      content_length: { store : true },
                      date: { store : true },
                      language: { store : true },
                      name: { store : true },
                      title: { store : true },
                      keywords: { store : true },
                      content_type: { store: true },
                      content: {
                        type: 'string',
                        analyzer: 'english',
                        term_vector: 'with_positions_offsets',
                        store: true
                      }
                    }
                  }

**Comment by sksamuel** [comment]
I've added a test that shows this working, so if its still not working for you, I'd try the latest version.
https://github.com/sksamuel/elastic4s/blob/25266432c76fbc76c725b6b5fee0710df255f006/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/MatchQueryTest.scala since it has been a while since this issue was opened.
