### ISSUE TITLE
Binary Request Yields Different Results

### ISSUE THREAD

**Issue by prahim** [sksamuel/elastic4s#598]
I am attempting to do a raw query: 
`elasticSearchClient.execute(search in index rawQuery(query)).await`
where query = 
`{
    "query": {
        "bool": {
            "should": [{
                "term": {
                    "associations.x”: “aaa”
                }
            }, {
                "term": {
                    “associations.x”: “bbb”
                }
            }, {
                "term": {
                    “associations.x”: “ccc”
                }
            }],
            "minimum_should_match": 1,
            "must": [{
                "match": {
                    “associations.x”: “bbb”
                }
            }, {
                "range": {
                    "json.created_at": {
                        "gte": 1438556519607,
                        "lte": 1468722842271
                    }
                }
            }, {
                "match": {
                    "json.parent_type": "field"
                }
            }]
        }
    },
    "size": 0,
    "aggs": {
        "activity": {
            "terms": {
                "field": "json.action_required"
            }
        }
    }
}`

But the result from elastic4s is different from executing the query manually. 

I did verify that the request going to elastic search is `{"query_binary":"<correct-base64-encoded-query>"}`

Is there something missing in my request?

**Comment by prahim** [comment]
Hi, just checking in on this issue... any feedback?

Thank you.

**Comment by sksamuel** [comment]
Can you try v5 with a wrapped query ?
