### ISSUE TITLE
ElasticSugar deleteOnExitHook doesn't work

### ISSUE THREAD

**Issue by ssemichev** [sksamuel/elastic4s#604]
The temporary directories are not deleted

sbt my-service/it:test

scala> System.getProperty("java.io.tmpdir")
res2: String = /var/folders/y5/lw613j_56sq4n_bkz4l9kr0r0000gn/T/

I can manually delete testNodeHomePath folder in afterAll method, but it seems it should work with existing deleteOnExitHook. Do you know why the hook doesn't work?

```
class IndexMatchersSpec extends UnitTestSpec with ElasticMatchers with ElasticSugar {
  val indexName = getClass.getSimpleName.toLowerCase

  behavior of "index matchers"

  it should "support index document count" in {
    indexName should haveCount(4)
    indexName should not(haveCount(11))
  }
}
```

Elasticsearch version:
2.3

JVM version:
1.8

OS version:
OSX 10.9.5

**Comment by sksamuel** [comment]
Is your process definitely ending?

**Comment by ssemichev** [comment]
Yes,

The command  `>sbt my-service/it:test` completed and the process should be ending

```
[info] All tests passed.
[info] Passed: Total 6, Failed 0, Errors 0, Passed 6
[success] Total time: 8 s, completed Jul 27, 2016 12:59:54 PM
```

**Comment by sksamuel** [comment]
Can you publish a small project that has the same symptoms?
