### ISSUE TITLE
Query timeout and retries

### ISSUE THREAD

**Issue by orpx** [sksamuel/elastic4s#605]
Hi there,
I am using the latest 2.3.0 elastic4s, In older versions I noticed there was a timeout property being passed when creating the ES client, How can I set a timeout and\or number of retries in the current version for delete by id?

Thanks,

**Comment by sksamuel** [comment]
When you wait on the future, you can set the timeout there.

**Comment by orpx** [comment]
That is right, thanks. 
Should I implement my own retry mechanism or have I missed some retry property along the way?

**Comment by sksamuel** [comment]
There's no retry directly in E4s or ES. It could be added if there was a universal approach but probably everyone wants something different?

**Comment by orpx** [comment]
I wasn't specific enough, I was talking about an internal retry_on_timeout property, it can be found in the python client for example - 
http://elasticsearch-py.readthedocs.io/en/master/index.html?highlight=retry_on_timeout

**Comment by sksamuel** [comment]
Looks like that's HTTP settings, max retries to connect to a node? Which
doesn't translate to the Java TCP client. What I can find in the Java API
is this
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/bulk/Retry.java
but wouldn't work with Scala futures. Might be worth adding a wrapper for
something like that.
