### ISSUE TITLE
Incompatible with Elasticsearch 2.3.2

### ISSUE THREAD

**Issue by pianista215** [sksamuel/elastic4s#606]
Using 2.3.0 from elastic4s: 

val settings = Settings.settingsBuilder() 
    .put("path.home", "/usr/share/elasticsearch/")

  private lazy val client = ElasticClient.local(settings.build)

Produces the next exception if you use Elasticsearch 2.3.2:

java.lang.IllegalArgumentException: Plugin [lang-expression] is incompatible with Elasticsearch [2.3.0]. Was designed for version [2.3.2]

```
at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:335)
at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:114)
at org.elasticsearch.node.Node.<init>(Node.java:158)
at org.elasticsearch.node.Node.<init>(Node.java:140)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:150)
at com.sksamuel.elastic4s.ElasticClient$.local(ElasticClient.scala:124)
```

**Comment by sksamuel** [comment]
What about 2.3.1 of e4s?

**Comment by pianista215** [comment]
Hehe, ok, I didn't see that 2.3.1 was available because the doc said that 2.3.0 is the latest. 
I'll give it a try tonight :)

**Comment by sksamuel** [comment]
It might be the same, but it's compiled against the latest version of elasticsearch

**Comment by stevebakh** [comment]
Sorry to resurrect this, but I have exactly the same problem. I'm using e4s 2.3.1 and es 2.3.5. 

```scala
val settings = Settings.settingsBuilder()
  .put("cluster.name", "cluster_name")
  .put("path.home", "/usr/local/opt/elasticsearch/libexec/").build

val client = ElasticClient.local(settings)
```

The only noteworthy thing about my stack is that I installed ES using homebrew on a mac.

**Comment by JD557** [comment]
That's odd... I'm also using e4s 2.3.1 and es 2.3.5, and I have no problem.

I never call `ElasticClient.local`, though (I only need a local client for unit tests, and I use the `ElasticSugar` trait for that, which also doesn't call `ElasticClient.local`). Maybe that's related?

**Comment by sksamuel** [comment]
I guess with 2.3.5, 2.4.0 and 5.0.0 this isn't an issue anymore.
