### ISSUE TITLE
http authentication in the elasticsearch uri

### ISSUE THREAD

**Issue by fadyZohdy** [sksamuel/elastic4s#609]
is there a way to add https authentication to the ElasticsearchClientUri without getting this error:
**Invalid uri, must be in format elasticsearch://host:port,host:port,...**
my connection uri looks like this: **"username:password@uri:port"**
i found out that you split the uri at " **:** " so i keep getting this error
is there any other way to add this kind of authentication ?
thanks in advance

**Comment by sksamuel** [comment]
The client is not a HTTP client.

**Comment by fadyZohdy** [comment]
thank you.
i guess i will have to look for another client

**Comment by sksamuel** [comment]
There's a couple out there 
https://github.com/gphat/wabisabi
https://github.com/bizreach/elastic-scala-httpclient

**Comment by marceloboeira** [comment]
For the purposes of documentation, since I could not find any examples on how to do that:
```scala
  lazy val provider = {
    val provider = new BasicCredentialsProvider
    val credentials = new UsernamePasswordCredentials("elastic", "changeme")
    provider.setCredentials(AuthScope.ANY, credentials)
    provider
  }
  val client = HttpClient(ElasticsearchClientUri("localhost", 9200), new RequestConfigCallback  {
    override def customizeRequestConfig(requestConfigBuilder: Builder) = {
      requestConfigBuilder
    }
  }, new HttpClientConfigCallback {
    override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder) = {
      httpClientBuilder.setDefaultCredentialsProvider(provider)
    }
  })
```

**Comment by missingfaktor** [comment]
> The client is not a HTTP client.

@sksamuel Apologies if I am missing something obvious, but I have run into the same problem. The client is in the `com.sksamuel.elastic4s.http` package, and is called `HttpClient`. What do you mean by it is not a HTTP client?

**Comment by sksamuel** [comment]
@missingfaktor this thread is from august 2016 when there was no http client.

**Comment by missingfaktor** [comment]
Okay. I am now using the HTTP client, but still running into this problem:

```
12:07:27.172 [ERROR] a.a.ActorSystemImpl - Error during processing of request: 'Invalid uri, must be in format elasticsearch://host:port,host:port?querystr'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
```

The URL I have is of the format `http://host:port`.

**Comment by sksamuel** [comment]
The error message tells you exactly why it's not working.

**Comment by missingfaktor** [comment]
Let me clarify my question: Why does the HTTP client expect a URI of format `elasticsearch://host:port`? Why not `http|https://host:port`?

**Comment by sksamuel** [comment]
Good question. Because the uri allows multiple host/ports, and http doesn't. It's to make it clear it's not the same thing as a http url.

**Comment by missingfaktor** [comment]
Okay, thanks.

**Comment by omrihq** [comment]
Is it possible to do this now without having to set-up apache configurations/credentials?
