### ISSUE TITLE
getSource / getSourceAsString : getting the raw _source ?

### ISSUE THREAD

**Issue by royrusso** [sksamuel/elastic4s#613]
Calling searchHit.getSource() or searchHit.getSourceAsString() return objects that don't look like the raw _source field in ES. Using 1.7x.

getsource:
There seems to be some casting when calling getSource, so Doubles are cast, but int/long are being cast as Object and quoted. 

getsourceasstring:
This seems to return the _source, still with int/longs quoted, yet doubles are kept as they are.

The _source looks like this on a URI GET:
`
inverter_input_pwr_hp_6117: 0,
load_pot_lim_1014: 14.2256,
fuel_rail_left_press_1370: 0,
tm3_trq_cmd_5007: 0,
trac_eff_fdbk_a2_5567: 0,
tmc_5_diag_1_7480: 10
`

![screen shot 2016-08-08 at 4 31 58 pm](https://cloud.githubusercontent.com/assets/654238/17495107/bf5d3420-5d85-11e6-9428-b0eb5db7074a.png)

![screen shot 2016-08-08 at 4 31 58 pm](https://cloud.githubusercontent.com/assets/654238/17495119/c7d36bce-5d85-11e6-8f41-8329cc0239cf.png)

**Comment by sksamuel** [comment]
Hi,

They're just pass through methods,

```
  def sourceRef: BytesReference = java.sourceRef()
  def source: Array[Byte] = if (java.source == null) Array.emptyByteArray else java.source
  def isSourceEmpty: Boolean = java.isSourceEmpty
  def sourceAsString: String = if (java.sourceAsString == null) "" else java.sourceAsString
  def sourceAsMap: Map[String, AnyRef] = if (java.sourceAsMap == null) Map.empty else java.sourceAsMap.asScala.toMap
```

Do you have an example project that shows the error?

**Comment by royrusso** [comment]
I dug in to the ES Java API code, and see that the issue stems from there. The ES discussion boards are also full of people with this problem, so I will close this issue. 

For anyone stumbling across this, I solved it by recasting the tuples to a Long. If they're already Doubles or can't be cast, they are preserved and added to the new Tuple.

`
try {
val another = item.copy(_2 = item._2.toString.toLong)
mmap += another
}
catch {
case e: NumberFormatException => None //println(e)
mmap += item
case f: Exception => None //println(f)
}
`

.. and damn this github formatting of code...
