### ISSUE TITLE
java.lang.OutOfMemoryError and bulk upserts

### ISSUE THREAD

**Issue by rcanzanese** [sksamuel/elastic4s#614]
I am using the bulk API for upserting a lot of documents, and receiving java.lang.OutOfMemoryError irrespective of my batch size.  For example, if I set my batch size to 1000, it fails around batch 35.  If I set my batch size to 100, it fails around batch 350.

The code in question loops over an indexed sequence of upsert commands: 

```
    upserts.grouped(commit_batch_size).foreach( batch => {
      client.execute {
        bulk(batch)
      }.await
    )}
```

Have I stumbled upon a bug here, or am I doing something incorrectly? 

elastic4s_2.10 1.7.6
elasticsearch 1.7.3
java 1.8.0_45

**Comment by sksamuel** [comment]
Is `upserts` some lazy sequence ?

**Comment by rcanzanese** [comment]
It is an IndexedSeq

**Comment by sksamuel** [comment]
I was wondering if by iterating over the seq you are doing some work that puts lots of objects into memory. Ie, do you have them all inflated before you begin iterating? Or take out the client.execute bit and make sure you can iterate over them creating the `bulk(batch)`es.

**Comment by rcanzanese** [comment]
Indeed, I am unable to iterate over them to create the `bulk(batch)`es -- I get the same `OutOfMemoryError`.

**Comment by sksamuel** [comment]
All `bulk` does is create instances of `BulkDefinition` which just wrap the requests adding each request to an instance of `BulkRequest` from the underlying elastic library. It's not doing anything special that would stop anything getting gc'ed.

**Comment by rcanzanese** [comment]
Hmm.  I get the same behavior if I just iterate over the sequence and do a `_.build` on each `IndexDefinition`.  I will spend some more time digging into this code to see if I can't better isolate the issue.

**Comment by sksamuel** [comment]
Ok sounds to me like you're just hitting general memory issues outside of e4s.

**Comment by rcanzanese** [comment]
Indeed.  I'll dig into this more and follow up when I can isolate the issue.

**Comment by rcanzanese** [comment]
Thanks for the insights -- the issue was how the sequence was getting evaluated in my code, and had nothing to do with yours.  Cheers!
