### ISSUE TITLE
Bring back delete-by-query

### ISSUE THREAD

**Issue by kutchar** [sksamuel/elastic4s#616]
Now that `delete-by-query` is a [plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/delete-by-query-usage.html), [delete-by-query dsl](https://github.com/sksamuel/elastic4s/commit/e5ad43bbc0bbea6d1a062e22ef9f68bc18ee98f0) can probably come back

**Comment by jason-heo** [comment]
FIY.

Delete By Query API which was deprecated in 1.5.3 and removed in 2.0 will come back in [5.0](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl.html)

**Comment by sksamuel** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-delete-by-query.html

This will be included in elastic4s 5.0

**Comment by sksamuel** [comment]
Delete by query does not exist in the Java client so I will have to write a HTTP client for this. Bumping to 5.1.

**Comment by Hindu** [comment]
Can you add "route" param to query?

**Comment by sksamuel** [comment]
I'd accept a PR.
