### ISSUE TITLE
Allow querying mappings for all types in an index

### ISSUE THREAD

**Issue by sakshamsharma** [sksamuel/elastic4s#619]
There's no way to get mappings for all types in an index right now, as far as I could see. This is the default behavior with `curl localhost:9200/index-name/_mapping?pretty` in the http interface of ElasticSearch. It'd be nice if this can be done in Elastic4s as well, since I don't see a call for listing the types either. So I'm pretty much stuck in my requirement.

I believe there should be a function without [this](https://github.com/sksamuel/elastic4s/blob/8346d2f4dcfed95b4279cb27d14e1ef76de22dd5/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/mappings/MappingDsl.scala#L29) line as well, that should fix it. I'm no expert though, so I might've ended up at the wrong place from this [start](https://github.com/sksamuel/elastic4s/blob/f279664d9780c715241b6be49e123fea4b5234f5/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/ElasticDsl.scala#L287).

**Comment by sksamuel** [comment]
In release 3.0.0 (pending) you can do

```
client.execute {
  getMapping("index")
}
```

Which will return all types.
