### ISSUE TITLE
Add SearchTemplate API

### ISSUE THREAD

**Issue by mandapakas** [sksamuel/elastic4s#625]
I am looking for an update on the API's to help with the search capabilities with a template. The idea behind the templating can be got here - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-template-query.html

I would appreciate if this is added to the API's.

Thanks,
Sathish

**Comment by sksamuel** [comment]
I can't get SearchTemplates to work with the Java API and there's very little documentation on line (as usual for elasticsearch!). So I'm parking this until there's better docs, an example, or someone else picks it up.

**Comment by sksamuel** [comment]
This has now been deprecated by elasticsearch in favour of the search template api
