### ISSUE TITLE
Alias doc out of date?

### ISSUE THREAD

**Issue by haggy** [sksamuel/elastic4s#628]
https://github.com/sksamuel/elastic4s/blob/master/guide/aliases.md

Im following that guide to create aliases using version 2.3 of the client. I was using 1.7.3 before and it was working fine. When I upgraded, I get compile errors:

```scala
val resp = client.execute {
  add alias "uk-locations" on "locations" filter termFilter("country", "uk")
}
```

```
Error: not found: value termFilter
```

I need to create a filtered alias. How do I accomplish that with the latest version of the client?

**Comment by haggy** [comment]
For anyone coming here with the same issue, the fix for me was to use `termQuery` instead of `termFilter`. `termFilter` seems to have been removed in favor of `termQuery`.

**Comment by sksamuel** [comment]
All filters have been removed from elasticsearch. Sorry I didn't see this earlier.

**Comment by sksamuel** [comment]
All filters have been removed from elasticsearch. Sorry I didn't see this
earlier.
