### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;

### ISSUE THREAD

**Issue by carnalim** [sksamuel/elastic4s#629]
Hello,
I posted in stackoverflow but not sure if anyone has seen this error before? 
http://stackoverflow.com/questions/39475881/elastic4s-in-spark-applicaiton

**Comment by sksamuel** [comment]
Guava issue. Something else has  a newer version of Guava but es wants 18.

**Comment by carnalim** [comment]
So the simplest way to not worry about this is wait for ES 5.0 where they remove Guava?

**Comment by sksamuel** [comment]
Override your other deps to use 18 and wait for 5.0 yeah.
