### ISSUE TITLE
Recover Index call missing implicit value

### ISSUE THREAD

**Issue by theshortcut** [sksamuel/elastic4s#638]
Attempting to upgrade from 1.7 to 2.x and looking at using the `recoverIndex` in place of the index status api.

A `recoverIndex` call like this:

```
elasticCheck <- es.client.execute { ElasticDsl.recoverIndex("documents") }
```

results in:

```
could not find implicit value for parameter executable: com.sksamuel.elastic4s.Executable[com.sksamuel.elastic4s.IndexRecoveryDefinition,R,Q]
```

**Comment by sksamuel** [comment]
You just need import `ElasticDsl._` somewhere in order to bring in the implicits.
