### ISSUE TITLE
Error Could Not Implicit Value ToResponseMarshaller[SearchResponse]

### ISSUE THREAD

**Issue by christianys14** [sksamuel/elastic4s#640]
hello, mr.samuel

im getting problem like she or he,

http://stackoverflow.com/questions/39715770/error-could-not-implicit-value-toresponsemarshallersearchresponse?noredirect=1#comment66734916_39715770

do you have any idea, how to deal with 
"could not find implicit value for parameter marshaller:
spray.httpx.marshalling.ToResponseMarshaller[org.eleasticsearch.action.search.SearchResponse]"?

regards,
Yohan

**Comment by sksamuel** [comment]
It's not an Elastic4s question but a generic Spray question. You need to have a marshaller in scope for SearchResponse. The comments/replies on your SO question cover it.
