### ISSUE TITLE
Error registering percolator (bulk)

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#642]
When registering percolators I got an error because refresh index op is not allowed when processing bulk operations.
I think that this is caused in by the line ".setRefresh(true)" in class RegisterDefinition, method build, file PercolateDsl.

Thank your for your great job!

**Comment by sksamuel** [comment]
Percolate has changed in elasticsearch 5.0.0. This test shows bulk register working with the latest version of percolate.
