### ISSUE TITLE
java.lang.ClassNotFoundException: org.elasticsearch.client.Client

### ISSUE THREAD

**Issue by michaelqiu94** [sksamuel/elastic4s#643]
Hi,
   Whenever I try to create an instance of ElasticClient, I get a Class Not Found Exception:

Caused by: java.lang.ClassNotFoundException: org.elasticsearch.client.Client

Any ideas as to what is causing this? I originally thought that this was a versioning issue, but I am using elastic4s 2.3.1 for Scala 2.11, so I don't think that is the case. Thanks!

**Comment by sksamuel** [comment]
Almost certainly a versioning issue. Check something else isn't bringing in an older/newer version of ES.
