### ISSUE TITLE
Not able to merge/overwrite mappings

### ISSUE THREAD

**Issue by yannick-cw** [sksamuel/elastic4s#646]
When you source a mapping all additional settings and mappings are ignored.
No warning or anything is displayed, that this happens.

Would it be possible to merge additional settings into the mapping?

``` scala
createIndex("test") source """ { "mapping" : ... } """ shards 2 replicas 1
```

It happens here, if there is a rawSource, everything else is ignored

``` scala
def build = _rawSource match {
    case Some(s) => new CreateIndexRequest(name).source(s)
    case None => new CreateIndexRequest(name).source(_source)
  }
```

**Comment by sksamuel** [comment]
I'm not sure really. The raw mapping is just passed through to the Java client, so if that doesn't support it, then it means parsing the raw json, and building an E4S query from it. Which means I'm then just writing a parser that will have to support everyone's raw json.
