### ISSUE TITLE
Elastic4s for es 2.4.x

### ISSUE THREAD

**Issue by avdv** [sksamuel/elastic4s#647]
I haven't tried yet, and I'm a bit weary... but does elastic4s 2.3.1 also work with es 2.4.x?

Otherwise could you prepare a release? Thanks!

**Comment by jmleoni** [comment]
From what we could test on our setup it doesn't work with 2.4
👍 for this one

**Comment by avdv** [comment]
@jmleoni which problems have you run into when trying the 2.4?

Currently we are facing `NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]` using 2.3.4 which is probably just a "concealed" `ClientStoppedException` (https://github.com/elastic/elasticsearch/issues/18708) and es 2.4.x has this fixed.

**Comment by jmleoni** [comment]
Well, the thing is I had little detail, has the setup where the problem was has been destroyed.
It had to do with the transportClient though. I need to retest to be sure. it should be done by next week. I will let you know in deeper details if we encounter the problem again.

**Comment by sksamuel** [comment]
I'll try and release a 2.4 tonight, been focusing on 5.0

**Comment by sksamuel** [comment]
I've just released this, sorry for the delay.
