### ISSUE TITLE
When bool query is given both a must and a should clause, it ignores must clause.

### ISSUE THREAD

**Issue by JohnAtWork** [sksamuel/elastic4s#649]
I'm using elastic4s 2.3.1 with version 2.4.1 of the ElasticSearch client.  When I try to use a bool query with both a must and a should clause, the must clause appears to get dropped from the query:
```
SearchDefinitionShow.show(
    search in ("index" -> "type") bool {
          should(
            matchQuery("first","john")
          )
          must(
            matchQuery("last", "smith")
          )
    }
 ) ==
"""{
  "query" : {
    "bool" : {
      "should" : {
        "match" : {
          "first" : {
            "query" : "john",
            "type" : "boolean"
          }
        }
      }
    }
  }
}"""

```

**Comment by sksamuel** [comment]
You're just running foul of a "scala-ism". You must put a comma between the should and must clauses, otherwise it will just use the last value.

It's the same as if you did this in raw-scala

val number = { 
  2
  3
}

**Comment by JohnAtWork** [comment]
Ah, my mistake -- that explains it. Thanks!
