### ISSUE TITLE
Wrong Description in README

### ISSUE THREAD

**Issue by littlejin** [sksamuel/elastic4s#665]
In README, it says when using multiple nodes, pass argument in this format "elasticsearch://host:port,host:port,...?param=value&param2=value2" to  ElasticsearchClientUri

    val uri = ElasticsearchClientUri("elasticsearch://foo:1234,boo:9876?cluster.name=escluster")

it turns out to be wrong, because apply function of ElasticsearchClientUri (line 147 in ElasticClient.scala)  first split by comma, then split by : to get host and port, so 9876?cluster.name=escluster will be treated as port, and will be cast to int, then throw exception

    def apply(str: String): ElasticsearchClientUri = {
        require(str != null && str.trim.nonEmpty, "Invalid uri, must be in format elasticsearch://host:port,host:port,...")
        val withoutPrefix = str.replace(PREFIX, "")
        val hosts = withoutPrefix.split(',').map { host =>
            val parts = host.split(':')
            if (parts.length == 2) {
                parts(0) -> parts(1).toInt
            } else {
                throw new IllegalArgumentException("Invalid uri, must be in format elasticsearch://host:port,host:port,...")
            }
        }
        ElasticsearchClientUri(str, hosts.toList)
      }

**Comment by sksamuel** [comment]
This isn't a bug actually, you're looking at the source for version 2, whereas the readme is for the current version which is 5.
