### ISSUE TITLE
Please release Elastic4s Play Json library with the last version of elastic4s core.

### ISSUE THREAD

**Issue by umnick84** [sksamuel/elastic4s#668]
Please release Elastic4s Play Json library with the last version of elastic4s core (5.0.0 or later).

**Comment by sksamuel** [comment]
I was waiting to see if they were going to release a 2.12 version.

**Comment by umnick84** [comment]
Does it mean that you are not going to release it for 2.11 version?

**Comment by sksamuel** [comment]
I suppose I can, it just requires some manual fiddling of the build during release.

**Comment by sksamuel** [comment]
I'll do this as part of 5.0.1 this week.

**Comment by umnick84** [comment]
Thanks a lot!

**Comment by sksamuel** [comment]
Released.
