### ISSUE TITLE
Add X-Pack security support

### ISSUE THREAD

**Issue by gabriele83** [sksamuel/elastic4s#670]
Add X-Pack security support for the Java transport client for Elasticsearch

**Comment by gabriele83** [comment]
thanks

**Comment by sksamuel** [comment]
This will be in 5.0.4 as a separate module, you can use `XPackElasticClient()` like you would  `ElasticClient()`

**Comment by gabriele83** [comment]
thank you so much!!

Il 03 dic 2016 00:00, "Stephen Samuel" <notifications@github.com> ha
scritto:

>

> Closed #670 <https://github.com/sksamuel/elastic4s/issues/670>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/elastic4s/issues/670#event-880703430>, or mute
the thread

**Comment by sksamuel** [comment]
Welcome.
