### ISSUE TITLE
ScrollDsl.searchScroll.keepAlive is interpreting FiniteDuration as 'id'

### ISSUE THREAD

**Issue by erwinverdonk** [sksamuel/elastic4s#676]
When using ScrollDsl searchScroll().keepAlive(5 minutes) instead of searchScroll.keepAlive("5m"), it will interpret the argument as case class SearchScrollDefinition.id. Reason for this is not using named parameters.

Pull request for this is below.

**Comment by sksamuel** [comment]
:+1:
