### ISSUE TITLE
RichSearchHitField API breaking changes in 5.x

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#678]
I'm trying to upgrade large code base from elastic4s 2.x to 5.x. 

I found that RichSearchHit API was changed, in 2.x we used

```
doc.field("group").value[String]
```

and in 5.x we have to use

```
doc.field("group").java.value[String]
```

Maybe you can preserve previous API?

**Comment by sksamuel** [comment]
That should still be there ?

Current code:

`def field(fieldName: String): RichSearchHitField = fields(fieldName)`

`case class RichSearchHitField(java: SearchHitField) extends HitField`

**Comment by RPGambit2** [comment]
I'm noticing allot of differences.  I am also going from 2.4x to 5.x and all my calls to elasticSearchClient.execute have to change.  sksamuel, is that true?

I have a ton of that are getting build errors for example:


        elasticSearchClient.execute {
          update ((elkEnrichmentStatsSubmitRunMessage.JobId, elkEnrichmentStatsSubmitRunMessage.RunId)) in "elk-indexing-node/elk-indexing-group" docAsUpsert (
            "RunId" -> elkEnrichmentStatsSubmitRunMessage.RunId,
            "JobId" -> elkEnrichmentStatsSubmitRunMessage.JobId
            ) retryOnConflict(5)
        }

is the execute command gone?

Thanks for your time!

**Comment by RPGambit2** [comment]
Also, it used to be: 

update id (id.....), changed to 
update (id....)

**Comment by sksamuel** [comment]
execute is still there.

**Comment by RPGambit2** [comment]
Okay.  I changed something I shouldn't have.  Since upgrading to 5, it crashes right on my call to ElasticClient.transport.

  // Create our client that will talk to Elasticsearch server to index Kafka data
  val settings = Settings.builder().put("cluster.name", "elasticsearch").build()
  val uri  = ElasticsearchClientUri("localhost", 9300)
  val client = ElasticClient.transport(settings, uri)

**Comment by sksamuel** [comment]
Crashes, at runtime? Or doesn't compile?

**Comment by RPGambit2** [comment]
Run time

**Comment by RPGambit2** [comment]
2017-01-06 18:01:41,808 [ElkIndexingTestSystem-akka.actor.default-dispatcher-4] INFO  (Slf4jLogger.scala:79) - Cluster Node [akka.tcp://ElkIndexingTestSystem@127.0.0.1:2551] - No seed-nodes configured, manual cluster join required
Uncaught error from thread [ElkIndexingTestSystem-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ElkIndexingTestSystem]
java.lang.NoSuchFieldError: LUCENE_6_3_0
	at org.elasticsearch.Version.<clinit>(Version.java:102)
	at org.elasticsearch.common.io.stream.StreamOutput.<init>(StreamOutput.java:74)
	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:60)
	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:57)
	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:47)

**Comment by sksamuel** [comment]
java.lang.NoSuchFieldError: LUCENE_6_3_0

looks like dep mismatch. Which version of ES are you on and which version of E4S. In elasticsearch 5 they changed all the deps to be compile time only in maven, which means they're not included by default.

**Comment by RPGambit2** [comment]
I changed/added to these dependencies (added esClientRest and all lucene, and nettyAll)
val elastic4sCore = "com.sksamuel.elastic4s" %% "elastic4s-core" % "5.1.1"
val esClient = "org.elasticsearch.client" % "transport" % "5.1.1"
val esClientRest = "org.elasticsearch.client" % "rest" % "5.1.1"
val luceneGrandParent = "org.apache.lucene" % "lucene-solr-grandparent" % "6.3.0"
val luceneHighlighter = "org.apache.lucene" % "lucene-highlighter" % "6.3.0"
val luceneJoin = "org.apache.lucene" % "lucene-join" % "6.3.0"
val luceneSpatial = "org.apache.lucene" % "lucene-spatial" % "6.3.0"
val luceneSpatialExtras = "org.apache.lucene" % "lucene-spatial-extras" % "6.3.0"
val luceneSpatial3d = "org.apache.lucene" % "lucene-spatial3d" % "6.3.0"
val luceneQueries = "org.apache.lucene" % "lucene-queries" % "6.3.0"
val luceneQueryParser = "org.apache.lucene" % "lucene-queryparser" % "6.3.0"
val nettyAll = "io.netty" % "netty-all" % "4.1.6.Final"

**Comment by RPGambit2** [comment]
I don't know if those are correct.  I spent all day trying to figure out which to add to my build.sbt file.  Finally got it to not error and was able to build.

**Comment by sksamuel** [comment]
Use e4s 5.1.5 which will bring in the dependencies for you. I don't know
why elastic decided to make the 5 series client not bring in the
dependencies it actually needs to work, seems a ridiculous decision to me.

**Comment by RPGambit2** [comment]
Okay.  I will try that.  I really appreciate you spending your own time helping me out.   Thanks so much!

**Comment by RPGambit2** [comment]
It worked!!!!!!!!!!!!!   Thank you so much.  Can't tell how much appreciation I have!!!!!

One last thing you may be able to answer.   Prior to 5.0 I was using the head plugin.   Is there a new version that you know about or an easy way to see the documents I have in my elasticsearch etc..???

**Comment by sksamuel** [comment]
I don't know what the head plugin is ?

**Comment by RPGambit2** [comment]
Oh.  Okay.  It allows you to see your documents in your elastic search cluster.  It also allows you to query elastic search etc...   Its a browser plugin.

Do you have any utility that you use to validate the data in elasticsearch (i.e. determine that what you wrote to ES is in there correctly?

**Comment by sksamuel** [comment]
I tend to just do it programmatically. Write a query and then unit test it.

**Comment by RPGambit2** [comment]
Okay.  I understand.  Thanks again and have a great weekend.  You were a BIG HELP!

**Comment by sksamuel** [comment]
You're welcome.
