### ISSUE TITLE
Filter aggregation API breaking changes in 5.x

### ISSUE THREAD

**Issue by maxcom** [sksamuel/elastic4s#679]
In 2.x filter aggregation was defined this way:

```
agg filter "topSections" filter termsQuery("section", topSections)
```

In 5.x:

```
agg filter "topSections" query termsQuery("section", topSections)
```

Please keep old "filter" method (mark it deprecated if you think that it is wrong name). This will make transition from 2.x much easier.

**Comment by sksamuel** [comment]
I renamed it because that's what ES did, but I've added it back as a deprecated method.

**Comment by maxcom** [comment]
Thank you.
