### ISSUE TITLE
Support geoShapeQuery with indexedShapeId and indexedShapeType parameters

### ISSUE THREAD

**Issue by kthompson** [sksamuel/elastic4s#681]
I just started looking through the elastic4s 5.0 stuff and noticed that there does not appear to be a signature for `geoShapeQuery(String name, String indexedShapeId, String indexedShapeType)` in `QueryDsl`.

Can this be added? This relates to  #639

Thanks

**Comment by sksamuel** [comment]
Done

**Comment by kthompson** [comment]
Awesome thanks!
