### ISSUE TITLE
How to index attachments using elastic4s and ingest plugin

### ISSUE THREAD

**Issue by ksarath** [sksamuel/elastic4s#685]
Using elastic4s 5.0.x, how can I index attachments using elastic search ingest attachment processor plugin? Currently I am using the following code to achieve the same.

elastic4sClient.java.index(
    indexInto(tenant, mappingName).id(id).fields (
      "id" -> id,
      "data" -> base64EncodedContent
    ).build.setPipeline("attachment")
  ).actionGet()

Is there any better way to do this?

**Comment by sksamuel** [comment]
I don't think it will be supported as mapper-attachments are being removed in 6.x.
