### ISSUE TITLE
"reindex(srcIndex) into dstIndex" gets stuck

### ISSUE THREAD

**Issue by kthompson** [sksamuel/elastic4s#686]
In attempting to run the new reindex api on ES5 it just seems to get stuck. I know the old version used a scroll to accomplish this and was pretty quick as well. I am not sure if this is an issue with the new API or what exactly. I have given the command a good 15minutes for an index with about 18k documents and nothing appears to be happening.

Any thoughts?

The code I am running looks like:

`elasticSearchClient.execute { reindex(srcIndex) into dstIndex }.await(Duration.Inf)`

Thanks

**Comment by kthompson** [comment]
Looks like this may be an actual issue. Running the command manually via Sense returns a failure with a response that looks like:

`{
   "took": 1680,
   "timed_out": false,
   "total": 6140,
   "updated": 0,
   "created": 999,
   "deleted": 0,
   "batches": 1,
   "version_conflicts": 0,
   "noops": 0,
   "retries": {
      "bulk": 0,
      "search": 0
   },
   "throttled_millis": 0,
   "requests_per_second": -1,
   "throttled_until_millis": 0,
   "failures": [
      {
         "index": "events-w91kbqy",
         "type": "event",
         "id": "549a4338-0bd9-43a0-b9bc-510c6c8be642",
         "cause": {
            "type": "illegal_argument_exception",
            "reason": "mapper [json.notes.note_id] of different type, current_type [text], merged_type [long]"
         },
         "status": 400
      }
   ]
}`

Maybe the error handling needs some work for this one.

**Comment by sksamuel** [comment]
Are you saying the underlying elasticsearch implementation is what is broken ?

**Comment by kthompson** [comment]
If you are referring to the java client, then yea, maybe so. I just know that running the command I originally posted isn't actually doing anything. When I ran a `POST _reindex` it seems to have worked but I had an error response from the POST originally indicating some of my data was inconsistent.

**Comment by sksamuel** [comment]
The Scala client doesn't do much other than call the Java one. I think the error must be in the Java one having looked at the code, there's only a few lines.
