### ISSUE TITLE
name clash - bulk

### ISSUE THREAD

**Issue by yurique** [sksamuel/elastic4s#687]
When having these imports:

```
import com.sksamuel.elastic4s._
import com.sksamuel.elastic4s.ElasticDsl._
```

and writing something like this:
```
client.execute(bulk(...))
```

we will get this:
```
reference to bulk is ambiguous;
it is imported twice in the same scope by
import com.sksamuel.elastic4s.ElasticDsl._
and import com.sksamuel.elastic4s._
```

that's because there's a `com.sksamuel.elastic4s.bulk` package which gets imported.

Can anything be done regarding this? :)

The workaround is simple:
```
import com.sksamuel.elastic4s.{bulk => _, _}
```

but took me a minute to figure out what was going on.

**Comment by yurique** [comment]
Same thing with `get`.

**Comment by sksamuel** [comment]
What's the reason for importing `import com.sksamuel.elastic4s._` as a wildcard, there's only ElasticClient really you want from that, along with the ElasticDsl class.

**Comment by yurique** [comment]
Well, I can't argue with that :) - no reason. I'm migrating our code to version 5, and accidentally there were some places with this wildcard import. Going to close this ticket. 

PS: maybe there's a place in some kind of FAQ to mention this?

**Comment by sksamuel** [comment]
I guess I could put it in the FAQ but its really just a Scala question, and nothing to do with Elastic4s. You'd have the same issue importing any two packages that have a class or method with the same name.
