### ISSUE TITLE
Inner Hits Regressions in 5.0.X

### ISSUE THREAD

**Issue by ANorwell** [sksamuel/elastic4s#688]
Inner hit support seems to have been removed as part of 5.0.X. Here are some things I have identified from looking at the code when upgrading from 2.3.1:

- The `inner` DSL method has disappeared and tests for this method are commented out.
- The `sourceInclude` and `sourceExclude` DSL methods seem to be missing on `InnerHitDefinition` (In 2.3.1, these were on `QueryInnerHitsDefinition`, but I can't find an analogue in 5.0.4. It looks like the relevant method in elasticsearch is `InnerHitBuilder.setFetchSourceContext`).

**Comment by sksamuel** [comment]
You need to use `fetchSource` and set an instance of `FetchSourceContext` which takes includes and excludes. That's a change in Elasticsearch itself so its just mirrored here.

As for inner query, you need to use `innerHits`,

**Comment by ANorwell** [comment]
Thanks, `fetchSource` works for me. 

I think `inner` has changed specifically for nested queries. Originally, something like `nestedQuery(...).query(...).inner(...)` would work. Now, `scoreMode` seems to be necessary -- `nestedQuery(...).query(...).scoreMode(...).inner(...)`.

**Comment by sksamuel** [comment]
Yep, elasticsearch made scoreMode mandatory.

**Comment by ANorwell** [comment]
Thanks, this resolved everything.

Thanks for your work in getting elastic4s compatible with ES 5.
