### ISSUE TITLE
SearchDefinition#extraSource is not implemented

### ISSUE THREAD

**Issue by imalygin** [sksamuel/elastic4s#691]
Could you please tell me if you have any plans on implementing SearchDefinition#extraSource?

**Comment by sksamuel** [comment]
I don't think it's possible to use the Java client to set the source as json anymore.

**Comment by imalygin** [comment]
Do you see any possible workaround for these cases? Let's say I want to add rescore query in addition to rawQuery I already have.

**Comment by sksamuel** [comment]
There's wrapped query that ES provides now if you want to provide a query in raw form. I'll update docs.

**Comment by LeiG** [comment]
Regarding this wrapped query, is there any docs anywhere describe how it works? Sorry I am pretty new to ES and my Google search failed me :(

**Comment by salaisuuxia** [comment]
latest version of documentation seems to still have extraSource. shouldn't this function also be removed? seems like it's better to be a compiler error than a runtime error.
