### ISSUE TITLE
multiMatchQuery does not support multiple fields with boostings

### ISSUE THREAD

**Issue by Dbzman** [sksamuel/elastic4s#692]
In #545 the functionality to add a single field with a boosting was added to 5.0. What's missing is the ability to add multiple fields at once.
The MultiMatchQueryBuilder already supports this but elastic4s does not provide a way.
```scala
/**
* Add several fields to run the query against with a specific boost.
*/
public MultiMatchQueryBuilder fields(Map<String, Float> fields) {
  this.fieldsBoosts.putAll(fields);
  return this;
}
```
In the version for ES 2.3 it was enough to just use the ```fields``` method on ```multiMatchQuery```. It now breaks and adds additional default boostings like this:
```title^10^1.0```

**Comment by sksamuel** [comment]
Added to 5.1.1

**Comment by Dbzman** [comment]
That was fast, thank you very much! :)
