### ISSUE TITLE
elasticsearch 5.1.1 needs LuceneVersion = "6.3.0" in Build.scala

### ISSUE THREAD

**Issue by kyal** [sksamuel/elastic4s#693]
I get a runtime error within `org.elasticsearch/elasticsearch/srcs/elasticsearch-5.1.1-sources.jar!/org/elasticsearch/Version.java` at line 102:

```public static final Version V_5_1_1 = new Version(V_5_1_1_ID, org.apache.lucene.util.Version.LUCENE_6_3_0);``` because `lucene-core-6.2.1` does not have that field.

Fixed by setting ```val LuceneVersion = "6.3.0"``` in Build.scala

This solves it and all tests pass. Can't submit a PR at the moment but this should do it.

**Comment by sksamuel** [comment]
Yes I see, I wonder why all the unit tests passed ok.

**Comment by sksamuel** [comment]
5.1.2 released.
