### ISSUE TITLE
Explicitly clear scroll after completion in ScrollPublisher

### ISSUE THREAD

**Issue by kutchar** [sksamuel/elastic4s#695]
I think the ScrollPublisher should [clear the scroll](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html#_clear_scroll_api) [after completion](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-streams/src/main/scala/com/sksamuel/elastic4s/streams/ScrollPublisher.scala#L146) (or failure) since Elasticsearch [doesn't automatically close completed scrolls anymore](https://github.com/elastic/elasticsearch/issues/10651).

Alternatively this behavior could be optional à la [elasticsearch-py's clear_scroll](http://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.scan)

**Comment by sksamuel** [comment]
Good suggestion thanks.
