### ISSUE TITLE
"The required text option is missing" is thrown when text is empty in suggestions

### ISSUE THREAD

**Issue by Dbzman** [sksamuel/elastic4s#697]
This exception is thrown on Elasticsearch side when the query is sent and you don't specify a "text" option.
It looks like the text you set on a suggestion is of type "Option[String]".
Excerpt from "SuggestionDefinition":
`def text: Option[String]`
When passing text via the DSL the "some" method is used which calls this:
```
object StringOption {
  def apply(str: String): Option[String] = Option(str).filter(_.trim.nonEmpty)
}
```
This now does not build suggestions when your query is empty. Our application relies on having this. I build a workaround for that for now.
I think it should be just "String" since it's required by Elasticsearch anyway. (it was a String as well in elastic4s < 5)

**Comment by sksamuel** [comment]
I've corrected this for 5.2.3+
