### ISSUE TITLE
java.getFields empty results

### ISSUE THREAD

**Issue by od0** [sksamuel/elastic4s#699]
Running version 5.1.1

`elasticSearchResp.hits.map(_.fields)` and `elasticSearchResp.hits.map(_.java.getFields)` both return empty results:

![image](https://cloud.githubusercontent.com/assets/2206712/21285315/1ee0e3a4-c403-11e6-85ba-6e0299595a17.png)

The fields are present though, and `elasticSearchResp.hits.map(_.sourceAsMap)` returns the expected result and the fields can be accessed:

![image](https://cloud.githubusercontent.com/assets/2206712/21285332/760d27aa-c403-11e6-9532-b90acf2fe50d.png)

It's late and maybe I'm missing something, but this was working for me before upgrading to ES5 :)

I can work around this but wanted to bubble up in case this actually a bug with the Java API

**Comment by sksamuel** [comment]
It's a change in elasticsearch.

> The fields parameter has been replaced by stored_fields. The stored_fields parameter will only return stored fields — it will no longer extract values from the _source.

**Comment by od0** [comment]
@sksamuel thanks for the quick followup - I had switched over to use the new `storedFields` but hadn't dug deeper into the underlying change
