### ISSUE TITLE
Creating alias on template

### ISSUE THREAD

**Issue by jpopol** [sksamuel/elastic4s#700]
I am trying to create an alias on a template.
On ES you can't add the alias on the template after it has been created, rather at the time of template creation:
```
curl -XPUT localhost:9200/_template/my_template -d '
{
    "template" : "index*",
    "settings" : {
        "number_of_shards" : 1
    },
    "aliases" : {
        "my_alias1" : {},
        "my_alias2" : {}
    }
}
```

When I look at the api I can't see a way of doing such an operation at once such as
```scala
client.execute(create.template(templateName).pattern(pattern).alias("my-alias"))
```
The following would not work:
```scala
client.execute(create.template(templateName).pattern(pattern))
client.execute(add.alias("my-alias").on(templateName))
```

Am I doing something wrong or missing a step ?
If not could I get some pointers to add this feature in ?
PS: elastic4s 2.3.1 is the version I use

**Comment by sksamuel** [comment]
Have you tried `createTemplate(name).pattern(pattern).alias(new Alias("my-alias"))`

**Comment by sksamuel** [comment]
In the upcoming 5.2.12 release you can pass in an instance of TemplateAlias which is like the Java Alias object but more scala friendly.
