### ISSUE TITLE
facets not recognized

### ISSUE THREAD

**Issue by 123avi** [sksamuel/elastic4s#706]
Hi ,
I am trying to use the example as shown in the guid/search.md 
```
client execute {
  search in "places"->"cities" query "london" facets (
    facet terms "landmark" field "type",
    facet range "age" field "year" range (1000->1200) to(1200) from(1400)
  )
}
```
however it seems that facets are not recognized . 
I might be missing an import or dependency 
I am using 
```
    "com.sksamuel.elastic4s"  %% "elastic4s-core"                     % 2.4.0,
    "com.sksamuel.elastic4s"  %% "elastic4s-streams"                  % 2.4.0
```

Please advise 
Thank you for this awesome project.

**Comment by sksamuel** [comment]
Facets are not in ES anymore, you need to use aggregations.
https://github.com/sksamuel/elastic4s/blob/master/guide/search.md#aggregations
I'll update the page to remove facets as well.
