### ISSUE TITLE
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps    scala 2.12.0  and 2.12.1

### ISSUE THREAD

**Issue by MyraBaba** [sksamuel/elastic4s#709]
I am always getting below error. can you help ?

ElasticClient.transport(ElasticsearchClientUri("122.94.254.231",8859))
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
  at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticClient.scala:121)
  at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticClient.scala:116)
  ... 38 elided

**Comment by MyraBaba** [comment]
in scala 2.11.8  all is fine..  

scala 2.12 +  shows above error.

**Comment by sksamuel** [comment]
NoSuchMethodError Usually means a version mismatch. Are you 100% sure you're using scala 2.12 with elastic4s 2.12.

**Comment by MyraBaba** [comment]
Actually I rebuild all from stratch. now there is no error.  it looks like a weird intellij cache problem.

thx

**Comment by srinivas10435** [comment]
Hi i got the same error would you help me to rectify that

**Comment by dashabinash** [comment]
I am also facing the same issue in my setup.

**Comment by SIGN369** [comment]
help .how to fix this

**Comment by Philippus** [comment]
Do you have a minimal example of the issue you're experiencing?
