### ISSUE TITLE
nested document index.

### ISSUE THREAD

**Issue by MyraBaba** [sksamuel/elastic4s#710]
How we can index nested document like 👍 

`PUT my_index/my_type/1
{
  "group" : "fans",
  "user" : [ 
    {
      "first" : "John",
      "last" :  "Smith"
    },
    {
      "first" : "Alice",
      "last" :  "White"
    }
  ]
}`

in this format: 

` esclient.execute{
        indexInto("test01" / "xx") fields(
          "created_at"  ->  xx.created_at,
          "user_id"     ->  xx.user.get.id,
          "text"        ->  xx.text,
          "user" -> tweet.user.get.screen_name
          )`

is there any way to do this in the indexInto ?

**Comment by sksamuel** [comment]
You can index a Map instead. So `indexInto("x" / "y").doc(Map("user" -> List(Map("first" -> "John"), Map("first" -> "alice"))`

Or even better, use the `Indexable` typeclass (see readme).
