### ISSUE TITLE
Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate org.elasticsearch.common.inject.InjectorImpl.toString()

### ISSUE THREAD

**Issue by MyraBaba** [sksamuel/elastic4s#712]
I have 

`Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate org.elasticsearch.common.inject.InjectorImpl.toString()`

when I try to connect :

`   val esclient= ElasticClient.transport(ElasticsearchClientUri("x.x.x.x",8882))
`

any idea.

**Comment by sksamuel** [comment]
Are you trying to connect to a HTTP port?

**Comment by sksamuel** [comment]
Also try this `val client = ElasticClient.transport(ElasticsearchClientUri("elasticsearch://host:port"))`

**Comment by MyraBaba** [comment]
9300

it gives same error still  but working !!
