### ISSUE TITLE
Search by missing field

### ISSUE THREAD

**Issue by pvcnt** [sksamuel/elastic4s#715]
Hi,

I found the missingAggregation query definition but nothing similar for a missingField. Did I miss something or is it a missing feature?

Thanks for this awesome library!

**Comment by sksamuel** [comment]
Is this what you are looking for ?
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html#_literal_missing_literal_query

**Comment by pvcnt** [comment]
Oops, I missed this... Thanks!
