### ISSUE TITLE
Buildable terms query is missing from HTTP API

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#727]

**Comment by hekaldama** [comment]
Would this give me bugs like:
`
Error:(43, 19) could not find implicit value for parameter buildable: com.sksamuel.elastic4s.searches.queries.term.BuildableTermsQuery[Any]
        termsQuery(field, values)
`

**Comment by sksamuel** [comment]
Yes.

**Comment by hekaldama** [comment]
Could this be a good "first bug" for me to try and handle?

**Comment by sksamuel** [comment]
Perhaps. Either that or add some missing query types with which you can
follow along the lines of what is there already.

**Comment by hekaldama** [comment]
K. I will take a look. I am needing `termsQuery` to work for the project I am working on fwiw. Thanks for this client!

**Comment by sksamuel** [comment]
I can sort that if you want. Up to you.

**Comment by hekaldama** [comment]
If you can fix this issue so that `termsQuery` works with HTTP client, that would be fantastic. I will keep getting familiar with the DSL.

**Comment by hekaldama** [comment]
Thanks much! Initial tests show it to be working as desired.
