### ISSUE TITLE
Fix score mode

### ISSUE THREAD

**Issue by everylifetechnologies** [sksamuel/elastic4s#730]
I am getting these kind of errors after bumping. I am seeing the correct versions in my dependencies and I cant seem to work out why this is happening. Here are a couple:

```com.sksamuel.elastic4s.searches.QueryDsl$NestedQueryExpectsQuery$NestedQueryExpectsScoreMode.scoreMode(Lorg/apache/lucene/search/join/ScoreMode;)Lcom/sksamuel/elastic4s/searches/queries/NestedQueryDefinition; 
java.lang.NoSuchMethodError: com.sksamuel.elastic4s.searches.QueryDsl$NestedQueryExpectsQuery$NestedQueryExpectsScoreMode.scoreMode(Lorg/apache/lucene/search/join/ScoreMode;)Lcom/sksamuel/elastic4s/searches/queries/NestedQueryDefinition;
```
```
Error:scalac: Unexpected type application scala.Predef.wrapRefArray[sym: scala.LowPriorityImplicits.wrapRefArray] in: scala.Predef.wrapRefArray[com.sksamuel.elastic4s.searches.QueryDefinition](Array[com.sksamuel.elastic4s.searches.QueryDefinition]{com.sksamuel.elastic4s.ElasticDsl.termQuery("tasks.task.type", taskType$1)})
```

I have cleaned/re-build and built from command line - I feel stuck.

**Comment by sksamuel** [comment]
Are you doing git clone and then just sbt compile?

**Comment by everylifetechnologies** [comment]
I've done several sbt update, sbt clean, sbt compile, etc. I get the second error if I comment out the code causing the first error.

I cleared the _2.11 versions out of my ivy cache to be sure. Lucene 6.3 seems to be listed.

**Comment by sksamuel** [comment]
Are you using the same version of sbt as what e4s uses on travis.

**Comment by everylifetechnologies** [comment]
So I downgraded our sbt to 0.13.12 to match your project - this fixed some issues thanks!

I still had some errors and had to add a ```.toString``` on the end of ```ScoreMode``` (e.g. ```.scoreMode(ScoreMode.Total.toString)```) so it would actually run correctly. Not really sure why.

Just to also note scala recommend using sbt 0.13.13 which is why I used it originally: http://scala-lang.org/news/2.12.0

**Comment by sksamuel** [comment]
I find the less I interact with sbt the better.

**Comment by everylifetechnologies** [comment]
I think after today I would have to agree with you. Are you going to investigate the ```ScoreMode``` issue I raised above or would you like me to close this ticket?

Thanks for your help and for your efforts with this library.

**Comment by sksamuel** [comment]
I'll fix score mode - which query was it that has the error ?

**Comment by sksamuel** [comment]
The only one I can find without the enum version of score mode is rescore. So was it that that you were using? Also I upgraded build to sbt 0.13.13 and it compiles fine.

**Comment by everylifetechnologies** [comment]
It was ```nestedQuery("test").query(/* */).scoreMode(ScoreMode.Total) inner (/* */)```. It complied fine but threw for method not found at runtime during our unit tests. When I do a ```.toString``` on ```ScoreMode``` it executes the tests fine. 

Hopefully this was helpful.
