### ISSUE TITLE
Improved `Show[SearchDefinition]` instance

### ISSUE THREAD

**Issue by jeantil** [sksamuel/elastic4s#735]
Since 5.2.0 `SearchDefinition` (and many others) is an immutable case class, it doesn't have a `_builder` property anymore.
That builder instance could be used to easily get a json string for the search query from just the definition.

The `Show` typeclass was introduced in 5.2.x but currently the default typeclass uses `SearchDefinition#toString` which is nice but not terribly useful. 

I would like to propose an alternative instance which recreates the json view. I file this as an issue and not a pull request because my proposed code is not complete and probably  fails to account for many cases. 

One thing I avoided on *purpose* is to have a dependency on the client in the Show instance. I use the proposed typeclass instance to log my queries in a manner that lets me copy/paste them directly in the kibana dev console. While not perfect it is still much more useful thant the current toString. 
The toJsonString is mostly lifted from SearchBuilderFn but removed all the parts which depend on the client. 

```
  implicit object JsonSearchDefinitionShow extends Show[SearchDefinition] {
    override def show(f: SearchDefinition): String = toJsonString(f)
  }

  private def toJsonString(search:SearchDefinition)={
    import scala.collection.JavaConverters._
    val builder = new SearchSourceBuilder()
    search.query.map(QueryBuilderFn.apply).foreach(builder.query)
    search.minScore.map(_.toFloat).foreach(builder.minScore)
    search.version.foreach(v=>builder.version(v))
    search.postFilter.map(QueryBuilderFn.apply).foreach(builder.postFilter)
    search.explain.foreach(b=>builder.explain(b))
    search.from.foreach(builder.from)
    search.size.foreach(builder.size)
    search.trackScores.foreach(builder.trackScores)
    search.terminateAfter.foreach(builder.terminateAfter)
    search.timeout.map(dur => TimeValue.timeValueNanos(dur.toNanos)).foreach(builder.timeout)
    search.indexBoosts.foreach { case (index, boost) => builder.indexBoost(index, boost.toFloat) }

    if (search.storedFields.nonEmpty)
      builder.storedFields(search.storedFields.asJava)

    if (search.aggs.nonEmpty)
      search.aggs.map(_.builder).foreach(builder.aggregation)

    if (search.inners.nonEmpty) {
      for (inner <- search.inners)
        sys.error("todo")
      // builder.(inner.name, inner.inner)
    }

    if (search.sorts.nonEmpty)
      search.sorts.foreach { sort =>
        builder.getClass.getMethod("addSort", classOf[SortBuilder[_]]).invoke(builder, SortBuilderFn.apply(sort))
      }

    if (search.scriptFields.nonEmpty)
      search.scriptFields.foreach {
        case ScriptFieldDefinition(name, script, None, None, _, ScriptType.INLINE) =>
          builder.scriptField(name, new Script(script))
        case ScriptFieldDefinition(name, script, lang, params, options, scriptType) =>
          builder.scriptField(name, new Script(scriptType, lang.getOrElse(Script.DEFAULT_SCRIPT_LANG), script,
            options.map(_.asJava).getOrElse(new java.util.HashMap()),
            params.map(_.asJava).getOrElse(new java.util.HashMap())))
      }
    if (search.suggs.nonEmpty) {
      val suggest = new SuggestBuilder()
      search.suggs.foreach { sugg => suggest.addSuggestion(sugg.name, sugg.builder) }
      builder.suggest(suggest)
    }

    search.highlight.foreach { highlight =>
      val highlightBuilder = HighlightBuilderFn(highlight.options, highlight.fields.toSeq)
      builder.highlighter(highlightBuilder)
    }

    search.rescorers.map(RescoreBuilderFn.apply).foreach(builder.addRescorer)

    if (search.stats.nonEmpty)
      builder.stats(search.stats.asJava)

    builder.toString
  }
```

**Comment by sksamuel** [comment]
An alternative is to use the Show definition that the HTTP Client uses - which uses the actual json that is sent to the server.

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/SearchImplicits.scala

Although the http client is experimental and still missing aggregations, highlighting and suggestions (but the latter two will be added in a few days).

**Comment by sksamuel** [comment]
I think I'll use yours for now, and once the HTTP is complete maybe use that for consistency.

**Comment by jeantil** [comment]
That would force users of the tcp client to still pull the http dependency to get a usable debug output ... 

Also note that this code doesn't depend on the client at all. You could have a `SearchDefinition => SearchSourceBuilder` conversion in `core` jar

Then the client specific stuff can go in the corresponding jar, also this gives you a mapping for every single search requests in both clients immediately. since calling `builder.toString` uses `XContent` to generate the actual json payload for the search query... and you can use 
`SearchRequestbuilder#setSource` to pass in the `SearchSourceBuilder` instance. This is what `SearchRequestBuilder` does anyway. 

The `SearchSourceBuilder` generates the full body of the query. the other parameters (scroll, routing, etc) are all meta params (query params in HTTP).

**Comment by sksamuel** [comment]
The SearchContentBody function just relies on the main elasticsearch jar, as does TCP, so moving that into the elastic4s-core would make it available for both users. That's where a lot of them are already.

I don't want to use search builder as a permanent solution as I suspect in upcoming releases, as elasticsearch begin building out the http client, that dependencies are going to start geting changed, and all the tcp builder classes are going to be moved out.

**Comment by jeantil** [comment]
Hmm if elasticsearch splits out the http (and/or) tcp client then isn't it likely that XContent will move to http too ? The TCP client seems to write binary data directly on the wire....

**Comment by sksamuel** [comment]
XContent is in their common package at the moment, so I don't know, as its quite useful and has no external deps. They'd probably use it for both I would think.
