### ISSUE TITLE
sourceExclude stops working with the latest version

### ISSUE THREAD

**Issue by umailprasanth** [sksamuel/elastic4s#741]
Its is observed that sourceExclude is not working with the latest version . 
I tested in all versions from 5.2.0.

**Comment by sksamuel** [comment]
Do you have an example that reproduces it as the unit tests pass.

**Comment by umailprasanth** [comment]
[elatsic4sbug.zip](https://github.com/sksamuel/elastic4s/files/763510/elatsic4sbug.zip)

Please find the attached sample sbt project .

Import the sbt project 
Edit application.conf with clustername
Run Main class

**Comment by umailprasanth** [comment]
Could anyone please confirm  the issue ?

**Comment by sksamuel** [comment]
I will once I get chance in the next few days.

**Comment by umailprasanth** [comment]
Thank you !

**Comment by sksamuel** [comment]
Should be fixed in 5.2.6
