### ISSUE TITLE
underlying elasticsearch error on multi_field

### ISSUE THREAD

**Issue by JohnGretzki** [sksamuel/elastic4s#744]
Hi,
currently we move our implementation from es 2.x to 5.2.x (latest).
For the mapping i've defined a view properties with the es4s - multiField keyword.
if i run any test, i receive (from underlying elasticsearch) an exception:

`[error] cannot create an instance for class xxx.TextRuleSearchServiceSpec
[error]   caused by MapperParsingException[Failed to parse mapping [variant]: No handler for type [multi_field] declared on field [MARKE_TXT]]; nested: MapperParsingException[No handler for type [multi_field] declared on field [MARKE_TXT]];
[error]   caused by MapperParsingException[No handler for type [multi_field] declared on field [MARKE_TXT]]`

the mapping shows here (2 excamples, booth throws the same error):

`multiField(MasterDataKeys.MARKE_TXT).multi(
          textField(MasterDataKeys.MARKE_TXT).index(IndexKeys.Analyzed),
          textField(IndexKeys.Keyword).analyzer(KeywordAnalyzer),
          textField(IndexKeys.Raw).index(NotAnalyzed)
        ),`

or

`
textField(MasterDataKeys.MARKE_TXT).multi(
          textField(MasterDataKeys.MARKE_TXT).index(IndexKeys.Analyzed),
          textField(IndexKeys.Keyword).analyzer(KeywordAnalyzer),
          textField(IndexKeys.Raw).index(NotAnalyzed)
        ),
`

As i read in elasticsearch-documentation, the multifield value is'nt supported anymore with ES 5.x.

Do i'm anything wrong or is here an issue with es4s 5.x and es 5.x

Regards,
Laszlo

**Comment by sksamuel** [comment]
Yep its been removed. I'll remove it from e4s.

**Comment by sksamuel** [comment]
Actually spoke too soon, we just need to tweak the way it uses the multi fields as it changed slightly in 5.x

**Comment by JohnGretzki** [comment]
Oh, no problem, actually i use the following workaround:
`
textField(MasterDataKeys.MARKE_TXT).fields( textField(MasterDataKeys.MARKE_TXT).index(IndexKeys.Analyzed), textField(IndexKeys.Keyword).analyzer(KeywordAnalyzer), textField(IndexKeys.Raw).index(NotAnalyzed) ),
`
That worked for me.

Thanks and btw. thank you for your fantastic work!

Regards,
Laszlo

**Comment by sksamuel** [comment]
The old multi_fields method has been removed now. That's been removed in elasticsearch 5.0 and you should continue with the nested fields like you have been.
