### ISSUE TITLE
client.show doesn't exists anymore in 5.2.4

### ISSUE THREAD

**Issue by JohnGretzki** [sksamuel/elastic4s#745]
Hi,
if you wrote here:
http://stackoverflow.com/questions/30864841/how-track-json-request-sent-to-elasticsearch-via-elastic4s-client
with elastic4s 5.2.0+ it is possible to generate the json-output of requests with the client.show method.
Did you mean the standard TcpClient?
In my project, there is no .show-method on the TcpClient. 
Is it possible that there is a missing dependency?

Actually there are the following dep. inserted:
`
  "com.sksamuel.elastic4s" % "elastic4s-core_2.11" % "5.2.4",
  "com.sksamuel.elastic4s" % "elastic4s-tcp_2.11" % "5.2.4",
  "com.sksamuel.elastic4s" % "elastic4s-embedded_2.11" % "5.2.4",
`

Regards,
Laszlo

**Comment by sksamuel** [comment]
I had added it to HttpClient and not TcpClient so my bad. I've added it now and will release 5.2.6.
