### ISSUE TITLE
Support for Secured AWS ElasticSearch

### ISSUE THREAD

**Issue by lostinplace** [sksamuel/elastic4s#749]
Is there a way (or a plan) to support IAM secured clusters on AWS ElastiscSearch?

**Comment by sksamuel** [comment]
What does IAM require?

**Comment by lostinplace** [comment]
You have to sign the requests with your AWS credentials

see https://aws.amazon.com/blogs/security/how-to-control-access-to-your-amazon-elasticsearch-service-domain/

**Comment by sksamuel** [comment]
If its an Amazon specific thing then I don't think it should be part of a
general e4s project.

**Comment by lostinplace** [comment]
does that mean that if I were to submit a pull request that did this, it would be rejected?

**Comment by sksamuel** [comment]
It really depends on what the support is for. If its something unique to elasticsearch then it would be fine to add to elastic4s. If it's a generic authentication used by all of Amazon's services then its better in some amazon library no?

**Comment by sksamuel** [comment]
Do you think this would work, if I add a hook into the HTTP client to use it easily?
https://github.com/inreachventures/aws-signing-request-interceptor

**Comment by lostinplace** [comment]
yup, that's exactly what's needed

**Comment by mdarcemont** [comment]
I'm very interested in a hook into the HTTP client too.

**Comment by alex1712** [comment]
I hope you already to work, but I use the same principle as the apache interceptor described previously and it works for me.

The only difference is that I had to modify the Host header to remove the port.

Here is the code -> https://gist.github.com/alex1712/f41091ea316b6cdb0429dda71151a6d9

Maybe can help someone.

**Comment by lustefaniak** [comment]
Would be great if something like that was provided in elastic4s. Probably as additional module.

**Comment by dmitry-avershin** [comment]
@sksamuel I can support here if needed

**Comment by sksamuel** [comment]
@dmitry-avershin feel free to create a PR. I would be looking at doing something along the lines of the link I posted in this thread, or open to other ideas.

**Comment by nemo83** [comment]
Hey all, I'm interested in this feature too. Is the hook implemented on any branch? Or shall I temporarily implement the code as per @alex1712? Please feel free to ping me if you need anyone to test it on AWS !

Great work everyone!

**Comment by sksamuel** [comment]
Yep please have a go.

**Comment by nemo83** [comment]
Ok, I did a test with @alex1712 snippet and elastic4s version `"5.4.3"` and it works like a charm.

I can work on a PR if no else is working on it....

**Comment by sksamuel** [comment]
I'm not working on it personally, there's been no movement from others so I think it's safe to pick up.

**Comment by saraiva132** [comment]
Would also love to have this. @nemo83, are you working on a PR?

**Comment by nemo83** [comment]
unfortunately not :-( @saraiva132

**Comment by saraiva132** [comment]
@alex1712 gist seems to contain everything I need which is cool. However, the dependency to aws-request-signer worries me. I will look into it as well and If I figure a decent enough solution I might look if it is enough for a PR.

**Comment by alex1712** [comment]
Hi, thanks for taking care.

This depency is actually this project here :
https://github.com/ticofab/aws-request-signer

Is only one class if you want a check the code.

**Comment by saraiva132** [comment]
@alex1712 Yeah, I have read the code and am also reading the aws documentation for signing (version 4). I am working on a request-signer and an object to provide a client with the interceptor and afterwards I will try and make a PR to see if this can be added to elastic4s 6 as a module. So basically the same as your gist and that project.

**Comment by sksamuel** [comment]
What I think we need is an elastic4s-aws module which contains an apache http interceptor. This interceptor would use the aws signer to sign the requests. Then the user can add the interceptor to the HttpClient, and we can provide an AwsHttpClient object method to do that conveniently.

**Comment by saraiva132** [comment]
@sksamuel Yep. Will work on just that.

**Comment by saraiva132** [comment]
@sksamuel I just finished my first working draft (took me longer than expected. Going to make the PR with my proposal soon, any advice from you? (i.e. expected tests, code style)

**Comment by sksamuel** [comment]
I'm not fussy - as long as there's tests for it, and it works, I'm happy :)

**Comment by sksamuel** [comment]
Merged into 6.0

**Comment by uccmen** [comment]
How do I use this? I see no documentation on README or wherever.

**Comment by hekaldama** [comment]
@uccmen did you get an answer figure it out?

**Comment by uccmen** [comment]
@hekaldama - I got it to work with the below conf.
```
val elasticEndpoint = s"elasticsearch://$esHost:$esPort?ssl=true"
val esConfig = Aws4ElasticConfig(elasticEndpoint, awsAccessKey, awsSecretKey, awsRegion)
val esClient = Aws4ElasticClient(esConfig)
```

and sorry for the late response!
