### ISSUE TITLE
`c.s.e.s.ScrollPublisher` stops before timeout when all current items have been retrieved

### ISSUE THREAD

**Issue by briantopping** [sksamuel/elastic4s#750]
Hi, thanks for your efforts on a great project.

I'd like to understand the motivation behind https://github.com/sksamuel/elastic4s/blob/master/elastic4s-streams/src/main/scala/com/sksamuel/elastic4s/streams/ScrollPublisher.scala#L139. I would like to monitor an ES index for hits that match a query and have the publisher provide those hits until the timeout is reached. 

What I am expecting is for the query to keep running, and when I add a new item to the index, it is published by the reactive publisher.

Instead, the publisher shuts down as soon as the query returns no more immediate results. As there are no conditionals around the line I included above, I am led to believe that I am using the code correctly but it does not handle this use case.

Any feedback appreciated!

**Comment by sksamuel** [comment]
The scroll API only shows a snapshot of items, so that once the scroll has been created, items added after that date will not appear in previous scroll requests. So once the scroll query stops returning items, you know its completed. That's the rationale behind this behavior.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

**Comment by briantopping** [comment]
Ah, thanks!

Is it sensible that there might be additional behavior that elastic4s can provide? If not, it just gets left up to the client to write code to fit the requirement, in which case pretty much all of the publisher code needs to be rewritten. It is very tightly encapsulated and there's really no way to reuse any of it with the way it's currently built.

**Comment by sksamuel** [comment]
What additional behaviour are you asking for - the ability for the stream to pick up new items as they arrive? If so then this is really difficult to do properly, and what we need is https://github.com/elastic/elasticsearch/issues/1242
Without that its best left to the user to decide on their strategy.
