### ISSUE TITLE
Modification of live Publisher query

### ISSUE THREAD

**Issue by briantopping** [sksamuel/elastic4s#751]
Use case: A bidirectional stream is established using using `ScrollPublisher.subscribe()` with a query. The stream peer receives hits over the stream as they are returned from the publisher. As the hits are digested by the peer, it is necessary for the peer to update the query.  

Existing behavior: `ScrollPublisher` has only one public interface and all of the instantiated objects and actors are privately scoped. There is no way to change the query except to create a new `ScrollPublisher` with a new query. Since running streams cannot have elements changed, there is no way to swap out the old and the new `ScrollPublisher` without shutting down the stream, there is also no way to maintain the endpoint that is provided by the peer, since it will also be shut down.

Desired behavior: Since the `TcpClient` is called with a new query for each scroll page of results, it should be reasonable that the query can be changed as a part of that process. (It's reasonable to expect that the scroll would be reset as a part of the query being changed.) The least cost change seems to be that `PublishActor` would accept a message for a query change. I am not up-to-date with the Reactive APIs, but in Akka Streams, the pattern would likely be for `PublishActor` to be exposed as a materialized value to the stream.

With the desired behavior, the running stream could accept new queries from the peer and new hits would be put on the stream as available. 

Lastly, a correlation value would be required so the peer could know which hits came from which query (there may be latency between when the query is updated and the new hits start arriving). 

Stretch goal: The discriminator would allow multiple concurrent queries to be active. In this case, the peer could add and remove queries with the hits sent to the subscriber as they arrive.

**Comment by sksamuel** [comment]
I think its a reasonable change to have the publish actor accept a new query, the question is, what about pending requests, should they be ignored, and a new query then "resets" it ?

**Comment by sksamuel** [comment]
After re-visiting this, I don't think it makes sense to change the query - it would be too complicated with inflight requests, when you can easily just stop the stream and make a new one.
