### ISSUE TITLE
Optional dependencies causing stub warnings

### ISSUE THREAD

**Issue by solicode** [sksamuel/elastic4s#754]
I noticed that the `Class ___ not found - continuing with a stub.` warning still exist in certain cases. For example, if you create a simple hello world application with just the following dependencies, the stub warnings will show up:

```scala
"com.sksamuel.elastic4s" %% "elastic4s-core" % "5.2.7",
"com.sksamuel.elastic4s" %% "elastic4s-http" % "5.2.7",
"com.sksamuel.elastic4s" %% "elastic4s-jackson" % "5.2.7"
```

When using `elastic4s-tcp`, the problem disappears.

I went looking for why that is, and it's because of how the dependencies are currently set up. Only the tcp project has the dependencies for `spatial4j`, `jts`, etc. `elastic4s-http` does not have these.

The real cause of all this is actually elasticsearch's use of optional dependencies [here](https://github.com/elastic/elasticsearch/blob/d235e489e6b36b4c84661b927481cd8cdcb87801/core/build.gradle#L79-L87).

To solve this, I only see 2 options:

1. Mark these dependencies Optional in all the elastic4s subprojects that use them. By doing this though, anybody who consumes elastic4s has to also add these dependencies in their own project (optionally marking them as `Optional` as well).
2. Simply make them compile dependencies in elastic4s (in core though, not just tcp). 

Personally, I like option 2 because optional dependencies seem to be quite problematic in Scala. It's up to you though. The tradeoff seems to be ease of use vs file size (due to potentially unnecessary jars being pulled in).

Since I already have option 2 ready, I'll create a PR. If you want to go with a different solution though, I can change it.

**Comment by sksamuel** [comment]
Adding in the spatial4j is ok to HTTP as that's a small enough dep that I'm sure it won't bloat builds. As for the changes you made to TCP - if you remove the lucene deps, it'll break. They're needed to run the TCP client.

**Comment by solicode** [comment]
Are they not already included with the `"org.elasticsearch.client" % "transport" % ElasticsearchVersion`? 

[transport](https://mvnrepository.com/artifact/org.elasticsearch.client/transport/5.2.0) -> [elasticsearch](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch/5.2.0)

Unless there's a reason to explicitly declare the transitive dependencies. I just figured it would cause more problems in the long run by accidentally pinning it to an older version of Lucene when it comes time to update `ElasticsearchVersion`.

**Comment by sksamuel** [comment]
No they aren't. You'd think so since they're needed to work!!!
https://github.com/sksamuel/elastic4s#release

**Comment by solicode** [comment]
Okay, now you're scaring me... 😛 That would invalidate everything I thought I knew about Maven. Please don't let that be the case.

Apparently I'm not seeing the same thing you are though. I see the transitive dependencies listed with `sbt dependencyTree` and I even ran one of my projects with my 5.2.8-SNAPSHOT and I haven't run into any problems so far.

**Comment by sksamuel** [comment]
If you look in maven they are marked as compile time only. They're not included in any fat jars you build.

**Comment by solicode** [comment]
Also, I was conflicted about keeping the logging dependencies `compile`, but I left it because that's what it was already set to. But I could see somebody in the future filing an issue about making that `Optional`.

**Comment by sksamuel** [comment]
If you try it without lucene it all breaks. There are issues in the issues
history about it.

**Comment by solicode** [comment]
I looked through the history. Some are just version conflict issues which is a different issue altogether (like the Play one, or the Lucene version mismatches). The rest look like they might be the fat jar problem, which yes, apparently can sort of [be solved](http://stackoverflow.com/a/38354027) by explicitly adding the Lucene dependencies and giving them priority. Merging [META-INF/services](https://github.com/elastic/elasticsearch/issues/3350#issuecomment-21283417) seems like the "proper" solution though.

Anyway, I won't push this further. If the current solution is working, then it can be kept as is.

Ignoring that, the "stub" issue still remains. A lot of people are going to run into that, especially the ones who treat warnings as errors. If you want to keep them all optional, that seems reasonable too. It would probably just be a good idea to put a note about it in the README in that case since we know the cause.

**Comment by sksamuel** [comment]
I'd prefer to keep the status quo on the deps for the tcp client and merge a pr with your fixes for the http client. Sound ok?

**Comment by solicode** [comment]
Making the 5 optional dependencies all compile? Okay, I did that and reverted my Lucene changes.

I hope the logging dependencies don't turn out to be an issue, but we'll see. I guess it's not hard to swap out if needed.
