### ISSUE TITLE
Allow to use HttpClient with streams

### ISSUE THREAD

**Issue by dzebleckis** [sksamuel/elastic4s#757]
Hello,

I was wondering if there are any reasons why TcpClient is used for stream Subscriber implementation? If there are no hidden obstacles I could try to implement one using HttpClient. What could be best approach, having something like typleclass with method `execute(req: BulkDefinition): Future[RichBulkResponse]`or try to separate `BulkIndexingSubscriber` into different packages for http and tcp? I hope I've made myself clear enough :)

**Comment by sksamuel** [comment]
The only reason is because HTTP is brand new to 5.2.x and there hasn't been time to retro fit the elastic4s-streams module to use it.

I think the best solution might be the typeclass approach.

```scala
trait StreamClient {
  execute(req: BulkDefinition): Future[RichBulkResponse]
}
```

Or something even more generic

**Comment by sksamuel** [comment]
Maybe the typeclass could support #751 too

**Comment by sksamuel** [comment]
5.4.2 has the new http-streams module.
