### ISSUE TITLE
IndexDefinition missing versionType parameter

### ISSUE THREAD

**Issue by tyth** [sksamuel/elastic4s#760]
Currently (version 5.2+) there is no way to specify a version_type parameter for `index` query.

**Comment by colestanfield** [comment]
Why is this closed? This is most definitely in the 5.2.1 jar [(code)](https://github.com/elastic/elasticsearch/blob/5.2/core/src/main/java/org/elasticsearch/action/index/IndexRequestBuilder.java#L200-L203) and is documented [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html#_using_versions_from_an_external_system).
