### ISSUE TITLE
HttpClient, fetchSourceContext works partially with simple GET

### ISSUE THREAD

**Issue by camory** [sksamuel/elastic4s#766]
With the HttpClient, fetching source context works partially with a simple GET

```scala
client.execute {
    get(id) from("beer" / "lager") fetchSourceContext(List("*"),List("type"))
}
```
All the fields of __source_ are returned. **_But the field `type` should not be returned_**

```scala
client.execute {
    multiget(
        get(id) from("beer" / "lager") fetchSourceContext(List("*"),List("type"))
    )
}
```
All the fields of __source_ except `type` are returned as expected.

```scala
client.execute {
    get(id) from("beer" / "lager") fetchSourceContext(false)
}
```
 __source_ is not returned  as expected.

**Comment by sksamuel** [comment]
You're saying include everything, but then exclude type. Does the exclude override what you say in include? The docs don't seem to specify it. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html

**Comment by sksamuel** [comment]
You were right there was a bug, so I've fixed it. However you still don't need to specify _*_ when using exclude, so I've added a couple of helpers. So you can do `get(id).from(x/y) fetchSourceExclude("type")` if you wish.

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/get/GetHttpTest.scala#L76-L107

**Comment by camory** [comment]
My examples are not clear. I put a `*` in the include list for simplicity but finally it is disturbing.

Here is another example which does not work:
```scala
client.execute {
    get(id) from("beer" / "lager") fetchSourceContext(List("country"),List("type"))
}
```
All the fields of __source_ are returned but it should only return `country`

**Comment by camory** [comment]
You are too fast !! :-). When will you release this fixed ?

**Comment by sksamuel** [comment]
By Sunday night.
