### ISSUE TITLE
Fuzziness options in the 'CompletionSuggestionDefinition'

### ISSUE THREAD

**Issue by nolledge** [sksamuel/elastic4s#774]
Hi,
I cant figure out how to set fuzziness option like 'min_length' and 'prefix_length' for the the 'CompletionSuggestionDefinition'? Am I missing something? I remember using that feature in previous versions.

**Comment by sksamuel** [comment]
Those seem to have been missed in the split out from core/tcp. I've restored it so will be in 5.2.10

**Comment by nolledge** [comment]
Thank you very much!
