### ISSUE TITLE
Error in importing x-pack-transport

### ISSUE THREAD

**Issue by salvob41** [sksamuel/elastic4s#775]
I added the dependency in my `build.sbt`:

`"com.sksamuel.elastic4s" % "elastic4s-xpack-security_2.11" % "5.1.5+"`

and this is the error

```
Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#api;0.13.13 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.13 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.13 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.scala-sbt#test-agent;0.13.13 ...
[info] Resolving org.scala-sbt#classfile;0.13.13 ...
[info] Resolving org.scala-sbt#completion;0.13.13 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.13 ...
[info] Resolving org.scala-sbt#logging;0.13.13 ...
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.elasticsearch.client#x-pack-transport;5.1.1: not found
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: org.elasticsearch.client#x-pack-transport;5.1.1: not found
[error] Total time: 13 s, completed Mar 1, 2017 4:40:59 PM</pre><br/>See complete log in <a href="/Users/salvob/Library/Logs/IdeaIC2016.3/sbt.last.log">/Users/salvob/Library/Logs/IdeaIC2016.3/sbt.last.log</a>
```

What am I missing?
Thank you in advance, Keep up the good work :D

**Comment by salvob41** [comment]
I can't find the repository
`org.elasticsearch.client` - `x-pack-transport`

In fact the link https://mvnrepository.com/artifact/org.elasticsearch.client/x-pack-transport is dead

**Comment by salvob41** [comment]
This dependency in `maven` works fine, though. But in `sbt` it gives the error above mentioned

**Comment by sksamuel** [comment]
Remove the plus after the version number?

**Comment by salvob41** [comment]
@sksamuel  no luck, Can't you reproduce it?

**Comment by sksamuel** [comment]
No works fine for me.

**Comment by salvob41** [comment]
Have you anything set in your `build.sbt` as `resolvers` for example?

**Comment by salvob41** [comment]
in my `build.sbt`, adding 
`resolvers +=  "elasticsearch-releases" at "https://artifacts.elastic.co/maven"`
fixed the issue. SBT, in fact, use as default the `maven` repository as explained [here](http://www.scala-sbt.org/0.13/docs/Resolvers.html). But the package `x-pack-transport` for some reason is not in that repository (anymore?). So you have to specify the repository `https://artifacts.elastic.co/maven` instead.

It might be a simple thing that I didn't know, maybe you could add this to the documentation?

Thank you very much!

**Comment by sksamuel** [comment]
Ah they must have moved it.

**Comment by sksamuel** [comment]
I've updated the readme.
