### ISSUE TITLE
_id is no longer configurable and the options to do so should be removed from e4s

### ISSUE THREAD

**Issue by nvartolomei** [sksamuel/elastic4s#777]
```scala
createIndex("index").mappings(
  mapping("hello").fields(
    id typed TextType analyzer KeywordAnalyzer store true includeInAll true,
  )
)
```

throws `IllegalArgumentException[Field [_id] is defined twice`

Example from [Analyzers](https://github.com/sksamuel/elastic4s/blob/v5.2.9/guide/analyzers.md) doc.

Using elastic4s v5.2.9. ES 5.2.2.

**Comment by sksamuel** [comment]
_id needs to be removed from elastic4s. So I'll use this ticket for that change.
See https://www.elastic.co/blog/great-mapping-refactoring#meta-fields
