### ISSUE TITLE
Possible regression in 5.2.9: stackoverflow on filteredAggregations with a subAggregations

### ISSUE THREAD

**Issue by halvorgb** [sksamuel/elastic4s#778]
I've made a runnable repository with reproduction instructions:
https://github.com/halvorgb/elastic4s-5.2.9-debugging

This is the query that fails: 
```scala
  def someQuery: AggregationDefinition =
    filterAggregation("filtered").query(
      filter(
        rangeQuery("some_date_field")
          .gte("now-1y")
          .to("now")
      )
    ).subAggregation(
        dateHistogramAggregation("per_month")
          .field("some_date_field")
          .interval(DateHistogramInterval.MONTH)
          .minDocCount(0L)
      )
```

**Comment by sksamuel** [comment]
Tcp or http.

**Comment by halvorgb** [comment]
Afaik the DSL is shared between TCP and HTTP. So neither?

Look at the repository i posted, it's a tiny example.

Den tor. 2. mar. 2017, 18.39 skrev Stephen Samuel <notifications@github.com
>:

> Tcp or http.
>
> On 2 Mar 2017 2:48 p.m., "Halvor Granskogen Bjørnstad" <

**Comment by sksamuel** [comment]
Ok I see. I've already fixed this the other night and it will be in release 5.2.10. your workaround at the moment is to use the method that accepts a seq of sub aggs.

**Comment by sksamuel** [comment]
I've added a test for this too now.
