### ISSUE TITLE
JsonParseException with http client due to StringEntity encoding

### ISSUE THREAD

**Issue by Fangrou** [sksamuel/elastic4s#783]
Hi @sksamuel ,
I'm using elastic4s http client and encountered an exception because of letters with accents. My exception is exactly the same as the one I found in the following link:
https://discuss.elastic.co/t/es5-2-restclient-content-type/74741

The default encoding of StringEntity is iso-8859-1 when no content type is specified. While if we initialize the StringEntity with JSON content type, the default encoding is UTF-8. I think this is what we should do for ES http client.

I tried to fix in my fork: https://github.com/Fangrou/elastic4s/commit/5f3c81703e67f0306f0f597fbcdab0ac19a94e1c . Please have a review on it #782 .

Cheers,
Fangrou

**Comment by sksamuel** [comment]
Yes perfect.
