### ISSUE TITLE
Support eager loading in mappings

### ISSUE THREAD

**Issue by tiancheng0307** [sksamuel/elastic4s#784]
I don't see an option to enable eager loading for data fields: https://www.elastic.co/guide/en/elasticsearch/guide/current/preload-fielddata.html

This mapping definition is what I was looking at:
https://github.com/sksamuel/elastic4s/blob/221e92abc44c50ee3aba7c1464541e2cdf4905a2/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/mappings/MappingDefinition.scala#L26

**Comment by sksamuel** [comment]
I'll add it to 5.2.11

**Comment by tiancheng0307** [comment]
Thank you!

**Comment by sksamuel** [comment]
Was looking at this now, but I can't seem to find it in elasticsearch 5.2. I wonder if its been dropped?

**Comment by tiancheng0307** [comment]
It seems that it is still supported but the query has been changed:
https://www.elastic.co/guide/en/elasticsearch/reference/current/_pre_loading_data_into_the_file_system_cache.html

Would it be possible to also add support for 2.x? Our clusters are still using 2.x and not upgraded yet.

**Comment by sksamuel** [comment]
You can set index settings already using the create/put index api which will work in any version of elastic4s. You can pass in any key value pairs so you should be good.
