### ISSUE TITLE
Circe could not find implicit decoder for http.search.SearchResponse 

### ISSUE THREAD

**Issue by mstockerl** [sksamuel/elastic4s#786]
If you use the experimental HttpClient together with Circe compilation fails with the following error: 

> could not find implicit value for parameter format: com.sksamuel.elastic4s.JsonFormat[U]
> [error]     val result: SearchResponse = Await.result(httpClient.execute { search("test") }, atMost = timeout)

After some investigation, we figured out that the reason for this behavior lies within the usage of **AnyRef** in the parameter list of [SearchHit](https://github.com/sksamuel/elastic4s/blob/217e3cc5947a2724d1ae758805dc4fd448afd49c/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/responses.scala#L12).

We verified the behavior with the following (failing) test case: 

```scala
import org.scalatest.{FunSuite, Matchers}

class AnyRefTest extends FunSuite with Matchers {

  type withAnyRef = Map[String, AnyRef]
  type withoutAnyRef = Map[String, Int]

  test("Implicitly find decoder for a map with AnyRef value type") {
      """
        import io.circe.generic.auto._
        import io.circe.Decoder
        implicitly[Decoder[withAnyRef]]
      """ should compile
  }

  test("Implicitly find decoder for a map with concrete value type") {
    """
        import io.circe.generic.auto._
        import io.circe.Decoder
        implicitly[Decoder[withoutAnyRef]]
    """ should compile
  }
}
```

**Comment by muuki88** [comment]
The current circe `JsonFormat` definition is implemented very simple:

Converting a `Hit` into a type `T` just uses the json source via `sourceAsString` from `Hit` and let circe do all the parsing.

```scala
def read(hit: Hit): Either[Throwable, T] = decode[T](hit.sourceAsString)
```

Would writing a `JsonFormat[SearchHit]` do the trick? E.g.

```scala
import io.circe._
import com.sksamuel.elastic4s.http.search._

implicit def httpSearchHitDecoder[T](
   implicit decoderT: Decoder[T]
): Decoder[SearchHit]] = Decoder[SearchHit].instance {
   hit => decode[T](hit.sourceAsString)
}
```

**Comment by kshakir** [comment]
Different group than the OP, but the fixes above work for us.

The latest 5.3.3-SNAPSHOT built from source works much better with circe and `IndexDefinition.doc` / `SearchResponse.to`. We're of course not trying reproduce the exact tests above-- trying to get circe to convert json to `AnyRef`, but jackson seems to be doing a fine job of that inside elastic4s.

Eagerly anticipating the eventual release.

**Comment by sksamuel** [comment]
5.4 supports circe by hiding the internal json marshalling.
