### ISSUE TITLE
Unifying TCP and HTTP tests

### ISSUE THREAD

**Issue by solicode** [sksamuel/elastic4s#790]
I made a quick little prototype because I wanted to get a better idea of what it would take to unify the TCP and HTTP tests. The motivation being to reduce copy/pasting and to uncover differences/bugs between the two APIs.

I'm not even sure if you're interested in unifying the tests, so I think I'll stop here and ask for your thoughts first.

I know the idea is that TCP will eventually be deprecated, but it's not clear when support will be completely dropped. If we're talking 1-2+ years, then the TCP tests will probably be around for a while.

Anyway, my experimental changes are [here](https://github.com/solicode/elastic4s/commit/becf332a413197f56278728769e3b9762ab1b4ec?w=1). For now I only converted `CountTest` and `BoolQueryTest` as an example.

The basic idea is that the test definitions remain almost the same, but the "dual" test helper runs each decorated test suite twice: once for HTTP, then once more for TCP, each in their own LocalNodes so that they don't interfere with each other.

I wouldn't mind going through all these tests and merging the TCP and HTTP tests that are basically the same (and add the ones that are completely missing on one side). Since the features aren't completely 1:1, I could mark the stuff that isn't yet complete with TODOs to give a clearer picture of what's missing. For stuff that only has an implementation on one side, maybe a little `tcpOnly { ... }` or `httpOnly { ... }` helper block or something could be used.

I'm getting ahead of myself though... I'd like to know what you think first.

**Comment by sksamuel** [comment]
I like the idea. It certainly saves writing two sets of tests and is better than the current approach.
One improvement might be to use the HTTP response classes as the _canonical_ model, and have adapters for the Java types? That might be easier than having to create a _common_ response model. As for TCP it will probably exist until version 6 at least I would have thought.

**Comment by solicode** [comment]
Ah, I see what you mean. That way the number of implicits needed gets cut in half (only need ones that convert the tcp models to the http models). That sounds like a good idea to me. And whenever it comes time to drop support for TCP, the transition would basically just be getting rid of the conversions, leaving you with the HTTP models which can be used as is.

So you're okay with me attempting this "for real" this time? It might be better to do this in chunks rather than all in one go. I'm thinking start off with converting a few tests, check back in to make sure things look good or if some refactoring is needed, and then take on progressively bigger chunks.

I'm expecting to hit a few roadblocks, but I won't know until I get deeper in the code. And I'll try to do the tests for the stuff that seems more stable and unlikely to change first.

**Comment by sksamuel** [comment]
I'm very happy for you to tackle this. And I think converting just a single
test is a good starting point.
 Something simple like create index.

On 7 Mar 2017 5:51 p.m., "Solicode" <notifications@github.com> wrote:

Ah, I see what you mean. That way the number of implicits needed gets cut
in half (only need ones that convert the tcp models to the http models).
That sounds like a good idea to me. And whenever it comes time to drop
support for TCP, the transition would basically just be getting rid of the
conversions, leaving you with the HTTP models which can be used as is.

So you're okay with me attempting this "for real" this time? It might be
better to do this in chunks rather than all in one go. I'm thinking start
off with converting a few tests, check back in to make sure things look
good or if some refactoring is needed, and then take on progressively
bigger chunks.

I'm expecting to hit a few roadblocks, but I won't know until I get deeper
in the code. And I'll try to do the tests for the stuff that seems more
stable and unlikely to change first.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/elastic4s/issues/790#issuecomment-284801694>,
or mute the thread

**Comment by solicode** [comment]
Okay, thanks. I'll get started on it soon.

**Comment by solicode** [comment]
Okay, I cleaned up the code and got rid of the copy/pasting I had done in the last commit.

So far I have `CreateIndexTest`, `FlushIndexTest`, `CountTest`, and `BoolQueryTest` done. More individual tests could be added to each, but I'm just focusing on the conversion of the existing tests for now.

The only issue so far has been what to do when the HTTP model has fields that can't be found in the TCP model (or inside `original`). It's hard for me to determine whether the field inside the HTTP model is supposed to be there or not. For example, `IndexResponse.totalHits`. I didn't know totalHits existed on responses other than search responses. Or is that an issue with the HTTP model?

For stuff that I can't find, I'm just filling them with `null` and putting a TODO on them. I'm actually not sure if the goal is to cover all the fields 100%. It would certainly be ideal, but technically only the fields that are being asserted on need to be converted (but might as well additionally do the fields that are trivial to convert regardless if they are being asserted on).

My latest changes are [here](https://github.com/sksamuel/elastic4s/compare/master...solicode:unify-tests?w=1).

**Comment by sksamuel** [comment]
I think the `totalHits` in [here ](https://github.com/sksamuel/elastic4s/blob/6e52f635842739d3f9834f40fedb496237c74e94/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/index/IndexResponse.scala)is a mistake and can be removed. Probably just a copy n paste error.

**Comment by solicode** [comment]
Yeah, looks like it. There were a bunch more in IndexResponse, so I removed those too.

Unfortunately I don't see docs/schemas for the Elasticsearch responses (only the requests). Even making sample requests and seeing what fields come back isn't reliable because sometimes fields get excluded entirely when null.

The most reliable way I've found so far is to just go [straight to the source](https://github.com/elastic/elasticsearch/blob/f9d9b74f0fb6d9be39d27f658479556230ecd8c1/core/src/main/java/org/elasticsearch/action/index/IndexResponse.java#L65) and inspect `toXContent` all the way up the inheritance tree for a particular resource to find all the fields. Maybe there's a better way, but I haven't found one so far.

Anyway, I did that for IndexResponse and also merged `IndexTcpTest` and `IndexHttpTest` to 1 file.

**Comment by solicode** [comment]
Okay, all tests in `elastic4s.indexes.*` have been converted. I also fixed the ignored and commented out tests in there. And various fixes like missing asserts and so on.

Everything in `elastic4s.delete.*` is also done. Here I found an issue with `HttpClient` where "valid" failure responses weren't returning. For example, when you try to delete a document that doesn't exist, you don't get a DeleteResponse with `found = false`. It just blows up with an exception instead (the same would be true for other responses like `GetResponse` as well). Anyway, that should be fixed now.

Maybe this is a good stopping point for review? Since there are quite a few bug fixes included and so on, if I continue, the PR could get too big and difficult to review. Whenever you get some free time, can you look over what I have so far? If you have any suggestions, I can fix those before preparing the PR. Or if you have any questions on what I've done so far I can answer those.

Thanks. 🙂

**Comment by solicode** [comment]
Also, maybe you forgot to commit some code in the [last push](https://github.com/sksamuel/elastic4s/commit/f702cb44d9eacf122dc7198bdcfac9932c54afc0)? Some of the tests broke, and I got compiler errors as well. For example, `maxInputLength` doesn't seem to exist. I fixed them on my branch, but just letting you know.

But yes, another reason I don't want this PR to get too big is because the merge conflicts are increasing as it grows. 😛

**Comment by sksamuel** [comment]
Likely I did, as I have a big field definition change pending and I probably messed up the commits as its all green locally.

**Comment by sksamuel** [comment]
I'm not sure if I can comment without a PR as I tried and can't figure it out.

**Comment by solicode** [comment]
Okay, that's fine. Maybe it's better that I wait for those changes, and then I'll fix the resulting conflicts on my side.

**Comment by sksamuel** [comment]
That suits me :)
Should hopefully not affect you anyway. Change will be up within the hour.

**Comment by sksamuel** [comment]
Commited.

https://github.com/sksamuel/elastic4s/commit/817d25c574d594a33bb28aca64d581a065a03af9

I've overhauled the field definitions so that they're aligned with the latest 5.x code. I noticed that some field types no longer existed, others had properties that no longer existed, and others were missing latest properties. Also it was using the previous style of code which focused on DRY over immutability and clarity. - I prefer the latter.

**Comment by solicode** [comment]
That wasn't too bad. 🙂 I merged the changes instead of rebasing because I wasn't sure if you checked out my changes and I don't want to change history in that case.

The inner and nested query tests that I had uncommented earlier don't compile now, so I commented them out again. Those methods don't exist on `BasicFieldDefinition`.

Other than that, everything else looks good to me.

**Comment by sksamuel** [comment]
Ready for a PR then ?

**Comment by solicode** [comment]
Okay, I created the PR. If you want me to clean up the history, I'll have to come back to that later today.

**Comment by solicode** [comment]
Thanks. Now that that's merged and the base is all there, I'm going to do the rest of what can be done. So you'll probably see a stream or PRs relating to this ticket whenever I get time to work on it. I'll try to split them up in logical chunks.

**Comment by sksamuel** [comment]
I think we can close this now, you've unified most of them, and any further ones you want to do don't require a ticket. I'll also migrate over some, but I'm focused mostly on finishing the HTTP support - it's quite advanced now.
