### ISSUE TITLE
Regex Query for elastic4s-http doesn't use `regex` field

### ISSUE THREAD

**Issue by zlumyo** [sksamuel/elastic4s#821]
As I can see in [RegexQueryBodyFn](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/term/RegexQueryBodyFn.scala) no pattern writes to final json. In case of that output of RegexQuery's serialization is
```
{
  "regexp": {
    "FIELD": {}
  }
}
```

**Comment by sksamuel** [comment]
Ok easy fix. If you do a PR I'll merge it otherwise I'll get to it soon.

**Comment by zlumyo** [comment]
Fixed with PR #822
