### ISSUE TITLE
migrating to 5.2 show method is not showing the json request

### ISSUE THREAD

**Issue by 123avi** [sksamuel/elastic4s#825]
in 2.X `show` method was showing the json request . which was excellent for logging but now it seems just calling `toString` on the query object. how can I log the query object ?

**Comment by sksamuel** [comment]
Are you on the latest 5.2.x because it was fixed in a subsequent release.

**Comment by 123avi** [comment]
yes, using 5.2.11 this how the `.show` method on `IndexInto` looks like :
`Indexing: {"my_type":"foo","name":"test112","component":"cpu","device":"dd"}`

**Comment by 123avi** [comment]
@sksamuel my last answer is partially true. some object are showing the json request (such as search , aggregations ... ) and some are just showing the `.toString` version

**Comment by sksamuel** [comment]
Not all requests in the TCP client have a proper json version. You could use the http client? Or which one has regressed and I'll take a look.
