### ISSUE TITLE
Possible issue in aggregations-result with ES 1.6.x

### ISSUE THREAD

**Issue by JohnGretzki** [sksamuel/elastic4s#842]
Hi,
currently i try to resolve a problem with possible aggregations-results in the processing of a query with elastic4s.
Scenario:
I search over all and aggregate a specific field. The (json-) translated query looks like this:
`
{
  "query" : {
    "has_child" : {
      "query" : {
        "bool" : {
          "must" : {
            "match_all" : { }
          }
        }
      },
      "child_type" : "variant"
    }
  },
  "aggregations" : {
    "variant" : {
      "children" : {
        "type" : "variant"
      },
      "aggregations" : {
        "MARKEN_SL.raw" : {
          "terms" : {
            "field" : "wws.MARKEN_SL.raw",
            "size" : 10000
          }
        }
      }
    }
  }
}
`
Where `wws.MARKEN_SL.raw` is the aggregated field. The match-all-query above is ok, so it's guarenteed that every document have the field (but i can also use an exists-query for wws.MARKEN_SL, for the result/issue, there's no difference).

If i search with postman with this query i receive a resultset with 2138 different keys. With elastic4s, the length of the buckets-list is 2022.

At the moment, i use the following method to extract the aggregation-results for my app. I'm only interested in keys and doccount.

`
  def getAggregations(searchResponse: SearchResponse): Map[String, List[(String, Long)]] = {
    searchResponse.getAggregations.asList().flatMap {
      _.asInstanceOf[InternalChildren].getAggregations.asList()
        .map(_.asInstanceOf[Terms])
        .map{terms =>
          val buckets: List[Bucket] = terms.getBuckets.toList
          val result: List[(String, Long)] = buckets.map(bucket => bucket.getKey -> bucket.getDocCount)
          terms.getName -> result
        }
    }.toMap
  }
`

I don't see any error or else. The method getAggregations ist called within a future e.g. 
Future[SearchResponse].map(getAggregations(_)).....

Is there a limit or something else that i'm attend?

Regards,
Laszlo

**Comment by sksamuel** [comment]
The limit will just be an issue with the underlying java client. 1.6 was last updated on 29-Jul-2015 so its quite out of date. I'd suggest you upgrade to 5.x at least.

**Comment by JohnGretzki** [comment]
Thank you. Update to ES 5.x is ongoing, refactoring in our project is done.
Waiting for the final play 2.6 Update (actually work with play 2.6 m3).

Regards,
Laszlo
