### ISSUE TITLE
HDR percentiles aggregation support

### ISSUE THREAD

**Issue by fcofdez** [sksamuel/elastic4s#843]
I was trying to use [HDR histograms](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html#_hdr_histogram) for perecentile aggregations but I couldn't find any reference. Is it implemented? if not, are PRs welcome?

**Comment by sksamuel** [comment]
It's not currently implement, and a PR is most welcome.
