### ISSUE TITLE
Broken hyperlinks in README.md

### ISSUE THREAD

**Issue by animageofmine** [sksamuel/elastic4s#846]
Most of the links in README.md are broken and leads to 404. Can this be quickly fixed?  Thank you very much.

**Comment by zolrag13** [comment]
@muuki88, I have found more links to fix:

- line 181: Create Index
- line 185: Analyzers
- line 216: Indexing
- line 240: Searching
- line 241: Multisearch
- line 265: Get (2 links to fix)
- line 288: Deleting
- line 303: Updates
- line 338: Bulk Operations

Cheers

**Comment by muuki88** [comment]
Thanks. Will fix them too 😎
