### ISSUE TITLE
sourceFiltering doesn't work

### ISSUE THREAD

**Issue by unoexperto** [sksamuel/elastic4s#847]
Sadly nobody responds in gitter so I apologize for asking here.

`sourceFiltering` doesn't work for me. Here is what I have

```
    val req = search(indexType) limit 20 sourceFiltering(List("title"), Nil) query {
      boolQuery().
        must(
          matchPhrasePrefixQuery("title", query).maxExpansions(1),
          termsQuery("ct", 0, 1)
        )
    }

    val zzz2 = elasticsearch.show(req)
```

resulting json doesn't have `_source` element. I see that constructor of `FetchSourceContext` is called but `FetchSourceContext.writeTo` is never called. Could you please explain why ?

**Comment by sksamuel** [comment]
As discussed on gitter, it's the .show method that doesn't show it because its a http query param.
