### ISSUE TITLE
totalHits

### ISSUE THREAD

**Issue by jainh** [sksamuel/elastic4s#848]
How to get totalHits if i extend from HitAs[T] reader ?

**Comment by sksamuel** [comment]
Try using HitReader unless you're on an old version?

**Comment by jainh** [comment]
com.sksamuel.elastic4s" %% "elastic4s-core" % "2.3.1"

**Comment by jainh** [comment]
this is a snippet of my one of the models
```
implicit case object UserMappingHitAs extends HitAs[Mapping[User]] {

      import scala.collection.JavaConversions._

      override def as(hit: RichSearchHit): Mapping[User] = {
...
```

**Comment by sksamuel** [comment]
No, total hits is in the search response itself.

**Comment by jainh** [comment]
So except response i would not be able to get total hits?

**Comment by sksamuel** [comment]
Correct. An individual search hit doesn't know anything about the wider request, why would it.

**Comment by jainh** [comment]
Make sense from hitAs point of view, is there convenience method to deserialize whole `RichSearchResponse`   to  case class with total count and respective hits...

**Comment by sksamuel** [comment]
I'm not sure on 2.3, but on at least 5.0 you can do `to` on the search response itself to get back a Seq[T].

**Comment by jainh** [comment]
you mean it would give Seq[HitReader]? which is same as Seq[HitAs] right? then again how would i get totalCount ? does there a way to get outer hits as HitAs or Hitreader result of elastic search response ? 

example:

```
RichSearchResponse({
	"took": 1,
	"timed_out": false,
	"_shards": {
		"total": 5,
		"successful": 5,
		"failed": 0
	},
	"hits": {
		"total": 3,
		"max_score": null,
		"hits": [{
			"_index": "userdata",
			"_type": "project",
			"_id": "AVrQvfsN1I8jvHDBAI8i",
			"_score": null,
			"_routing": "test",
			"_parent": "test",
			"_source": {
				"name": "defaultProject",
				"createdDate": "2017-03-14 23:53:15",
				"updatedDate": "2017-03-14 23:53:15"
			},
			"sort": [1489535595000]
		}, {
			"_index": "userdata",
			"_type": "project",
			"_id": "AVrPcemu1I8jvHDBAI8f",
			"_score": null,
			"_routing": "test",
			"_parent": "test",
			"_source": {
				"name": "defaultProject",
				"createdDate": "2017-03-14 17:50:33",
				"updatedDate": "2017-03-14 17:50:33"
			},
			"sort": [1489513833000]
		}, {
			"_index": "userdata",
			"_type": "project",
			"_id": "AVrPRjgs1I8jvHDBAI8S",
			"_score": null,
			"_routing": "00000000-0000-0000-0000-000000000000",
			"_parent": "00000000-0000-0000-0000-000000000000",
			"_source": {
				"name": "defaultProject",
				"createdDate": "2017-03-14 17:02:50",
				"updatedDate": "2017-03-14 17:02:50"
			},
			"sort": [1489510970000]
		}]
	}
})

'''

**Comment by sksamuel** [comment]
`client.execute { search ... }.await.totalHits` ?

**Comment by jainh** [comment]
I know  _searchResult.totalHits giving me totalHit can i map external hits object with implicit case object that extends HitAs to get totalHits ?

**Comment by sksamuel** [comment]
I don't know sorry.

**Comment by jainh** [comment]
Like in your readme you have this
```
// .as[Character] will look for an implicit HitAs[Character] in scope
// and then convert all the hits into Characters for us.
```
So is there a way to pass from response totalHits to implicit HitAs[T] ? or something else?

**Comment by sksamuel** [comment]
That was your original question. The answer was no, you can't get total hits in HitAs as HitAs is given a RichHit which doesn't have it.

Why don't you just make your HitAs take the total hits as a parameter.

```scala

def hitas[T](totalHits: Long) = new HitAs[T] {
  // whatever you want total hits for in here
}

val resp = client.execute {
    search(foo)
}.await

implicit val myhitas = hitas[Foo](resp.totalHits)
resp.to[Foo]
```



```
