### ISSUE TITLE
Parent children mapping

### ISSUE THREAD

**Issue by mladendinev** [sksamuel/elastic4s#851]
Parent-child mapping such as this one

`        mapping("parent") fields(
          id typed IntegerType,
          intField("field1"),
          )
        mapping("children") fields(
          id typed IntegerType,
          intField("field2"),
          ) parent "parent"`

gives the following error:   **Can't specify parent if no parent field has been configured** . If I create the mapping explicitly before running the code as CURL command, it works, but it isn't supposed to establish the parent-children mapping when I create the index ?

**Comment by sksamuel** [comment]
Can you paste the entire snippet that creates the index. I suspect you're doing { mapping, mapping } not ( mapping, mapping ) but I can't tell from this modified snippet.
