### ISSUE TITLE
play_json implicit formats not found

### ISSUE THREAD

**Issue by alex1712** [sksamuel/elastic4s#858]
Hi, 

I am not sure if that is an issue or is just something that I understood wrong or just not implemented yet.

The case is that when I try to use the Http client with play_json I always get an error telling me that the Formats for the Response classes were not found [(Small play application with error)](https://github.com/alex1712/elastic4s_play_json_format_error).

What I did to fix the error is a custom version of elastic4s defining the implicits by myself but I would like to know if I did something wrong or if the formats are going to be implemented in future versions.

Thank you very much in advance :)

**Comment by sksamuel** [comment]
Playjson uses implicits of `play.api.libs.jsonReads` to deserialize. So however you normally bring those into scope, you need to bring into scope alongside the elastic4s playjson implicits.

**Comment by alex1712** [comment]
Hi, 

Thank you very much for your answer.

Sorry for writing again but there has to be something that I am missing. Here is a copy of my test code:

```
class ES @Inject() (lifecycle: ApplicationLifecycle) {
  import play.api.libs.json.Reads._
  import com.sksamuel.elastic4s.playjson._

  val exist = client().execute {
    indexExists("catalog")
  }.await

  private def client() = {
    val uri = ElasticsearchClientUri(s"elasticsearch://elasticsearch-local.de:9200")
    HttpClient(uri)
  }
}
```

And when I try to compile I still getting this error:
```
[error] /Users/alex/Workspace/play-json-elastic4s/play-scala-seed/app/testing/ES.scala:18: could not find implicit value for parameter format: com.sksamuel.elastic4s.JsonFormat[U]
[error]   val exist = client().execute {
[error]                                ^
```

**Comment by sksamuel** [comment]
I'm sure it's something to so with the reads implicits. I've never used
playjson before so I don't really know.

**Comment by alex1712** [comment]
As I understand the playjson package object should define the implicits, something like this:
```
  implicit val indexExistResponseResponseReads = Json.reads[IndexExistsResponse]
  implicit val createIndexResponseReads = Json.reads[CreateIndexResponse]
  implicit val deleteIndexResponseReads = Json.reads[DeleteIndexResponse]
  implicit val putMappingResponseReads = Json.reads[PutMappingResponse]
  ...
``` 

I did that for the Responses I needed and it worked.
