### ISSUE TITLE
LocalNode code typo

### ISSUE THREAD

**Issue by vans239** [sksamuel/elastic4s#860]
Actual:
`val ip: Int = ipAndPort.dropWhile(_ != ':').drop(1).toInt`

Expected:
` val port: Int = ipAndPort.dropWhile(_ != ':').drop(1).toInt`
or 
` val ip: Int = ipAndPort.takeWhile(_ != ':')`

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-embedded/src/main/scala/com/sksamuel/elastic4s/embedded/LocalNode.scala

**Comment by sksamuel** [comment]
Thanks, fixed.
