### ISSUE TITLE
Cut a 5.3.0 release?

### ISSUE THREAD

**Issue by telser** [sksamuel/elastic4s#861]
So there is a security vulnerability with x-pack 5.2.x with a recommendation to upgrade. Thoughts on cutting a 5.3.0 release?

Thanks!

**Comment by sksamuel** [comment]
I'm on holiday at the moment, so can merge PRs but don't have access to my GPG key to do releases. I'll release on Sunday 9th.

**Comment by attritionorg** [comment]
@telser, have a reference for the vulnerability?

**Comment by telser** [comment]
@attritionorg It is ESA-2017-03, Looking at https://www.elastic.co/community/security there is no CVE listed, but the field is blank whereas others that didn't get a CVE have "N/A". So maybe there will be a CVE? Not sure.

**Comment by attritionorg** [comment]
@telser Thanks. If Elastic isn't requesting a CVE ID then odds are it won't be issued, or at least in the near future. Pretty sure that project is not on MITRE's short list for assignments. They can request an ID though, via a web form on the MITRE CVE site. Until then, ESA-2017-03 as pertains to Elastic becomes a good cross-reference.

**Comment by sksamuel** [comment]
5.3.0 is released.
