### ISSUE TITLE
HttpClient returns `null` when Elasticsearch cannot be reached

### ISSUE THREAD

**Issue by ricardoatsouza** [sksamuel/elastic4s#867]
Hello,

We have been using elastic4s for a few weeks now, and we notice what seems to be a weird behaviour.

This is a snippet of the code:
```
    val host = "a.valid.host"
    val port = 80
    val httpClient = HttpClient(ElasticsearchClientUri(host, port))

    val json = "{'test': 'json'}"

    val requestResult = transportClient.execute {
      indexInto("a-index" / "a-type") id "a-id" source json
    }.await(Duration.Inf)

    logger.info(s"Result status: ${requestResult.result}")
```

We are connecting to our Elasticsearch service in AWS and we noticed that, when the Access Policy does not allow our IP to connect, the `requestResult.result` is returning `null` instead of a `created`, `updated` or a failure. Is this the intended behaviour?

Thanks

**Comment by sksamuel** [comment]
That's a bug I think.

**Comment by sksamuel** [comment]
I've added a test that the http client can open a socket but I don't have a cluster with AWS to test further.

**Comment by sksamuel** [comment]
Please do.

On 8 May 2017 12:25, "Ricardo" <notifications@github.com> wrote:

Do you mind if I create an AWS cluster (in my personal account), with the
same configuration, to test?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/elastic4s/issues/867#issuecomment-299841814>,
or mute the thread

**Comment by ricardoatsouza** [comment]
Sorry for taking a few days to answer back.
You can test with this DNS: https://search-dev-myown-dflwj7tcnfsdcmsq3nqlpvy3z4.eu-central-1.es.amazonaws.com/

**Comment by sksamuel** [comment]
Ok I'm testing this now.

**Comment by sksamuel** [comment]
I actually get this:

13:48:26.351 [main] INFO  com.sksamuel.elastic4s.http.HttpClient$ - Creating HTTP client on http://search-dev-myown-dflwj7tcnfsdcmsq3nqlpvy3z4.eu-central-1.es.amazonaws.com:80
13:48:26.653 [main] DEBUG com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$ - Endpoint=/a-index/a-type/a-id
13:48:26.656 [main] DEBUG com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$ - Executing elastic request PUT:/a-index/a-type/a-id?
13:48:26.663 [main] DEBUG com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$ - {'test': 'json'}
Exception in thread "main" org.elasticsearch.client.ResponseException: PUT http://search-dev-myown-dflwj7tcnfsdcmsq3nqlpvy3z4.eu-central-1.es.amazonaws.com:80/a-index/a-type/a-id: HTTP/1.1 403 Forbidden
{"Message":"User: anonymous is not authorized to perform: es:ESHttpPut on resource: dev-myown"}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)

**Comment by sksamuel** [comment]
The program I am running is here:

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/Issue867.scala

**Comment by ricardoatsouza** [comment]
When I run the same code I do see a forbidden message in the logs (like you), but for me no exception is thrown. As a result, I see `Result status: null`:

```
14-05-2017 16:03:36.007 TKD [main]    INFO  c.s.elastic4s.http.HttpClient$ - Creating HTTP client on http://search-dev-myown-dflwj7tcnfsdcmsq3nqlpvy3z4.eu-central-1.es.amazonaws.com:80
14-05-2017 16:03:36.779 TKD [main]    DEBUG c.s.e.h.i.IndexImplicits$IndexHttpExecutable$ - Endpoint=/a-index/a-type/a-id
14-05-2017 16:03:39.963 TKD [I/O dispatcher 1]    DEBUG c.s.e.h.i.IndexImplicits$IndexHttpExecutable$ - onFailure org.elasticsearch.client.ResponseException: PUT http://search-dev-myown-dflwj7tcnfsdcmsq3nqlpvy3z4.eu-central-1.es.amazonaws.com:80/a-index/a-type/a-id: HTTP/1.1 403 Forbidden
{"Message":"User: anonymous is not authorized to perform: es:ESHttpPut on resource: dev-myown"}
14-05-2017 16:03:39.974 TKD [I/O dispatcher 1]    DEBUG c.s.e.j.ElasticJackson$Implicits$ - Deserializing {"Message":"User: anonymous is not authorized to perform: es:ESHttpPut on resource: dev-myown"} to class com.sksamuel.elastic4s.http.index.IndexResponse
Result status: null
```

Note: I had to add this import, otherwise the code wouldn't compile: 
```
import com.sksamuel.elastic4s.jackson.ElasticJackson.Implicits._
```

**Comment by sksamuel** [comment]
Are you in 5.3.x ? You don't need the ElasticJackson.Implicits in 5.4.x.
Can you try with that, as the error may have gone away in the latest code anyway.

**Comment by ricardoatsouza** [comment]
Indeed, I was using an older version.
Using 5.4.x, I got the error as an exception:

```
Exception in thread "main" org.elasticsearch.client.ResponseException: PUT http://search-dev-myown-dflwj7tcnfsdcmsq3nqlpvy3z4.eu-central-1.es.amazonaws.com:80/a-index/a-type/a-id: HTTP/1.1 403 Forbidden
{"Message":"User: anonymous is not authorized to perform: es:ESHttpPut on resource: dev-myown"}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
```

Thank you very much for the patience
One issue less :)

**Comment by sksamuel** [comment]
Cool.
