### ISSUE TITLE
Question: Get all indices with their alias

### ISSUE THREAD

**Issue by animageofmine** [sksamuel/elastic4s#871]
There is an API in elasticsearch to get a map of index to its alias `(GET /_aliases)`. However, I wasn't able to find anything equivalent in `AliasesApi` class in elastic4s. All I get back is the indices with assigned aliases. If an index is not mapped with an alias, I don't get that back in the result. 

Reason: I want to create delete orphaned data (the one that is not aliased). Hence, I would like to get [index,List<alias>] map and delete all indices that does not have any alias associated with it. 

Please let me know if there is a way to do that already.

**Comment by sksamuel** [comment]
added to 5.4
