### ISSUE TITLE
Is CAT API Supported?

### ISSUE THREAD

**Issue by animageofmine** [sksamuel/elastic4s#872]
Is CAT API supported by elastic4s using transport client?

https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html

I want to check if node is a master. Could you please point how can this be achieved?

**Comment by sksamuel** [comment]
No but we can add it.

**Comment by animageofmine** [comment]
That would be great since we use this library for our production customers. A couple of quick questions: 

1. Would you mind cost the work and provide ETA? It would help us a lot. 
2. Is there an alternative in the meanwhile to get the master node name?

**Comment by sksamuel** [comment]
Most of the cat apis are supported in 5.4
