### ISSUE TITLE
ElasticClient not found

### ISSUE THREAD

**Issue by Howon** [sksamuel/elastic4s#874]
Hello,

I included 
```
"com.sksamuel.elastic4s" %% "elastic4s-core" % "5.3.1"
```
into my build.sbt file but when I try to use any of the example code
that relies on ElasticClient IntelliJ seems unable to find that module.
Is that moved elsewhere?

Thanks,

**Comment by Howon** [comment]
I now see that its been deprecated in favor of TcpClient.
Perhaps the documentation should be updated to accommodate for that?

**Comment by sksamuel** [comment]
Thanks, I've added a note to that effect in the introduction.

**Comment by animageofmine** [comment]
@sksamuel Do I need to add elastic4s-tcp to build.sbt to use TcpClient? I can't seem to find TcpClient just by including elastic4s-core. 

DOES NOT WORK
`"com.sksamuel.elastic4s" %% "elastic4s-core" % "5.3.0"`

WORKS
```
"com.sksamuel.elastic4s" %% "elastic4s-core" % "5.3.0",
"com.sksamuel.elastic4s" %% "elastic4s-tcp" % "5.3.0"
```

**Comment by sksamuel** [comment]
@animageofmine  Yes, you add either tcp client or http client depending on what you want to use.
