### ISSUE TITLE
Writing to ES using a scala map takes 5 times as long as not using a scala map

### ISSUE THREAD

**Issue by RPGambit2** [sksamuel/elastic4s#887]
This takes 3 to 5 seconds to write 250 messages to Elasticsearch:
// We will only write the job information to Elastisearch for the Start Run message
elkIndexingStatsElasticSetupMessage.client.execute {
  update ((elkEnrichmentStatsStartRunMessage.JobId, elkEnrichmentStatsStartRunMessage.RunId)) in elasticNodeType4Stats docAsUpsert (
    "RunId" -> elkEnrichmentStatsStartRunMessage.RunId,
    "JobId" -> elkEnrichmentStatsStartRunMessage.JobId,
    "Client" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.Client,
    "DataFeed" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.DataFeed,
    "DataTable" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.DataTable,
    "SourceURL" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.SourceURL,
    "TargetURL" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetURL,
    "TargetURI" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetURI,
    "TargetDriverClass" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetDriverClass,
    "TargetDBString" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetDBString,
    "Topic" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.Topic,
    "CreatedBy" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.CreatedBy,
    "CreatedOnTimestamp" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.CreatedOn,
    "CreatedOnTimestampMS" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.CreatedOn,
    "SerializationFmt" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.SerializationFmt,
    "ReversePubFlag" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.ReversePubFlag,
    "StartTimeTimestamp" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.StartTime * 1000,
    "StartTimeTimestampMS" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.StartTime * 1000,
    "EndTimeTimestamp" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.EndTime * 1000,
    "EndTimeTimestampMS" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.EndTime * 1000,
    "Status" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.Status,
    "StatusDescription" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.StatusDescription,
    "ErrorMessage" -> errorMessage,
    "ErrorCounter" -> errorCounter
  ) retryOnConflict(numberOfRetries)
}

This takes about 15 to 20 seconds to write the same 250 messages to Elasticsearch:
ESStatsMap += "RunId" -> elkEnrichmentStatsStartRunMessage.RunId
ESStatsMap += "JobId" -> elkEnrichmentStatsStartRunMessage.JobId
ESStatsMap += "Client" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.Client
ESStatsMap += "DataFeed" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.DataFeed
ESStatsMap += "DataTable" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.DataTable
ESStatsMap += "SourceURL" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.SourceURL
ESStatsMap += "TargetURL" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetURL
ESStatsMap += "TargetURI" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetURI
ESStatsMap += "TargetDriverClass" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetDriverClass
ESStatsMap += "TargetDBString" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.TargetDBString
ESStatsMap += "Topic" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.Topic
ESStatsMap += "CreatedBy" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.CreatedBy
ESStatsMap += "CreatedOnTimestamp" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.CreatedOn
ESStatsMap += "CreatedOnTimestampMS" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.CreatedOn
ESStatsMap += "SerializationFmt" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.SerializationFmt
ESStatsMap += "ReversePubFlag" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.ReversePubFlag
ESStatsMap += "StartTimeTimestamp" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.StartTime * 1000
ESStatsMap += "StartTimeTimestampMS" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.StartTime * 1000
ESStatsMap += "EndTimeTimestamp" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.EndTime * 1000
ESStatsMap += "EndTimeTimestampMS" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.EndTime * 1000
ESStatsMap += "Status" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.Status
ESStatsMap += "StatusDescription" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.StatusDescription
ESStatsMap += "ErrorMessage" -> (ErrorDataTimestamp.toString + "- " + elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.ErrorMessage)
ESStatsMap += "ErrorCounter" -> elkEnrichmentStatsStartRunMessage.elkEnrichmentStatsDTOMessage.ErrorCounter

elkIndexingStatsElasticSetupMessage.client.execute {
  update((elkEnrichmentStatsStartRunMessage.JobId, elkEnrichmentStatsStartRunMessage.RunId)) in elasticNodeType4Stats docAsUpsert (
    ESStatsMap
    ) retryOnConflict (numberOfRetries)
}

**Comment by sksamuel** [comment]
I don't have your objects so can't recreate, so you could make me a stand alone sample of code that exhibits this behavior? Failing that, can you time it without actually executing the requests, eg, just make the request and don't put it inside client.execute. Also what are you using - http or tcp ?

**Comment by RPGambit2** [comment]
Stephen,

Thanks for getting back to me.  This morning I figured out what was
actually happening.   In the non-map case, I left out 1 field from being
written to elasticsearch.  That field was changing prior to each write.
Since it was left out, I assume elasticsearch, when doing the update,
realized that no changes were made and therefore returned quickly from the
update.

In the case where I was using the map, the field that was changing was
being added to the map correctly, which caused elasticsearch to actually
update the document causing it to take longer.

I'm assuming that if nothing changes, elasticsearch doesn't do the actual
document update which caused it to quickly return in that case (non map).

Thanks!

RP
