### ISSUE TITLE
Dependency on elasticsearch 5.3.0 is problematic

### ISSUE THREAD

**Issue by jacool** [sksamuel/elastic4s#889]
The ES v5.3.0 build had several showstopper bugs
 (e.g.
 https://github.com/elastic/elasticsearch/pull/21955
 https://www.elastic.co/blog/multi-data-path-bug-in-elasticsearch-5-3-0
)
Please move to 5.3.1 to eliminate the dependency.

**Comment by sksamuel** [comment]
I'll do a new release soon, but you can work around it by just adding the elasticsearch 5.3.1 dependency to your build, which will cause sbt / gradle / maven to use that and not the 5.3.0 declared in elastic4s.
