### ISSUE TITLE
failureMessageOpt in RichBulkResponse doesn't work as an option

### ISSUE THREAD

**Issue by ajrnz** [sksamuel/elastic4s#890]
Currently defined as:

    def failureMessageOpt: Option[String] = Option(failureMessage)

however `failureMessage` always returns a string and never `null`

A more appropriate definition would be:

    def failureMessageOpt: Option[String] = if (x.hasFailures) Some(x.failureMessage) else None

**Comment by sksamuel** [comment]
Good spot, I've used your suggestion for 5.3.3
