### ISSUE TITLE
Semantics of must/should on queries

### ISSUE THREAD

**Issue by jacool** [sksamuel/elastic4s#892]
Consider `should(x).should(y)` - with current definition of should/must the first query x will be disregarded as the methods are defined as `copy(should = queries.toSeq)` rather than `copy(should = should ++ queries.toSeq)`
Besides being counter-intuitive this breaks the old V2 code with no compile time detection.

**Comment by sksamuel** [comment]
I think the methods are not intuitive and as you say I've broken them anyway. I think the best solution is to deprecate the current ones and create two new ones that make it clear.

**Comment by sksamuel** [comment]
So one option is:

```scala
boolQuery().withNot()
```

and

```scala
boolQuery().appendNot().appendNot()
```

**Comment by sksamuel** [comment]
I've added the `appendXXX` variants. Whether we deprecate the original and replace with something else, or just leave them is open for discussion.

**Comment by jacool** [comment]
I think you better deprecate the old ones. Because they are too easy to confuse with the appendxxx ones and will break code in subtle ways. (Mine was broken and I didn't catch it until after it went to production.)

**Comment by sksamuel** [comment]
All don for 5.3.3
