### ISSUE TITLE
Template Query

### ISSUE THREAD

**Issue by jainh** [sksamuel/elastic4s#894]
Is it possible to do Template query using this library ? 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-template-query.html#query-dsl-template-query

**Comment by sksamuel** [comment]
Template query has been deprecated in favour of search templates, but that needs to be added.

**Comment by sksamuel** [comment]
Added in 5.4

**Comment by jainh** [comment]
Hi @sksamuel so search template added in 5.4 version of the client? where is the documentation ?

**Comment by sksamuel** [comment]
in the source code :)

**Comment by jainh** [comment]
@sksamuel can you point me where to look? so 5.4 has support for search template based query ?

**Comment by sksamuel** [comment]
Yep,

Open up SearchTemplateApi and it should be easy enough to follow from there.
