### ISSUE TITLE
Create 'create index' automatically from a type

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#896]
What do you think @solicode @muuki88

**Comment by muuki88** [comment]
This means deriving a `IndexDefinition` from a given type? This is nice for getting started quickly and simple uses cases. How would I configure the index settings? Annotations?

**Comment by sksamuel** [comment]
could do those via a nap still.

**Comment by solicode** [comment]
You mean via meta-programming? It's not something I've used in Scala, so I won't be very helpful in this discussion. Maybe I should finally take a look at `scala.meta` and see where it's at.

I like the idea though. Anything that catches stuff at compile-time I'm for. Removing boilerplate is nice too.

But I'm having trouble imagining what it would look like. For example, in ES5 there's `text` and `keyword`. How do you determine which to choose just by Scala type? So even for simple cases, it seems like generating an index from a type would break down quickly. Unless additional information is provided to the type, like with annotations as @muuki88 already mentioned.

**Comment by sksamuel** [comment]
Yes on reflection might not really be do-able.
