### ISSUE TITLE
multisearch drop pagination info

### ISSUE THREAD

**Issue by lyf1988** [sksamuel/elastic4s#901]
Thank you for  your work. 
I am trying to use elastic4s to talk with AWS Elasticsearch.

It seems the multi search will drop the pagination information(defined in from() and size()).
Or I am wrong from the beginning, the multi search does not support pagination?

Below is the example request I am trying to do.
I am using elastic4s-core with elastic4s-http both in version 5.3.2.

```
client.execute {
      multi(
       search(esIndexName)
          .bool(
            must(
              someTermsQuery,
              someRangeQuery
            )
          ).from(0).size(100) ,
        search(esIndexName)
          .bool(
            must(
              someTermsQuery,
              someRangeQuery
            )
          ).from(0).size(100)            
      )
}
```

I tried to do some debugging.
I cannot found pagination params from the  result of  `MultiSearchContentBuilder`, 
so I assume here is the place cause the problem?

BTW, do the search one by one, pagination works fine.

**Comment by sksamuel** [comment]
You can set from/size as either http params, or in the body. I was doing the former, but have changed it to use the body. Then it will work in multisearch as well.
