### ISSUE TITLE
No more Search builder? 

### ISSUE THREAD

**Issue by animageofmine** [sksamuel/elastic4s#902]
In 5.0.1, `SearchDefinition` used to have builder like the following:

```
case class SearchDefinition(indexesTypes: IndexesAndTypes) {

  val _builder = {
    new SearchRequestBuilder(ProxyClients.client, SearchAction.INSTANCE)
      .setIndices(indexesTypes.indexes: _*)
      .setTypes(indexesTypes.types: _*)
  }

```

This allowed us to build queries in the following format:

```
val aggregateSearchDefinition : SearchDefinition = search(request) size 0

    // apply aggregations to search definition
    aggregateSearchDefinition.aggregations(getAggregateQuery(request))
    
    // apply filters to query. getFilterQuery returns Option[QueryDefinition]
    getFilterQuery(request).map { queryDefinition =>
      aggregateSearchDefinition query constantScoreQuery(queryDefinition)
    }

    val aggregateResponseFuture = esClient.execute { aggregateSearchDefinition }
```

The new version 5.3.2 does not have builder at all, which means the above code wouldn't work. Is this expected? Is this replaced by some other builder? What is the best way to build search queries?

**Comment by sksamuel** [comment]
`com.sksamuel.elastic4s.searches.SearchBuilderFn`

Do you not like using the elastic4s dsl? 

`search(index/type).query(termQuery("field", "name")).aggs(...)`

**Comment by animageofmine** [comment]
I like elastic4s dsl, but it broke my code after upgrading it. 

Also, I updated the above example to show a better example of why builder could be useful. As you can see the code, getFilterQuery returns an Option[QueryDefinition]. I only want to add query if is Some[QueryDefinition]. I am not sure if I can do that using the dsl. 

Do you have some examples of SearchBuilderFn? It does not accept TcpClient

**Comment by sksamuel** [comment]
You should use the DSL as that's how elastic4s is designed, If you want to make search builders directly, then you might as well just use the Java api.

**Comment by animageofmine** [comment]
Fair enough! Thanks for pushing back.

**Comment by sksamuel** [comment]
You can make the case class directly,

SearchDefinition(....)

But if the DSL isn't working for you, then I'd rather improve that than have people use internal classes directly.
