### ISSUE TITLE
Ability to extract whole search response as string/json

### ISSUE THREAD

**Issue by halvorgb** [sksamuel/elastic4s#909]
We mainly use elasticsearch for aggregating data, as such all we're interested in when looking at a `SearchResponse` are the aggregations.

An example of a query we run: 
```scala
search(organizationData2Conf.index / "ticket")
      .query { // snip }
      .aggs {
        termsAggregation("by_event_id").size(512).field("event_id")
          .subAggregations(
            revenueAggregation,
            eventStatsPerPeriod(
              period = Month,
              interval = DateHistogramInterval.DAY
            )
          )
      }
      .size(0)
```

We find that the aggregation helper methods are not enough for us, we wind up with `Buckets` from the term aggregations with nowhere to continue.

Could a helper method be added to searchResponse to simply get the whole response as a string or the jackson JsonNode that is used internally? 

We've made some workarounds to get around this issue:

First when using `elastic4s-tcp` we used the `XContent` to build json: https://gist.github.com/halvorgb/296a8b3b7e2591aaeda60e8f6576db48

Now when we're porting to `elastic4s-http` we can't see another way than creating a custom `HttpExecutable[SearchDefinition, Json]` (which is not a pretty solution to say the least): https://gist.github.com/halvorgb/76816db1919925c24916615b659020ea

**Comment by sksamuel** [comment]
Decent request. I'll add this for 5.4.3.
As another issue, what could be added to aggregations so that you don't have to use the raw string.

**Comment by halvorgb** [comment]
Great,  thanks for the swift response.

As for your question: we see no way of getting to sub aggregation results. If the `Bucket` case class had a way of getting sub aggregations it'd be possible to use. We are comfortable defining a schema and validating the responses against it though.

given this query, which has multiple aggregations within a term aggregation within a term aggregation:
```json
{
  "_source": "*",
  "query": {
    "bool": {
      "filter": {
        "term": {
          "is_revoked": false
        }
      }
    }
  },
  "aggs": {
    "by_ticket_type_id": {
      "terms": {
        "field": "ticket_type_id"
      },
      "aggs": {
        "by_checkout_method": {
          "terms": {
            "field": "checkout_method"
          },
          "aggs": {
            "revenue": {
              "sum": {
                "field": "price"
              }
            },
            "total_fee": {
              "sum": {
                "field": "fee"
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
```

`termsAgg("by_ticket_type_id")` would yield:
```scala
TermsAggregationResult(
  name: "by_ticket_type_id"
  buckets: Seq(
    Bucket(
      "key": "456789",
      "doc_count": 4
     ),
    Bucket(
      "key": "456721312",
      "doc_count": 2
     )
  ),
  docCountErrorUpperBound: xxx,
  otherDocCount: yyy
)
```

**Comment by sksamuel** [comment]
I've added .aggregationsAsString to 5.4.3.

**Comment by pedrocalais** [comment]
What I should do to get the full json response as a string?

**Comment by sksamuel** [comment]
Which version?

**Comment by pedrocalais** [comment]
6.2.2!

**Comment by sksamuel** [comment]
In the client, the object you receive back is a ResponseSuccess which has the status, body and headers of the http response.

```case class RequestSuccess[U](override val status: Int, // the http status code of the response
                             override val body: Option[String], // the http response body if the response included one
                             override val headers: Map[String, String], // any http headers included in the response
                             override val result: U)```

https://github.com/sksamuel/elastic4s/blob/release/6.2.x/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/HttpClient.scala#L27-L34

**Comment by pedrocalais** [comment]
Oh, sure. Thanks!
