### ISSUE TITLE
add support for type-less operations on all requests that require an index and type.

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#913]
ES is removing support for "types" (in the sense of indexes and types) in 7.0. In 6.0 they are limiting new indexes to a single type. The Scala API should be upgraded to allow _typeless_ operations which will use a default type name under the hood.

**Comment by vbabenkoru** [comment]
@sksamuel Most APIs still seem to be using `IndexAndType`, are any changes planned for this?

**Comment by sksamuel** [comment]
Working on 8.x release which will remove them all.

**Comment by vbabenkoru** [comment]
@sksamuel How does one use it now? I'm getting `Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.` in ES7 because `IndexAndType` _requires_ the type to be specified.
