### ISSUE TITLE
FunctionScoreQueryDefinition is not handled in QueryBuilderFn

### ISSUE THREAD

**Issue by adrian83** [sksamuel/elastic4s#915]
Using FunctionScoreQueryDefinition ends with an exception:

scala.MatchError: FunctionScoreQueryDefinition(Some(BoolQueryDefinition(None,None,None,...,None) (of class com.sksamuel.elastic4s.searches.queries.funcscorer.FunctionScoreQueryDefinition)
	at com.sksamuel.elastic4s.http.search.queries.QueryBuilderFn$.apply(QueryBuilderFn.scala:60)
	at com.sksamuel.elastic4s.http.search.queries.nested.HasChildBodyFn$.apply(HasChildBodyFn.scala:21)

Probably the simplest solution would be to include this definition in com.sksamuel.elastic4s.http.search.queries.QueryBuilderFn

**Comment by sksamuel** [comment]
PR welcome.

**Comment by sksamuel** [comment]
Thanks for the PR.
