### ISSUE TITLE
Match Error in SortContentBuilder

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#916]
ScoreSortDefinition is not actually considering all implemented sort definitions. The only supported implementation is FieldSortDefinition.

elastic4s/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/queries/SortContentBuilder.scala

**Comment by sksamuel** [comment]
Fastest thing is to add a PR for the one you want, then I can do a release.

**Comment by sksamuel** [comment]
@Aadrian83 has kindly added these to master.

**Comment by sksamuel** [comment]
@Adrian83 has kindly added these to master.
