### ISSUE TITLE
Support GeoHashGridAggregation for http client

### ISSUE THREAD

**Issue by jodylapp** [sksamuel/elastic4s#919]
I would like to be able to use the http library to construct geo hash grid aggregations, but they don't seem to be supported.  I noticed that there is no entry for a GeoHashGridAggregationDefinition/GeoHashGridAggregationBuilder in the [AggregationBuilderFn](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/aggs/AggregationBuilderFn.scala).

**Comment by sksamuel** [comment]
It's only in the TCP client atm.

**Comment by jodylapp** [comment]
Do you have an idea of when it might be added to the http client?

**Comment by sksamuel** [comment]
It'll be added to 6.0.

**Comment by sksamuel** [comment]
This has been added to master and will be in 6.0.0-rc2.
