### ISSUE TITLE
Term with array of strings

### ISSUE THREAD

**Issue by jainh** [sksamuel/elastic4s#920]
`ElasticDsl.termsQuery("tags", tags.mkString(","))`  What i want to achieve is passing tags as array of string not single string separated by `,`.   like query = { ....  "tags":["a", "b"] ....}  which is ultimately refer to `QueryDefinition`

**Comment by sksamuel** [comment]
Does `termsQuery("tags", Seq("a", "b"))` or `termsQuery("tags", "a", "b")` not work ?
