### ISSUE TITLE
Add Lucene required note in quick  start

### ISSUE THREAD

**Issue by ibaisi** [sksamuel/elastic4s#924]
I think adding "Java client has dependencies on Netty, Lucene and others that it does not bring in transitively" somewhere in the quick start section would be way more helpful than under the release section. Maybe even in the "Example SBT Setup".

It could save people new to ES and elastic4s some time.

**Comment by sksamuel** [comment]
This was added to the readme but forgot to close this ticket. Thanks for the report.
