### ISSUE TITLE
No cats.Show for DeleteIndexDefinition

### ISSUE THREAD

**Issue by frozenspider** [sksamuel/elastic4s#929]
I think it's reasonable to expect implicit `Show` available for **every** request type, so that it can e.g. be logged.
```scala
// could not find implicit value for parameter show: cats.Show[com.sksamuel.elastic4s.indexes.DeleteIndexDefinition]
log.debug("ES request: " + esClient.show(deleteIndex("myIndex")))
```

**Comment by frozenspider** [comment]
Same applies problem with `DeleteByIdDefinition`, btw

**Comment by sksamuel** [comment]
I don't think it makes sense to have them for requests which have no body. The show typeclass only logs out the json body. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html

**Comment by frozenspider** [comment]
Got it. Could you please at least explicitly state that somewhere, e.g. in scaladocs for `show` method?

**Comment by sksamuel** [comment]
I've added this to master.

  /**
    * Returns a json String containing the request body.
    * Note: This only works for requests which have a cats.Show typeclass implemented, which is most,
    * but not all. Also, some requests intentionally do not provide a Show implementation as
    * they are "header only" requests - that is, they have no body - for example, delete by id, or delete index.
    */
