### ISSUE TITLE
Timeout definition inconsistency

### ISSUE THREAD

**Issue by frozenspider** [sksamuel/elastic4s#933]
Looks like code excerpts from elastic4s itself are pretty self-explanatory:
```scala
// case class IndexDefinition
def timeout(timeout: String): IndexDefinition = copy(timeout = timeout.some)
```
```scala
// case class SearchDefinition
def timeout(duration: FiniteDuration): SearchDefinition = copy(timeout = duration.some)
```

**Comment by sksamuel** [comment]
Have renamed the second in master. Thanks.

**Comment by frozenspider** [comment]
> are pretty self-explanatory

Ehm, or maybe not. What I've meant is that we define timeout via `String` in one place and via `FiniteDuration` in another.

**Comment by sksamuel** [comment]
Ok it wasn't clear to me from the code snippet alone sorry.
I will equalize the two variants for 6.0.0.
