### ISSUE TITLE
Not indicesOptions apply in SearchHttpExecutable

### ISSUE THREAD

**Issue by fggarcia** [sksamuel/elastic4s#943]
SearchDefinition indicesOptions are not apply in execute

SearchHttpExecutable

`

    override def execute(client: RestClient,
                         request: SearchDefinition): Future[SearchResponse] = {

      val endpoint = if (request.indexesTypes.indexes.isEmpty && request.indexesTypes.types.isEmpty)
        "/_search"
      else if (request.indexesTypes.indexes.isEmpty)
        "/_all/" + request.indexesTypes.types.mkString(",") + "/_search"
      else if (request.indexesTypes.types.isEmpty)
        "/" + request.indexesTypes.indexes.mkString(",") + "/_search"
      else
        "/" + request.indexesTypes.indexes.mkString(",") + "/" + request.indexesTypes.types.mkString(",") + "/_search"

      val params = scala.collection.mutable.Map.empty[String, String]
      request.keepAlive.foreach(params.put("scroll", _))
      request.pref.foreach(params.put("preference", _))
      request.requestCache.map(_.toString).foreach(params.put("request_cache", _))
      request.routing.foreach(params.put("routing", _))
      request.searchType.map(_.toString).foreach(params.put("search_type", _))
      request.terminateAfter.map(_.toString).foreach(params.put("terminate_after", _))
      request.timeout.map(_.toMillis + "ms").foreach(params.put("timeout", _))
      request.version.map(_.toString).foreach(params.put("version", _))

      val builder = SearchBodyBuilderFn(request)
      logger.debug("Executing search request: " + builder.string)

      val body = builder.string()
      val entity = new StringEntity(body, ContentType.APPLICATION_JSON)
      client.async("POST", endpoint, params.toMap, entity, ResponseHandler.default)
    }
`

**Comment by sksamuel** [comment]
Fixed in 5.4.4
