### ISSUE TITLE
Issue when building percentiles aggregation (missing percentils)

### ISSUE THREAD

**Issue by pgorin** [sksamuel/elastic4s#948]
PercentilesAggregationBuilder is not setting percentiles when building aggregation.
file: com.sksamuel.elastic4s.searches.aggs.PercentilesAggregationBuilder

**Comment by sksamuel** [comment]
Fixed in 6.0.0-rc1

**Comment by pgorin** [comment]
Thanks!

**Comment by pgorin** [comment]
Hi Stephen, how are you. I have a question. I'm currently using elastic4s version 5.4.5 over elasticsearch version 5.5. I see that you fixed this bug on elastic4s 6.x versions. Is there a chance that you can include this fix on elastic4s 5.5.x version? Thank!
