### ISSUE TITLE
Publish 2.12 version of lib for elasticsearch 2.x

### ISSUE THREAD

**Issue by haggy** [sksamuel/elastic4s#957]
Hi,

We're using this client against an ES cluster that is running ES versions 2.x. I noticed that you only published 2.12 version for 5.x+. Since ES version 2.x is not EOL and still very much used in production, can you publish 2.12 for that as well? Thanks!

**Comment by sksamuel** [comment]
I don't support earlier versions anymore, so I can't do improvements, etc, but I can do a 2.12 build if its just a case of changing the scala version. What version are you running exactly.

**Comment by haggy** [comment]
OK 🤞 that it "just works" heh We're running version `2.3.1`. Let me know if you need any other info. Thanks!

**Comment by sksamuel** [comment]
I've spent a couple of hours on 2.x branch getting a 2.12 release but have hit another issue so I'm parking it for now. It won't compile on what I think is just 2.12 being weird about Java boxed types and scala types. If you want to check out the branch and have a go at fixing it I'll do a release.

**Comment by haggy** [comment]
OK yea I'll check it out and see if I can get it going.

**Comment by avdv** [comment]
Hi.

We need this too :crying_cat_face: since we are still using Elasticsearch 2.4.6. So I ported the 2.4.x branch to Scala 2.12:

Here are the changes: https://github.com/sksamuel/elastic4s/compare/731f7d9...avdv:scala-2.12-for-2.4

If you create a suitable branch, I would love to create a pull request. :-)

Cheers.

**Comment by haggy** [comment]
@avdv That's awesome! @sksamuel Thoughts on the changes above?

**Comment by sksamuel** [comment]
@avdv please make the PR against the 2.4.x branch, adding 2.12 as a cross build, and I will release it. Thanks very much.

**Comment by avdv** [comment]
There's no 2.4.x branch, as far as I see... 🤔

**Comment by sksamuel** [comment]
Yes that's a good point :dancer:

**Comment by sksamuel** [comment]
There is now :tada:

**Comment by avdv** [comment]
Hey @sksamuel, just in case you missed it: I have created a PR [here](#1015).

**Comment by sksamuel** [comment]
Merged and 2.4.1 released.
