### ISSUE TITLE
Pluggable HTTP clients

### ISSUE THREAD

**Issue by msbarry** [sksamuel/elastic4s#958]
At Twitter, we'd like to use elastic4s but need to use the finagle HTTP client for transport instead of the Apache HTTP async rest client used by elasticsearch's Java REST client. Does it seem realistic to make elastic4s  allow clients to implement an interface similar to [RichRestClient](https://github.com/sksamuel/elastic4s/blob/558b9297a90561ec81189c470b6e827e54da5b7f/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/HttpExecutable.scala#L43) to provide their own HTTP client?

**Comment by sksamuel** [comment]
It's a good idea. I think a trait that exposes a "send request" method and another trait representing the response, then any client could create a wrapper easily. What do you think.

**Comment by msbarry** [comment]
Yes, that would be great. How complicated do you think the refactor would
be?

**Comment by sksamuel** [comment]
Not very. I'll do it. Do you want to contribute code that adapts finagle to use it.

**Comment by msbarry** [comment]
Awesome. Sure, I could do that. Are you thinking a new "elastic4s-finagle-http" module in this repo? Also, do you expect this would land in v6 release? Or will there be a version with 5.4 compatibility?  Thanks.

**Comment by sksamuel** [comment]
Yes exactly, I'm going to add a trait like HttpManager or something, (since HttpClient is already used) which will have a `def request(method:String, endpoint:String, params:Map[String,String], body:String, contentType:String):Response` method. And then elastic4s-finagle-http can implement that.

**Comment by msbarry** [comment]
Sounds good. I'll wait for your change to land then get working on the elastic4s-finagle-http module.

**Comment by msbarry** [comment]
Do you have any rough idea of the timeline for the elasticsearch/elastic4s v6 release?

**Comment by sksamuel** [comment]
Probably like a day after the official release of elasticsearch server 6.0.
I've put up an alpha already and I'll do a proper milestone build once elasticsearch do the same. There's more changes to come, as in types are going away in 7 so in 6 they're fully deprecated.

**Comment by kharnt0x** [comment]
At www.seek.com.au we are using finangle and elastic4s together as well. If we can assist let me know

**Comment by sksamuel** [comment]
I'm just away at the moment, I reckon I'll do this end of the week.

**Comment by kharnt0x** [comment]
Any updates on this @sksamuel

**Comment by sksamuel** [comment]
This is in master now. I've also released 6.0.0-M2 which should be compatible with any 5.x server as well. To use this, you need to implement `HttpRequestClient` and then pass that instance into `HttpClient.apply`.

I'm happy to make changes given feedback.

**Comment by sksamuel** [comment]
Did anyone ever use this work ?

**Comment by msbarry** [comment]
I am out on parental leave now and wasn't able to get to it beforehand. We will likely be able to add the finagle request client implementation as part of migrating to elasticsearch 6 when I'm back.

**Comment by kharnt0x** [comment]
hey @sksamuel , I had a try at using this but there were problems. I'll report them when I get a chance
