### ISSUE TITLE
Multi criteria sort in term aggregation

### ISSUE THREAD

**Issue by To-om** [sksamuel/elastic4s#960]
Since elastic4s 5.4.1, in term aggregation, [def order(order: Terms.Order)](https://github.com/sksamuel/elastic4s/blob/v5.4.5/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/searches/aggs/TermsAggregationDefinition.scala#L45) is deprecated and replaced by [def order(order: TermsOrder)](https://github.com/sksamuel/elastic4s/blob/v5.4.5/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/searches/aggs/TermsAggregationDefinition.scala#L42).

`Terms.Order` supports multi criteria with `Order.compound` but it seems that `TermsOrder` doesn't.

Is it still possible to order term aggregation with several criteria ? If yes how ?

**Comment by sksamuel** [comment]
Thanks, good spot. I'll fix it in the 6.0 release train. For 5.4 just use the deprecated method.
