### ISSUE TITLE
Backport bulk api routing fix from 6.0.0 to 5.4.x

### ISSUE THREAD

**Issue by nyaa** [sksamuel/elastic4s#963]
In version 5.4.x bulk api routing broken (`com.sksamuel.elastic4s.http.bulk.BulkContentBuilder`), but it was fixed in 6.0.0 (https://github.com/sksamuel/elastic4s/commit/b6c7b520bfe49fad6e5e18bb85a87788887e8bbf)

Please backport this fix to 5.4.x release

Thanks!

**Comment by prikha** [comment]
+1 vote for this. It breaks production stuff

**Comment by sksamuel** [comment]
Yes I'll backport and do a release.

**Comment by prikha** [comment]
👏 nice

**Comment by prikha** [comment]
@sksamuel any thoughts on this, we would appreciate version bump

**Comment by sksamuel** [comment]
Sorry I did this but forgot to reply to say I had released. Needless to say you probably found that out yourself!
