### ISSUE TITLE
Min/Max aggregation results throw NPE when processing

### ISSUE THREAD

**Issue by fvlankvelt** [sksamuel/elastic4s#966]
Elasticsearch can return the value *null* for min/max aggregations, when there are no documents containing the relevant field in the resultset.  When using the HasAggregations#min (or #max) method, elastic4s tries to coerce the null into a (scala) Double.

I'm not sure if the set {min,max} is complete, or whether "avg", "cardinality", "valueCount" suffer from the same problem.

IMO this situation needs to be reflected in the API, e.g. by giving the value the type Option[Double].  When a null value is provided in the response, the aggregation value should be None; otherwise it should just wrap the actual value.

**Comment by sksamuel** [comment]
Ok good spot. I take it you're building from master or using the alpha. I'll change the API as you suggest to use Options for the values.

**Comment by sksamuel** [comment]
It seems to only be the min/max that is affected. Which makes sense, as the sum of nothing is 0, and the count of zero hits is 0. I've added tests for them all. It's fixed in master.
