### ISSUE TITLE
Delete Indices based on Index Meta Data (alias and creation date)

### ISSUE THREAD

**Issue by arsalan94** [sksamuel/elastic4s#967]
Hi,

I've run into an issue that I'm not sure how to resolve. I want to delete indices that do not have aliases and that were created more than 7 days ago. This will run periodically to clean out old stale data.

Originally, I was going to use getAliases and getSettings to find the indices that meet the criteria specified above (using creation_date in the settings to get the ones older than 7 days) and then delete those using deleteIndex. However, the issue that I ran into was that getAliases does not work with a TcpClient (I'd get: could not find implicit value for parameter executable) but would work fine on an HttpClient. On the other hand, getSettings seems to only work for a TcpClient. When I try to use both of these together, I'd get conflicts with com.sksamuel.elastic4s.ElasticDsl._ and com.sksamue.elastic4s.http.ElasticDsl saying that the reference to getAliases is ambiguous.

Do you have a workaround for this? Is there anyway you could add support so that TcpClients can handle getAliases and getSettings (we've been using a TcpClient this whole time).

**Comment by sksamuel** [comment]
More likely is that I'd add getSettings for the http client.

**Comment by sksamuel** [comment]
6.0.0-rc1 contains get / update settings for the http client. So that's the way to go.
