### ISSUE TITLE
NoNodeAvailableException[None of the configured nodes are available: {127.0.0.1:9300}]]

### ISSUE THREAD

**Issue by subhasish23sahu** [sksamuel/elastic4s#972]
Not able to connect to localhost and also opened 9300 at Firewall:

Usuing ES: 5.4.2 and Lucene : 6.5.1

Error:
----------

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{VImCcIXfTtKXhB8Ky6Vghg}{127.0.0.1}{127.0.0.1:9300}]]

CODE:
------------
                 Settings settings =Settings.builder()
		    		.put("client.transport.sniff",false)
		    		.put("cluster.name", "my-application").build();
		    System.out.println(InetAddress.getLocalHost());
		    System.out.println(InetAddress.getByName("localhost"));
    	        Client  client = new PreBuiltTransportClient(settings)
                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300));
		    
		   //CreateIndexRequestBuilder createIndexRequestBuilder = client.admin().indices().prepareCreate("subu");
	       //createIndexRequestBuilder.execute().actionGet();
              Settings settings =Settings.builder()
		    		.put("client.transport.sniff",false)
		    		.put("cluster.name", "my-application").build();
    
		Client  client = new PreBuiltTransportClient(settings)
                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300));
		    
		   CreateIndexRequestBuilder createIndexRequestBuilder = client.admin().indices().prepareCreate("subu");
	          createIndexRequestBuilder.execute().actionGet();

**Comment by sksamuel** [comment]
So your cluster is not called my-application probably, or you didn't expose the cluster on 127.0.0.1.
Navigate to 127.0.0.1:9200 and see if it works.

**Comment by subhasish23sahu** [comment]
tried using 9200 also it is not working and in my yml file i have this entry also
cluster.name: my-application

**Comment by sksamuel** [comment]
If you can't connect to 9200 in your browser, then your elasticsearch server is just not setup right. This is not an issue with this library.

https://stackoverflow.com/questions/24063644/whats-the-difference-between-bind-host-and-publish-host-in-elasticsearch

**Comment by subhasish23sahu** [comment]
i am able to connect using PostMan to 9200 but through Java API it is giving the issue to connect to either 9200 or 9300

**Comment by sksamuel** [comment]
TCP Client must go through 9300, HTTP through 9200. All that's happening here is you're not putting in the right details _or_ your cluster is not setup to accept TCP on the right ip address. I'd just re-read the elasticsearch install guide.

**Comment by subhasish23sahu** [comment]
This is my es.yml file:

# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: _gce_
#network.publish_host: 104.100.100.96
#
# Set a custom port for HTTP:
#
http.port: 8500
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true

**Comment by sksamuel** [comment]
Do you mean to comment out 
#network.host: gce
#network.publish_host: 104.100.100.96

**Comment by subhasish23sahu** [comment]
the above entry i had added to do some kind of testing which didnt work out.

even though i enable :  network.host: 127.0.0.1

it it still not working

**Comment by sksamuel** [comment]
Try network.host :0.0.0.0

**Comment by subhasish23sahu** [comment]
still not working

made changes in yml file as :  network.host: 0.0.0.0

and java file as : 

           Client  client = new PreBuiltTransportClient(settings)
            .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("0.0.0.0"), 9300));

**Comment by sksamuel** [comment]
Don't know any more sorry.

**Comment by subhasish23sahu** [comment]
no issue.thanks for the help

**Comment by subhasish23sahu** [comment]
Yes this has been solved.Please follow my Blog:

https://wordpress.com/post/subhasishsahu.wordpress.com/409

**Comment by srinathji** [comment]
Hi @subhasish23sahu can you please share the solution for this. Thanks in advance.

**Comment by HieJulia** [comment]
Hi, none of your solutions work for my case. The same issue. Anybody up for more solution.

**Comment by arun-badhai** [comment]
@subhasish23sahu  Thanks its work for me :)

**Comment by mindcrusher11** [comment]
add transport.host: localhost or any ip property in elasticsearch.yml file.

**Comment by HugoIT** [comment]
It's a very weird question. Sometimes success, sometimes failure
