### ISSUE TITLE
Possibly deprecate the TCP client ?

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#979]
Once the HTTP client reaches parity (which it should in 6.0, it's already better in many areas), should the TCP client be deprecated in order to encourage people to move to the HTTP client. Is there any reason for preferring the TCP client at this stage ?

See https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients

**Comment by douglaz** [comment]
@fernandors87, I know you love the TCP client. Would you like to comment?

**Comment by sksamuel** [comment]
I've deprecated it. It brings in dependencies which issues with things like spark; every time there's a reason I have to update tons of things, and the API is not as nice as the HTTP one.

**Comment by douglaz** [comment]
@sksamuel I think one problem with the HTTP client is that it that in general failures lack proper message/stacktraces. Sometimes only through the log on the client or on the server I can see exactly what went wrong. I have no experience with the TCP client, but @fernandors87 says it's better in this aspect.

**Comment by sksamuel** [comment]
I agree. I was planning on changing the http client for M4 such that requests return an Either of a proper error object or the actual success response. What do you think.

**Comment by douglaz** [comment]
@sksamuel looks good to me

**Comment by abankowski** [comment]
I understand all advantages of dropping TCP client support though in the JVM based languages Transport or Node clients should be preferred over REST api. Scala is a perfect choice for high performance ES based apps.

I would personally vote against dropping support of native ES protocol in elastic4s if possible and look for other solution if amount of work is exceeds velocity of sole contributor.

For all involved, as a background it's worth to read this short article:
https://www.elastic.co/blog/found-interfacing-elasticsearch-picking-client

**Comment by sksamuel** [comment]
Thanks for the feedback @abankowski it's nice to get other people's thoughts.

So a couple of things. Firstly, and most importantly, ES themselves have said they plan (eventually) to remove the transport client and that we should favour the HTTP client. This article is more recent than the one you linked to. https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients 

Secondly, the TCP client is a pain to work with as it brings in the entire es dep chain. And that causes errors with things like logging clients, netty clashes with spark and so on. It's really just a drain on my time keeping both going.

So another question would be - given we know there's a _slight_ performance gain from TCP, what reasons would someone want to use the TCP over the HTTP client other than that ?

**Comment by abankowski** [comment]
@sksamuel Cool article, I'v missed it somehow. It's a good point as we have in REST api load balancing across all available nodes and sniffing - imho both key features of binary protocol client.

When major advantages of TCP client are no longer valid and whole ES team is suggesting migration I totally understand your point and agree with dropping binary wrapper.

By the way, I would like to thank you for giving elastic4s to the community, great contribution.

**Comment by sksamuel** [comment]
> By the way, I would like to thank you for giving elastic4s to the community, great contribution.

You're welcome.

**Comment by sksamuel** [comment]
In 5.6.0 they've said the TCP client will be removed in 7.0, so I guess this is no longer a question of if, but when. https://www.elastic.co/blog/elasticsearch-5-6-0-released
