### ISSUE TITLE
Question: is the get by id and tag consistent? (not eventual consistent) thanks

### ISSUE THREAD

**Issue by tomer-ben-david** [sksamuel/elastic4s#987]
example
```
val resp = client.execute {
  get id 8 from "beer/lager"
}
```
am i always sure to get the last value written which means its not eventual consistent but consistent?

**Comment by sksamuel** [comment]
you'll get whatever is indexed on the node. if you want it consistent set
refresh policy to immediate when indexing but that'll only work for low
load.

**Comment by tomer-ben-david** [comment]
so when i 'set' (like `PUT`) something on elastic search it might be the case that it was not indexed yet and a `GET` won't get the last update? but elasticsearch documentation says the following (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#realtime)

>  If a document has been updated but is not yet refreshed, the get API will issue a refresh call in-place to make the document visible

according to this documentation snippet it looks like the get api issues automatically a refresh call in place, so i always get on GET the last value, isn't that what I should understand from this documentation snippet?

**Comment by sksamuel** [comment]
Yes seems that it is, unless you set realtime to false.

**Comment by tomer-ben-david** [comment]
cool, so i get it now. "realtime" flag effects this get consistency/eventual consistency behaviour thanks.

**Comment by tomer-ben-david** [comment]
it looks like `get` operation is dependent on the target node whether it's master or replica.  also with `realtime` flag on.  

[https://www.elastic.co/guide/en/elasticsearch/guide/1.x/distrib-read.html](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/distrib-read.html)

> It is possible that, while a document is being indexed, the document will already be present on the primary shard but not yet copied to the replica shards. In this case, a replica might report that the document doesn’t exist, while the primary would have returned the document successfully. Once the indexing request has returned success to the user, the document will be available on the primary and all replica shards.

[(https://www.elastic.co/guide/en/elasticsearch/guide/1.x/translog.html)](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/translog.html)

> The translog is also used to provide real-time CRUD. When you try to retrieve, update, or delete a document by ID, it first checks the translog for any recent changes before trying to retrieve the document from the relevant segment. This means that it always has access to the latest known version of the document, in real-time.
