### ISSUE TITLE
Support for Count API

### ISSUE THREAD

**Issue by budde377** [sksamuel/elastic4s#992]
Are there any plans for supporting the [Count API](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-count.html) for ES 5.4? 
If not, how do I achieve this functionality through the existing implementation.

**Comment by sksamuel** [comment]
I didn't realize they'd added it back in. They had it before and removed it.
For now, just set the size parameter on search to 0.

**Comment by budde377** [comment]
Cheers. That works!
