### ISSUE TITLE
ElasticJackson Implicits not working after a package change

### ISSUE THREAD

**Issue by rogerzxu** [sksamuel/elastic4s#993]
Using v5.2.2, I've run into this very bizarre error. 

I have the following classes that I am casting search hits into using `ElasticJackson.Implicits._`:
```
case class User(
  id: String,
  name: String,
  roles: Seq[UserRole.Value],
  email: String,
  status: UserStatus.Value
)

object UserRole extends Enumeration {
  val Student = Value("Student")
  val Instructor = Value("Instructor")
  val Admin = Value("Admin")
}
```

at some point during refactoring, I changed the package name from `foo.search.model` to `foo.searchapi.model`, and now the implicit hit readers do not work. 

Strangely enough, the following error appears: 
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: foo.search.model.UserRole (through reference chain: foo.searchapi.model.User["roles"]->com.fasterxml.jackson.module.scala.deser.BuilderWrapper[0])
```

It's trying to resolve UserRole with the old package name! I deleted my entire local .ivy2 cache for good measure and I'm still seeing this issue.

**Comment by sksamuel** [comment]
I don't think this is an elastic4s bug. I mean it doesn't store your package names anyway, it just uses jackson under the hood. I bet you've got an old build lurking about somehow.
