### ISSUE TITLE
HTTP client does not serialize TermsOrder to JSON properly

### ISSUE THREAD

**Issue by FrankLaan** [sksamuel/elastic4s#994]
When you use a TermsAggregation with an order of "_count" "descending" the expected JSON is like this:

`"order": { "_count" : "desc" } `

(see [Elastic doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html))

However you get

`"order" : "TermsOrder(_count,false)"`

**Comment by sksamuel** [comment]
Seems ok in 6.0. I've added another couple of tests to catch any regressions.
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/search/aggs/TermsAggregationHttpTest.scala#L112-L132
