### ISSUE TITLE
HTTP client throws scala match error on DateRangeAggregation

### ISSUE THREAD

**Issue by FrankLaan** [sksamuel/elastic4s#995]
When you include a DataRangeAggregation in your query and use the HTTP client, the JSON conversion fails because the AggregationBuilderFn has no case for that type:

`DateRangeAggregation(byStartDate,Some(creationDate),None,None,None,Some(Europe/Amsterdam),None,List(),List((Some(today),now/d), (Some(yesterday),now-1d/d), (Some(week),now-1w/d), (Some(allTime),now+2d/d)),List(),List(),Map()) (of class com.sksamuel.elastic4s.searches.aggs.DateRangeAggregation)
scala.MatchError: DateRangeAggregation(byStartDate,Some(creationDate),None,None,None,Some(Europe/Amsterdam),None,List(),List((Some(today),now/d), (Some(yesterday),now-1d/d), (Some(week),now-1w/d), (Some(allTime),now+2d/d)),List(),List(),Map()) (of class com.sksamuel.elastic4s.searches.aggs.DateRangeAggregation)
	at com.sksamuel.elastic4s.http.search.aggs.AggregationBuilderFn$.apply(AggregationBuilderFn.scala:9)`

**Comment by sksamuel** [comment]
It's missing in the http client atm.

**Comment by sksamuel** [comment]
This is now implemented in master and will be released with 6.0.0-rc2.
