### ISSUE TITLE
elastic4s http-client not support authentication ? 

### ISSUE THREAD

**Issue by beartistic** [sksamuel/elastic4s#998]
hi:
I saw your sample code as follow, 
val client = HttpClient(ElasticsearchClientUri("localhost", 9200))
....
But I want to create client with username & password, how should I do ?

**Comment by sksamuel** [comment]
From the readme.

The http client internally uses the Apache Http Client, which we can customize by passing in two callbacks.

val client = HttpClient(ElasticsearchClientUri("localhost", 9200), new RequestConfigCallback {
    override def customizeRequestConfig(requestConfigBuilder: Builder) = ...
    }
  }, new HttpClientConfigCallback {
    override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder) = ...
  })

**Comment by marceloboeira** [comment]
For the purposes of documentation, since I could not find any examples on how to do that:
```scala
  lazy val provider = {
    val provider = new BasicCredentialsProvider
    val credentials = new UsernamePasswordCredentials("elastic", "changeme")
    provider.setCredentials(AuthScope.ANY, credentials)
    provider
  }
  val client = HttpClient(ElasticsearchClientUri("localhost", 9200), new RequestConfigCallback  {
    override def customizeRequestConfig(requestConfigBuilder: Builder) = {
      requestConfigBuilder
    }
  }, new HttpClientConfigCallback {
    override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder) = {
      httpClientBuilder.setDefaultCredentialsProvider(provider)
    }
  })
```

**Comment by andbed** [comment]
It would be really useful to add @marceloboeira example to the official docs

**Comment by jacool** [comment]
It is important to note that if you are using authentication you probably also have SSL, which will work only if you pass the option like this:
`ElasticsearchClientUri(null, List(("some-host", 9243)), Map("ssl" -> "true"))`

**Comment by andbed** [comment]
I use the following syntax which appears to work:
ElasticsearchClientUri(s"elasticsearch://${config.host}:${config.port}?ssl=true")

**Comment by wadouk** [comment]
Any advice with up to date API ?
HttpClient => JavaClient ?
ElasticsearchClientUri => ElasticProperties ?

`ssl=true` still needed ?

elastic 7.14
