### ISSUE TITLE
Port Nested Aggregation to 5.4.x

### ISSUE THREAD

**Issue by kutchar** [sksamuel/elastic4s#999]
Currently `NestedAggregationDefinition` exists in elastic4s-http `5.4.7` but using it causes a `scala.MatchError`. The functionality exists in `master` and looks simple enough to be able to be ported back.

In `master`
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/aggs/NestedAggregationBuilder.scala

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/search/aggs/AggregationBuilderFn.scala#L19

**Comment by sksamuel** [comment]
If it's easy then it's easy to do a PR right ;) ;)

**Comment by kutchar** [comment]
@sksamuel just wanted to get the green light that you'll publish it when I make the PR ;)

**Comment by sksamuel** [comment]
:+1:

**Comment by kutchar** [comment]
Please review/merge the PR when you get a chance. BTW, thanks for this awesome library!

**Comment by sksamuel** [comment]
You're welcome.

**Comment by sksamuel** [comment]
Merged.

**Comment by kutchar** [comment]
Thanks. When would you be able to publish a release?

**Comment by sksamuel** [comment]
Will do it now.

**Comment by kutchar** [comment]
Awesome!
